import * as THREE from "three";
import { mapDevelopablePoint, validateDevelopableFoldScene } from "./developable-surfaces.js";
import type { DevelopableFoldScene, SurfacePoint } from "./developable-surfaces.js";

export interface DevelopableThreeMapping{group:THREE.Group;components:Map<string,THREE.Object3D>;apply(scene:DevelopableFoldScene):void;setSeamVisible(visible:boolean):void;dispose():void;}
function samples(scene:DevelopableFoldScene):{points:SurfacePoint[];rows:number;columns:number}{const columns=64,rows=scene.solidType==="cylinder"?1:16,points:SurfacePoint[]=[];const min=scene.solidType==="cylinder"?0:scene.solidType==="cone"?0:scene.dimensions.innerRadius,max=scene.solidType==="cylinder"?scene.dimensions.height:scene.solidType==="cone"?scene.dimensions.slantHeight:scene.dimensions.outerRadius;for(let row=0;row<=rows;row++)for(let column=0;column<=columns;column++)points.push({surfaceId:scene.lateralSurfaceId,theta:2*Math.PI*column/columns,longitudinal:min+(max-min)*row/rows});return{points,rows,columns};}
function positions(scene:DevelopableFoldScene,points:SurfacePoint[]){return points.flatMap(point=>mapDevelopablePoint(scene,point).value!);}
function diskTarget(scene:DevelopableFoldScene,id:string){if(scene.solidType==="cylinder")return{id,position:new THREE.Vector3(0,id==="base-top"?scene.dimensions.height:0,scene.dimensions.radius),rotation:new THREE.Euler(Math.PI/2,0,0)};const gamma=Math.asin((scene.solidType==="cone"?scene.dimensions.radius:scene.dimensions.largeRadius-scene.dimensions.smallRadius)/scene.dimensions.slantHeight),rho=id==="base-top"?scene.dimensions.innerRadius:scene.solidType==="cone"?scene.dimensions.slantHeight:scene.dimensions.outerRadius;return{id,position:new THREE.Vector3(0,0,rho*Math.cos(gamma)),rotation:new THREE.Euler(0,0,0)};}
export function createDevelopableThreeMapping(scene:DevelopableFoldScene):DevelopableThreeMapping{
  if(scene.status!=="PASS"||scene.metadata.model!=="developable"||validateDevelopableFoldScene(scene).status!=="PASS")throw new Error("INVALID_DEVELOPABLE_FOLD_SCENE");const group=new THREE.Group();group.name=scene.id;const components=new Map<string,THREE.Object3D>(),sample=samples(scene),geometry=new THREE.BufferGeometry();geometry.setAttribute("position",new THREE.Float32BufferAttribute(positions(scene,sample.points),3));const indices:number[]=[];for(let row=0;row<sample.rows;row++)for(let column=0;column<sample.columns;column++){const a=row*(sample.columns+1)+column,b=a+1,c=a+sample.columns+1,d=c+1;indices.push(a,c,b,b,c,d);}geometry.setIndex(indices);geometry.computeVertexNormals();const lateral=new THREE.Mesh(geometry,new THREE.MeshStandardMaterial({color:0x60a5fa,side:THREE.DoubleSide,transparent:true,opacity:.86}));lateral.name=scene.lateralSurfaceId;lateral.userData.surfaceId=scene.lateralSurfaceId;lateral.userData.visualTessellationOnly=true;group.add(lateral);components.set(scene.lateralSurfaceId,lateral);
  const seamGeometry=new THREE.BufferGeometry(),seam=new THREE.Line(seamGeometry,new THREE.LineBasicMaterial({color:0xef4444}));seam.name="surface-seam";seam.userData.seam=true;group.add(seam);components.set("surface-seam",seam);
  for(const primitive of scene.net.primitives.filter(item=>item.type==="circle")){const disk=new THREE.Mesh(new THREE.CircleGeometry(primitive.radius,64),new THREE.MeshStandardMaterial({color:0xfbbf24,side:THREE.DoubleSide,transparent:true,opacity:.8}));disk.name=primitive.id;disk.userData.surfaceId=primitive.id;group.add(disk);components.set(primitive.id,disk);}
  const apply=(next:DevelopableFoldScene)=>{if(next.solidType!==scene.solidType)throw new Error("DEVELOPABLE_SCENE_SOLID_MISMATCH");const values=positions(next,sample.points),attribute=geometry.getAttribute("position") as THREE.BufferAttribute;values.forEach((value,index)=>attribute.setComponent(Math.floor(index/3),index%3,value));attribute.needsUpdate=true;geometry.computeVertexNormals();const seamPoints=sample.points.filter((_,index)=>index%(sample.columns+1)===0).map(point=>new THREE.Vector3(...mapDevelopablePoint(next,point).value!));seamGeometry.setFromPoints(seamPoints);for(const primitive of next.net.primitives.filter(item=>item.type==="circle")){const disk=components.get(primitive.id)!;if(next.progress===0){disk.position.set(primitive.center[0],primitive.center[1],0);disk.rotation.set(0,0,0);}else{const target=diskTarget(next,primitive.id),phase=Math.max(0,(next.progress-.65)/.35);disk.position.lerpVectors(new THREE.Vector3(primitive.center[0],primitive.center[1],0),target.position,phase);disk.rotation.set(target.rotation.x*phase,target.rotation.y*phase,target.rotation.z*phase);}}};apply(scene);
  return{group,components,apply,setSeamVisible:(visible)=>{seam.visible=visible;},dispose:()=>{group.traverse(object=>{const renderable=object as THREE.Mesh;renderable.geometry?.dispose();const materials=renderable.material?(Array.isArray(renderable.material)?renderable.material:[renderable.material]):[];materials.forEach(material=>material.dispose());});group.clear();components.clear();}};
}
