import * as THREE from "three";
import { mapDevelopablePoint, validateDevelopableFoldScene } from "./developable-surfaces.js";
import type { DevelopableFoldScene, SurfacePoint } from "./developable-surfaces.js";
export interface DevelopableThreeMapping{group:THREE.Group;components:Map<string,THREE.Object3D>;apply(scene:DevelopableFoldScene):void;setSeamVisible(visible:boolean):void;setSurfaceVisible(surfaceId:string,visible:boolean):void;setEducationalOverlayVisible(id:string,visible:boolean):void;dispose():void;}
type Sample={points:SurfacePoint[];rows:number;columns:number};
function sampleRange(scene:DevelopableFoldScene,min:number,max:number,rows=24):Sample{const columns=96,points:SurfacePoint[]=[];for(let row=0;row<=rows;row++)for(let column=0;column<=columns;column++)points.push({surfaceId:scene.lateralSurfaceId,theta:2*Math.PI*column/columns,longitudinal:min+(max-min)*row/rows});return{points,rows,columns};}
function lateralSample(scene:DevelopableFoldScene){return sampleRange(scene,scene.solidType==="cylinder"?0:scene.solidType==="cone"?0:scene.dimensions.innerRadius,scene.solidType==="cylinder"?scene.dimensions.height:scene.solidType==="cone"?scene.dimensions.slantHeight:scene.dimensions.outerRadius,scene.solidType==="cylinder"?1:24);}
const mapped=(scene:DevelopableFoldScene,points:SurfacePoint[])=>points.flatMap(p=>mapDevelopablePoint(scene,p).value!);
function smoothNormals(scene:DevelopableFoldScene,points:SurfacePoint[]){if(scene.progress<1e-10)return points.flatMap(()=>[0,0,1]);if(scene.solidType==="cylinder")return points.flatMap(p=>{const theta=(p.theta/Math.PI/2-.5)*2*Math.PI*scene.progress;return[-Math.sin(theta),0,Math.cos(theta)];});const target=Math.asin((scene.solidType==="cone"?scene.dimensions.radius:scene.dimensions.largeRadius-scene.dimensions.smallRadius)/scene.dimensions.slantHeight),gamma=Math.PI/2+(target-Math.PI/2)*scene.progress,flat=scene.dimensions.sectorAngleRadians;return points.flatMap(p=>{const beta=p.theta*flat/(2*Math.PI)-flat/2,azimuth=beta/Math.sin(gamma);return[Math.cos(gamma)*Math.cos(azimuth),Math.cos(gamma)*Math.sin(azimuth),-Math.sin(gamma)];});}
function meshGeometry(scene:DevelopableFoldScene,sample:Sample){const geometry=new THREE.BufferGeometry();geometry.setAttribute("position",new THREE.Float32BufferAttribute(mapped(scene,sample.points),3));geometry.setAttribute("normal",new THREE.Float32BufferAttribute(smoothNormals(scene,sample.points),3));geometry.setAttribute("surfaceTheta",new THREE.Float32BufferAttribute(sample.points.map(p=>p.theta),1));geometry.setAttribute("surfaceLongitudinal",new THREE.Float32BufferAttribute(sample.points.map(p=>p.longitudinal),1));const indices:number[]=[];for(let r=0;r<sample.rows;r++)for(let c=0;c<sample.columns;c++){const a=r*(sample.columns+1)+c,b=a+1,d=(r+1)*(sample.columns+1)+c,e=d+1;indices.push(a,d,b,b,d,e);}geometry.setIndex(indices);return geometry;}
function updateGeometry(geometry:THREE.BufferGeometry,scene:DevelopableFoldScene,points:SurfacePoint[]){const values=mapped(scene,points),normalValues=smoothNormals(scene,points),position=geometry.getAttribute("position") as THREE.BufferAttribute,normal=geometry.getAttribute("normal") as THREE.BufferAttribute;values.forEach((v,i)=>position.setComponent(Math.floor(i/3),i%3,v));normalValues.forEach((v,i)=>normal.setComponent(Math.floor(i/3),i%3,v));position.needsUpdate=true;normal.needsUpdate=true;}
function diskTarget(scene:DevelopableFoldScene,id:string){if(scene.solidType==="cylinder")return{position:new THREE.Vector3(0,id==="base-top"?scene.dimensions.height:0,scene.dimensions.radius),rotation:new THREE.Euler(Math.PI/2,0,0)};const gamma=Math.asin((scene.solidType==="cone"?scene.dimensions.radius:scene.dimensions.largeRadius-scene.dimensions.smallRadius)/scene.dimensions.slantHeight),rho=id==="base-top"?scene.dimensions.innerRadius:scene.solidType==="cone"?scene.dimensions.slantHeight:scene.dimensions.outerRadius;return{position:new THREE.Vector3(0,0,rho*Math.cos(gamma)),rotation:new THREE.Euler()};}
export function createDevelopableThreeMapping(scene:DevelopableFoldScene):DevelopableThreeMapping{
 if(scene.status!=="PASS"||validateDevelopableFoldScene(scene).status!=="PASS")throw Error("INVALID_DEVELOPABLE_FOLD_SCENE");const group=new THREE.Group(),components=new Map<string,THREE.Object3D>(),sample=lateralSample(scene),geometry=meshGeometry(scene,sample),lateral=new THREE.Mesh(geometry,new THREE.MeshBasicMaterial({color:0x4f8fdf,side:THREE.DoubleSide}));lateral.name=scene.lateralSurfaceId;lateral.userData={surfaceId:scene.lateralSurfaceId,visualTessellationOnly:true,continuousParameterizedSurface:true};group.add(lateral);components.set(scene.lateralSurfaceId,lateral);
 const seamGeometry=new THREE.BufferGeometry(),seam=new THREE.Line(seamGeometry,new THREE.LineBasicMaterial({color:0xef4444}));seam.name="surface-seam";seam.userData.seam=true;group.add(seam);components.set("surface-seam",seam);
 for(const primitive of scene.net.primitives.filter(p=>p.type==="circle")){const disk=new THREE.Mesh(new THREE.CircleGeometry(primitive.radius,96),new THREE.MeshStandardMaterial({color:0xfbbf24,side:THREE.DoubleSide,roughness:.7}));disk.name=primitive.id;disk.userData.surfaceId=primitive.id;group.add(disk);components.set(primitive.id,disk);}
 const overlays:Array<{id:string;sample:Sample;mesh:THREE.Mesh}>=[];if(scene.solidType==="conical_frustum"){const definitions=[{id:"removed-top-cone",min:0,max:scene.dimensions.innerRadius,color:0xf472b6,opacity:.28,visible:true},{id:"parent-cone-reference",min:0,max:scene.dimensions.outerRadius,color:0x64748b,opacity:.1,visible:false}];for(const d of definitions){const s=sampleRange(scene,d.min,d.max),mesh=new THREE.Mesh(meshGeometry(scene,s),new THREE.MeshBasicMaterial({color:d.color,side:THREE.DoubleSide,transparent:true,opacity:d.opacity,depthWrite:false,wireframe:d.id.includes("parent")}));mesh.name=d.id;mesh.visible=d.visible;mesh.renderOrder=d.id.includes("parent")?-2:-1;mesh.userData.educationalOverlay=true;group.add(mesh);components.set(d.id,mesh);overlays.push({id:d.id,sample:s,mesh});}}
 if(scene.solidType==="conical_frustum"){const a=scene.dimensions.sectorAngleRadians,complement=new THREE.Mesh(new THREE.RingGeometry(scene.dimensions.innerRadius,scene.dimensions.outerRadius,96,1,a/2,2*Math.PI-a),new THREE.MeshBasicMaterial({color:0x94a3b8,side:THREE.DoubleSide,transparent:true,opacity:.12,depthWrite:false}));complement.name="development-complement";complement.position.z=-.03;complement.visible=false;complement.userData={educationalOverlay:true,requestedVisible:false,flatOnly:true};group.add(complement);components.set(complement.name,complement);}
 const apply=(next:DevelopableFoldScene)=>{if(next.solidType!==scene.solidType)throw Error("DEVELOPABLE_SCENE_SOLID_MISMATCH");updateGeometry(geometry,next,sample.points);overlays.forEach(o=>updateGeometry(o.mesh.geometry,next,o.sample.points));const complement=components.get("development-complement") as THREE.Mesh|undefined;if(complement){complement.visible=Boolean(complement.userData.requestedVisible)&&next.progress<.98;(complement.material as THREE.MeshBasicMaterial).opacity=.12*(1-next.progress);}const seamPoints=sample.points.filter((_,i)=>i%(sample.columns+1)===0).map(p=>new THREE.Vector3(...mapDevelopablePoint(next,p).value!));seamGeometry.setFromPoints(seamPoints);for(const primitive of next.net.primitives.filter(p=>p.type==="circle")){const disk=components.get(primitive.id)!;if(next.progress===0){const center=next.solidType==="cylinder"?[0,primitive.id==="base-top"?next.dimensions.height+primitive.radius+.5:-primitive.radius-.5,0]:[primitive.center[0],primitive.center[1],0];disk.position.set(...center as [number,number,number]);disk.rotation.set(0,0,0);}else{const target=diskTarget(next,primitive.id),phase=Math.max(0,(next.progress-.65)/.35);const flat=next.solidType==="cylinder"?new THREE.Vector3(0,primitive.id==="base-top"?next.dimensions.height+primitive.radius+.5:-primitive.radius-.5,0):new THREE.Vector3(primitive.center[0],primitive.center[1],0);disk.position.lerpVectors(flat,target.position,phase);disk.rotation.set(target.rotation.x*phase,target.rotation.y*phase,target.rotation.z*phase);}}};apply(scene);
 return{group,components,apply,setSeamVisible:v=>{seam.visible=v;},setSurfaceVisible:(id,v)=>{const x=components.get(id);if(!x)throw Error(`UNKNOWN_SURFACE:${id}`);x.visible=v;},setEducationalOverlayVisible:(id,v)=>{const x=components.get(id);if(!x||!x.userData.educationalOverlay)throw Error(`UNKNOWN_EDUCATIONAL_OVERLAY:${id}`);x.userData.requestedVisible=v;x.visible=v;},dispose:()=>{group.traverse(x=>{const r=x as THREE.Mesh;r.geometry?.dispose();const materials=r.material?(Array.isArray(r.material)?r.material:[r.material]):[];materials.forEach(m=>m.dispose());});group.clear();components.clear();}};
}
