import type { FoldBuildResult, FoldIssue, Vec2, Vec3 } from "./types.js";

export type DevelopableSolidType="cylinder"|"cone"|"conical_frustum";
export type DevelopableNetPrimitive=
  |{id:string;type:"rectangle";width:number;height:number;origin:Vec2}
  |{id:string;type:"circle";radius:number;center:Vec2}
  |{id:string;type:"sector";radius:number;angleRadians:number;center:Vec2;startAngle:number}
  |{id:string;type:"annular_sector";innerRadius:number;outerRadius:number;angleRadians:number;center:Vec2;startAngle:number};
export interface SurfaceAttachment{id:string;surfaceId:string;componentId:string;boundary:"top"|"bottom";mode:"staged";}
export interface SurfaceCoordinate{id:string;system:"theta_z"|"slant_theta"|"disk_xy";seamTheta:number;}
export interface DevelopableFoldScene{
  id:string;solidType:DevelopableSolidType;progress:number;status:"PASS";lateralSurfaceId:string;
  dimensions:Record<string,number>;net:{id:string;primitives:DevelopableNetPrimitive[]};
  coordinateSystems:SurfaceCoordinate[];attachments:SurfaceAttachment[];
  metadata:{model:"developable";rendererTessellationIsVisualOnly:true;normalizedFrom?:"conical_frustum"};
}
export interface SurfacePoint{surfaceId:string;theta:number;longitudinal:number;}
export interface DevelopmentPoint{surfaceId:string;point:Vec2;}

const fail=(code:string,message:string):FoldBuildResult<DevelopableFoldScene>=>({status:"FAIL",issues:[{code,severity:"error",path:"dimensions",message}]});
const validPositive=(value:number)=>Number.isFinite(value)&&value>0&&value<=1e6;
const validProgress=(value:number)=>Number.isFinite(value)&&value>=0&&value<=1;
const normalizeTheta=(theta:number,seam:number)=>{let value=theta-seam;while(value<0)value+=Math.PI*2;while(value>=Math.PI*2)value-=Math.PI*2;return value;};

export function createDevelopableFoldScene(input:{solidType:DevelopableSolidType;radius?:number;largeRadius?:number;smallRadius?:number;height:number;seamTheta?:number},progress=0):FoldBuildResult<DevelopableFoldScene>{
  if(!["cylinder","cone","conical_frustum"].includes(input.solidType))return fail("UNSUPPORTED_CURVED_SOLID","Curved solid is not supported.");
  if(!validProgress(progress))return fail("INVALID_PROGRESS","Progress must be finite and within [0,1].");if(!validPositive(input.height))return fail("INVALID_HEIGHT","Height must be finite and positive.");const seam=input.seamTheta??0;if(!Number.isFinite(seam))return fail("INVALID_SEAM","Seam angle must be finite.");
  if(input.solidType==="cylinder"){const r=input.radius!;if(!validPositive(r))return fail("INVALID_RADIUS","Cylinder radius must be finite and positive.");const circumference=2*Math.PI*r;return{status:"PASS",value:{id:`developable-cylinder-${r}-${input.height}`,solidType:"cylinder",progress,status:"PASS",lateralSurfaceId:"surface-lateral",dimensions:{radius:r,height:input.height,circumference},net:{id:"net-cylinder",primitives:[{id:"surface-lateral",type:"rectangle",width:circumference,height:input.height,origin:[0,0]},{id:"base-bottom",type:"circle",radius:r,center:[r,-r-0.5]},{id:"base-top",type:"circle",radius:r,center:[circumference-r,input.height+r+0.5]}]},coordinateSystems:[{id:"surface-lateral",system:"theta_z",seamTheta:seam},{id:"base-bottom",system:"disk_xy",seamTheta:seam},{id:"base-top",system:"disk_xy",seamTheta:seam}],attachments:[{id:"attachment-bottom",surfaceId:"surface-lateral",componentId:"base-bottom",boundary:"bottom",mode:"staged"},{id:"attachment-top",surfaceId:"surface-lateral",componentId:"base-top",boundary:"top",mode:"staged"}],metadata:{model:"developable",rendererTessellationIsVisualOnly:true}},issues:[]};}
  if(input.solidType==="cone"){const r=input.radius!;if(!validPositive(r))return fail("INVALID_RADIUS","Cone radius must be finite and positive.");const slantHeight=Math.hypot(r,input.height);if(!validPositive(slantHeight))return fail("INVALID_SLANT_HEIGHT","Cone slant height is invalid.");const sectorAngleRadians=2*Math.PI*r/slantHeight;return{status:"PASS",value:{id:`developable-cone-${r}-${input.height}`,solidType:"cone",progress,status:"PASS",lateralSurfaceId:"surface-lateral",dimensions:{radius:r,height:input.height,slantHeight,sectorRadius:slantHeight,sectorAngleRadians,sectorAngleDegrees:sectorAngleRadians*180/Math.PI},net:{id:"net-cone",primitives:[{id:"surface-lateral",type:"sector",radius:slantHeight,angleRadians:sectorAngleRadians,center:[0,0],startAngle:0},{id:"base-bottom",type:"circle",radius:r,center:[slantHeight+r+0.5,0]}]},coordinateSystems:[{id:"surface-lateral",system:"slant_theta",seamTheta:seam},{id:"base-bottom",system:"disk_xy",seamTheta:seam}],attachments:[{id:"attachment-bottom",surfaceId:"surface-lateral",componentId:"base-bottom",boundary:"bottom",mode:"staged"}],metadata:{model:"developable",rendererTessellationIsVisualOnly:true}},issues:[]};}
  const R=input.largeRadius!,r=input.smallRadius!;if(!Number.isFinite(R)||!Number.isFinite(r)||R<=0||r<0)return fail("INVALID_FRUSTUM_RADII","Frustum radii require R > r >= 0.");if(R<r)return fail("INVALID_FRUSTUM_RADII","Large radius must not be smaller than top radius.");if(Math.abs(R-r)<1e-12){const cylinder=createDevelopableFoldScene({solidType:"cylinder",radius:R,height:input.height,seamTheta:seam},progress);if(cylinder.value){cylinder.value.metadata.normalizedFrom="conical_frustum";cylinder.issues.push({code:"DEGENERATE_FRUSTUM",severity:"warning",path:"dimensions",message:"Equal frustum radii were normalized to cylinder behavior."});}return cylinder;}
  const slantHeight=Math.hypot(input.height,R-r),outerRadius=slantHeight*R/(R-r),innerRadius=slantHeight*r/(R-r),sectorAngleRadians=2*Math.PI*(R-r)/slantHeight;if(![slantHeight,outerRadius,innerRadius,sectorAngleRadians].every(Number.isFinite))return fail("INVALID_SURFACE_MAPPING","Frustum development is non-finite.");return{status:"PASS",value:{id:`developable-frustum-${R}-${r}-${input.height}`,solidType:"conical_frustum",progress,status:"PASS",lateralSurfaceId:"surface-lateral",dimensions:{largeRadius:R,smallRadius:r,height:input.height,slantHeight,outerRadius,innerRadius,sectorAngleRadians,sectorAngleDegrees:sectorAngleRadians*180/Math.PI},net:{id:"net-conical-frustum",primitives:[{id:"surface-lateral",type:"annular_sector",innerRadius,outerRadius,angleRadians:sectorAngleRadians,center:[0,0],startAngle:0},{id:"base-bottom",type:"circle",radius:R,center:[outerRadius+R+0.5,0]},{id:"base-top",type:"circle",radius:r,center:[-(outerRadius+r+0.5),0]}]},coordinateSystems:[{id:"surface-lateral",system:"slant_theta",seamTheta:seam},{id:"base-bottom",system:"disk_xy",seamTheta:seam},{id:"base-top",system:"disk_xy",seamTheta:seam}],attachments:[{id:"attachment-bottom",surfaceId:"surface-lateral",componentId:"base-bottom",boundary:"bottom",mode:"staged"},{id:"attachment-top",surfaceId:"surface-lateral",componentId:"base-top",boundary:"top",mode:"staged"}],metadata:{model:"developable",rendererTessellationIsVisualOnly:true}},issues:[]};
}

export function validateDevelopableFoldScene(scene:DevelopableFoldScene){const issues:FoldIssue[]=[];const add=(code:string,path:string,message:string)=>issues.push({code,severity:"error",path,message});if(!validProgress(scene.progress))add("INVALID_PROGRESS","progress","Progress must be within [0,1].");if(!scene.coordinateSystems.some(item=>item.id===scene.lateralSurfaceId))add("INVALID_SURFACE_MAPPING","coordinateSystems","Lateral coordinate system is missing.");if(scene.coordinateSystems.some(item=>!Number.isFinite(item.seamTheta)))add("INVALID_SEAM","coordinateSystems.seamTheta","Seams must be finite.");const ids=new Set(scene.net.primitives.map(item=>item.id));for(const attachment of scene.attachments)if(attachment.surfaceId!==scene.lateralSurfaceId||!ids.has(attachment.componentId))add("INVALID_SURFACE_ATTACHMENT",`attachments.${attachment.id}`,"Attachment references an unknown surface component.");for(const primitive of scene.net.primitives){if(primitive.type==="circle"&&(!Number.isFinite(primitive.radius)||primitive.radius<0))add("INVALID_RADIUS",`net.${primitive.id}`,"Circle radius is invalid.");if((primitive.type==="sector"||primitive.type==="annular_sector")&&(!Number.isFinite(primitive.angleRadians)||primitive.angleRadians<=0||primitive.angleRadians>2*Math.PI+1e-9))add("INVALID_SECTOR_ANGLE",`net.${primitive.id}`,"Sector angle is invalid.");if(primitive.type==="sector"&&(!validPositive(primitive.radius)))add("INVALID_SECTOR_RADIUS",`net.${primitive.id}`,"Sector radius is invalid.");if(primitive.type==="annular_sector"&&(!Number.isFinite(primitive.innerRadius)||!validPositive(primitive.outerRadius)||primitive.innerRadius<0||primitive.innerRadius>=primitive.outerRadius))add("INVALID_SECTOR_RADIUS",`net.${primitive.id}`,"Annular sector radii are invalid.");}
  if(scene.solidType==="cylinder"&&Math.abs(scene.dimensions.circumference-2*Math.PI*scene.dimensions.radius)>1e-8)add("INVALID_ARC_LENGTH","dimensions.circumference","Cylinder circumference invariant failed.");if(scene.solidType==="cone"&&Math.abs(scene.dimensions.sectorRadius*scene.dimensions.sectorAngleRadians-2*Math.PI*scene.dimensions.radius)>1e-8)add("INVALID_ARC_LENGTH","dimensions.sectorAngleRadians","Cone arc invariant failed.");if(scene.solidType==="conical_frustum"&&(Math.abs(scene.dimensions.outerRadius*scene.dimensions.sectorAngleRadians-2*Math.PI*scene.dimensions.largeRadius)>1e-8||Math.abs(scene.dimensions.innerRadius*scene.dimensions.sectorAngleRadians-2*Math.PI*scene.dimensions.smallRadius)>1e-8))add("INVALID_ARC_LENGTH","dimensions.sectorAngleRadians","Frustum arc invariant failed.");return{status:issues.length?"FAIL" as const:"PASS" as const,issues};}

export function updateDevelopableFoldScene(scene:DevelopableFoldScene,progress:number):FoldBuildResult<DevelopableFoldScene>{return validProgress(progress)?{status:"PASS",value:{...scene,progress},issues:[]}:fail("INVALID_PROGRESS","Progress must be finite and within [0,1].");}
export function surfacePointToDevelopment(scene:DevelopableFoldScene,point:SurfacePoint):FoldBuildResult<DevelopmentPoint>{const coordinate=scene.coordinateSystems.find(item=>item.id===point.surfaceId);if(!coordinate||point.surfaceId!==scene.lateralSurfaceId)return{status:"FAIL",issues:[{code:"INVALID_SURFACE_MAPPING",severity:"error",path:"surfaceId",message:"Unknown or unsupported surface coordinate system."}]};if(!Number.isFinite(point.theta)||!Number.isFinite(point.longitudinal))return{status:"FAIL",issues:[{code:Number.isNaN(point.theta)||Number.isNaN(point.longitudinal)?"NAN_SURFACE_POINT":"INFINITE_SURFACE_POINT",severity:"error",path:"point",message:"Surface point must be finite."}]};const theta=normalizeTheta(point.theta,coordinate.seamTheta);if(scene.solidType==="cylinder")return{status:"PASS",value:{surfaceId:point.surfaceId,point:[scene.dimensions.radius*theta,point.longitudinal]},issues:[]};const gamma=Math.asin((scene.solidType==="cone"?scene.dimensions.radius:scene.dimensions.largeRadius-scene.dimensions.smallRadius)/scene.dimensions.slantHeight);return{status:"PASS",value:{surfaceId:point.surfaceId,point:[point.longitudinal*Math.cos(theta*Math.sin(gamma)),point.longitudinal*Math.sin(theta*Math.sin(gamma))]},issues:[]};}
export function developmentPointToSurface(scene:DevelopableFoldScene,development:DevelopmentPoint):FoldBuildResult<SurfacePoint>{const coordinate=scene.coordinateSystems.find(item=>item.id===development.surfaceId),[x,y]=development.point;if(!coordinate||development.surfaceId!==scene.lateralSurfaceId||![x,y].every(Number.isFinite))return{status:"FAIL",issues:[{code:"INVALID_SURFACE_MAPPING",severity:"error",path:"development",message:"Development point is invalid."}]};if(scene.solidType==="cylinder")return{status:"PASS",value:{surfaceId:development.surfaceId,theta:x/scene.dimensions.radius+coordinate.seamTheta,longitudinal:y},issues:[]};const rho=Math.hypot(x,y),gamma=Math.asin((scene.solidType==="cone"?scene.dimensions.radius:scene.dimensions.largeRadius-scene.dimensions.smallRadius)/scene.dimensions.slantHeight),rawTheta=Math.atan2(y,x)/Math.sin(gamma)+coordinate.seamTheta,theta=normalizeTheta(rawTheta,coordinate.seamTheta)+coordinate.seamTheta;return{status:"PASS",value:{surfaceId:development.surfaceId,theta,longitudinal:rho},issues:[]};}

export function mapDevelopablePoint(scene:DevelopableFoldScene,point:SurfacePoint):FoldBuildResult<Vec3>{const developed=surfacePointToDevelopment(scene,point);if(!developed.value)return{status:"FAIL",issues:developed.issues};if(scene.progress===0)return{status:"PASS",value:[developed.value.point[0],developed.value.point[1],0],issues:[]};if(scene.solidType==="cylinder"){const s=developed.value.point[0],effectiveRadius=scene.dimensions.radius/scene.progress,angle=scene.progress*s/scene.dimensions.radius;return{status:"PASS",value:[effectiveRadius*Math.sin(angle),point.longitudinal,effectiveRadius*(1-Math.cos(angle))],issues:[]};}const target=Math.asin((scene.solidType==="cone"?scene.dimensions.radius:scene.dimensions.largeRadius-scene.dimensions.smallRadius)/scene.dimensions.slantHeight),gamma=Math.PI/2+(target-Math.PI/2)*scene.progress,beta=Math.atan2(developed.value.point[1],developed.value.point[0]),azimuth=beta/Math.sin(gamma),rho=point.longitudinal;return{status:"PASS",value:[rho*Math.sin(gamma)*Math.cos(azimuth),rho*Math.sin(gamma)*Math.sin(azimuth),rho*Math.cos(gamma)],issues:[]};}

const n=(value:number)=>Number(value.toFixed(6)).toString();
export function developableNetToSvg(scene:DevelopableFoldScene){const primitives=scene.net.primitives.map(item=>item.type==="rectangle"?`<rect id="${item.id}" x="${n(item.origin[0])}" y="${n(item.origin[1])}" width="${n(item.width)}" height="${n(item.height)}"/>`:item.type==="circle"?`<circle id="${item.id}" cx="${n(item.center[0])}" cy="${n(item.center[1])}" r="${n(item.radius)}"/>`:`<path id="${item.id}" data-net-primitive="${item.type}" data-angle="${n(item.angleRadians)}" data-${item.type==="sector"?"radius":"outer-radius"}="${n(item.type==="sector"?item.radius:item.outerRadius)}"/>`);return{status:"PASS" as const,output:`<svg xmlns="http://www.w3.org/2000/svg">${primitives.join("")}</svg>`};}
export function developableNetToTikz(scene:DevelopableFoldScene){const primitives=scene.net.primitives.map(item=>item.type==="rectangle"?`\\draw (${n(item.origin[0])},${n(item.origin[1])}) rectangle ++(${n(item.width)},${n(item.height)});`:item.type==="circle"?`\\draw (${n(item.center[0])},${n(item.center[1])}) circle (${n(item.radius)});`:`% ${item.type} radius data, angle=${n(item.angleRadians)} rad`);return{status:"PASS" as const,output:["\\begin{tikzpicture}",...primitives,"\\end{tikzpicture}"].join("\n")};}
export function createDevelopableManimBoundary(scene:DevelopableFoldScene){return{status:"PARTIAL" as const,available:false,scene,issues:[{code:"UNAVAILABLE_RENDERER",severity:"warning" as const,path:"renderer.manim",message:"Developable scene is ready for the future Manim curved-surface adapter."}] as FoldIssue[]};}
