import { DependencyGraph, type MathConstraint, type MathEntity, type MathScene } from "../math-ir/index.js";
import { CONSTRUCTION_TOOLS, applySessionCommand, createConstructionSession, deserializeConstructionSession, eligibleTools, inferSnaps, redoSession, serializeConstructionSession, undoSession, type ConstructionCommand, type ConstructionCommandId, type ConstructionSession, type SnapCandidate, type Vec2, type Vec3 } from "../dynamic-geometry/index.js";
import { adaptRenderSnapshot, analyzeDegreesOfFreedom, createRenderSnapshot, orchestrateConstraints, type AdapterKind, type ConstraintDiagnostic, type RenderSnapshot } from "../constraint-orchestration/index.js";

export type WorkspaceMode="2D"|"3D"|"LINKED"|"FOLD";
export type WorkspaceToolCategory="SELECT"|"POINT"|"LINE"|"CIRCLE"|"POLYGON"|"CONSTRUCTION"|"TRANSFORM"|"CONSTRAINT"|"THREE_D"|"FOLD";
export interface WorkspaceTool{id:string;label:string;category:WorkspaceToolCategory;dimension:"2d"|"3d"|"both";requiredInputs:number;allowedInputTypes:string[][];outputTypes:string[];shortcut?:string;commandId?:ConstructionCommandId;iconKey:string;helpKey:string;}
const labels:Partial<Record<ConstructionCommandId,string>>={CREATE_FREE_POINT:"Point",CREATE_POINT_ON_OBJECT:"Point on Object",CREATE_LINE:"Line",CREATE_RAY:"Ray",CREATE_SEGMENT:"Segment",CREATE_CIRCLE_CENTER_RADIUS:"Circle: Center + Radius",CREATE_CIRCLE_CENTER_POINT:"Circle: Center + Point",CREATE_POLYGON:"Polygon",CREATE_MIDPOINT:"Midpoint",CREATE_INTERSECTION:"Intersection",CREATE_PROJECTION:"Projection",CREATE_PARALLEL_LINE:"Parallel",CREATE_PERPENDICULAR_LINE:"Perpendicular",TRANSLATE_OBJECT:"Translate",ROTATE_OBJECT:"Rotate",REFLECT_OBJECT:"Reflect",SCALE_OBJECT:"Scale",CREATE_FREE_POINT_3D:"Point 3D",CREATE_LINE_3D:"Line 3D",CREATE_SEGMENT_3D:"Segment 3D",CREATE_PLANE:"Plane",PROJECT_POINT_TO_PLANE:"Project to Plane",CREATE_LINE_PLANE_INTERSECTION:"Line-Plane Intersection"};
const category=(id:ConstructionCommandId):WorkspaceToolCategory=>id.includes("3D")||id.includes("PLANE")?"THREE_D":id.includes("POINT")?"POINT":id.includes("LINE")||id.includes("RAY")||id.includes("SEGMENT")?"LINE":id.includes("CIRCLE")?"CIRCLE":id.includes("POLYGON")?"POLYGON":id.includes("TRANSLATE")||id.includes("ROTATE")||id.includes("REFLECT")||id.includes("SCALE")?"TRANSFORM":"CONSTRUCTION";
export const WORKSPACE_TOOL_REGISTRY:readonly WorkspaceTool[]=[{id:"SELECT",label:"Select",category:"SELECT",dimension:"both",requiredInputs:0,allowedInputTypes:[],outputTypes:[],shortcut:"V",iconKey:"cursor",helpKey:"workspace.select"},...CONSTRUCTION_TOOLS.filter(x=>labels[x.id]).map(tool=>({id:tool.id,label:labels[tool.id]!,category:category(tool.id),dimension:tool.id.includes("3D")||tool.id.includes("PLANE")?"3d":"2d",requiredInputs:tool.requiredInputs,allowedInputTypes:tool.allowedInputTypes,outputTypes:tool.outputTypes,commandId:tool.id,iconKey:tool.id.toLowerCase(),helpKey:`workspace.${tool.id.toLowerCase()}`} as WorkspaceTool)),{id:"CONSTRAINT",label:"Constraint",category:"CONSTRAINT",dimension:"both",requiredInputs:2,allowedInputTypes:[[],[]],outputTypes:[],shortcut:"K",iconKey:"constraint",helpKey:"workspace.constraint"},{id:"FOLD_MODE",label:"Fold",category:"FOLD",dimension:"both",requiredInputs:0,allowedInputTypes:[],outputTypes:[],iconKey:"fold",helpKey:"workspace.fold"}] as const;

export interface WorkspaceViewState{activeToolId:string;selection:string[];hoverId?:string;candidate?:SnapCandidate;dragState?:{objectId:string;start:Vec2|Vec3;candidate:Vec2|Vec3};viewport:{minX:number;maxX:number;minY:number;maxY:number};camera:{position:Vec3;target:Vec3;zoom:number};grid:{visible:boolean;size:number};snap:{enabled:boolean;tolerance:number};activeInspectorTab:"PROPERTIES"|"DEPENDENCIES"|"CONSTRAINTS"|"EXPORT";panels:{toolbar:boolean;inspector:boolean};mode:WorkspaceMode;toolInputs:string[];message:string;lastDiagnostics:ConstraintDiagnostic[];}
export interface DynamicMathWorkspace{session:ConstructionSession;view:WorkspaceViewState;renderSnapshot:RenderSnapshot;}
export interface WorkspaceResult{status:"PASS"|"FAIL";workspace:DynamicMathWorkspace;error?:{code:string;message:string};createdIds:string[];updatedIds:string[];}
const defaultView=():WorkspaceViewState=>({activeToolId:"SELECT",selection:[],viewport:{minX:-10,maxX:10,minY:-10,maxY:10},camera:{position:[8,8,8],target:[0,0,0],zoom:1},grid:{visible:true,size:1},snap:{enabled:true,tolerance:.35},activeInspectorTab:"PROPERTIES",panels:{toolbar:true,inspector:true},mode:"2D",toolInputs:[],message:"Ready",lastDiagnostics:[]});
export function createDynamicMathWorkspace(scene:MathScene,view:Partial<WorkspaceViewState>={}):DynamicMathWorkspace{const next={...defaultView(),...view};return{session:createConstructionSession(scene),view:next,renderSnapshot:createRenderSnapshot(scene)};}
const result=(workspace:DynamicMathWorkspace,status:"PASS"|"FAIL",createdIds:string[]=[],updatedIds:string[]=[],error?:WorkspaceResult["error"]):WorkspaceResult=>({status,workspace,createdIds,updatedIds,...(error?{error}:{})});
const refresh=(workspace:DynamicMathWorkspace,session:ConstructionSession,view:WorkspaceViewState=workspace.view):DynamicMathWorkspace=>({...workspace,session,view:{...view,selection:view.selection.filter(id=>session.scene.entities.some(x=>x.id===id))},renderSnapshot:createRenderSnapshot(session.scene,workspace.renderSnapshot)});
export function selectObjects(workspace:DynamicMathWorkspace,ids:string[],mode:"REPLACE"|"ADD"|"TOGGLE"|"CLEAR"="REPLACE"):DynamicMathWorkspace{const valid=ids.filter(id=>workspace.session.scene.entities.some(x=>x.id===id)),current=workspace.view.selection;let selection:string[]=[];if(mode==="ADD")selection=[...new Set([...current,...valid])];else if(mode==="TOGGLE")selection=valid.reduce((next,id)=>next.includes(id)?next.filter(x=>x!==id):[...next,id],[...current]);else if(mode!=="CLEAR")selection=[...new Set(valid)];return{...workspace,view:{...workspace.view,selection}};}
export function pickSemanticObject(workspace:DynamicMathWorkspace,pick:{semanticObjectId?:string;rendererObjectId?:string}):DynamicMathWorkspace{const id=pick.semanticObjectId??workspace.renderSnapshot.objects.find(x=>x.rendererObjectId===pick.rendererObjectId)?.id;return id?selectObjects(workspace,[id]):selectObjects(workspace,[],"CLEAR");}
export function setActiveTool(workspace:DynamicMathWorkspace,toolId:string):WorkspaceResult{if(!WORKSPACE_TOOL_REGISTRY.some(x=>x.id===toolId))return result(workspace,"FAIL",[],[],{code:"INVALID_TOOL_INPUT",message:`Unknown tool ${toolId}`});return result({...workspace,view:{...workspace.view,activeToolId:toolId,toolInputs:[],candidate:undefined,message:`${toolId} active`}},"PASS");}
export function cancelWorkspaceTransient(workspace:DynamicMathWorkspace):DynamicMathWorkspace{return{...workspace,view:{...workspace.view,activeToolId:"SELECT",toolInputs:[],candidate:undefined,dragState:undefined,message:"Cancelled"}};}
export function previewSnap(workspace:DynamicMathWorkspace,candidate:Vec2):DynamicMathWorkspace{const snap=workspace.view.snap.enabled?inferSnaps(workspace.session.scene,candidate,workspace.view.snap.tolerance)[0]:undefined;return{...workspace,view:{...workspace.view,candidate:snap,message:snap?`SNAP_PREVIEW: ${snap.kind}`:"Ready"}};}
export function executeWorkspaceCommand(workspace:DynamicMathWorkspace,command:ConstructionCommand):WorkspaceResult{const applied=applySessionCommand(workspace.session,command);if(!applied.result.scene)return result({...workspace,view:{...workspace.view,message:applied.result.issues[0]?.message??"Command rejected"}},"FAIL",[],[],{code:applied.result.issues[0]?.code??"UNSUPPORTED_OPERATION",message:applied.result.issues[0]?.message??"Command rejected"});const next=refresh(workspace,applied.session,{...workspace.view,selection:applied.result.createdIds.length?applied.result.createdIds:command.inputIds??[],toolInputs:[],candidate:undefined,message:`${command.id}: PASS`});return result(next,"PASS",applied.result.createdIds,applied.result.updatedIds);}
export function acceptToolInput(workspace:DynamicMathWorkspace,objectId:string):WorkspaceResult{const tool=WORKSPACE_TOOL_REGISTRY.find(x=>x.id===workspace.view.activeToolId);if(!tool?.commandId)return result(workspace,"FAIL",[],[],{code:"INVALID_TOOL_INPUT",message:"Active tool does not accept object inputs"});const entity=workspace.session.scene.entities.find(x=>x.id===objectId),index=workspace.view.toolInputs.length,allowed=tool.allowedInputTypes[index]??[];if(!entity||allowed.length&&!allowed.includes(entity.type))return result(workspace,"FAIL",[],[],{code:"INVALID_TOOL_INPUT",message:`Expected ${allowed.join("|")||"object"}`});const toolInputs=[...workspace.view.toolInputs,objectId];if(toolInputs.length<tool.requiredInputs)return result({...workspace,view:{...workspace.view,toolInputs,message:`Next input ${toolInputs.length+1}/${tool.requiredInputs}`}},"PASS");return executeWorkspaceCommand(workspace,{id:tool.commandId,inputIds:toolInputs});}
export function availableContextActions(workspace:DynamicMathWorkspace):Array<{id:ConstructionCommandId;available:boolean;reason?:string}>{const ids=workspace.view.selection,tools=eligibleTools(workspace.session.scene,ids);return(["RENAME_OBJECT","SET_VISIBILITY","DELETE_OBJECT","TRANSLATE_OBJECT","ROTATE_OBJECT","REFLECT_OBJECT","SCALE_OBJECT"] as ConstructionCommandId[]).map(id=>({id,available:ids.length===1&&!!tools.find(x=>x.id===id)?.available,...(ids.length!==1?{reason:"Select one semantic object"}:{})}));}
export function dragWorkspaceObject(workspace:DynamicMathWorkspace,objectId:string,position:Vec2|Vec3):WorkspaceResult{const object=workspace.session.scene.entities.find(x=>x.id===objectId),dof=analyzeDegreesOfFreedom(workspace.session.scene,objectId);if(!object||object.type!=="point")return result(workspace,"FAIL",[],[],{code:"DEPENDENT_OBJECT_NOT_DRAGGABLE",message:"Only semantic points can be dragged"});if(dof.classification==="DEPENDENT"||dof.classification==="FIXED_0D")return result(workspace,"FAIL",[],[],{code:dof.classification==="FIXED_0D"?"FIXED_OBJECT":"DEPENDENT_OBJECT_NOT_DRAGGABLE",message:`${dof.classification} object cannot be dragged directly`});const constrained=workspace.session.scene.constraints.some(c=>c.mode==="LOCKED"&&c.entityIds[0]===objectId);if(!constrained)return executeWorkspaceCommand(workspace,{id:"MOVE_POINT",inputIds:[objectId],parameters:{position}});const orchestrated=orchestrateConstraints(workspace.session.scene,{objectId,position});if(orchestrated.status==="FAIL")return result({...workspace,view:{...workspace.view,lastDiagnostics:orchestrated.constraintResults,message:orchestrated.issues[0]?.message??"Drag rejected"}},"FAIL",[],[],{code:orchestrated.issues[0]?.code??"CONSTRAINT_CONFLICT",message:orchestrated.issues[0]?.message??"Drag rejected"});const session:{scene:MathScene;selectedIds:string[];toolInputs:string[];history:MathScene[];future:MathScene[]}={...workspace.session,scene:orchestrated.updatedScene,history:[...workspace.session.history,structuredClone(workspace.session.scene)],future:[]};return result(refresh(workspace,session,{...workspace.view,lastDiagnostics:orchestrated.constraintResults,message:"Constraint drag: PASS"}),"PASS",[],orchestrated.affectedIds);}
export function addWorkspaceConstraint(workspace:DynamicMathWorkspace,constraint:MathConstraint):WorkspaceResult{if(workspace.session.scene.constraints.some(x=>x.id===constraint.id))return result(workspace,"FAIL",[],[],{code:"INVALID_INPUT",message:"Duplicate constraint ID"});const scene={...workspace.session.scene,constraints:[...workspace.session.scene.constraints,structuredClone(constraint)]},session={...workspace.session,scene,history:[...workspace.session.history,structuredClone(workspace.session.scene)],future:[]};return result(refresh(workspace,session,{...workspace.view,message:`Constraint ${constraint.id} added`}),"PASS");}
export function removeWorkspaceConstraint(workspace:DynamicMathWorkspace,id:string):WorkspaceResult{if(!workspace.session.scene.constraints.some(x=>x.id===id))return result(workspace,"FAIL",[],[],{code:"INVALID_INPUT",message:"Constraint not found"});const scene={...workspace.session.scene,constraints:workspace.session.scene.constraints.filter(x=>x.id!==id)},session={...workspace.session,scene,history:[...workspace.session.history,structuredClone(workspace.session.scene)],future:[]};return result(refresh(workspace,session,{...workspace.view,message:`Constraint ${id} removed`}),"PASS");}
export function updateWorkspaceConstraint(workspace:DynamicMathWorkspace,id:string,patch:Partial<Omit<MathConstraint,"id">>):WorkspaceResult{const current=workspace.session.scene.constraints.find(x=>x.id===id);if(!current)return result(workspace,"FAIL",[],[],{code:"INVALID_INPUT",message:"Constraint not found"});const constraint={...current,...structuredClone(patch),id},scene={...workspace.session.scene,constraints:workspace.session.scene.constraints.map(x=>x.id===id?constraint:x)},session={...workspace.session,scene,history:[...workspace.session.history,structuredClone(workspace.session.scene)],future:[]};return result(refresh(workspace,session,{...workspace.view,message:`Constraint ${id} updated`}),"PASS",[],constraint.entityIds);}
export function executeContextAction(workspace:DynamicMathWorkspace,id:ConstructionCommandId,parameters:Record<string,unknown>={}):WorkspaceResult{if(workspace.view.selection.length!==1)return result(workspace,"FAIL",[],[],{code:"INVALID_TOOL_INPUT",message:"Select one semantic object"});const action=availableContextActions(workspace).find(x=>x.id===id);if(!action?.available)return result(workspace,"FAIL",[],[],{code:"INVALID_TOOL_INPUT",message:action?.reason??`${id} is unavailable`});return executeWorkspaceCommand(workspace,{id,inputIds:[workspace.view.selection[0]],parameters});}
export function setWorkspaceInspectorTab(workspace:DynamicMathWorkspace,activeInspectorTab:WorkspaceViewState["activeInspectorTab"]):DynamicMathWorkspace{return{...workspace,view:{...workspace.view,activeInspectorTab}};}
export function beginWorkspaceDrag(workspace:DynamicMathWorkspace,objectId:string,start:Vec2|Vec3):WorkspaceResult{const object=workspace.session.scene.entities.find(x=>x.id===objectId),dof=analyzeDegreesOfFreedom(workspace.session.scene,objectId);if(!object||object.type!=="point"||["DEPENDENT","FIXED_0D"].includes(dof.classification))return result(workspace,"FAIL",[],[],{code:dof.classification==="FIXED_0D"?"FIXED_OBJECT":"DEPENDENT_OBJECT_NOT_DRAGGABLE",message:"Object cannot begin a direct drag"});return result({...workspace,view:{...workspace.view,dragState:{objectId,start,candidate:start},selection:[objectId],message:"Dragging"}},"PASS");}
export function updateWorkspaceDrag(workspace:DynamicMathWorkspace,position:Vec2|Vec3):DynamicMathWorkspace{return workspace.view.dragState?{...workspace,view:{...workspace.view,dragState:{...workspace.view.dragState,candidate:position}}}:workspace;}
export function commitWorkspaceDrag(workspace:DynamicMathWorkspace):WorkspaceResult{const drag=workspace.view.dragState;if(!drag)return result(workspace,"FAIL",[],[],{code:"INVALID_TOOL_INPUT",message:"No active drag"});const applied=dragWorkspaceObject(workspace,drag.objectId,drag.candidate);return{...applied,workspace:{...applied.workspace,view:{...applied.workspace.view,dragState:undefined}}};}
export function undoWorkspace(workspace:DynamicMathWorkspace):DynamicMathWorkspace{return refresh(workspace,undoSession(workspace.session),{...workspace.view,message:"Undo"});}
export function redoWorkspace(workspace:DynamicMathWorkspace):DynamicMathWorkspace{return refresh(workspace,redoSession(workspace.session),{...workspace.view,message:"Redo"});}
export function handleWorkspaceKey(workspace:DynamicMathWorkspace,key:string,options:{ctrlKey?:boolean;metaKey?:boolean;shiftKey?:boolean}={}):WorkspaceResult{const command=options.ctrlKey||options.metaKey;if(command&&key.toLowerCase()==="z")return result(options.shiftKey?redoWorkspace(workspace):undoWorkspace(workspace),"PASS");if(command&&key.toLowerCase()==="y")return result(redoWorkspace(workspace),"PASS");if(key==="Escape")return result(cancelWorkspaceTransient(workspace),"PASS");if((key==="Delete"||key==="Backspace")&&workspace.view.selection.length===1)return executeContextAction(workspace,"DELETE_OBJECT");const tool=WORKSPACE_TOOL_REGISTRY.find(x=>x.shortcut?.toLowerCase()===key.toLowerCase());return tool?setActiveTool(workspace,tool.id):result(workspace,"FAIL",[],[],{code:"INVALID_TOOL_INPUT",message:`No workspace action for ${key}`});}
export function inspectWorkspaceObject(workspace:DynamicMathWorkspace,id:string){const object=workspace.session.scene.entities.find(x=>x.id===id);if(!object)return;const graph=new DependencyGraph(workspace.session.scene.semantics?.dependencies??[]),definition=object.metadata?.adapterMetadata?.construction as {sourceIds?:string[];freedom?:string;parameters?:Record<string,unknown>}|undefined;return{id:object.id,label:object.label,type:object.type,dimension:object.semanticCoordinate?.dimension??workspace.session.scene.dimension,freedom:definition?.freedom??"FREE",construction:definition,parents:graph.directDependencies(id),children:graph.dependents(id),transitiveDependents:graph.recomputationOrder([id]),constraints:workspace.session.scene.constraints.filter(c=>c.entityIds.includes(id)),dof:analyzeDegreesOfFreedom(workspace.session.scene,id),visible:object.metadata?.adapterMetadata?.visible!==false};}
export function setWorkspaceMode(workspace:DynamicMathWorkspace,mode:WorkspaceMode):DynamicMathWorkspace{return{...workspace,view:{...workspace.view,mode,message:`${mode} workspace`}};}
export function setWorkspaceCamera(workspace:DynamicMathWorkspace,camera:WorkspaceViewState["camera"]):DynamicMathWorkspace{return{...workspace,view:{...workspace.view,camera}};}
export function exportWorkspace(workspace:DynamicMathWorkspace,kind:AdapterKind){return adaptRenderSnapshot(workspace.renderSnapshot,kind);}
export function serializeWorkspace(workspace:DynamicMathWorkspace):string{return JSON.stringify({schemaVersion:"dynamic-workspace/v1",math:serializeConstructionSession(workspace.session),view:{...workspace.view,candidate:undefined,dragState:undefined,lastDiagnostics:[]}});}
export function deserializeWorkspace(value:string):DynamicMathWorkspace{const parsed=JSON.parse(value) as {schemaVersion:string;math:string;view:WorkspaceViewState};if(parsed.schemaVersion!=="dynamic-workspace/v1")throw new Error("UNSUPPORTED_WORKSPACE_VERSION");const session=deserializeConstructionSession(parsed.math);return{session,view:{...defaultView(),...parsed.view},renderSnapshot:createRenderSnapshot(session.scene)};}
