import { execFileSync } from "node:child_process";
import { existsSync, mkdirSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { KNTT_SOURCE_DEFINITIONS, resolveNlsSourceRoot } from "./definitions.js";
import { registerKnttSources } from "./registry.js";

export type StructureNodeType = "BOOK" | "CHAPTER" | "LESSON" | "SECTION";
export type StructureConfidence = "VERIFIED" | "HIGH_CONFIDENCE" | "NEEDS_REVIEW" | "UNKNOWN";
export type VerificationStatus = "VERIFIED" | "NEEDS_REVIEW" | "UNKNOWN";
export type EvidenceStatus = "VERIFIED" | "DERIVED" | "NEEDS_REVIEW" | "UNKNOWN";
export interface StructureEvidence { sourceId: string; pdfPageNumber: number; printedPageNumber?: number; evidenceType: "TOC_OCR" | "BOUNDARY_OCR" | "HUMAN_SOURCE_REVIEW"; ocrConfidence?: StructureConfidence; detectedHeading: string; }
export interface StructureNode { id: string; sourceId: string; nodeType: StructureNodeType; grade: 10 | 11 | 12; title: string; parentId: string | null; order: number; pdfStartPage: number | null; pdfEndPage: number | null; printedStartPage: number | null; printedEndPage: number | null; confidence: StructureConfidence; verificationStatus: VerificationStatus; evidence: StructureEvidence[]; titleStatus?: EvidenceStatus; orderStatus?: EvidenceStatus; startBoundaryStatus?: EvidenceStatus; endBoundaryStatus?: EvidenceStatus; sourceTraceabilityStatus?: EvidenceStatus; structureUsable?: boolean; lessons?: StructureNode[]; }
export interface StructureBook extends StructureNode { nodeType: "BOOK"; parentId: null; volumeType: string; pageCount: number; chapters: StructureNode[]; }
export interface StructureManifest { schemaVersion: 1; sourceRegistryVersion: 1; strategy: "TOC_FIRST_SELECTIVE_OCR"; fullBookOcr: false; totalPdfPages: number; ocrPagesTotal: number; ocrPageRatio: number; books: StructureBook[]; }

const normalize = (value: string): string => value.normalize("NFD").replace(/[\u0300-\u036f]/g, "").toUpperCase().replace(/Đ/g, "D");
const marker = (value: string): boolean => /^(?:CHƯƠNG|CHUONG|CHUYÊN ĐỀ|CHUYEN DE)\b/i.test(value.trim()) || /^BÀI\s+\d+/i.test(value.trim());
const printedPage = (value: string): number | null => { const match = /(?:^|\s)(\d{1,3})\s*$/.exec(value); return match ? Number(match[1]) : null; };

function parseHeadings(sourceId: string, grade: 10 | 11 | 12, text: string, tocPage: number): StructureNode[] {
  const lines = text.split(/\r?\n/).map((line) => line.replace(/[|*_`]/g, " ").replace(/\s+/g, " ").trim()).filter(Boolean); const chapters: StructureNode[] = []; let current: StructureNode | undefined;
  for (let index = 0; index < lines.length; index += 1) { const line = lines[index]; const chapterMatch = /^(CHƯƠNG|CHUONG|CHUYÊN ĐỀ|CHUYEN DE)\s+([IVXLC]+|\d+)\.?\s*(.*)$/i.exec(line) || /^(CHUONG|CHUYEN DE)\s+([IVXLC]+|\d+)\.?\s*(.*)$/i.exec(normalize(line)); if (chapterMatch) { const chapterTitle = chapterMatch[3].trim() || (lines[index + 1] && !marker(lines[index + 1]) ? lines[++index] : ""); current = { id: `${sourceId}-CH${String(chapters.length + 1).padStart(2, "0")}`, sourceId, nodeType: "CHAPTER", grade, title: chapterTitle || `CHƯƠNG ${chapterMatch[2]}`, parentId: `${sourceId}-BOOK`, order: chapters.length + 1, pdfStartPage: null, pdfEndPage: null, printedStartPage: null, printedEndPage: null, confidence: chapterTitle ? "NEEDS_REVIEW" : "UNKNOWN", verificationStatus: "NEEDS_REVIEW", evidence: [{ sourceId, pdfPageNumber: tocPage, evidenceType: "TOC_OCR", ocrConfidence: chapterTitle ? "NEEDS_REVIEW" : "UNKNOWN", detectedHeading: line }], lessons: [] }; chapters.push(current); continue; }
    const lessonMatch = /^BÀI\s+(\d+)\.\s*(.*)$/i.exec(line) || /^BAI\s+(\d+)\.\s*(.*)$/i.exec(normalize(line)); if (lessonMatch && current) { let titleAndPage = lessonMatch[2].trim(); let next = lines[index + 1]; while (next && !marker(next) && !/^(?:Bảng|Bang|Hoạt động|HOẠT ĐỘNG|Bài tập)/i.test(next) && printedPage(titleAndPage) === null && titleAndPage.length < 90) { titleAndPage = `${titleAndPage} ${next}`.trim(); index += 1; next = lines[index + 1]; } const page = printedPage(titleAndPage); if (page !== null) titleAndPage = titleAndPage.replace(new RegExp(`\\s${page}$`), "").trim(); const lessons = current.lessons!; lessons.push({ id: `${current.id}-L${String(lessons.length + 1).padStart(2, "0")}`, sourceId, nodeType: "LESSON", grade, title: titleAndPage || `Bài ${lessonMatch[1]}`, parentId: current.id, order: lessons.length + 1, pdfStartPage: null, pdfEndPage: null, printedStartPage: page, printedEndPage: null, confidence: page !== null && titleAndPage.length > 3 ? "NEEDS_REVIEW" : "UNKNOWN", verificationStatus: "NEEDS_REVIEW", evidence: [{ sourceId, pdfPageNumber: tocPage, ...(page !== null ? { printedPageNumber: page } : {}), evidenceType: "TOC_OCR", ocrConfidence: page !== null ? "NEEDS_REVIEW" : "UNKNOWN", detectedHeading: line }] }); }
  }
  if (chapters.length === 0 && /-CD$/.test(sourceId)) for (let i = 1; i <= 3; i += 1) chapters.push({ id: `${sourceId}-CH${String(i).padStart(2, "0")}`, sourceId, nodeType: "CHAPTER", grade, title: `CHUYÊN ĐỀ ${i}`, parentId: `${sourceId}-BOOK`, order: i, pdfStartPage: null, pdfEndPage: null, printedStartPage: null, printedEndPage: null, confidence: "UNKNOWN", verificationStatus: "NEEDS_REVIEW", evidence: [{ sourceId, pdfPageNumber: tocPage, evidenceType: "TOC_OCR", ocrConfidence: "UNKNOWN", detectedHeading: "SPECIALIZED_TOPIC_FALLBACK" }], lessons: [] });
  return chapters;
}

function ocrPage(sourcePath: string, sourceSha: string, page: number, cacheRoot: string, tessdata: string): string { const cache = join(cacheRoot, sourceSha, `page-${String(page).padStart(4, "0")}.txt`); mkdirSync(join(cacheRoot, sourceSha), { recursive: true }); if (existsSync(cache)) return readFileSync(cache, "utf8"); const base = join(cacheRoot, sourceSha, `page-${String(page).padStart(4, "0")}`); execFileSync("pdftoppm", ["-f", String(page), "-l", String(page), "-singlefile", "-jpeg", "-r", "200", sourcePath, base], { windowsHide: true, stdio: "ignore" }); const text = execFileSync("tesseract", [`${base}.jpg`, "stdout", "--tessdata-dir", tessdata, "-l", "vie+eng", "--psm", "6"], { encoding: "utf8", windowsHide: true }); writeFileSync(cache, text, "utf8"); rmSync(`${base}.jpg`, { force: true }); return text; }

export function discoverKnttStructure(options: { sourceRoot?: string; cacheRoot?: string; tessdata?: string; frontMatterPages?: number } = {}): StructureManifest { if (options.frontMatterPages !== undefined && (options.frontMatterPages < 1 || options.frontMatterPages > 30)) throw new Error("OCR_SCOPE_EXCEEDED"); const sourceRoot = options.sourceRoot ?? resolveNlsSourceRoot(); const cacheRoot = options.cacheRoot ?? join(process.env.LOCALAPPDATA ?? process.cwd(), "MathAIStudio", "nls-ocr-cache", "tesseract-5.4.0-vie-eng-r200-psm6"); const tessdata = options.tessdata ?? join(process.env.LOCALAPPDATA ?? process.cwd(), "MathAIStudio", "nls-ocr-tools", "tessdata"); const frontMatterPages = options.frontMatterPages ?? 15; const registry = registerKnttSources(sourceRoot); const books: StructureBook[] = []; for (const source of registry.sources) { const pages = Math.min(frontMatterPages, source.pageCount); const texts = Array.from({ length: pages }, (_, i) => ocrPage(join(sourceRoot, source.filename), source.sha256, i + 1, cacheRoot, tessdata)); const tocIndex = texts.findIndex((text) => /MỤC LỤC|MỤC LỤ|UC LUC|CHƯƠNG I|CHUONG I|CHUYÊN ĐỀ 1|CHUYEN DE 1/i.test(normalize(text))); const tocPage = tocIndex >= 0 ? tocIndex + 1 : 1; const chapters = parseHeadings(source.sourceId, source.grade, texts.slice(tocIndex >= 0 ? tocIndex : 0, tocIndex >= 0 ? Math.min(tocIndex + 3, texts.length) : texts.length).join("\n"), tocPage); books.push({ id: `${source.sourceId}-BOOK`, sourceId: source.sourceId, nodeType: "BOOK", grade: source.grade, title: source.filename.replace(/\.pdf$/i, ""), parentId: null, order: books.length + 1, pdfStartPage: 1, pdfEndPage: source.pageCount, printedStartPage: null, printedEndPage: null, confidence: "HIGH_CONFIDENCE", verificationStatus: "VERIFIED", evidence: [{ sourceId: source.sourceId, pdfPageNumber: tocPage, evidenceType: "TOC_OCR", ocrConfidence: tocIndex >= 0 ? "HIGH_CONFIDENCE" : "UNKNOWN", detectedHeading: tocIndex >= 0 ? "MỤC LỤC" : "FRONT_MATTER" }], volumeType: source.volumeType, pageCount: source.pageCount, chapters }); } const totalPdfPages = registry.sources.reduce((total, source) => total + source.pageCount, 0); const ocrPagesTotal = registry.sources.reduce((total, source) => total + Math.min(frontMatterPages, source.pageCount), 0); return { schemaVersion: 1, sourceRegistryVersion: 1, strategy: "TOC_FIRST_SELECTIVE_OCR", fullBookOcr: false, totalPdfPages, ocrPagesTotal, ocrPageRatio: Number((ocrPagesTotal / totalPdfPages).toFixed(6)), books }; }

export function validateStructureManifest(manifest: StructureManifest, registeredSourceIds: readonly string[] = KNTT_SOURCE_DEFINITIONS.map((item) => item.sourceId)): void { if (manifest.schemaVersion !== 1 || manifest.sourceRegistryVersion !== 1 || manifest.fullBookOcr !== false) throw new Error("STRUCTURE_SCHEMA_INVALID"); if (manifest.books.length !== registeredSourceIds.length || new Set(manifest.books.map((book) => book.sourceId)).size !== manifest.books.length || new Set(manifest.books.map((book) => book.sourceId)).size !== new Set(registeredSourceIds).size || registeredSourceIds.some((sourceId) => !manifest.books.some((book) => book.sourceId === sourceId))) throw new Error("STRUCTURED_SOURCE_SET_INVALID"); const ids = new Set<string>(); const walk = (node: StructureNode, parent: StructureNode | null) => { if (ids.has(node.id)) throw new Error("DUPLICATE_STRUCTURE_ID"); ids.add(node.id); if (node.parentId !== (parent?.id ?? null)) throw new Error("STRUCTURE_PARENT_INVALID"); if (node.order < 1) throw new Error("STRUCTURE_ORDER_INVALID"); if (node.pdfStartPage !== null && node.pdfEndPage !== null && (node.pdfStartPage < 1 || node.pdfStartPage > node.pdfEndPage)) throw new Error("STRUCTURE_PAGE_RANGE_INVALID"); if (node.verificationStatus === "VERIFIED" && node.evidence.length === 0) throw new Error("VERIFIED_WITHOUT_EVIDENCE"); }; for (const book of manifest.books) { if (book.nodeType !== "BOOK" || book.pdfEndPage !== book.pageCount) throw new Error("BOOK_PAGE_RANGE_INVALID"); walk(book, null); for (const chapter of book.chapters) { walk(chapter, book); for (const lesson of chapter.lessons ?? []) walk(lesson, chapter); } } }
export const serializeStructureManifest = (manifest: StructureManifest): string => `${JSON.stringify(manifest, null, 2)}\n`;
