import assert from "node:assert/strict";
import { execFileSync } from "node:child_process";
import { createHash } from "node:crypto";
import { mkdtempSync, readFileSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { createSceneGraph, createSceneNode } from "../image-animation/core/scene-graph/index.js";
import { createAnimationTimeline } from "../image-animation/core/timeline/index.js";
import { compileManim } from "../image-animation/renderers/manim/index.js";
import { routeMotion } from "../image-animation/renderers/router/index.js";
import { PythonManimRendererAdapter } from "../server/adapters/rendererAdapter.js";
const graph = createSceneGraph([createSceneNode({ identity: { id: "marker" }, geometry: { kind: "point", x: -2, y: 0 }, style: { fill: "YELLOW" } }), createSceneNode({ identity: { id: "result" }, geometry: { kind: "label", position: { x: 0, y: -2 }, text: "x = 2" } })]);
const timeline = createAnimationTimeline([{ id: "move", type: "move", targetId: "marker", start: 0, duration: 1.5, to: { x: 2, y: 0 } }, { id: "show", type: "appear", targetId: "result", start: 1.5, duration: 0.5 }], graph);
const compilation = compileManim(graph, { sceneClassName: "Phase4A3Timeline", timeline });
const route = routeMotion({ id: "phase4a3", geometryAuthority: "exact", requestedRenderer: "auto" }, { deterministicRenderer: "manim", generativeEnabled: false }); assert.equal(route.status, "ready"); if (route.status !== "ready") throw new Error("Renderer route denied."); assert.equal(route.renderer, "manim");
const adapter = new PythonManimRendererAdapter(); const job = await adapter.submitRenderJob({ jobId: "phase4a3", outputFormat: "mp4", resolution: "720p", fps: 30, videoSpec: { manim_python_code: compilation.source } as never });
assert.equal(job.status, "COMPLETED", job.errorMessage); const artifact = (job.artifacts as Array<{ pathOrUrl: string; sizeBytes: number }>).find(item => item.pathOrUrl.endsWith("render.mp4")); assert.ok(artifact && artifact.sizeBytes > 0);
const response = await fetch(new URL(artifact.pathOrUrl, "http://127.0.0.1:8765")); const bytes = new Uint8Array(await response.arrayBuffer()); const dir = mkdtempSync(join(tmpdir(), "phase4a3-")); const mp4 = join(dir, "timeline.mp4"); writeFileSync(mp4, bytes);
const probe = JSON.parse(execFileSync("ffprobe", ["-v", "error", "-show_entries", "format=duration", "-show_entries", "stream=codec_type", "-of", "json", mp4], { encoding: "utf8" })); assert.ok(Number(probe.format.duration) > 0); assert.ok(probe.streams.some((s: { codec_type: string }) => s.codec_type === "video"));
const first = join(dir, "first.png"), last = join(dir, "last.png"); execFileSync("ffmpeg", ["-loglevel", "error", "-y", "-ss", "0.1", "-i", mp4, "-frames:v", "1", "-update", "1", first]); execFileSync("ffmpeg", ["-loglevel", "error", "-y", "-ss", "1.8", "-i", mp4, "-frames:v", "1", "-update", "1", last]); const hash = (file: string) => createHash("sha256").update(readFileSync(file)).digest("hex"); assert.notEqual(hash(first), hash(last));
console.log(`ANIMATION_NOT_STATIC_QA=PASS\nREAL_ANIMATION_PIPELINE_QA=PASS\nMANIM_RENDER_QA=PASS\nANIMATION_ARTIFACT_QA=PASS\nFFPROBE_QA=PASS\nPHASE_4A_3_MP4_PATH=${mp4}\nPHASE_4A_3_MP4_SIZE=${bytes.length}\nPHASE_4A_3_MP4_DURATION=${probe.format.duration}`);
