import assert from "node:assert/strict";
import { execFileSync } from "node:child_process";
import { mkdtempSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { PythonManimRendererAdapter } from "../server/adapters/rendererAdapter.js";
const url = "http://127.0.0.1:8765";
const adapter = new PythonManimRendererAdapter(url);
const capability = await adapter.capabilities();
assert.equal(capability.status, "READY"); assert.equal(capability.manimAvailable, true); assert.equal(capability.ffmpegAvailable, true);
const code = `from manim import *\nclass StudioRenderSmoke(Scene):\n    def construct(self):\n        self.play(Write(Text("Studio Render Smoke")))\n        self.wait(0.2)\n`;
const job = await adapter.submitRenderJob({ jobId: "studio-render-smoke", outputFormat: "mp4", resolution: "720p", fps: 30, videoSpec: { manim_python_code: code } as never });
assert.equal(job.status, "COMPLETED", job.errorMessage); assert.equal(job.exitCode, 0); assert.equal(job.rendererMode, "REAL_LOCAL");
const artifact = (job.artifacts as Array<{ pathOrUrl?: string; sizeBytes?: number }>).find(item => item.pathOrUrl?.endsWith("render.mp4"));
assert.ok(artifact?.pathOrUrl); assert.ok((artifact.sizeBytes ?? 0) > 0);
const response = await fetch(new URL(artifact.pathOrUrl, url)); assert.equal(response.ok, true);
const bytes = new Uint8Array(await response.arrayBuffer()); assert.ok(bytes.length > 0);
const directory = mkdtempSync(join(tmpdir(), "studio-render-smoke-")); const file = join(directory, "render.mp4"); writeFileSync(file, bytes);
const probe = JSON.parse(execFileSync("ffprobe", ["-v", "error", "-show_entries", "stream=codec_type", "-show_entries", "format=duration", "-of", "json", file], { encoding: "utf8", windowsHide: true }));
assert.ok(Number(probe.format.duration) > 0); assert.ok(probe.streams.some((stream: { codec_type: string }) => stream.codec_type === "video"));
console.log("BRIDGE_HEALTH_QA=PASS\nMANIM_RUNTIME_PROBE_QA=PASS\nFFMPEG_RUNTIME_QA=PASS\nREAL_RENDER_SMOKE_QA=PASS\nRENDER_SMOKE_ARTIFACT_QA=PASS\nFFPROBE_QA=PASS");
