import assert from "node:assert/strict";
import { createHash } from "node:crypto";
import { mkdtempSync, readFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { TeacherWorkflowService } from "../server/services/teacherWorkflowService.js";
import { JsonQuestionBankRepository } from "../src/modules/question-bank/repository.js";

const root = mkdtempSync(join(tmpdir(), "mst-p3-correction-"));
const repositoryPath = join(root, "question-bank.json");
const sidecarPath = join(root, "corrections.json");
const repository = new JsonQuestionBankRepository(repositoryPath);
const service = new TeacherWorkflowService(repository, sidecarPath);
const realPath = "D:/math-ai-video-studio/NA-MATH-QUESTION-BANK/acceptance/Ha Tinh. Chuyen Toan 2025.docx";
const realBytes = new Uint8Array(readFileSync(realPath));
const sourceBefore = Buffer.from(realBytes);
const sourceHashBefore = createHash("sha256").update(sourceBefore).digest("hex");
const imported = service.importDocx(sourceBefore.toString("base64"), "Ha Tinh. Chuyen Toan 2025.docx");
assert.ok(imported.imported.length >= 1);
const question = repository.load().questions[0]!;
const editQuestion = repository.load().questions[1]!;
assert.equal(question.source.document, "Ha Tinh. Chuyen Toan 2025.docx");
assert.equal(question.source.sourceHash, sourceHashBefore);

const pending = service.getCorrectionState(question.id);
assert.ok(pending.analysis.proposals.length > 0);
const proposalId = pending.analysis.proposals[0]!.issueId;
const revised = structuredClone(question);
revised.options = [{ label: "A", content: [{ type: "text", value: "2" }] }, { label: "B", content: [{ type: "text", value: "3" }] }];
assert.throws(() => service.decideCorrection(question.id, proposalId, "ACCEPT"), /REVISION_REQUIRED/);
const accepted = service.decideCorrection(question.id, proposalId, "ACCEPT", revised);
assert.equal(accepted.revision?.teacherDecision, "ACCEPTED");
assert.equal(accepted.revision?.provenance.kind, "TEACHER_AUTHORED");
assert.notEqual(accepted.revision?.revalidation, undefined);
const reloaded = new TeacherWorkflowService(new JsonQuestionBankRepository(repositoryPath), sidecarPath).getCorrectionState(question.id);
assert.equal(reloaded.revision?.revisionId, accepted.revision?.revisionId);
assert.equal(reloaded.analysis.questionId, question.id);

const editState = service.getCorrectionState(editQuestion.id);
const editRevision = structuredClone(revised); editRevision.id = editQuestion.id; editRevision.source = { ...editRevision.source, document: editQuestion.source.document };
const edited = service.decideCorrection(editQuestion.id, editState.analysis.proposals[0]!.issueId, "EDIT", editRevision);
assert.equal(edited.revision?.teacherDecision, "EDITED");
assert.equal(edited.revision?.provenance.kind, "TEACHER_AUTHORED");
const rejected = new TeacherWorkflowService(new JsonQuestionBankRepository(repositoryPath), sidecarPath).decideCorrection(question.id, proposalId, "REJECT");
assert.equal(rejected.analysis.proposals.find((item) => item.issueId === proposalId)?.teacherDecision, "REJECTED");
assert.equal(Buffer.compare(sourceBefore, new Uint8Array(readFileSync(realPath))), 0);
assert.equal(createHash("sha256").update(readFileSync(realPath)).digest("hex"), sourceHashBefore);

console.log("REAL_DOCX_IMPORT=PASS");
console.log("QUESTION_NATURALLY_IMPORTED=PASS");
console.log("REVIEW_NATURALLY_GENERATED=PASS");
console.log("TEACHER_ACCEPT=PASS");
console.log("TEACHER_EDIT=PASS");
console.log("TEACHER_REJECT=PASS");
console.log("AUTHORIZED_APPLY=PASS");
console.log("UNAUTHORIZED_MUTATION_BLOCKED=PASS");
console.log("REVISION_PERSISTED=PASS");
console.log("REVISION_RELOADED=PASS");
console.log("PROVENANCE=PASS");
console.log("REVALIDATION=PASS");
console.log("REAL_DOCX_BYTES_UNCHANGED=PASS");
console.log("SOURCE_HASH_UNCHANGED=PASS");
