import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import { createHash } from "node:crypto";
import { validateInputSource, ingestToDocumentIR } from "../src/modules/document-ingest/index.js";
import { extractQuestionsFromDocumentIR } from "../src/modules/question-bank/pipeline.js";
import { DOCX_FIXTURES } from "../src/modules/document-engine/fixtures.js";

const png = new Uint8Array([137,80,78,71,13,10,26,10]);
const jpeg = new Uint8Array([255,216,255,224,0,0,255,217]);
const pdf = new TextEncoder().encode("%PDF-1.7");
const accepted = (name: string, bytes: Uint8Array) => validateInputSource({ name, bytes });
assert.equal(accepted("a.png", png).sourceType, "PNG");
assert.equal(accepted("a.jpeg", jpeg).sourceType, "JPEG");
assert.equal(accepted("a.pdf", pdf).sourceType, "PDF");
assert.equal(accepted("a.txt", png).sourceType, "UNSUPPORTED");
assert.equal(accepted("a.png", new Uint8Array()).fileIntegrity, "INVALID");
assert.equal(accepted("a.png", jpeg).issues[0].code, "EXTENSION_SIGNATURE_MISMATCH");
const docx = new Uint8Array(readFileSync("tests/golden/docx/GOLDEN_00_FOUNDATION.docx"));
const before = Buffer.from(docx);
const gate = accepted("foundation.docx", docx);
assert.equal(gate.inputQuality, "A");
assert.equal(gate.sourceHash, createHash("sha256").update(docx).digest("hex"));
const document = ingestToDocumentIR({ name: "foundation.docx", bytes: docx });
assert.equal(document.sourceHash, gate.sourceHash);
assert.deepEqual(Buffer.from(docx), before);
const extracted = extractQuestionsFromDocumentIR(document);
assert.equal(extracted.document, document);
assert.ok(Array.isArray(extracted.questions));
console.log("PIMATH_UNIFIED_INPUT_V1_QA=PASS");
