import assert from "node:assert/strict";
import {createMathScene} from "../src/modules/math-ir/index.js";
import {applySessionCommand,createConstructionSession} from "../src/modules/dynamic-geometry/index.js";
import {executeMathIntent} from "../src/modules/intelligent-math-runtime/index.js";
import {AUTHORING_TEMPLATE_REGISTRY,BILINGUAL_MATH_TERMINOLOGY,MV5_MAX_AUTHORING_DEPTH,affectedVerificationTargets,authoringIntentToMathIntent,createRuntimeProbe,deserializeAuthoringReport,executeAuthoringSession,inspectRuntimeHealth,normalizeBilingualOperation,resolveMathReference,routeRuntimeWithFallback,serializeAuthoringReport,verifyConstruction,type AuthoringIntent} from "../src/modules/math-authoring-verification/index.js";

let session=createConstructionSession(createMathScene({id:"mv5",name:"MV5",dimension:"2d",entities:[],constraints:[]}));for(const position of [[0,0],[4,0],[0,3]] as const)session=applySessionCommand(session,{id:"CREATE_FREE_POINT",parameters:{position}}).session;session={...session,scene:{...session.scene,entities:session.scene.entities.map((entity,index)=>({...entity,label:["A","B","P"][index]}))}};const[a,b,p]=session.scene.entities.map(x=>x.id);session=applySessionCommand(session,{id:"CREATE_LINE",inputIds:[a,b]}).session;const line=session.scene.entities.at(-1)!.id;
assert.equal(normalizeBilingualOperation("Dựng trung điểm M của AB").operation,"MIDPOINT");assert.equal(normalizeBilingualOperation("Construct the midpoint M of AB").operation,"MIDPOINT");assert.equal(normalizeBilingualOperation("Dựng đường trung trực của AB").operation,"PERPENDICULAR_BISECTOR");assert.equal(normalizeBilingualOperation("Draw a line parallel to d").operation,"PARALLEL");assert.ok(BILINGUAL_MATH_TERMINOLOGY.MIDPOINT.vi.includes("trung điểm"));
assert.equal(resolveMathReference(session.scene,"A",["point"]).status,"RESOLVED");assert.equal(resolveMathReference(session.scene,"AB",["line"]).semanticIds[0],line);assert.equal(resolveMathReference(session.scene,"missing").status,"NOT_FOUND");assert.equal(resolveMathReference(session.scene,"A",["line"]).status,"TYPE_MISMATCH");
assert.deepEqual(Object.keys(AUTHORING_TEMPLATE_REGISTRY),["MIDPOINT_OF_SEGMENT","PERPENDICULAR_BISECTOR","PARALLEL_THROUGH_POINT","PERPENDICULAR_THROUGH_POINT","PROJECTION_TO_LINE"]);
const vi:AuthoringIntent={authoringId:"vi-mid",operation:"MIDPOINT",references:["A","B"],language:"vi",sourceText:"Dựng trung điểm M của AB"},en:AuthoringIntent={...vi,authoringId:"en-mid",language:"en",sourceText:"Construct midpoint M of AB"};const viMath=authoringIntentToMathIntent(session.scene,vi).intent!,enMath=authoringIntentToMathIntent(session.scene,en).intent!;assert.deepEqual({...viMath,intentId:"same",metadata:undefined},{...enMath,intentId:"same",metadata:undefined});const viResult=executeMathIntent(session.scene,viMath),enResult=executeMathIntent(session.scene,enMath);assert.deepEqual(viResult.scene.entities.at(-1),enResult.scene.entities.at(-1));
const midpointId=viResult.createdIds[0],verified=verifyConstruction(viResult.scene,{verificationId:"v-mid",claim:"MIDPOINT",targetIds:[midpointId],referenceIds:[a,b]});assert.equal(verified.status,"VERIFIED");assert.ok(verified.evidence.some(x=>x.type==="DEPENDENCY"||x.type==="CONSTRUCTION_OPERATION"));assert.equal(verified.failedChecks.length,0);
const moved=applySessionCommand({...session,scene:viResult.scene},{id:"MOVE_POINT",inputIds:[a],parameters:{position:[-2,2]}}).session.scene,reverified=verifyConstruction(moved,{verificationId:"v-mid-moved",claim:"MIDPOINT",targetIds:[midpointId],referenceIds:[a,b]});assert.equal(reverified.status,"VERIFIED");assert.ok(affectedVerificationTargets(moved,[a]).includes(midpointId));assert.ok(reverified.operationCount<10);
const parallel=executeMathIntent(session.scene,{intentId:"parallel",type:"CREATE_OBJECT",operation:"PARALLEL_LINE",targets:[p,line]});const createdLine=parallel.createdIds.at(-1)!;assert.equal(verifyConstruction(parallel.scene,{verificationId:"v-parallel",claim:"PARALLEL",targetIds:[createdLine],referenceIds:[line]}).status,"VERIFIED");const falseRelation=verifyConstruction(session.scene,{verificationId:"v-fail",claim:"PERPENDICULAR",targetIds:[line],referenceIds:[line]});assert.equal(falseRelation.status,"FAILED");assert.ok(falseRelation.failedChecks[0].suggestedRepair);
const report=executeAuthoringSession(session.scene,[vi],"session-vi");assert.equal(report.status,"PASS");assert.equal(report.verifications[0].status,"VERIFIED");assert.equal(report.transactionCommitted,true);const restored=deserializeAuthoringReport(serializeAuthoringReport(report));assert.deepEqual(restored.scene,report.scene);assert.deepEqual(restored.verifications,report.verifications);
const missing=executeAuthoringSession(session.scene,[{authoringId:"bad",operation:"MIDPOINT",references:["A","ghost"]}]);assert.equal(missing.status,"FAIL");assert.deepEqual(missing.scene,session.scene);assert.equal(missing.transactionCommitted,false);const tooDeep=executeAuthoringSession(session.scene,Array.from({length:MV5_MAX_AUTHORING_DEPTH+1},(_,index)=>({...vi,authoringId:`deep-${index}`})));assert.equal(tooDeep.issues[0].code,"PLAN_INVALID");
assert.equal(inspectRuntimeHealth("three").status,"HEALTHY");assert.equal(inspectRuntimeHealth("geogebra").status,"UNAVAILABLE");const fallback=routeRuntimeWithFallback({capability:"interactive_2d",preferredBridgeId:"geogebra"});assert.equal(fallback.fallback,true);assert.equal(fallback.bridge?.bridgeId,"three");assert.equal(fallback.diagnostic?.code,"RUNTIME_FALLBACK");assert.equal(fallback.telemetry.containsSensitiveData,false);assert.equal(createRuntimeProbe("manim").run().status,"UNAVAILABLE");
assert.equal(authoringIntentToMathIntent(session.scene,{authoringId:"circle",operation:"CREATE_CIRCLE",references:[]}).issues.length,0);assert.equal(authoringIntentToMathIntent(session.scene,{authoringId:"fold",operation:"FOLD_OPERATION",references:[]}).issues[0].code,"UNSUPPORTED_CONSTRUCTION");
console.log("MV_5_RUNTIME_MODULARIZATION=PASS\nMV_5_BILINGUAL_AUTHORING=PASS\nMV_5_VERIFICATION_ENGINE=PASS\nMV_5_DYNAMIC_INCREMENTAL_VERIFICATION=PASS\nMV_5_RUNTIME_INTELLIGENCE=PASS\nMV_5_AUTHORING_SESSION=PASS\nMV_5_SECURITY_AND_SERIALIZATION=PASS");
