import assert from "node:assert/strict";
import {createMathScene,type MathConstraint} from "../src/modules/math-ir/index.js";
import {applySessionCommand,createConstructionSession} from "../src/modules/dynamic-geometry/index.js";
import {MV4_MAX_PLAN_STEPS,MV4_MAX_REPAIR_ATTEMPTS,MV4_MAX_SOLVER_STEPS,MV4_NONLINEAR_LIMITS,PROVIDER_NEUTRAL_LANGUAGE_ADAPTER,RUNTIME_BRIDGE_REGISTRY,analyzeAdvancedDof,classifyMixedConstraints,compareRuntimeSemantics,createConstraintReplayRecord,deserializeCommandLog,executeAdvancedConstraints,executeConstructionPlan,executeMathIntent,executeRuntimeBridge,explainConstraintConflict,parseProviderIntent,planMathIntent,repairConstructionPlan,replayCommandLog,replayConstraintTransaction,routeRuntime,runControlledNonlinear,serializeCommandLog,type ConstructionPlan,type MathIntent} from "../src/modules/intelligent-math-runtime/index.js";

const empty=createMathScene({id:"mv4",name:"MV4",dimension:"2d",entities:[],constraints:[]});let session=createConstructionSession(empty);
for(const position of [[0,0],[4,0],[0,3]] as const){const result=applySessionCommand(session,{id:"CREATE_FREE_POINT",parameters:{position}});assert.equal(result.result.status,"PASS");session=result.session;}
const[a,b,c]=session.scene.entities.map(x=>x.id);session={...session,scene:{...session.scene,entities:session.scene.entities.map((x,index)=>({...x,label:["A","B","C"][index]}))}};
let built=applySessionCommand(session,{id:"CREATE_LINE",inputIds:[a,b]});assert.equal(built.result.status,"PASS");session=built.session;const lineId=built.result.createdIds[0];

const midpointIntent:MathIntent={intentId:"intent-midpoint",type:"CREATE_OBJECT",operation:"MIDPOINT",targets:["A","B"],requestedOutput:"midpoint"};
const planned=planMathIntent(session.scene,midpointIntent);assert.equal(planned.status,"PASS");assert.equal(planned.plan?.steps[0].commandId,"CREATE_MIDPOINT");const ai=executeMathIntent(session.scene,midpointIntent);assert.equal(ai.status,"PASS");assert.equal(ai.transactionCommitted,true);const midpoint=ai.scene.entities.find(x=>ai.createdIds.includes(x.id))!;assert.deepEqual(midpoint.semanticCoordinate,{dimension:"2d",x:2,y:0});
const human=applySessionCommand(session,{id:"CREATE_MIDPOINT",inputIds:[a,b]});assert.deepEqual(ai.scene.entities.at(-1),human.session.scene.entities.at(-1),"AI and human must converge on MV-1 semantics");assert.equal(ai.commandLog[0].command.id,"CREATE_MIDPOINT");

const ambiguous=executeMathIntent(session.scene,{intentId:"ambiguous",type:"CREATE_OBJECT",operation:"PARALLEL_LINE",targets:[lineId]});assert.equal(ambiguous.status,"FAIL");assert.equal(ambiguous.issues[0].code,"MISSING_INPUT");assert.deepEqual(ambiguous.scene,session.scene,"Ambiguity must not mutate scene");
const hallucinated=executeMathIntent(session.scene,{intentId:"bad-ref",type:"CREATE_OBJECT",operation:"MIDPOINT",targets:["A","hallucinated-99"]});assert.equal(hallucinated.issues[0].code,"INVALID_REFERENCE");assert.deepEqual(hallucinated.scene,session.scene);
assert.equal(parseProviderIntent("not-json-data").issues[0].code,"INVALID_INTENT");assert.equal(parseProviderIntent({intentId:"x",type:"RUN_SHELL",parameters:{command:"calc.exe"}}).issues[0].code,"INVALID_INTENT");assert.equal(PROVIDER_NEUTRAL_LANGUAGE_ADAPTER.providerNeutral,true);

const perpendicular=executeMathIntent(session.scene,{intentId:"perp",type:"CREATE_OBJECT",operation:"PERPENDICULAR_BISECTOR",targets:[a,b]});assert.equal(perpendicular.status,"PASS");assert.deepEqual(perpendicular.commandLog.map(x=>x.command.id),["CREATE_MIDPOINT","CREATE_LINE","CREATE_PERPENDICULAR_LINE"]);assert.equal(perpendicular.scene.semantics?.dependencies?.some(x=>x.kind==="CREATE_PERPENDICULAR_LINE"),true);
const invalidPlan:ConstructionPlan={schemaVersion:"mv4-construction-plan/v1",planId:"invalid",intentId:"invalid",steps:[{stepId:"one",commandId:"CREATE_MIDPOINT",inputRefs:[a,"missing"]},{stepId:"two",commandId:"CREATE_LINE",inputRefs:["$never",b]}],repairTrace:[]};const rolled=executeConstructionPlan(session.scene,invalidPlan);assert.equal(rolled.status,"FAIL");assert.equal(rolled.transactionCommitted,false);assert.deepEqual(rolled.scene,session.scene);assert.equal(repairConstructionPlan(invalidPlan,rolled.issues[0],1).repairTrace.length,1);

const pointOnLine:MathConstraint={id:"on-line",type:"point_on_line",entityIds:[c,lineId],mode:"LOCKED",fact:{origin:"given"}};const fixedDistance:MathConstraint={id:"fixed-distance",type:"distance",entityIds:[c,a],mode:"LOCKED",parameters:{distance:3,fixed:true},fact:{origin:"given"}};const constrained={...session.scene,constraints:[pointOnLine,fixedDistance]};assert.equal(classifyMixedConstraints(constrained.constraints),"CHAIN_SOLVABLE");const advanced=executeAdvancedConstraints(constrained,{objectId:c,position:[2,4]});assert.equal(advanced.status,"PASS");assert.equal(advanced.transactionCommitted,true);assert.ok(advanced.solverRoute.length<=MV4_MAX_SOLVER_STEPS);assert.ok(advanced.satisfiedConstraintIds.includes("on-line"));assert.equal(analyzeAdvancedDof(constrained,c).generalCadRankAnalysis,false);
const replayRecord=createConstraintReplayRecord(constrained,{objectId:c,position:[2,4]},advanced);assert.deepEqual(replayConstraintTransaction(constrained,replayRecord).updatedScene,advanced.updatedScene);
const unsupported=executeAdvancedConstraints({...session.scene,constraints:[{id:"angle",type:"angle",entityIds:[a,b,c],mode:"LOCKED",fact:{origin:"given"}}]},{objectId:a,position:[1,1]});assert.equal(unsupported.status,"PARTIAL");assert.equal(unsupported.transactionCommitted,false);
const nonlinear=runControlledNonlinear(session.scene,{variableCount:2,constraintTypes:["distance"]});assert.equal(nonlinear.status,"UNSUPPORTED");assert.equal(nonlinear.iterations,0);assert.equal(MV4_NONLINEAR_LIMITS.maxIterations,32);
const conflictScene={...session.scene,constraints:[{...fixedDistance,id:"d1",parameters:{distance:2,fixed:true}},{...fixedDistance,id:"d2",parameters:{distance:5,fixed:true}}]};const conflict=executeAdvancedConstraints(conflictScene,{objectId:c,position:[1,1]});assert.equal(conflict.status,"FAIL");assert.equal(conflict.transactionCommitted,false);assert.ok(conflict.proposedRepairs.every(x=>x.automatic===false));assert.equal(explainConstraintConflict(conflictScene,c,conflict.conflictingConstraintIds).canonicalDependencyGraphReused,true);

const serialized=serializeCommandLog(ai.commandLog),roundTrip=deserializeCommandLog(serialized),replayed=replayCommandLog(session.scene,roundTrip);assert.equal(replayed.status,"PASS");assert.deepEqual(replayed.scene,ai.scene);assert.ok(ai.commandLog.every((x,index)=>x.sequence===index));
assert.equal(routeRuntime({capability:"interactive_3d"}).bridge?.bridgeId,"three");assert.equal(routeRuntime({capability:"publication_2d"}).status,"RUNTIME_NOT_AVAILABLE");assert.equal(executeRuntimeBridge(ai.scene,"three").status,"AVAILABLE");assert.equal(executeRuntimeBridge(ai.scene,"fold").domainSpecific,true);assert.equal(compareRuntimeSemantics(ai.scene).status,"PASS");assert.ok(RUNTIME_BRIDGE_REGISTRY.every(x=>x.semanticAuthority===false));
assert.equal(MV4_MAX_REPAIR_ATTEMPTS,3);assert.equal(MV4_MAX_PLAN_STEPS,32);assert.equal(parseProviderIntent({intentId:"unsafe",type:"RUN_CODE",parameters:{source:"arbitrary"}}).intent,undefined);
console.log("MV_4_ADVANCED_CONSTRAINT_RUNTIME=PASS\nMV_4_INTELLIGENT_CONSTRUCTION_PLANNER=PASS\nMV_4_NATIVE_RUNTIME_ORCHESTRATION=PASS\nMV_4_REPLAY_AND_RECOVERY=PASS\nMV_4_PROVIDER_SAFETY=PASS\nMV_4_BOUNDED_WORK=PASS");
