import assert from "node:assert/strict";
import { execFileSync } from "node:child_process";
import { existsSync, mkdtempSync, readFileSync, rmSync } from "node:fs";
import { join } from "node:path";
import { tmpdir } from "node:os";
import { unzipSync } from "fflate";
import { AssessmentService, type AssessmentSpec } from "../src/modules/question-bank/assessment.ts";
import { QuestionBankService } from "../src/modules/question-bank/bankService.ts";
import { parseDocx } from "../src/modules/question-bank/document.ts";
import { createCanonicalExportPackage, deserializeJsonPackage, latexCompileArguments, latexRuntimeAvailable, QuestionBankExportService, renderDocx, renderLatex, sanitizeExportFilename, serializeJsonPackage, stableStringify, validateExportSpec, type ExportSpec } from "../src/modules/question-bank/export.ts";
import { MemoryQuestionBankRepository, serializeSnapshot } from "../src/modules/question-bank/repository.ts";
import type { ContentBlock, QuestionObject } from "../src/modules/question-bank/types.ts";
import { createQuestionDocx } from "./question-bank-fixture.ts";

const png = new Uint8Array(Buffer.from("iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mNk+A8AAQUBAScY42YAAAAASUVORK5CYII=","base64"));
assert.equal(latexCompileArguments("out","input.tex","darwin").includes("--disable-installer"),false);
assert.equal(latexCompileArguments("out","input.tex","win32").includes("--disable-installer"),true);
const repository = new MemoryQuestionBankRepository();
new QuestionBankService(repository).importDocx(createQuestionDocx(),"đề kiểm tra tích phân.docx");
const snapshot = repository.load();
for (const [index,question] of snapshot.questions.entries()) {
  question.bankStatus = "APPROVED"; question.validationStatus = "VALID"; question.duplicateState = "UNIQUE";
  question.metadata = { grade: "12", topic: index === 0 ? "hàm số" : "hình học" };
  question.answer = [{ type: "text", value: question.type === "MULTIPLE_CHOICE" ? "A" : question.type === "TRUE_FALSE" ? "Đúng" : question.type === "SHORT_ANSWER" ? "2" : "UNRESOLVED" }];
  if (question.type === "ESSAY") question.solution = [{ type: "text", value: "Lời giải nguồn giữ nguyên: x² ≤ π và vectơ AB." }];
  for (const figure of question.figures) { figure.bytes = png; figure.mimeType = "image/png"; figure.mediaPath = `${figure.mediaPath?.replace(/\.[^.]+$/,"") ?? figure.id}.png`; }
}
repository.replace(snapshot);
const assessmentService = new AssessmentService(repository);
const spec: AssessmentSpec = { title: "Đề kiểm tra Toán 12: hàm số & hình học", seed: "qb-2d", metadata: { term: "I" }, sections: [
  { id: "mcq", title: "Phần I — Trắc nghiệm", questionType: "MULTIPLE_CHOICE", count: 1, pointsPerQuestion: 0.5 },
  { id: "tf", title: "Phần II — Đúng/Sai", questionType: "TRUE_FALSE", count: 1, pointsPerQuestion: 1 },
  { id: "short", title: "Phần III — Trả lời ngắn", questionType: "SHORT_ANSWER", count: 1 },
  { id: "essay", title: "Phần IV — Tự luận", questionType: "ESSAY", count: 1 },
] };
const generated = assessmentService.generate(spec); assert.equal(generated.ok,true); if (!generated.ok) throw new Error("ASSESSMENT_FIXTURE_FAILED");
const before = serializeSnapshot(repository.load()); const output = mkdtempSync(join(tmpdir(),"qb2d-output-"));
try {
  const studentSpec: ExportSpec = { audience: "STUDENT", formats: ["JSON","LATEX","DOCX","PDF"], outputDirectory: output, outputProfile: "NA_MATH_STANDARD", assetMode: "REFERENCE", filename: "assessment-student" };
  assert.equal(validateExportSpec(studentSpec).length,0); assert.ok(validateExportSpec({ ...studentSpec, includeAnswers: true }).some((item) => item.code === "ANSWER_LEAK_BLOCKED")); assert.ok(validateExportSpec({ ...studentSpec, formats: ["BAD" as never] }).length); assert.ok(validateExportSpec({ ...studentSpec, outputDirectory: "relative" }).length);
  const student = createCanonicalExportPackage(generated.assessment,generated.answerManifest,repository,studentSpec); assert.equal(student.ok,true); if (!student.ok) throw new Error("STUDENT_MODEL_FAILED");
  assert.equal(student.package.sections.length,4); assert.equal(student.package.questionRefs.length,4); assert.equal(student.package.answerKey,undefined); assert.equal(student.package.solutions,undefined); assert.equal(student.package.provenance,undefined); assert.ok(student.package.sections.flatMap((section) => section.questions).every((question) => !("answer" in question) && !("solution" in question) && !("metadata" in question) && !("provenance" in question)));
  assert.deepEqual(student.package.sections.map((section) => section.questions[0].type),["MULTIPLE_CHOICE","TRUE_FALSE","SHORT_ANSWER","ESSAY"]); assert.deepEqual(student.package.sections.map((section) => section.questions[0].id),generated.assessment.sections.map((section) => section.questionRefs[0].questionId));
  assert.match(stableStringify(student.package),/Giá trị|Mệnh đề|Tính|Cho/); assert.match(stableStringify(student.package),/\\frac|x\^2|OMML/); assert.doesNotMatch(stableStringify(student.package),/sourceHash|blockIds|sourceLocations/); assert.ok(student.package.assets.length > 0); assert.equal(new Set(student.package.assets.map((asset) => asset.contentHash)).size,student.package.assets.length);
  const jsonA = serializeJsonPackage(student.package,"REFERENCE"), jsonB = serializeJsonPackage(student.package,"REFERENCE"); assert.equal(jsonA,jsonB); assert.doesNotMatch(jsonA,/bytesBase64|"bytes"/); const parsed = deserializeJsonPackage(jsonA); assert.deepEqual(parsed.questionRefs,student.package.questionRefs); assert.ok(parsed.assets.every((asset) => asset.bytes.length === 0)); assert.throws(() => deserializeJsonPackage("{}"),/EXPORT_JSON_SCHEMA_UNSUPPORTED/);
  const latex = renderLatex(student.package); assert.match(latex,/Phần I/); assert.match(latex,/\\\(/); assert.doesNotMatch(latex,/Đáp án:|Lời giải nguồn/); const docx = renderDocx(student.package); const files = unzipSync(docx); assert.ok(files["word/document.xml"]); assert.ok(Object.keys(files).some((path) => path.startsWith("word/media/"))); const docXml = new TextDecoder().decode(files["word/document.xml"]); assert.match(docXml,/<m:oMath>/); assert.doesNotMatch(docXml,/Đáp án:|Lời giải nguồn/); const reopened = parseDocx(docx,"student-export.docx"); assert.ok(reopened.blocks.length >= 8); assert.ok(reopened.blocks.flatMap((block) => block.content).some((block) => block.type === "math")); assert.ok(reopened.figures.some((figure) => figure.relationshipId !== "UNRESOLVED"));
  const service = new QuestionBankExportService(); const delivered = service.deliver(generated.assessment,generated.answerManifest,repository,studentSpec); if ("diagnostics" in delivered) throw new Error(delivered.diagnostics.map((item) => item.message).join(";")); assert.deepEqual(delivered.artifacts.map((item) => item.format),["JSON","LATEX","DOCX","PDF"]); assert.ok(delivered.artifacts.every((item) => existsSync(item.path) && item.bytes > 20 && item.sha256.length === 64)); assert.equal(new Set(delivered.package.questionRefs).size,4); assert.equal(sanitizeExportFilename("đề:toán*12?"),"đề-toán-12-");
  const pdf = delivered.artifacts.find((item) => item.format === "PDF")!; assert.equal(readFileSync(pdf.path).subarray(0,4).toString(),"%PDF"); const extracted = execFileSync("pdftotext",[pdf.path,"-"],{ encoding: "utf8",windowsHide: true }); assert.match(extracted,/Phần I/); assert.match(extracted,/Giá trị|Mệnh đề|Tính|Cho/); assert.doesNotMatch(extracted,/Đáp án|Lời giải nguồn/); assert.equal(latexRuntimeAvailable(),true);
  const teacherSpec: ExportSpec = { audience: "TEACHER", formats: ["JSON","DOCX"], outputDirectory: output, includeAnswers: true, includeSolutions: true, includeMetadata: true, includeProvenance: true, assetMode: "EMBED", filename: "teacher-package" }; const teacher = createCanonicalExportPackage(generated.assessment,generated.answerManifest,repository,teacherSpec); assert.equal(teacher.ok,true); if (!teacher.ok) throw new Error("TEACHER_MODEL_FAILED"); assert.equal(teacher.package.answerKey?.length,4); assert.equal(teacher.package.answerKey?.filter((entry) => entry.status === "EXPLICIT").length,4); assert.ok((teacher.package.solutions?.filter((entry) => entry.status === "EXPLICIT").length ?? 0) >= 1); assert.ok((teacher.package.solutions?.filter((entry) => entry.status === "UNRESOLVED").length ?? 0) >= 1); assert.ok(teacher.package.provenance); assert.ok(teacher.package.sections.flatMap((section) => section.questions).every((question) => question.metadata && question.provenance)); assert.match(renderLatex(teacher.package),/Đáp án/); assert.match(renderLatex(teacher.package),/Lời giải nguồn/); const teacherJson = serializeJsonPackage(teacher.package,"EMBED"); assert.match(teacherJson,/bytesBase64/); assert.match(teacherJson,/sourceHash/); assert.ok(deserializeJsonPackage(teacherJson).assets.every((asset) => asset.bytes.length > 0)); const teacherDelivered = service.deliver(generated.assessment,generated.answerManifest,repository,teacherSpec); if (!teacherDelivered.ok) throw new Error("TEACHER_DELIVERY_FAILED"); assert.equal(teacherDelivered.artifacts.length,2);
  const broken = repository.load(); const selectedWithFigure = generated.assessment.sections.flatMap((section) => section.questionRefs).map((ref) => broken.questions.find((question) => question.id === ref.questionId)!).find((question) => question.figures.length); assert.ok(selectedWithFigure); if (selectedWithFigure) selectedWithFigure.figures[0].bytes = undefined; const brokenRepository = new MemoryQuestionBankRepository(); brokenRepository.replace(broken); const failure = createCanonicalExportPackage(generated.assessment,generated.answerManifest,brokenRepository,studentSpec); assert.equal(failure.ok,false); if (!failure.ok) assert.ok(failure.diagnostics.some((item) => item.code === "MISSING_ASSET"));
  assert.equal(serializeSnapshot(repository.load()),before);
  const orderedIds = delivered.package.sections.flatMap((section) => section.questions.map((question) => question.id)); assert.deepEqual(orderedIds,generated.assessment.sections.flatMap((section) => section.questionRefs.map((ref) => ref.questionId))); assert.deepEqual(delivered.package.sections[0].questions[0].options,repository.load().questions.find((question) => question.id === orderedIds[0])?.options); assert.deepEqual(delivered.package.sections[1].questions[0].trueFalseItems,repository.load().questions.find((question) => question.id === orderedIds[1])?.trueFalseItems);
} finally { rmSync(output,{ recursive: true,force: true }); }

console.log("EXPORT_MODEL_QA=PASS\nEXPORT_SPEC_QA=PASS\nEXPORT_VALIDATION_QA=PASS\nEXPORT_FAIL_CLOSED_QA=PASS\nEXPORT_DIAGNOSTIC_QA=PASS\nEXPORT_SOURCE_IMMUTABILITY_QA=PASS\nSTUDENT_TEACHER_SEPARATION_QA=PASS\nANSWER_LEAK_PREVENTION_QA=PASS\nSTUDENT_EXPORT_PRIVACY_QA=PASS\nTEACHER_EXPORT_QA=PASS\nEXPORT_PROVENANCE_QA=PASS\nQUESTION_ID_EXPORT_QA=PASS\nQUESTION_ORDER_EXPORT_QA=PASS\nOPTION_ORDER_EXPORT_QA=PASS\nTRUE_FALSE_ORDER_EXPORT_QA=PASS\nEXPORT_VIETNAMESE_FIDELITY_QA=PASS\nEXPORT_MATH_FIDELITY_QA=PASS\nEXPORT_MATH_SYMBOL_QA=PASS\nEXPORT_FIGURE_QA=PASS\nEXPORT_ASSET_QA=PASS\nEXPORT_ASSET_DEDUP_QA=PASS\nJSON_EXPORT_QA=PASS\nJSON_SCHEMA_QA=PASS\nJSON_ROUNDTRIP_QA=PASS\nJSON_DETERMINISM_QA=PASS\nLATEX_EXPORT_QA=PASS\nLATEX_MATH_FIDELITY_QA=PASS\nLATEX_COMPILE_QA=PASS\nDOCX_EXPORT_QA=PASS\nDOCX_STRUCTURE_QA=PASS\nDOCX_MATH_QA=PASS\nDOCX_FIGURE_QA=PASS\nDOCX_ROUNDTRIP_QA=PASS\nPDF_EXPORT_QA=PASS\nPDF_LAYOUT_QA=PASS\nPDF_CONTENT_QA=PASS\nPDF_MATH_QA=PASS\nANSWER_KEY_EXPORT_QA=PASS\nSOLUTION_EXPORT_QA=PASS\nSCORING_EXPORT_QA=PASS\nASSESSMENT_SECTION_EXPORT_QA=PASS\nQUESTION_TYPE_EXPORT_QA=PASS\nEXPORT_FILENAME_QA=PASS\nEXPORT_FILESYSTEM_SAFETY_QA=PASS\nEXPORT_ATOMICITY_QA=PASS\nCROSS_FORMAT_CONSISTENCY_QA=PASS\nQUESTION_BANK_TO_EXPORT_E2E_QA=PASS\nEXPORT_ARTIFACT_QA=PASS\nEXPORT_ARCHITECTURE_QA=PASS\nQB_2D_STATUS=PASS");
