import assert from "node:assert/strict";
import { buildFoldTopology, createDevelopableFoldScene, createNGonalSolidScene } from "../src/modules/fold-3d/index.js";
import { polyhedralIntersectionToSurfacePoint, solveSurfaceShortestPath } from "../src/modules/surface-shortest-path/index.js";
import type { CanonicalSurfacePoint, PathWaypoint } from "../src/modules/surface-shortest-path/index.js";
import { Vector3 } from "three";

const prism=buildFoldTopology(createNGonalSolidScene({kind:"prism",baseSides:6}).value!).value!;
const vertexPoint=(id:string,vertexId:string,faces:string[]):CanonicalSurfacePoint=>({id,solidId:prism.solidId,surfaceId:faces[0],attachmentType:"VERTEX",localCoordinates:{kind:"face_barycentric",vertexIds:[vertexId],weights:[1]},incidentSurfaceIds:faces,provenance:"user"});
const edgePoint=(id:string,vertices:[string,string],faces:string[]):CanonicalSurfacePoint=>({id,solidId:prism.solidId,surfaceId:faces[0],attachmentType:"EDGE",localCoordinates:{kind:"face_barycentric",vertexIds:vertices,weights:[.5,.5]},incidentSurfaceIds:faces,provenance:"user"});
const faceCenter=(id:string,faceId:string):CanonicalSurfacePoint=>{const face=prism.faces.find(item=>item.id===faceId)!;return{id,solidId:prism.solidId,surfaceId:faceId,attachmentType:"FACE",localCoordinates:{kind:"face_barycentric",vertexIds:face.vertexIds,weights:face.vertexIds.map(()=>1/face.vertexIds.length)},provenance:"user"};};
const shared=prism.edges.find(edge=>edge.incidentFaceIds.includes("fold-face-side-0")&&edge.incidentFaceIds.includes("fold-face-side-1"))!,edge=edgePoint("A",shared.vertexIds,["fold-face-side-0","fold-face-side-1"]),end=faceCenter("B","fold-face-side-3");const edgeResult=solveSurfaceShortestPath({surface:{kind:"polyhedral",topology:prism},startPoint:edge,endPoint:end});assert.equal(edgeResult.status,"PASS");assert.ok(edgeResult.candidateRoutes.some(candidate=>candidate.surfaceSequence[0]==="fold-face-side-0"));assert.ok(edgeResult.candidateRoutes.some(candidate=>candidate.surfaceSequence[0]==="fold-face-side-1"));
const vertexId=prism.faces.find(face=>face.id==="fold-face-side-0")!.vertexIds[0],incident=prism.faces.filter(face=>face.vertexIds.includes(vertexId)).map(face=>face.id),vertex=vertexPoint("A",vertexId,incident),vertexResult=solveSurfaceShortestPath({surface:{kind:"polyhedral",topology:prism},startPoint:vertex,endPoint:end});assert.equal(vertexResult.status,"PASS");assert.ok(new Set(vertexResult.candidateRoutes.map(candidate=>candidate.surfaceSequence[0])).size>=incident.length);
const waypoint={...edgePoint("C",shared.vertexIds,["fold-face-side-0","fold-face-side-1"]),order:0,required:true} as PathWaypoint,via=solveSurfaceShortestPath({surface:{kind:"polyhedral",topology:prism},startPoint:faceCenter("A","fold-face-side-5"),endPoint:end,waypoints:[waypoint]});assert.equal(via.status,"PASS");assert.equal(via.segments.length,2);assert.equal(via.waypoints[0].id,"C");
const clockwise=solveSurfaceShortestPath({surface:{kind:"polyhedral",topology:prism},startPoint:faceCenter("A","fold-face-side-0"),endPoint:end,directive:{mode:"MANUAL",rootSurfaceId:"fold-face-side-0",surfaceSequence:["fold-face-side-0","fold-face-side-3"],direction:"CLOCKWISE"}}),counter=solveSurfaceShortestPath({surface:{kind:"polyhedral",topology:prism},startPoint:faceCenter("A","fold-face-side-0"),endPoint:end,directive:{mode:"MANUAL",rootSurfaceId:"fold-face-side-0",surfaceSequence:["fold-face-side-0","fold-face-side-3"],direction:"COUNTERCLOCKWISE"}});assert.equal(clockwise.status,"PASS");assert.equal(counter.status,"PASS");assert.notDeepEqual(clockwise.selectedRoute,counter.selectedRoute);
const cylinder=createDevelopableFoldScene({solidType:"cylinder",radius:2,height:5}).value!,curve=(id:string,theta:number):CanonicalSurfacePoint=>({id,solidId:cylinder.id,surfaceId:cylinder.lateralSurfaceId,attachmentType:"CURVED_SURFACE",localCoordinates:{kind:"curved",theta,longitudinal:2},provenance:"user"}),a=curve("A",.2),b=curve("B",5.8),seam0=solveSurfaceShortestPath({surface:{kind:"developable",scene:cylinder},startPoint:a,endPoint:b,directive:{mode:"MANUAL",seamTheta:0,surfaceSequence:["surface-lateral"],rootSurfaceId:"surface-lateral"}}),seam1=solveSurfaceShortestPath({surface:{kind:"developable",scene:cylinder},startPoint:a,endPoint:b,directive:{mode:"MANUAL",seamTheta:1,surfaceSequence:["surface-lateral"],rootSurfaceId:"surface-lateral"}});assert.equal(seam0.status,"PASS");assert.equal(seam1.status,"PASS");assert.ok(Math.abs(seam0.length-seam1.length)<1e-8);assert.notDeepEqual(seam0.path2D,seam1.path2D);
for(const barycentric of [[.2,.3,.5],[.5,.5,0],[1,0,0]] as [number,number,number][]){const point=polyhedralIntersectionToSurfacePoint({id:"picked",solidId:"solid",faceId:"face",triangleVertexIds:["a","b","c"],barycentric,worldPoint:new Vector3(),incidentSurfaceIds:["face","other"]});assert.equal(point.attachmentType,barycentric[0]===1?"VERTEX":barycentric[2]===0?"EDGE":"FACE");assert.equal("object" in point,false);}
console.log("SURFACE_SHORTEST_PATH_REMEDIATION_V1_TESTS=PASS");
