import assert from "node:assert/strict";
import { AssessmentService, createAssessmentQueryPlan, validateAssessmentSpec, type AssessmentSpec } from "../src/modules/question-bank/assessment.ts";
import { QuestionBankService } from "../src/modules/question-bank/bankService.ts";
import { MemoryQuestionBankRepository, serializeSnapshot } from "../src/modules/question-bank/repository.ts";
import type { QuestionObject } from "../src/modules/question-bank/types.ts";
import { createQuestionDocx } from "./question-bank-fixture.ts";

const repository = new MemoryQuestionBankRepository(); new QuestionBankService(repository).importDocx(createQuestionDocx(), "đề toán.docx"); const base = repository.load(); const questions: QuestionObject[] = [];
for (const [sourceIndex, source] of ["đề toán.docx","tuyển tập.docx","chuyên đề.docx"].entries()) for (const original of base.questions) { const question = structuredClone(original); question.id = `${original.id}-s${sourceIndex}`; question.source.document = source; question.source.sourceHash = `source-${sourceIndex}`; question.bankStatus = "APPROVED"; question.validationStatus = "VALID"; question.duplicateState = "UNIQUE"; question.metadata = { grade: original.type === "MULTIPLE_CHOICE" ? "12" : "11", topic: original.type === "MULTIPLE_CHOICE" ? "đạo hàm" : "hình học" }; questions.push(question); }
questions[0].answer = [{ type: "text", value: "A" }]; questions[0].solution = [{ type: "text", value: "Lời giải nguồn: giữ nguyên dấu ≤ và π." }]; const possible = structuredClone(questions[0]); possible.id = `${possible.id}-possible`; possible.source.document = "nguồn tương tự.docx"; possible.duplicateState = "POSSIBLE_DUPLICATE"; questions.push(possible); const quarantined = structuredClone(questions[0]); quarantined.id = `${quarantined.id}-quarantined`; quarantined.bankStatus = "QUARANTINED"; quarantined.duplicateState = "UNIQUE"; questions.push(quarantined); repository.replace({ schemaVersion: 1, questions, orphanFigures: base.orphanFigures });
const service = new AssessmentService(repository); const before = serializeSnapshot(repository.load());
const spec: AssessmentSpec = { title: "Đề kiểm tra hàm số", seed: "lop-12-a", sections: [ { id: "mcq", title: "Trắc nghiệm", questionType: "MULTIPLE_CHOICE", count: 2, filters: { metadata: { grade: "12", topic: "đạo hàm" }, hasFigures: true }, ordering: "SEEDED_SHUFFLE", sourcePolicy: "DISTINCT_SOURCE_REQUIRED", pointsPerQuestion: 0.5 }, { id: "tf", questionType: "TRUE_FALSE", count: 1 }, { id: "short", questionType: "SHORT_ANSWER", count: 1 }, { id: "essay", questionType: "ESSAY", count: 1 } ] };
assert.equal(validateAssessmentSpec(spec).length,0); const plan = createAssessmentQueryPlan(spec); assert.equal(plan.length,4); assert.deepEqual(plan[0].query.statuses,["APPROVED"]); assert.deepEqual(plan[0].query.types,["MULTIPLE_CHOICE"]); const first = service.generate(spec); assert.equal(first.ok,true); const second = service.generate(spec); assert.equal(second.ok,true); const ids = first.assessment.sections.flatMap((x) => x.questionRefs.map((ref) => ref.questionId)); assert.deepEqual(second.assessment.sections.flatMap((x) => x.questionRefs.map((ref) => ref.questionId)),ids); assert.equal(first.assessment.id,second.assessment.id); assert.deepEqual(first.assessment.sections.map((x) => x.questionRefs.length),[2,1,1,1]); assert.equal(new Set(ids).size,5); assert.ok(first.assessment.sections.every((section,index) => section.questionRefs.every((ref) => ref.type === spec.sections[index].questionType && ref.status === "APPROVED" && ref.source.document))); assert.equal(new Set(first.assessment.sections[0].questionRefs.map((x) => x.source.document)).size,2); assert.equal(first.assessment.sections[0].questionRefs[0].points,0.5); assert.ok(first.assessment.diagnostics.some((x) => x.code === "POSSIBLE_DUPLICATE_EXCLUDED"));
const materialized = service.materialize(first.assessment); assert.equal(materialized.length,5); const selectedMcq = materialized.find((q) => q.id === questions[0].id); if (selectedMcq) { assert.deepEqual(selectedMcq.options,questions[0].options); assert.deepEqual(selectedMcq.figures,questions[0].figures); assert.match(JSON.stringify(selectedMcq),/\\frac/); assert.match(JSON.stringify(selectedMcq),/Giá trị/); } const answer = first.answerManifest.entries.find((x) => x.questionId === questions[0].id); if (ids.includes(questions[0].id)) { assert.deepEqual(answer?.answer,[{ type: "text", value: "A" }]); assert.match(JSON.stringify(answer?.solution),/giữ nguyên dấu ≤ và π/); }
const variationSpec: AssessmentSpec = { seed: "one", sections: [{ id: "mcq", questionType: "MULTIPLE_CHOICE", count: 2, ordering: "SEEDED_SHUFFLE" }] }; const variedA = service.generate(variationSpec), variedB = service.generate({ ...variationSpec, seed: "different" }); assert.ok(variedA.ok && variedB.ok); if (variedA.ok && variedB.ok) assert.notDeepEqual(variedA.assessment.sections[0].questionRefs.map((x) => x.questionId),variedB.assessment.sections[0].questionRefs.map((x) => x.questionId)); const fixedA = service.generate({ ...variationSpec, seed: "one", sections: [{ ...variationSpec.sections[0], ordering: "FIXED" }] }); const fixedB = service.generate({ ...variationSpec, seed: "different", sections: [{ ...variationSpec.sections[0], ordering: "FIXED" }] }); assert.ok(fixedA.ok && fixedB.ok); if (fixedA.ok && fixedB.ok) assert.deepEqual(fixedA.assessment.sections[0].questionRefs.map((x) => x.questionId),fixedB.assessment.sections[0].questionRefs.map((x) => x.questionId));
const insufficient = service.generate({ seed: 1, sections: [{ id: "too-many", questionType: "ESSAY", count: 99 }] }); assert.equal(insufficient.ok,false); if (!insufficient.ok) assert.ok(insufficient.diagnostics.some((x) => x.code === "ASSESSMENT_INSUFFICIENT_CANDIDATES")); const diversity = service.generate({ seed: 1, sections: [{ id: "sources", questionType: "ESSAY", count: 4, sourcePolicy: "DISTINCT_SOURCE_REQUIRED" }] }); assert.equal(diversity.ok,false); if (!diversity.ok) assert.ok(diversity.diagnostics.some((x) => x.code === "SOURCE_DIVERSITY_UNAVAILABLE")); const metadata = service.generate({ seed: 1, sections: [{ id: "missing-meta", questionType: "ESSAY", count: 1, filters: { metadata: { difficulty: "HARD" } } }] }); assert.equal(metadata.ok,false); if (!metadata.ok) assert.equal(metadata.diagnostics[0].code,"UNSUPPORTED_METADATA_CONSTRAINT"); assert.ok(validateAssessmentSpec({ seed: "", statuses: ["BAD" as never], sections: [{ id: "", questionType: "BAD" as never, count: -1, ordering: "BAD" as never, sourcePolicy: "BAD" as never }] }).length > 0); assert.throws(() => service.materialize({ ...first.assessment, sections: [{ id: "broken", questionRefs: [{ ...first.assessment.sections[0].questionRefs[0], questionId: "missing" }] }] }),/ASSESSMENT_QUESTION_NOT_FOUND/); materialized[0].metadata.mutated = "yes"; assert.equal(serializeSnapshot(repository.load()),before);
console.log("ASSESSMENT_SPEC_QA=PASS\nASSESSMENT_SECTION_QA=PASS\nASSESSMENT_QUERY_PLAN_QA=PASS\nQUESTION_BANK_SELECTION_INTEGRATION_QA=PASS\nASSESSMENT_SAFE_REUSE_QA=PASS\nSEEDED_REPRODUCIBILITY_QA=PASS\nSEED_VARIATION_QA=PASS\nASSESSMENT_DUPLICATE_PREVENTION_QA=PASS\nPOSSIBLE_DUPLICATE_POLICY_QA=PASS\nINSUFFICIENT_BANK_QA=PASS\nASSESSMENT_COUNT_QA=PASS\nASSESSMENT_TYPE_INTEGRITY_QA=PASS\nASSESSMENT_METADATA_QA=PASS\nASSESSMENT_SOURCE_POLICY_QA=PASS\nASSESSMENT_FIGURE_CONSTRAINT_QA=PASS\nASSESSMENT_MATERIALIZATION_QA=PASS\nASSESSMENT_PROVENANCE_QA=PASS\nANSWER_MANIFEST_QA=PASS\nSOLUTION_REFERENCE_PRESERVATION_QA=PASS\nASSESSMENT_SCORING_METADATA_QA=PASS\nASSESSMENT_ID_QA=PASS\nASSESSMENT_AUDITABILITY_QA=PASS\nASSESSMENT_ORDER_QA=PASS\nOPTION_ORDER_PRESERVATION_QA=PASS\nTRUE_FALSE_ORDER_PRESERVATION_QA=PASS\nASSESSMENT_FIGURE_PRESERVATION_QA=PASS\nASSESSMENT_MATH_FIDELITY_QA=PASS\nASSESSMENT_VIETNAMESE_QA=PASS\nASSESSMENT_SPEC_VALIDATION_QA=PASS\nASSESSMENT_FINAL_VALIDATION_QA=PASS\nASSESSMENT_FAIL_CLOSED_QA=PASS\nASSESSMENT_BANK_IMMUTABILITY_QA=PASS\nQB_2A_STATUS=PASS");
