import assert from "node:assert/strict";
import { createConeFromSector, createDevelopableFoldScene, createFrustumFromSector, developableSeamGap, developableSweep, mapDevelopablePoint, updateDevelopableFoldScene } from "../src/modules/fold-3d/index.js";
import { createDevelopableThreeMapping } from "../src/modules/fold-3d/developable-three-adapter.js";
const near=(a:number,b:number,e=1e-7)=>assert.ok(Math.abs(a-b)<e,`${a} != ${b}`),progresses=[0,.25,.5,.75,1];
const cylinder=createDevelopableFoldScene({solidType:"cylinder",radius:3,height:4}).value!;near(cylinder.dimensions.circumference,6*Math.PI);const flatStart=mapDevelopablePoint(cylinder,{surfaceId:cylinder.lateralSurfaceId,theta:0,longitudinal:0}).value!,flatEnd=mapDevelopablePoint(cylinder,{surfaceId:cylinder.lateralSurfaceId,theta:2*Math.PI-1e-12,longitudinal:4}).value!;near(flatStart[0],-3*Math.PI);near(flatEnd[0],3*Math.PI,1e-6);near(flatEnd[1]-flatStart[1],4);near(developableSweep(cylinder),0);near(developableSeamGap(cylinder),6*Math.PI);
const cone=createDevelopableFoldScene({solidType:"cone",radius:3,height:4}).value!;near(cone.dimensions.slantHeight,5);near(cone.dimensions.sectorAngleDegrees,216);near(cone.dimensions.sectorRadius*cone.dimensions.sectorAngleRadians,6*Math.PI);const coneSector=createConeFromSector({slantHeight:5,sectorAngleRadians:216*Math.PI/180}).value!;near(coneSector.dimensions.radius,3);near(coneSector.dimensions.height,4);
const frustum=createDevelopableFoldScene({solidType:"conical_frustum",largeRadius:4,smallRadius:2,height:3}).value!,s=Math.sqrt(13);near(frustum.dimensions.slantHeight,s);near(frustum.dimensions.outerRadius,s*2);near(frustum.dimensions.innerRadius,s);near(frustum.dimensions.outerRadius*frustum.dimensions.sectorAngleRadians,8*Math.PI);near(frustum.dimensions.innerRadius*frustum.dimensions.sectorAngleRadians,4*Math.PI);const sectorFrustum=createFrustumFromSector({innerRadius:s,outerRadius:2*s,sectorAngleRadians:4*Math.PI/s}).value!;near(sectorFrustum.dimensions.largeRadius,4);near(sectorFrustum.dimensions.smallRadius,2);near(sectorFrustum.dimensions.height,3);
for(const source of[cylinder,cone,frustum]){const ids=source.net.primitives.map(p=>p.id);for(const p of progresses){const current=updateDevelopableFoldScene(source,p).value!;assert.deepEqual(current.net.primitives.map(x=>x.id),ids);for(const theta of[0,.7,2.1,Math.PI*2-1e-9])for(const longitudinal of source.solidType==="cylinder"?[0,current.dimensions.height]:source.solidType==="cone"?[0,current.dimensions.slantHeight]:[current.dimensions.innerRadius,current.dimensions.outerRadius])assert.ok(mapDevelopablePoint(current,{surfaceId:current.lateralSurfaceId,theta,longitudinal}).value!.every(Number.isFinite));}assert.deepEqual(updateDevelopableFoldScene(updateDevelopableFoldScene(source,1).value!,0).value!,source);}
const mapping=createDevelopableThreeMapping(frustum);assert.equal((mapping.components.get("surface-lateral") as {userData:Record<string,unknown>}).userData.continuousParameterizedSurface,true);mapping.setEducationalOverlayVisible("removed-top-cone",true);mapping.setEducationalOverlayVisible("parent-cone-reference",true);mapping.setEducationalOverlayVisible("development-complement",true);assert.equal(mapping.components.get("removed-top-cone")!.visible,true);assert.equal(mapping.components.get("development-complement")!.visible,true);mapping.apply(updateDevelopableFoldScene(frustum,1).value!);assert.equal(mapping.components.get("development-complement")!.visible,false);mapping.dispose();
console.log("IA_4_9R2V_DEVELOPABLE_VIEWER_TESTS=PASS");
