import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import { ingestDocxQuestions } from "../src/modules/question-bank/pipeline.ts";
import { MemoryQuestionBankRepository } from "../src/modules/question-bank/repository.ts";
import { QuestionSearchService } from "../src/modules/question-bank/search.ts";

const sourcePath = process.env.MAS_REAL_DOCX_SOURCE;
if (!sourcePath) throw new Error("MAS_REAL_DOCX_SOURCE is required for pagination QA");
const imported = ingestDocxQuestions(new Uint8Array(readFileSync(sourcePath)), sourcePath).questions;
const repository = new MemoryQuestionBankRepository();
repository.replace({ schemaVersion: 1, questions: imported, orphanFigures: [] });
const service = new QuestionSearchService(repository);
const query = (offset: number) => service.query({ includeQuarantined: true, sort: { field: "INDEX", direction: "ASC" }, offset, limit: 50 });
const pages = [query(0), query(50), query(100), query(150)];
assert.equal(pages[0].total, 158);
assert.deepEqual(pages.map((page) => [page.items[0].index, page.items.at(-1)?.index]), [[1, 50], [51, 100], [101, 150], [151, 158]]);
assert.equal(pages[1].items.find((question) => question.index === 51)?.index, 51);
assert.equal(pages[3].items.find((question) => question.index === 158)?.index, 158);
const ids = pages.flatMap((page) => page.items.map((question) => question.id));
assert.equal(new Set(ids).size, 158);
assert.deepEqual(new Set(ids), new Set(imported.map((question) => question.id)));
assert.equal(imported.find((question) => question.index === 37)?.index, 37);
assert.equal(pages[3].items.length, 8);

const filteredPage = service.query({ includeQuarantined: true, sort: { field: "INDEX", direction: "ASC" }, text: "Câu 51", offset: 0, limit: 50 });
assert.ok(filteredPage.items.some((question) => question.index === 51));
const uiSource = readFileSync("src/components/teacher/TeacherWorkspace.tsx", "utf8");
assert.match(uiSource, /offset, limit: questionPageSize/);
assert.match(uiSource, /Trang trước/);
assert.match(uiSource, /Trang tiếp/);
assert.match(uiSource, /questionOffset \+ questions\.length >= total/);
assert.match(uiSource, /setQuestionOffset\(0\)/);
console.log("QUESTION_BANK_PAGINATION_MODEL_QA=PASS");
console.log("QUESTION_BANK_PAGINATION_UI_QA=PASS");
console.log("QUESTION_NUMBER_ACROSS_PAGES_QA=PASS");
console.log("NO_PAGE_DUPLICATION_QA=PASS");
console.log("NO_PAGE_GAP_QA=PASS");
console.log("PAGINATION_FILTER_QA=PASS");
console.log("PAGINATION_SELECTION_ID_QA=PASS");
console.log("REAL_SOURCE_PAGINATION_QA=PASS");
