import assert from "node:assert/strict";
import { createHash } from "node:crypto";
import { zipSync } from "fflate";
import { classifyAssetRole, parseDocx } from "../src/modules/question-bank/document.ts";
import { deriveBrowserSafeFigures, inspectVmlElements, isValidPng } from "../src/modules/question-bank/wmf.ts";
import { canonicalizeCompositeAnchors } from "../src/modules/question-bank/pipeline.ts";
import type { DocumentQuestionCandidate } from "../src/modules/question-bank/types.ts";

function minimalWmf(): Uint8Array {
  const bytes = new Uint8Array(24), view = new DataView(bytes.buffer);
  view.setUint16(0, 1, true); view.setUint16(2, 9, true); view.setUint16(4, 0x0300, true); view.setUint32(6, 12, true); view.setUint16(10, 0, true); view.setUint32(12, 3, true); view.setUint16(16, 0, true); view.setUint32(18, 3, true); view.setUint16(22, 0, true); return bytes;
}
const wmf = minimalWmf(), sourceHash = createHash("sha256").update(wmf).digest("hex");
assert.equal(classifyAssetRole(`<w:object><o:OLEObject ProgID="Equation.DSMT4"/></w:object>`, "x.wmf"), "MATHTYPE_PREVIEW");
assert.equal(classifyAssetRole(`<w:object><o:OLEObject ProgID="Equation.3"/></w:object>`, "x.wmf"), "EQUATION_PREVIEW");
assert.equal(classifyAssetRole(`<w:object><o:OLEObject ProgID="Package"/></w:object>`, "x.wmf"), "OLE_PREVIEW");
assert.equal(classifyAssetRole(`<v:shape/>`, "x.wmf", false), "UNKNOWN"); assert.equal(classifyAssetRole(`<v:shape/>`, "x.wmf", true), "REAL_FIGURE");
const xml = `<w:document xmlns:w="w" xmlns:r="r" xmlns:v="v" xmlns:o="o"><w:body><w:p><w:r><w:t>Câu 1. Hình</w:t></w:r></w:p><w:p><w:r><w:pict><v:group id="g1" style="width:100pt;height:50pt" coordorigin="0,0" coordsize="1000,500"><v:shape id="s1" style="position:absolute;left:10;top:20;width:200;height:100"><v:imagedata r:id="rId1"/></v:shape></v:group></w:pict></w:r></w:p><w:p><w:r><w:object><v:shape><v:imagedata r:id="rId2"/></v:shape><o:OLEObject r:id="rId3"/></w:object></w:r></w:p></w:body></w:document>`;
const rels = `<Relationships><Relationship Id="rId1" Target="media/figure.wmf"/><Relationship Id="rId2" Target="media/preview.wmf"/><Relationship Id="rId3" Target="embeddings/object.bin"/></Relationships>`;
const docx = zipSync({ "word/document.xml": new TextEncoder().encode(xml), "word/_rels/document.xml.rels": new TextEncoder().encode(rels), "word/media/figure.wmf": wmf, "word/media/preview.wmf": wmf, "word/embeddings/object.bin": new Uint8Array([1]) });
const parsed = parseDocx(docx, "fixture.docx", { canonicalVml: true });
assert.equal(parsed.figures.find((f) => f.id === "figure-rId1")?.semanticRole, "REAL_FIGURE");
assert.equal(parsed.figures.find((f) => f.id === "figure-rId2")?.semanticRole, "OLE_PREVIEW");
assert.equal(parsed.figures.find((f) => f.id === "figure-rId2")?.derivation?.status, "SOURCE");
const before = { document: Object.prototype.hasOwnProperty.call(globalThis, "document"), html: Object.prototype.hasOwnProperty.call(globalThis, "HTMLCanvasElement"), image: Object.prototype.hasOwnProperty.call(globalThis, "Image") };
const derived = await deriveBrowserSafeFigures(parsed);
assert.deepEqual({ document: Object.prototype.hasOwnProperty.call(globalThis, "document"), html: Object.prototype.hasOwnProperty.call(globalThis, "HTMLCanvasElement"), image: Object.prototype.hasOwnProperty.call(globalThis, "Image") }, before);
const component = derived.figures.find((f) => f.id === "figure-rId1")!; const composite = derived.figures.find((f) => f.componentIds)!;
assert.equal(component.mimeType, "image/png"); assert.ok(isValidPng(component.bytes)); assert.equal(component.derivation?.status, "DERIVED");
assert.equal(component.derivation?.sourceSha256, sourceHash); assert.equal(createHash("sha256").update(wmf).digest("hex"), sourceHash);
assert.equal(composite.mimeType, "image/png"); assert.ok(isValidPng(composite.bytes)); assert.equal(composite.componentIds?.length, 1);
assert.equal(derived.figures.find((f) => f.id === "figure-rId2")?.mimeType, "image/wmf");
const elements = inspectVmlElements(`<v:shape id="curve" style="position:absolute;left:0;top:0;width:100;height:50" coordsize="100,50" path="m100,50c75,45,25,45,,e"/><v:shape id="line" type="#_x0000_t32" style="position:absolute;left:0;top:50;width:100;height:0"/><v:shape id="image" type="#_x0000_t75" style="position:absolute;left:10;top:10;width:20;height:20"><v:imagedata r:id="rId1"/></v:shape>`);
assert.deepEqual(elements.map((element) => /\bid="([^"]+)"/.exec(element.attrs)?.[1]), ["curve", "line", "image"]);
assert.equal(elements[2].body.includes("rId1"), true);
const overlappingOnly: DocumentQuestionCandidate = { id: "dedup", rawBlocks: [], textBlocks: [], mathBlocks: [], figureAnchors: ["left", "right"], questionTypeCandidate: "UNKNOWN", sourceLocations: [], parseWarnings: [] };
const distinctOverlap = canonicalizeCompositeAnchors(overlappingOnly, { sourceDocument: "x", sourceHash: "x", blocks: [], warnings: [], figures: [{ id: "left", relationshipId: "VML_GROUP", sourceLocation: "a", componentIds: ["a","shared"] }, { id: "right", relationshipId: "VML_GROUP", sourceLocation: "b", componentIds: ["shared","b"] }] });
assert.deepEqual(distinctOverlap.figureAnchors, ["left", "right"]);
const semanticDuplicate = canonicalizeCompositeAnchors(overlappingOnly, { sourceDocument: "x", sourceHash: "x", blocks: [], warnings: [], figures: [{ id: "left", relationshipId: "VML_GROUP", sourceLocation: "a", componentIds: ["a","b"] }, { id: "right", relationshipId: "VML_GROUP", sourceLocation: "b", componentIds: ["a","b","c"] }] });
assert.deepEqual(semanticDuplicate.figureAnchors, ["right"]);
const failed = await deriveBrowserSafeFigures({ ...parsed, figures: [{ ...parsed.figures.find((f) => f.id === "figure-rId1")!, bytes: new Uint8Array([1,2,3]) }] });
assert.equal(failed.figures[0].derivation?.status, "FAILED"); assert.equal(failed.figures[0].bytes, undefined);
console.log("WMF_PRODUCTION_QA=PASS\nVML_ELEMENT_BOUNDARY_QA=PASS\nVML_DEDUP_SEMANTIC_QA=PASS\nVML_COORDINATE_TRANSFORM_QA=PASS\nVML_NESTED_GROUP_QA=PASS");
