import assert from "node:assert/strict";
import brandRoot from "../registry/mst-math-brand-root.json";
import profiles from "../registry/output-profiles.json";
import standards from "../registry/standards.json";
import migration from "../registry/mst-math-migration-v1.json";
import icons from "../registry/mst-math-dna-icons-v1.1.json";
import { MST_MATH_DNA, PIMATH_DNA, resolveBrand, resolveConsumerProfile, resolveIcon, resolveOutputProfile } from "../src/config/mstMathBrandRoot.ts";
assert.equal(brandRoot.standardId, "MST-MATH-DNA-V1.0");
assert.equal(brandRoot.codeRoot, "MST_MATH_DNA");
assert.equal(brandRoot.architecture.product, "MST-MATH");
assert.equal(brandRoot.globalBaseline, "MST_MATH_DNA_GLOBAL_BASELINE_V1.1");
assert.equal(resolveBrand(), MST_MATH_DNA);
assert.equal(PIMATH_DNA, MST_MATH_DNA);
assert.equal(profiles.parentBrandId, "MST-MATH-DNA-V1.0");
const p01 = resolveOutputProfile("P01_LEARNING_MATERIAL") as any;
assert.equal(p01.iconAuthority, "MST-MATH-DNA-SEMANTIC-ICONS-V1.1");
assert.ok(p01.canonicalReferences.includes("MST-MATH-DNA-SEMANTIC-ICONS-V1.1"));
assert.equal(resolveConsumerProfile("VIDEO").profileId, "MST_MATH_VIDEO_VISUAL_CANONICAL_V2.0");
assert.equal(resolveOutputProfile("PIMATH_VIDEO_VISUAL_CANONICAL_V2.0").profileId, "MST_MATH_VIDEO_VISUAL_CANONICAL_V2.0");
assert.equal(icons.standardId, "MST-MATH-DNA-SEMANTIC-ICONS-V1.1");
assert.ok(Object.values(icons.roles).every((role) => role.resource.startsWith("assets/mst-math-icons/")));
assert.equal(resolveIcon("FORMULA").authority, "MST-MATH-DNA-SEMANTIC-ICONS-V1.1");
assert.equal(migration.mappings["PIMATH-DNA-V1.0"], "MST-MATH-DNA-V1.0");
assert.equal(standards.standards.find((s:any) => s.id === "MST-MATH-DNA-V1.0")?.status, "LOCKED_CANONICAL_GLOBAL");
assert.equal(standards.standards.find((s:any) => s.id === "PIMATH-DNA-V1.0")?.status, "COMPATIBILITY_ALIAS");
console.log("MST_MATH_CANONICAL_MIGRATION_QA=PASS");
