import assert from "node:assert/strict";
import fs from "node:fs";
import { FOLD_FIXTURES, buildFoldTopology, createDevelopableFoldScene, createDevelopableManimBoundary, createFoldScene, createManimFoldBoundary, createNGonalSolidScene, developableNetToSvg, developableNetToTikz, foldNetToSvg, foldNetToTikz, updateDevelopableFoldScene, updateFoldScene } from "../src/modules/fold-3d/index.js";
import { solveSurfaceShortestPath } from "../src/modules/surface-shortest-path/index.js";
import type { CanonicalSurfacePoint, PathWaypoint } from "../src/modules/surface-shortest-path/index.js";
import { buildPatternTopology, createPatternFoldScene, PATTERN_FOLD_FIXTURES, toPatternManimBoundary, toPatternSvg, toPatternTikz, updatePatternFoldScene } from "../src/modules/pattern-fold/index.js";
const close=(a:number,b:number,e=1e-8)=>assert.ok(Math.abs(a-b)<e,`${a} != ${b}`),finite=(values:number[])=>assert.ok(values.every(Number.isFinite));
for(const kind of ["prism","pyramid"] as const)for(const n of [3,5,8,10]){const source=createNGonalSolidScene({kind,baseSides:n});assert.equal(source.status,"PASS");const topology=buildFoldTopology(source.value!).value!,scene=createFoldScene(source.value!,0).value!,ids={faces:topology.faces.map(x=>x.id),edges:topology.edges.map(x=>x.id)};for(const progress of [0,.5,1,0]){const next=updateFoldScene(scene,progress).value!;assert.deepEqual(next.topology.faces.map(x=>x.id),ids.faces);assert.deepEqual(next.topology.edges.map(x=>x.id),ids.edges);next.state.faceTransforms.forEach(x=>finite(x.matrix));}if(n===10)assert.deepEqual([topology.vertices.length,topology.edges.length,topology.faces.length],kind==="prism"?[20,30,12]:[11,20,11]);}
const curved=[createDevelopableFoldScene({solidType:"cylinder",radius:2,height:5}).value!,createDevelopableFoldScene({solidType:"cone",radius:3,height:4}).value!,createDevelopableFoldScene({solidType:"conical_frustum",largeRadius:4,smallRadius:2,height:3}).value!];close(curved[0].dimensions.circumference,4*Math.PI);close(curved[1].dimensions.slantHeight,5);close(curved[1].dimensions.sectorAngleDegrees,216);close(curved[2].dimensions.outerRadius*curved[2].dimensions.sectorAngleRadians,8*Math.PI);for(const scene of curved){const flat=updateDevelopableFoldScene(scene,0).value!;assert.equal(updateDevelopableFoldScene(updateDevelopableFoldScene(scene,1).value!,0).value!.progress,flat.progress);assert.match(developableNetToSvg(scene).output,/^<svg/);assert.match(developableNetToTikz(scene).output,/tikzpicture/);assert.equal(createDevelopableManimBoundary(scene).scene,scene);}
const prism=buildFoldTopology(createNGonalSolidScene({kind:"prism",baseSides:6}).value!).value!,facePoint=(id:string,faceId:string):CanonicalSurfacePoint=>{const face=prism.faces.find(x=>x.id===faceId)!;return {id,solidId:prism.solidId,surfaceId:faceId,attachmentType:"FACE",localCoordinates:{kind:"face_barycentric",vertexIds:face.vertexIds,weights:face.vertexIds.map(()=>1/face.vertexIds.length)},provenance:"user"};},a=facePoint("A","fold-face-side-0"),c1={...facePoint("C1","fold-face-side-1"),order:0,required:true} as PathWaypoint,c2={...facePoint("C2","fold-face-side-2"),order:1,required:true} as PathWaypoint,b=facePoint("B","fold-face-side-3");const auto=solveSurfaceShortestPath({surface:{kind:"polyhedral",topology:prism},startPoint:a,endPoint:b,waypoints:[c1,c2]});assert.equal(auto.status,"PASS");assert.deepEqual(auto.waypoints.map(x=>x.id),["C1","C2"]);assert.equal(auto.metadata.orderedWaypointsPreserved,true);const manual=solveSurfaceShortestPath({surface:{kind:"polyhedral",topology:prism},startPoint:a,endPoint:b,waypoints:[c1,c2],directive:{mode:"MANUAL",rootSurfaceId:a.surfaceId,surfaceSequence:[a.surfaceId,c1.surfaceId,c2.surfaceId,b.surfaceId],direction:"CLOCKWISE"}});assert.equal(manual.status,"PASS");const bad=solveSurfaceShortestPath({surface:{kind:"polyhedral",topology:prism},startPoint:a,endPoint:b,directive:{mode:"MANUAL",rootSurfaceId:a.surfaceId,surfaceSequence:[a.surfaceId,"missing-face",b.surfaceId]}});assert.equal(bad.status,"FAIL");const counter=solveSurfaceShortestPath({surface:{kind:"polyhedral",topology:prism},startPoint:a,endPoint:b,directive:{mode:"MANUAL",rootSurfaceId:a.surfaceId,surfaceSequence:[a.surfaceId,b.surfaceId],direction:"COUNTERCLOCKWISE"}});assert.notDeepEqual(manual.unfoldDirective.direction,counter.unfoldDirective.direction);
for(const id of ["P02","P04","P06","P07","P08"]){const scene=createPatternFoldScene(PATTERN_FOLD_FIXTURES[id],0).value!;const flat=updatePatternFoldScene(scene,0,0).value!,folded=updatePatternFoldScene(scene,Math.max(0,scene.sequence.steps.length-1),1).value!,returned=updatePatternFoldScene(folded,0,0).value!;assert.deepEqual(returned.state.regionTransforms,flat.state.regionTransforms);assert.deepEqual(folded.correspondence,scene.correspondence);assert.match(toPatternSvg(scene).output!,/^<svg/);assert.match(toPatternTikz(scene).output!,/tikzpicture/);assert.equal(toPatternManimBoundary(scene).scene,scene);}assert.equal(createPatternFoldScene(PATTERN_FOLD_FIXTURES.P04).value!.topology.holes.length,1);assert.ok(buildPatternTopology(PATTERN_FOLD_FIXTURES.P09).issues.some(x=>x.code==="DETACHED_FOLD_COMPONENT"));assert.ok(buildPatternTopology(PATTERN_FOLD_FIXTURES.P10).issues.some(x=>x.code==="CUT_CREASE_CONFLICT"));const invalid=structuredClone(PATTERN_FOLD_FIXTURES.P02);invalid.cuts.push({id:"invalid-cut",points:[[Number.NaN,0]],cutType:"FULL"});assert.equal(buildPatternTopology(invalid).status,"FAIL");
const cube=createFoldScene(FOLD_FIXTURES.cube,0).value!;assert.match(foldNetToSvg(cube).output!,/^<svg/);assert.match(foldNetToTikz(cube).output!,/tikzpicture/);assert.equal(createManimFoldBoundary(cube).scene,cube);
const viewer=fs.readFileSync("src/components/dev/Fold3DViewer.tsx","utf8"),patternViewer=fs.readFileSync("src/components/dev/PatternFoldViewerPanel.tsx","utf8"),main=fs.readFileSync("src/main.tsx","utf8");assert.match(viewer,/SOLID.*SHORTEST_PATH.*PATTERN/);assert.match(viewer,/\[sceneModel,viewerMode\]/);for(const token of ["cancelAnimationFrame","observer.disconnect","removeEventListener","controls.dispose","mapping.dispose","renderer.dispose","forceContextLoss"])assert.match(viewer,new RegExp(token));for(const token of ["cancelAnimationFrame","observer.disconnect","controls.dispose","mapping.dispose","renderer.dispose","forceContextLoss"])assert.match(patternViewer,new RegExp(token));assert.match(main,/\/dev\/fold-3d/);
console.log("IA_4_9_FOLD_STUDIO_INTEGRATION_TESTS=PASS");
