import assert from "node:assert/strict";
import { addConstructionCircle, addConstructionPoint, addConstructionSegment, addSymmetryGuide, applyDiscard, assignCircleSemantic, assignMirroredCrease, assignSegmentSemantic, assignSymmetricSegmentSemantic, createExactEdgeJoin, createPlanarPattern, deriveEdgeToEdgeFold, derivePointToPointCrease, mirrorConstructionPoint, mirrorConstructionSegment, previewDiscardRegion, previewSymmetricDiscard, resolveGridType, snapConstructionPoint, updateCreaseFoldSide, updateGrid, updateSymmetricCreasePair, validateSymmetricCreasePair } from "../src/modules/pattern-fold/index.js";

let sheet=createPlanarPattern({kind:"square",side:8}).value!;
assert.equal(resolveGridType(sheet,"AUTO"),"CARTESIAN");sheet=updateGrid(sheet,{visible:true,snapGrid:true,spacing:1}).value!;assert.deepEqual(snapConstructionPoint(sheet,[1.13,1.86]),[1,2]);
sheet=addConstructionPoint(sheet,[-2,0]).value!;sheet=addConstructionPoint(sheet,[2,0]).value!;sheet=addConstructionSegment(sheet,["point-1","point-2"]).value!;assert.equal(sheet.construction!.segments[0].semantic,"NEUTRAL");
sheet=assignSegmentSemantic(sheet,"segment-1","GUIDE").value!;assert.equal(sheet.cuts.length,0);assert.equal(sheet.creases.length,0);
sheet=assignSegmentSemantic(sheet,"segment-1","CREASE","VALLEY","B").value!;assert.equal(sheet.creases.length,1);assert.equal(sheet.creases[0].movingRegionId,sheet.creases[0].regionIds[1]);sheet=updateCreaseFoldSide(sheet,"crease-1","A").value!;assert.equal(sheet.creases[0].foldSide,"A");
let circle=createPlanarPattern({kind:"circle",radius:6}).value!;assert.equal(resolveGridType(circle,"AUTO"),"POLAR_REFERENCE");circle=addConstructionPoint(circle,[0,0]).value!;circle=addConstructionCircle(circle,"point-1",2).value!;assert.equal(circle.construction!.circles[0].semantic,"NEUTRAL");
circle=assignCircleSemantic(circle,"circle-1","CUT").value!;assert.equal(circle.construction!.circles[0].semantic,"CUT");assert.equal(circle.shapes[0].geometry.kind,"circle");assert.equal(circle.regions.length,2);
let symmetric=createPlanarPattern({kind:"square",side:8}).value!;symmetric=addConstructionPoint(symmetric,[-2,-2]).value!;symmetric=addConstructionPoint(symmetric,[-2,2]).value!;symmetric=addConstructionSegment(symmetric,["point-1","point-2"]).value!;symmetric=addSymmetryGuide(symmetric,"VERTICAL_AXIS").value!;symmetric=mirrorConstructionPoint(symmetric,"point-1","symmetry-1").value!;symmetric=mirrorConstructionSegment(symmetric,"segment-1","symmetry-1").value!;assert.equal(symmetric.construction!.segments.length,2);symmetric=assignSymmetricSegmentSemantic(symmetric,"segment-1","CUT").value!;assert.equal(symmetric.cuts.length,2);
let mirroredCreases=createPlanarPattern({kind:"square",side:8}).value!;mirroredCreases=addConstructionPoint(mirroredCreases,[-2,-2]).value!;mirroredCreases=addConstructionPoint(mirroredCreases,[-2,2]).value!;mirroredCreases=addConstructionSegment(mirroredCreases,["point-1","point-2"]).value!;mirroredCreases=addSymmetryGuide(mirroredCreases,"VERTICAL_AXIS").value!;mirroredCreases=mirrorConstructionSegment(mirroredCreases,"segment-1","symmetry-1").value!;mirroredCreases=assignMirroredCrease(mirroredCreases,"segment-1").value!;assert.equal(mirroredCreases.creases.length,2);assert.equal(validateSymmetricCreasePair(mirroredCreases,"crease-1").value!.status,"VALID");mirroredCreases=updateSymmetricCreasePair(mirroredCreases,"crease-1",{assignment:"MOUNTAIN",foldSide:"A",targetAngleRadians:Math.PI/3},true).value!;assert.deepEqual(mirroredCreases.creases.map(x=>[x.assignment,x.foldSide,x.targetAngleRadians]),[["MOUNTAIN","A",Math.PI/3],["MOUNTAIN","A",Math.PI/3]]);assert.equal(validateSymmetricCreasePair(mirroredCreases,"crease-2").status,"PASS");
const pending=previewSymmetricDiscard(symmetric,"region-1","symmetry-1").value!;assert.equal(pending.regions.filter(r=>r.status==="DISCARD_PREVIEW").length,2);const retained=applyDiscard(pending);assert.equal(retained.status,"PASS");assert.ok(retained.value!.removedRegions!.length>=2);
let target=createPlanarPattern({kind:"square",side:8}).value!;target=addConstructionPoint(target,[-1,0]).value!;target=addConstructionPoint(target,[1,0]).value!;const p2p=derivePointToPointCrease(target,"point-1","point-2");assert.equal(p2p.status,"PASS");assert.ok(Math.abs(p2p.value!.creases[0].points[0][0])<1e-8);
assert.equal(deriveEdgeToEdgeFold([[0,0],[2,0]],[[0,1],[2,1]]).status,"PASS");assert.equal(deriveEdgeToEdgeFold([[0,0],[2,0]],[[0,1],[3,1]]).issues[0].code,"EDGE_COINCIDENCE_UNRESOLVED");assert.equal(createExactEdgeJoin([],[[0,0],[2,0]],[[0,1],[2,1]]).status,"PASS");assert.equal(createExactEdgeJoin([],[[0,0],[2,0]],[[0,1],[3,1]]).issues[0].code,"JOIN_LENGTH_MISMATCH");
let cutSheet=createPlanarPattern({kind:"square",side:8}).value!;cutSheet=addConstructionPoint(cutSheet,[-4,0]).value!;cutSheet=addConstructionPoint(cutSheet,[4,0]).value!;cutSheet=addConstructionSegment(cutSheet,["point-1","point-2"]).value!;cutSheet=assignSegmentSemantic(cutSheet,"segment-1","CUT").value!;const preview=previewDiscardRegion(cutSheet,"region-1").value!;assert.equal(preview.regions[0].status,"DISCARD_PREVIEW");assert.equal(applyDiscard(preview).value!.removedRegions!.length,1);
console.log("FOLD_STUDIO_MASTER_ENGINE_TESTS=PASS");
