import assert from "node:assert/strict";
import { PIMATH_DNA, resolveAccessibilityAuthority, resolveVoiceNarrationAuthority } from "../src/config/naMathBrandRoot.ts";
const accessibility = resolveAccessibilityAuthority();
const voice = resolveVoiceNarrationAuthority();
assert.equal(PIMATH_DNA.references.accessibility, "PIMATH_ACCESSIBILITY_CANONICAL_V1.0");
assert.equal(PIMATH_DNA.references.voice, "PIMATH_VOICE_NARRATION_CANONICAL_V1.0");
assert.equal(PIMATH_DNA.references.icons, "PIMATH-DNA-SEMANTIC-ICONS-V2.0");
assert.equal(accessibility.authority.role, "ACCESSIBILITY_AUTHORITY");
assert.equal(accessibility.authority.consumes.icons, "PIMATH-DNA-SEMANTIC-ICONS-V2.0");
assert.equal(voice.authority.role, "VOICE_NARRATION_AUTHORITY");
assert.equal(accessibility.authority.overrideCoreDna, false);
assert.equal(voice.authority.overrideCoreDna, false);
assert.equal(accessibility.provenance.binding, "CANONICAL_BINDING");
assert.equal(voice.provenance.binding, "CANONICAL_BINDING");
assert.ok("ttsAdapterPolicy" in voice.authority.contract);
assert.match(voice.authority.contract.ttsAdapterPolicy, /TTS_PROVIDER != VOICE_AUTHORITY/);
assert.ok("videoVisual" in voice.authority.consumes);
assert.equal(voice.authority.consumes.videoVisual, "PIMATH_VIDEO_VISUAL_CANONICAL_V2.0");
console.log("ACCESSIBILITY_AUTHORITY_REGISTERED=PASS\nACCESSIBILITY_AUTHORITY_RESOLVED=PASS\nACCESSIBILITY_ICON_AUTHORITY_V2=PASS\nACCESSIBILITY_PROVENANCE=PASS\nVOICE_AUTHORITY_REGISTERED=PASS\nVOICE_AUTHORITY_RESOLVED=PASS\nVOICE_PROVENANCE=PASS\nTTS_PROVIDER_NOT_AUTHORITY=PASS\nNO_PARALLEL_ACCESSIBILITY_AUTHORITY=PASS\nNO_PARALLEL_VOICE_AUTHORITY=PASS");
