import assert from "node:assert/strict";
import { FOLD_FIXTURES, buildFoldTopology, createDevelopableFoldScene, createNGonalSolidScene } from "../src/modules/fold-3d/index.js";
import { curvedIntersectionToSurfacePoint, polyhedralIntersectionToSurfacePoint, solveSurfaceShortestPath } from "../src/modules/surface-shortest-path/index.js";
import type { CanonicalSurfacePoint, PathWaypoint } from "../src/modules/surface-shortest-path/index.js";
import { Vector3 } from "three";

const close=(a:number,b:number,t=1e-7)=>assert.ok(Math.abs(a-b)<t,`${a} != ${b}`);
function facePoint(topology:ReturnType<typeof buildFoldTopology>["value"],faceId:string,id:string):CanonicalSurfacePoint{const face=topology!.faces.find(item=>item.id===faceId)!;const positions=new Map(topology!.vertices.map(v=>[v.id,v.foldedPosition])),world=face.vertexIds.reduce<[number,number,number]>((sum,vertexId)=>{const p=positions.get(vertexId)!;return[sum[0]+p[0]/face.vertexIds.length,sum[1]+p[1]/face.vertexIds.length,sum[2]+p[2]/face.vertexIds.length];},[0,0,0]);return{id,solidId:topology!.solidId,surfaceId:faceId,attachmentType:"FACE",localCoordinates:{kind:"face_barycentric",vertexIds:face.vertexIds,weights:face.vertexIds.map(()=>1/face.vertexIds.length)},worldCoordinates:world,provenance:"user"};}
function polySolve(scene:typeof FOLD_FIXTURES.cube,startFace:string,endFace:string){const topology=buildFoldTopology(scene).value!,start=facePoint(topology,startFace,"A"),end=facePoint(topology,endFace,"B"),result=solveSurfaceShortestPath({surface:{kind:"polyhedral",topology},startPoint:start,endPoint:end});assert.equal(result.status,"PASS",JSON.stringify(result.issues));assert.ok(result.length>=0);return{topology,start,end,result};}

const same=polySolve(FOLD_FIXTURES.cube,"fold-face-front","fold-face-front");assert.equal(same.result.selectedRoute.length,1);
const adjacent=polySolve(FOLD_FIXTURES.cube,"fold-face-front","fold-face-right");assert.ok(adjacent.result.crossingPoints.length>=1);
polySolve(FOLD_FIXTURES.cube,"fold-face-front","fold-face-back");polySolve(FOLD_FIXTURES.rectangularPrism,"fold-face-bottom","fold-face-top");polySolve(FOLD_FIXTURES.tetrahedron,"fold-face-base","fold-face-abd");
for(const kind of ["prism","pyramid"] as const)for(const n of [3,5,8,10]){const scene=createNGonalSolidScene({kind,baseSides:n}).value!,topology=buildFoldTopology(scene).value!,start=facePoint(topology,"fold-face-side-0","A"),end=facePoint(topology,`fold-face-side-${Math.min(2,n-1)}`,"B"),result=solveSurfaceShortestPath({surface:{kind:"polyhedral",topology},startPoint:start,endPoint:end});assert.equal(result.status,"PASS",`${kind}-${n}:${JSON.stringify(result.issues)}`);}
const manual=solveSurfaceShortestPath({surface:{kind:"polyhedral",topology:adjacent.topology},startPoint:adjacent.start,endPoint:adjacent.end,directive:{mode:"MANUAL",rootSurfaceId:"fold-face-front",surfaceSequence:["fold-face-front","fold-face-right"]}});assert.equal(manual.status,"PASS");assert.deepEqual(manual.selectedRoute,["fold-face-front","fold-face-right"]);
const badManual=solveSurfaceShortestPath({surface:{kind:"polyhedral",topology:adjacent.topology},startPoint:adjacent.start,endPoint:adjacent.end,directive:{mode:"MANUAL",rootSurfaceId:"fold-face-front",surfaceSequence:["fold-face-front","fold-face-back","fold-face-right"]}});assert.equal(badManual.status,"FAIL");
const waypoint={...facePoint(adjacent.topology,"fold-face-bottom","C"),order:0,required:true} as PathWaypoint;const waypointResult=solveSurfaceShortestPath({surface:{kind:"polyhedral",topology:adjacent.topology},startPoint:adjacent.start,endPoint:adjacent.end,waypoints:[waypoint]});assert.equal(waypointResult.status,"PASS");assert.equal(waypointResult.segments.length,2);assert.equal(waypointResult.waypoints[0].id,"C");

function curvedPoint(scene:ReturnType<typeof createDevelopableFoldScene>["value"],id:string,theta:number,longitudinal:number):CanonicalSurfacePoint{return{id,solidId:scene!.id,surfaceId:scene!.lateralSurfaceId,attachmentType:"CURVED_SURFACE",localCoordinates:{kind:"curved",theta,longitudinal},provenance:"user"};}
for(const scene of [createDevelopableFoldScene({solidType:"cylinder",radius:2,height:5}).value!,createDevelopableFoldScene({solidType:"cone",radius:3,height:4}).value!,createDevelopableFoldScene({solidType:"conical_frustum",largeRadius:4,smallRadius:2,height:3}).value!]){const longitudinal=scene.solidType==="cylinder"?2:scene.solidType==="cone"?3:(scene.dimensions.innerRadius+scene.dimensions.outerRadius)/2,a=curvedPoint(scene,"A",.1,longitudinal),b=curvedPoint(scene,"B",5.9,longitudinal),ab=solveSurfaceShortestPath({surface:{kind:"developable",scene},startPoint:a,endPoint:b}),ba=solveSurfaceShortestPath({surface:{kind:"developable",scene},startPoint:b,endPoint:a});assert.equal(ab.status,"PASS");assert.equal(ba.status,"PASS");close(ab.length,ba.length);assert.equal(ab.metadata.candidateCount,5);const zero=solveSurfaceShortestPath({surface:{kind:"developable",scene},startPoint:a,endPoint:{...a,id:"B"}});close(zero.length,0);const waypoint={...curvedPoint(scene,"C",2,longitudinal),order:0,required:true} as PathWaypoint;const via=solveSurfaceShortestPath({surface:{kind:"developable",scene},startPoint:a,endPoint:b,waypoints:[waypoint]});assert.equal(via.segments.length,2);assert.equal(via.metadata.orderedWaypointsPreserved,true);}
const cylinder=createDevelopableFoldScene({solidType:"cylinder",radius:2,height:5}).value!,seamA=curvedPoint(cylinder,"A",.1,2),seamB=curvedPoint(cylinder,"B",2*Math.PI-.1,2),seamRoute=solveSurfaceShortestPath({surface:{kind:"developable",scene:cylinder},startPoint:seamA,endPoint:seamB});assert.notEqual(seamRoute.segments[0].selectedCandidate?.periodicCopy,0);close(seamRoute.length,.4);
const frustum=createDevelopableFoldScene({solidType:"conical_frustum",largeRadius:4,smallRadius:2,height:3}).value!,fa=curvedPoint(frustum,"A",0,frustum.dimensions.outerRadius),fb=curvedPoint(frustum,"B",Math.PI,frustum.dimensions.outerRadius),frustumResult=solveSurfaceShortestPath({surface:{kind:"developable",scene:frustum},startPoint:fa,endPoint:fb});assert.equal(frustumResult.status,"PASS");assert.ok(frustumResult.candidateRoutes.some(candidate=>!candidate.valid&&candidate.rejectionReason==="PATH_OUTSIDE_ROUTE_STRIP"));
const pickedPoly=polyhedralIntersectionToSurfacePoint({id:"picked",solidId:"solid",faceId:"face",triangleVertexIds:["a","b","c"],barycentric:[.2,.3,.5],worldPoint:new Vector3(1,2,3)});assert.equal(pickedPoly.localCoordinates.kind,"face_barycentric");const pickedCurve=curvedIntersectionToSurfacePoint({id:"picked-curve",solidId:"solid",surfaceId:"surface-lateral",theta:1,longitudinal:2,worldPoint:new Vector3()});assert.equal(pickedCurve.localCoordinates.kind,"curved");

console.log("SURFACE_SHORTEST_PATH_V1_TESTS=PASS");
