import assert from "node:assert/strict";
import { addStraightCrease, clipLineToGeometry, createPatternFoldScene, createPlanarPattern, updatePatternFoldScene } from "../src/modules/pattern-fold/index.js";
import { createDevelopableFoldScene } from "../src/modules/fold-3d/index.js";
import { createDevelopableThreeMapping } from "../src/modules/fold-3d/developable-three-adapter.js";

const near=(a:number,b:number,e=1e-7)=>assert.ok(Math.abs(a-b)<e,`${a} != ${b}`);
const square=createPlanarPattern({kind:"square",side:6});assert.equal(square.status,"PASS");assert.deepEqual(square.value!.boundary.geometry,{kind:"polygon",vertices:[[-3,-3],[3,-3],[3,3],[-3,3]]});
const squareFold=addStraightCrease(square.value!,[-10,0],[10,0],"VALLEY",90,"B");assert.equal(squareFold.status,"PASS");assert.deepEqual(squareFold.value!.creases[0].points,[[-3,0],[3,0]]);assert.equal(squareFold.value!.regions.length,2);
const squareScene=createPatternFoldScene(squareFold.value!,1).value!;const moving=squareScene.state.regionTransforms.find(x=>x.regionId===squareFold.value!.creases[0].regionIds[1])!;for(let i=1;i<moving.transformedVertices.length;i++){const a=moving.transformedVertices[0],b=moving.transformedVertices[i];near(Math.hypot(...b.position3D.map((x,j)=>x-a.position3D[j]) as [number,number,number]),Math.hypot(b.position2D[0]-a.position2D[0],b.position2D[1]-a.position2D[1]));}assert.deepEqual(updatePatternFoldScene(squareScene,0,0).value!.state.regionTransforms.map(x=>x.transformedVertices.map(v=>v.position3D)),createPatternFoldScene(squareFold.value!,0).value!.state.regionTransforms.map(x=>x.transformedVertices.map(v=>v.position3D)));
const circle=createPlanarPattern({kind:"circle",radius:4});assert.equal(circle.value!.boundary.geometry.kind,"circle");const diameter=clipLineToGeometry(circle.value!.boundary.geometry,[-10,0],[10,0]).value!;near(diameter[0][0],-4);near(diameter[1][0],4);const chord=clipLineToGeometry(circle.value!.boundary.geometry,[-10,2],[10,2]).value!;near(chord[0][0],-Math.sqrt(12));near(chord[1][0],Math.sqrt(12));assert.equal(addStraightCrease(circle.value!,[-10,0],[10,0],"MOUNTAIN",90).value!.regions.length,2);
assert.equal(createPlanarPattern({kind:"triangle",a:1,b:2,c:9}).issues[0].code,"INVALID_TRIANGLE");const triangle=createPlanarPattern({kind:"triangle",a:5,b:5,c:6}).value!;assert.equal(addStraightCrease(triangle,[-10,0],[10,0],"VALLEY",60).status,"PASS");
const curved=createDevelopableFoldScene({solidType:"cylinder",radius:2,height:5}).value!,mapping=createDevelopableThreeMapping(curved),topology=structuredClone(curved.net);mapping.setSurfaceVisible("base-top",false);assert.equal(mapping.components.get("base-top")!.visible,false);assert.deepEqual(curved.net,topology);mapping.setSurfaceVisible("base-top",true);assert.equal(mapping.components.get("base-top")!.visible,true);mapping.dispose();
console.log("IA_4_9R2_AUTHORING_TESTS=PASS");
