import type { Vec2 } from "../fold-3d/types.js";
import { createPatternFoldScene } from "./engine.js";
import type { FoldAssignment, PatternBoundarySegment, PatternCrease, PatternFoldScene, PatternFoldSequence, PatternGeometry, PatternResult, PatternSheet } from "./types.js";
const EPS=1e-8;
const fail=<T>(code:string,path:string,message:string):PatternResult<T>=>({status:"FAIL",issues:[{code,severity:"error",path,message}]});
const positive=(n:number)=>Number.isFinite(n)&&n>EPS;
const cross=(a:Vec2,b:Vec2,c:Vec2)=>(b[0]-a[0])*(c[1]-a[1])-(b[1]-a[1])*(c[0]-a[0]);
const unique=(points:Vec2[])=>points.filter((p,i)=>points.findIndex(q=>Math.hypot(p[0]-q[0],p[1]-q[1])<EPS)===i);
const area=(p:Vec2[])=>Math.abs(p.reduce((s,a,i)=>s+a[0]*p[(i+1)%p.length][1]-a[1]*p[(i+1)%p.length][0],0))/2;
const centroid=(p:Vec2[]):Vec2=>[p.reduce((s,x)=>s+x[0],0)/p.length,p.reduce((s,x)=>s+x[1],0)/p.length];
export type PlanarShapeInput={kind:"square";side:number}|{kind:"rectangle";width:number;height:number}|{kind:"circle";radius:number}|{kind:"triangle";a:number;b:number;c:number};
export const tessellateCircle=(center:Vec2,radius:number,segments=96):Vec2[]=>Array.from({length:segments},(_,i)=>[center[0]+radius*Math.cos(2*Math.PI*i/segments),center[1]+radius*Math.sin(2*Math.PI*i/segments)]);
export function createPlanarPattern(input:PlanarShapeInput,id="authored-pattern"):PatternResult<PatternSheet>{let geometry:PatternGeometry,vertices:Vec2[],sourceShape:NonNullable<PatternSheet["sourceShape"]>,kind:PatternSheet["boundary"]["kind"]=input.kind;if(input.kind==="square"){if(!positive(input.side))return fail("INVALID_DIMENSION","side","Side must be positive and finite");const h=input.side/2;vertices=[[-h,-h],[h,-h],[h,h],[-h,h]];geometry={kind:"polygon",vertices};sourceShape={type:"SQUARE",side:input.side};}else if(input.kind==="rectangle"){if(!positive(input.width)||!positive(input.height))return fail("INVALID_DIMENSION","dimensions","Width and height must be positive and finite");const x=input.width/2,y=input.height/2;vertices=[[-x,-y],[x,-y],[x,y],[-x,y]];geometry={kind:"polygon",vertices};sourceShape={type:"RECTANGLE",width:input.width,height:input.height};}else if(input.kind==="circle"){if(!positive(input.radius))return fail("INVALID_RADIUS","radius","Radius must be positive and finite");const center:Vec2=[0,0];geometry={kind:"circle",center,radius:input.radius};vertices=tessellateCircle(center,input.radius);sourceShape={type:"CIRCLE",center,radius:input.radius};}else{if(![input.a,input.b,input.c].every(positive)||input.a+input.b<=input.c+EPS||input.a+input.c<=input.b+EPS||input.b+input.c<=input.a+EPS)return fail("INVALID_TRIANGLE","sides","Triangle inequality is not satisfied");const x=(input.b**2+input.c**2-input.a**2)/(2*input.c),y=Math.sqrt(input.b**2-x**2);vertices=[[-input.c/2,0],[input.c/2,0],[x-input.c/2,y]];const cy=vertices.reduce((s,p)=>s+p[1],0)/3;vertices=vertices.map(p=>[p[0],p[1]-cy]);geometry={kind:"polygon",vertices};sourceShape={type:"TRIANGLE",a:input.a,b:input.b,c:input.c};}return{status:"PASS",issues:[],value:{id,sourceShape,boundary:{id:`${id}:boundary`,kind,geometry},shapes:[],cuts:[],creases:[],regions:[{id:"region-1",vertices,role:"BASE"}],rootRegionId:"region-1"}};}
export const geometryContainsPoint=(geometry:PatternGeometry,point:Vec2):boolean=>geometry.kind==="circle"?Math.hypot(point[0]-geometry.center[0],point[1]-geometry.center[1])<=geometry.radius+EPS:(()=>{let inside=false;for(let i=0,j=geometry.vertices.length-1;i<geometry.vertices.length;j=i++){const a=geometry.vertices[i],b=geometry.vertices[j];if(Math.abs(cross(a,b,point))<EPS&&point[0]>=Math.min(a[0],b[0])-EPS&&point[0]<=Math.max(a[0],b[0])+EPS&&point[1]>=Math.min(a[1],b[1])-EPS&&point[1]<=Math.max(a[1],b[1])+EPS)return true;if((a[1]>point[1])!==(b[1]>point[1])&&point[0]<(b[0]-a[0])*(point[1]-a[1])/(b[1]-a[1])+a[0])inside=!inside;}return inside;})();
export function clipLineToGeometry(g:PatternGeometry,start:Vec2,end:Vec2):PatternResult<[Vec2,Vec2]>{if(![...start,...end].every(Number.isFinite))return fail("INVALID_CREASE","line","Line coordinates must be finite");if(Math.hypot(end[0]-start[0],end[1]-start[1])<EPS)return fail("ZERO_LENGTH_CREASE","line","Line endpoints must differ");const d:Vec2=[end[0]-start[0],end[1]-start[1]];let hits:Vec2[]=[];if(g.kind==="circle"){const f:Vec2=[start[0]-g.center[0],start[1]-g.center[1]],aa=d[0]**2+d[1]**2,bb=2*(f[0]*d[0]+f[1]*d[1]),cc=f[0]**2+f[1]**2-g.radius**2,disc=bb**2-4*aa*cc;if(disc<=EPS)return fail("CUT_OUTSIDE_MATERIAL","line","Line does not cross the material twice");hits=[(-bb-Math.sqrt(disc))/(2*aa),(-bb+Math.sqrt(disc))/(2*aa)].map(t=>[start[0]+t*d[0],start[1]+t*d[1]]);}else for(let i=0;i<g.vertices.length;i++){const p=g.vertices[i],q=g.vertices[(i+1)%g.vertices.length],e:Vec2=[q[0]-p[0],q[1]-p[1]],den=d[0]*e[1]-d[1]*e[0];if(Math.abs(den)<EPS)continue;const t=((p[0]-start[0])*e[1]-(p[1]-start[1])*e[0])/den,u=((p[0]-start[0])*d[1]-(p[1]-start[1])*d[0])/den;if(u>=-EPS&&u<=1+EPS)hits.push([start[0]+t*d[0],start[1]+t*d[1]]);}hits=unique(hits);if(hits.length<2)return fail("CUT_OUTSIDE_MATERIAL","line","Line does not cross the material twice");hits.sort((p,q)=>(p[0]-start[0])*d[0]+(p[1]-start[1])*d[1]-((q[0]-start[0])*d[0]+(q[1]-start[1])*d[1]));return{status:"PASS",value:[hits[0],hits.at(-1)!],issues:[]};}
const clipHalf=(vertices:Vec2[],a:Vec2,b:Vec2,pos:boolean)=>{const out:Vec2[]=[];for(let i=0;i<vertices.length;i++){const p=vertices[i],q=vertices[(i+1)%vertices.length],sp=(pos?1:-1)*cross(a,b,p),sq=(pos?1:-1)*cross(a,b,q),pin=sp>=-EPS,qin=sq>=-EPS;if(pin)out.push(p);if(pin!==qin){const t=sp/(sp-sq);out.push([p[0]+(q[0]-p[0])*t,p[1]+(q[1]-p[1])*t]);}}return unique(out);};
const properIntersection=(a:Vec2,b:Vec2,c:Vec2,d:Vec2)=>{const s1=cross(a,b,c),s2=cross(a,b,d),s3=cross(c,d,a),s4=cross(c,d,b);return s1*s2<-EPS&&s3*s4<-EPS;};
function analyticCircleSegments(g:Extract<PatternGeometry,{kind:"circle"}>,line:[Vec2,Vec2],positiveSide:boolean):PatternBoundarySegment[]{const angles=line.map(p=>Math.atan2(p[1]-g.center[1],p[0]-g.center[0])) as [number,number],mid=(angles[0]+angles[1])/2,test:Vec2=[g.center[0]+g.radius*Math.cos(mid),g.center[1]+g.radius*Math.sin(mid)],ccw=(positiveSide?1:-1)*cross(line[0],line[1],test)>=0;return[{kind:"line",start:line[0],end:line[1]},{kind:"arc",center:g.center,radius:g.radius,startAngle:angles[1],endAngle:angles[0],counterclockwise:ccw}];}
function repartition(sheet:PatternSheet):PatternResult<PatternSheet>{const dividers=[...sheet.cuts.filter(c=>c.cutType==="FULL").map(c=>({id:c.id,points:c.points as [Vec2,Vec2],kind:"cut" as const})),...sheet.creases.map(c=>({id:c.id,points:c.points,kind:"crease" as const}))],source=sheet.boundary.geometry.kind==="circle"?tessellateCircle(sheet.boundary.geometry.center,sheet.boundary.geometry.radius):sheet.boundary.geometry.vertices;let cells=[source];for(const divider of dividers){const next:Vec2[][]=[];for(const cell of cells){const a=clipHalf(cell,...divider.points,true),b=clipHalf(cell,...divider.points,false);if(a.length>=3&&b.length>=3&&area(a)>EPS&&area(b)>EPS)next.push(a,b);else next.push(cell);}cells=next;}cells.sort((a,b)=>{const x=centroid(a),y=centroid(b);return x[0]-y[0]||x[1]-y[1];});const regions=cells.map((vertices,i)=>({id:`region-${i+1}`,vertices,role:"PANEL" as const}));if(sheet.boundary.geometry.kind==="circle"&&dividers.length===1&&regions.length===2)regions.forEach((r,i)=>Object.assign(r,{boundarySegments:analyticCircleSegments(sheet.boundary.geometry as Extract<PatternGeometry,{kind:"circle"}>,dividers[0].points,i===1)}));const updatedCreases=sheet.creases.map(crease=>{const adjacent=regions.filter(r=>r.vertices.filter(p=>Math.abs(cross(crease.points[0],crease.points[1],p))<1e-6).length>=2);if(adjacent.length!==2)return crease;adjacent.sort((a,b)=>a.id.localeCompare(b.id));return{...crease,regionIds:[adjacent[0].id,adjacent[1].id] as [string,string]};});return{status:"PASS",issues:[],value:{...sheet,regions,creases:updatedCreases,rootRegionId:regions[0].id}};}
export function addStraightCut(sheet:PatternSheet,start:Vec2,end:Vec2,cutType:"FULL"|"PARTIAL"="FULL"):PatternResult<PatternSheet>{if(Math.hypot(end[0]-start[0],end[1]-start[1])<EPS)return fail("ZERO_LENGTH_CUT","line","Cut endpoints must differ");const clipped=clipLineToGeometry(sheet.boundary.geometry,start,end);if(!clipped.value)return fail(clipped.issues[0].code==="ZERO_LENGTH_CREASE"?"ZERO_LENGTH_CUT":"CUT_OUTSIDE_MATERIAL","line",clipped.issues[0].message);return repartition({...sheet,cuts:[...sheet.cuts,{id:`cut-${sheet.cuts.length+1}`,points:clipped.value,cutType}]});}
export function addStraightCrease(sheet:PatternSheet,start:Vec2,end:Vec2,assignment:FoldAssignment="UNASSIGNED",degrees=90,_movingSide:"A"|"B"="B"):PatternResult<PatternSheet>{if(!Number.isFinite(degrees)||degrees<0||degrees>180)return fail("INVALID_FOLD_ANGLE","angle","Angle must be in [0,180]");const clipped=clipLineToGeometry(sheet.boundary.geometry,start,end);if(!clipped.value)return fail(clipped.issues[0].code==="CUT_OUTSIDE_MATERIAL"?"CREASE_DOES_NOT_PARTITION_REGION":clipped.issues[0].code,"line",clipped.issues[0].message);if(sheet.creases.some(c=>properIntersection(c.points[0],c.points[1],clipped.value![0],clipped.value![1])))return fail("UNSUPPORTED_CREASE_INTERSECTION","line","Crossing authored creases are not supported");const used=new Set(sheet.creases.map(c=>Number(c.id.match(/(\d+)$/)?.[1]??0))),number=Array.from({length:used.size+1},(_,i)=>i+1).find(n=>!used.has(n))??used.size+1,crease:PatternCrease={id:`crease-${number}`,points:clipped.value,assignment,regionIds:[sheet.rootRegionId,sheet.rootRegionId],targetAngleRadians:degrees*Math.PI/180,order:sheet.creases.length};return repartition({...sheet,creases:[...sheet.creases,crease]});}
export function deleteAuthoredCrease(sheet:PatternSheet,id:string):PatternResult<PatternSheet>{if(!sheet.creases.some(c=>c.id===id))return fail("INVALID_CREASE","creaseId","Selected crease does not exist");return repartition({...sheet,creases:sheet.creases.filter(c=>c.id!==id).map((c,i)=>({...c,order:i}))});}
export function updateAuthoredCrease(sheet:PatternSheet,id:string,patch:Partial<Pick<PatternCrease,"assignment"|"targetAngleRadians">>):PatternResult<PatternSheet>{const crease=sheet.creases.find(c=>c.id===id);if(!crease)return fail("INVALID_CREASE","creaseId","Selected crease does not exist");if(patch.targetAngleRadians!==undefined&&(!Number.isFinite(patch.targetAngleRadians)||patch.targetAngleRadians<0||patch.targetAngleRadians>Math.PI))return fail("INVALID_FOLD_ANGLE","targetAngleRadians","Angle must be in [0,pi]");return{status:"PASS",issues:[],value:{...sheet,creases:sheet.creases.map(c=>c.id===id?{...c,...patch}:c)}};}
export function validateFoldSequence(sheet:PatternSheet,sequence:PatternFoldSequence):PatternResult<PatternFoldSequence>{const ids=sequence.steps.map(s=>s.creaseId),known=new Set(sheet.creases.map(c=>c.id));if(new Set(ids).size!==ids.length)return fail("DUPLICATE_SEQUENCE_ENTRY","steps","A crease may occur only once");if(ids.some(id=>!known.has(id)))return fail("MISSING_SEQUENCE_CREASE","steps","Sequence references a missing crease");if(ids.length!==sheet.creases.length)return fail("INVALID_FOLD_SEQUENCE","steps","Every crease must occur exactly once");return{status:"PASS",value:sequence,issues:[]};}
export function moveSequenceItem(sequence:PatternFoldSequence,creaseId:string,direction:-1|1):PatternResult<PatternFoldSequence>{const index=sequence.steps.findIndex(s=>s.creaseId===creaseId),target=index+direction;if(index<0)return fail("MISSING_SEQUENCE_CREASE","creaseId","Sequence crease does not exist");if(target<0||target>=sequence.steps.length)return fail("INVALID_SEQUENCE_ORDER","order","Sequence item cannot move farther");const steps=[...sequence.steps];[steps[index],steps[target]]=[steps[target],steps[index]];return{status:"PASS",issues:[],value:{...sequence,steps}};}
export function sceneFromAuthoredPattern(sheet:PatternSheet,sequence?:PatternFoldSequence):PatternResult<PatternFoldScene>{return createPatternFoldScene(sheet,0,sequence);}
