// Pattern FOLD compatibility implementation for legacy Dynamic Geometry APIs.
// Canonical Dynamic Geometry authority remains construction-engine.ts.

import type { Vec2 } from "../fold-3d/types.js";
import { containsPoint } from "../geometry-engine/planar.js";
import type { ConstructionOperation, ConstructionPoint, ObjectFreedom, PatternIssue, PatternResult, PatternSheet } from "./types.js";

export type DynamicGeometryObjectType = "POINT" | "SEGMENT" | "CIRCLE" | "REGION" | "CREASE" | "CUT";
export interface DynamicGeometryObject { id:string; label:string; type:DynamicGeometryObjectType; constructionKind:string; parents:string[]; children:string[]; constraints:string[]; freedom:ObjectFreedom; visible:boolean; metadata:Record<string,unknown>; }
export type DynamicCommand = "CREATE_SEGMENT" | "SET_GUIDE" | "SET_CUT" | "SET_CREASE" | "FOLD_POINT_TO_POINT" | "JOIN_EDGES" | "DELETE";
export interface SelectionContext { selectedIds:string[]; selectedTypes:DynamicGeometryObjectType[]; validCommands:DynamicCommand[]; invalidCommandReasons:Partial<Record<DynamicCommand,string>>; }
export type DynamicGeometryErrorCode = "DEPENDENCY_CYCLE" | "INVALID_DEPENDENCY" | "DEPENDENT_OBJECT_NOT_DIRECTLY_DRAGGABLE" | "PATH_CONSTRAINT_VIOLATION" | "DUPLICATE_LABEL" | "INVALID_LABEL" | "DELETE_HAS_DEPENDENTS" | "CONSTRUCTION_INPUT_INVALID" | "CONSTRUCTION_UNRESOLVED" | "TOPOLOGY_INVALID_AFTER_UPDATE";

const issue=(code:DynamicGeometryErrorCode,path:string,message:string):PatternIssue=>({code,severity:"error",path,message});
const fail=<T>(code:DynamicGeometryErrorCode,path:string,message:string):PatternResult<T>=>({status:"FAIL",issues:[issue(code,path,message)]});
const pass=<T>(value:T):PatternResult<T>=>({status:"PASS",value,issues:[]});
const c=(sheet:PatternSheet)=>sheet.construction;
const pointLabel=(point:ConstructionPoint)=>point.label??point.id;
export function nextPointLabel(points:ConstructionPoint[]):string{const used=new Set(points.map(pointLabel));for(let cycle=0;;cycle++)for(let i=0;i<26;i++){const label=String.fromCharCode(65+i)+(cycle?String(cycle):"");if(!used.has(label))return label;}}
export function normalizeDynamicGeometry(sheet:PatternSheet):PatternSheet{if(!c(sheet))return sheet;const construction=c(sheet)!;return {...sheet,construction:{...construction,operations:construction.operations??[],points:construction.points.map((p,i)=>({...p,label:p.label??nextPointLabel(construction.points.slice(0,i)),labelVisible:p.labelVisible??true,freedom:p.freedom??"FREE",constructionKind:p.constructionKind??"FREE_POINT",parentIds:p.parentIds??[]})),segments:construction.segments.map(s=>({...s,label:s.label??s.pointIds.map(id=>pointLabel(construction.points.find(p=>p.id===id)!)).join("")})),circles:construction.circles.map((x,i)=>({...x,label:x.label??String.fromCharCode(99+i)}))}};}
export function dependencyIndex(sheet:PatternSheet):Map<string,string[]>{const normalized=normalizeDynamicGeometry(sheet),index=new Map<string,string[]>();for(const object of describeDynamicGeometry(normalized))for(const parent of object.parents)index.set(parent,[...(index.get(parent)??[]),object.id]);return index;}
export function describeDynamicGeometry(sheet:PatternSheet):DynamicGeometryObject[]{const construction=c(sheet);if(!construction)return [];const children=dependencyIndexWithoutDescribe(sheet);const common=(id:string,label:string,type:DynamicGeometryObjectType,kind:string,parents:string[],freedom:ObjectFreedom,metadata:Record<string,unknown>):DynamicGeometryObject=>({id,label,type,constructionKind:kind,parents,children:children.get(id)??[],constraints:[],freedom,visible:true,metadata});return [...construction.points.map(p=>common(p.id,pointLabel(p),"POINT",p.constructionKind??"FREE_POINT",p.parentIds??[],p.freedom??"FREE",{position:p.position,labelVisible:p.labelVisible??true,pathId:p.pathId})),...construction.segments.map(s=>common(s.id,s.label??s.id,"SEGMENT","SEGMENT",s.pointIds,"DEPENDENT",{semantic:s.semantic})),...construction.circles.map(x=>common(x.id,x.label??x.id,"CIRCLE","CIRCLE",[x.centerPointId],"DEPENDENT",{radius:x.radius,semantic:x.semantic})),...sheet.regions.map(r=>common(r.id,r.id,"REGION","REGION",[],"DEPENDENT",{status:r.status??"KEEP"})),...sheet.creases.map(x=>common(x.id,x.id,"CREASE","CREASE",construction.segments.filter(s=>s.semantic==="CREASE").map(s=>s.id),"DEPENDENT",{assignment:x.assignment,foldSide:x.foldSide})),...sheet.cuts.map(x=>common(x.id,x.id,"CUT","CUT",construction.segments.filter(s=>s.semantic==="CUT").map(s=>s.id),"DEPENDENT",{}))];}
function dependencyIndexWithoutDescribe(sheet:PatternSheet):Map<string,string[]>{const construction=c(sheet),index=new Map<string,string[]>();if(!construction)return index;const add=(child:string,parents:string[])=>parents.forEach(parent=>index.set(parent,[...(index.get(parent)??[]),child]));construction.points.forEach(p=>add(p.id,p.parentIds??[]));construction.segments.forEach(s=>add(s.id,s.pointIds));construction.circles.forEach(x=>add(x.id,[x.centerPointId]));return index;}
export function validateDependencyGraph(sheet:PatternSheet):PatternResult<PatternSheet>{const objects=describeDynamicGeometry(sheet),ids=new Set(objects.map(x=>x.id)),visiting=new Set<string>(),done=new Set<string>(),byId=new Map(objects.map(x=>[x.id,x]));for(const object of objects)for(const parent of object.parents)if(!ids.has(parent))return fail("INVALID_DEPENDENCY",object.id,`Missing parent ${parent}`);const visit=(id:string):boolean=>{if(visiting.has(id))return false;if(done.has(id))return true;visiting.add(id);for(const child of byId.get(id)?.children??[])if(!visit(child))return false;visiting.delete(id);done.add(id);return true;};for(const id of ids)if(!visit(id))return fail("DEPENDENCY_CYCLE",id,"Circular construction dependency rejected");return pass(sheet);}
const operation=(sheet:PatternSheet,type:ConstructionOperation["type"],inputs:string[],outputs:string[],parameters?:ConstructionOperation["parameters"]):PatternSheet=>{const construction=c(sheet)!;const operations=construction.operations??[];return {...sheet,construction:{...construction,operations:[...operations,{id:`operation-${operations.length+1}`,type,inputs,outputs,parameters}]}};};
export function createMidpoint(sheet:PatternSheet,aId:string,bId:string):PatternResult<PatternSheet>{const normalized=normalizeDynamicGeometry(sheet),construction=c(normalized),a=construction?.points.find(p=>p.id===aId),b=construction?.points.find(p=>p.id===bId);if(!construction||!a||!b||a.id===b.id)return fail("CONSTRUCTION_INPUT_INVALID","midpoint","Midpoint requires two distinct points");const p:ConstructionPoint={id:`point-${Math.max(0,...construction.points.map(x=>Number(x.id.match(/(\d+)$/)?.[1]??0)))+1}`,position:[(a.position[0]+b.position[0])/2,(a.position[1]+b.position[1])/2],label:nextPointLabel(construction.points),labelVisible:true,freedom:"DEPENDENT",constructionKind:"MIDPOINT",parentIds:[a.id,b.id]};const next={...normalized,construction:{...construction,points:[...construction.points,p]}};return pass(operation(next,"MIDPOINT",[a.id,b.id],[p.id]));}
export function createPointOnCircle(sheet:PatternSheet,circleId:string,candidate:Vec2):PatternResult<PatternSheet>{const normalized=normalizeDynamicGeometry(sheet),construction=c(normalized),circle=construction?.circles.find(x=>x.id===circleId),center=construction?.points.find(p=>p.id===circle?.centerPointId);if(!construction||!circle||!center)return fail("CONSTRUCTION_INPUT_INVALID","circleId","Point on object requires a construction circle");const dx=candidate[0]-center.position[0],dy=candidate[1]-center.position[1],length=Math.hypot(dx,dy);if(length<1e-9)return fail("PATH_CONSTRAINT_VIOLATION","position","Choose a direction from the circle center");const position:Vec2=[center.position[0]+dx/length*circle.radius,center.position[1]+dy/length*circle.radius],p:ConstructionPoint={id:`point-${Math.max(0,...construction.points.map(x=>Number(x.id.match(/(\d+)$/)?.[1]??0)))+1}`,position,label:nextPointLabel(construction.points),labelVisible:true,freedom:"PATH_BOUND",constructionKind:"POINT_ON_CIRCLE",parentIds:[circle.id],pathId:circle.id};const next={...normalized,construction:{...construction,points:[...construction.points,p]}};return pass(operation(next,"CREATE_POINT_ON_CIRCLE",[circle.id],[p.id]));}
export function renameDynamicObject(sheet:PatternSheet,id:string,label:string):PatternResult<PatternSheet>{const normalized=normalizeDynamicGeometry(sheet),trimmed=label.trim(),construction=c(normalized);if(!construction||!trimmed)return fail("INVALID_LABEL",id,"Label must not be empty");if(construction.points.some(p=>p.id!==id&&pointLabel(p)===trimmed))return fail("DUPLICATE_LABEL",id,`Label ${trimmed} is already in use`);if(!construction.points.some(p=>p.id===id))return fail("INVALID_DEPENDENCY",id,"Object does not exist");return pass({...normalized,construction:{...construction,points:construction.points.map(p=>p.id===id?{...p,label:trimmed}:p),segments:construction.segments.map(s=>({...s,label:s.pointIds.map(pointId=>pointLabel((construction.points.map(p=>p.id===id?{...p,label:trimmed}:p)).find(p=>p.id===pointId)!)).join("")}))}});}
function descendants(sheet:PatternSheet,id:string):string[]{const index=dependencyIndex(sheet),seen=new Set<string>(),walk=(x:string)=>(index.get(x)??[]).forEach(child=>{if(!seen.has(child)){seen.add(child);walk(child);}});walk(id);return [...seen];}
export function deleteDynamicObject(sheet:PatternSheet,id:string,cascade=false):PatternResult<PatternSheet>{const normalized=normalizeDynamicGeometry(sheet),construction=c(normalized);if(!construction)return fail("INVALID_DEPENDENCY",id,"Object does not exist");const affected=descendants(normalized,id);if(affected.length&&!cascade)return fail("DELETE_HAS_DEPENDENTS",id,`Delete affects: ${affected.join(", ")}`);const ids=new Set([id,...affected]);return pass({...normalized,construction:{...construction,points:construction.points.filter(p=>!ids.has(p.id)),segments:construction.segments.filter(s=>!ids.has(s.id)&&s.pointIds.every(x=>!ids.has(x))),circles:construction.circles.filter(x=>!ids.has(x.id)&&!ids.has(x.centerPointId)),operations:(construction.operations??[]).filter(x=>x.outputs.every(output=>!ids.has(output)))}});}
export function moveDynamicPoint(sheet:PatternSheet,id:string,candidate:Vec2):PatternResult<PatternSheet>{const normalized=normalizeDynamicGeometry(sheet),construction=c(normalized),point=construction?.points.find(p=>p.id===id);if(!construction||!point)return fail("INVALID_DEPENDENCY",id,"Point does not exist");if(point.freedom==="DEPENDENT")return fail("DEPENDENT_OBJECT_NOT_DIRECTLY_DRAGGABLE",id,"Dependent points move through their parents");let position=candidate;if(point.freedom==="PATH_BOUND"){const circle=construction.circles.find(x=>x.id===point.pathId),center=construction.points.find(p=>p.id===circle?.centerPointId);if(!circle||!center)return fail("INVALID_DEPENDENCY",id,"Path definition is unresolved");const dx=candidate[0]-center.position[0],dy=candidate[1]-center.position[1],length=Math.hypot(dx,dy);if(length<1e-9)return fail("PATH_CONSTRAINT_VIOLATION",id,"Point cannot project from the path center");position=[center.position[0]+dx/length*circle.radius,center.position[1]+dy/length*circle.radius];}if(!containsPoint(normalized.boundary.geometry,position))return fail("PATH_CONSTRAINT_VIOLATION",id,"Point must remain on source material");let points=construction.points.map(p=>p.id===id?{...p,position}:p);const byId=()=>new Map(points.map(p=>[p.id,p]));for(let passIndex=0;passIndex<points.length;passIndex++){let changed=false;points=points.map(p=>{if(p.constructionKind!=="MIDPOINT"||!p.parentIds?.length)return p;const map=byId(),a=map.get(p.parentIds[0]),b=map.get(p.parentIds[1]);if(!a||!b)return p;changed=true;return {...p,position:[(a.position[0]+b.position[0])/2,(a.position[1]+b.position[1])/2] as Vec2};});if(!changed)break;}return pass({...normalized,construction:{...construction,points}});}
export function evaluateSelection(sheet:PatternSheet,selectedIds:string[]):SelectionContext{const objects=describeDynamicGeometry(normalizeDynamicGeometry(sheet)),selected=selectedIds.map(id=>objects.find(x=>x.id===id)).filter(Boolean) as DynamicGeometryObject[],types=selected.map(x=>x.type),valid:DynamicCommand[]=["DELETE"],reasons:SelectionContext["invalidCommandReasons"]={};const points=selected.filter(x=>x.type==="POINT"),segments=selected.filter(x=>x.type==="SEGMENT");if(points.length===2){valid.push("CREATE_SEGMENT","FOLD_POINT_TO_POINT");}else{reasons.CREATE_SEGMENT="Select two points.";reasons.FOLD_POINT_TO_POINT="Select two points.";}if(segments.length===1){valid.push("SET_GUIDE","SET_CUT","SET_CREASE");}else{reasons.SET_GUIDE=reasons.SET_CUT=reasons.SET_CREASE="Select a segment.";}if(segments.length===2)valid.push("JOIN_EDGES");else reasons.JOIN_EDGES="Select two free compatible edges.";return {selectedIds,selectedTypes:types,validCommands:valid,invalidCommandReasons:reasons};}
