import { identity4, multiply4, rotationAroundAxis, transformPoint } from "../fold-3d/math.js";
import type { Mat4, Vec2, Vec3 } from "../fold-3d/types.js";
import type { PatternFoldEdge, PatternFoldScene, PatternFoldSequence, PatternFoldState, PatternGeometry, PatternIssue, PatternResult, PatternSheet, PatternShape, PatternTopology } from "./types.js";

const EPS=1e-8, idPattern=/^[A-Za-z][A-Za-z0-9_.:-]*$/;
const issue=(code:string,path:string,message:string):PatternIssue=>({code,severity:"error",path,message});
const cross=(a:Vec2,b:Vec2,c:Vec2)=>(b[0]-a[0])*(c[1]-a[1])-(b[1]-a[1])*(c[0]-a[0]);
const pointOn=(p:Vec2,a:Vec2,b:Vec2)=>Math.abs(cross(a,b,p))<EPS&&p[0]>=Math.min(a[0],b[0])-EPS&&p[0]<=Math.max(a[0],b[0])+EPS&&p[1]>=Math.min(a[1],b[1])-EPS&&p[1]<=Math.max(a[1],b[1])+EPS;
const segmentsIntersect=(a:Vec2,b:Vec2,c:Vec2,d:Vec2)=>{const x1=cross(a,b,c),x2=cross(a,b,d),x3=cross(c,d,a),x4=cross(c,d,b);return (x1*x2<-EPS&&x3*x4<-EPS)||pointOn(c,a,b)||pointOn(d,a,b)||pointOn(a,c,d)||pointOn(b,c,d);};
const polygonContains=(polygon:Vec2[],p:Vec2)=>{let inside=false;for(let i=0,j=polygon.length-1;i<polygon.length;j=i++){const a=polygon[i],b=polygon[j];if(pointOn(p,a,b))return true;if((a[1]>p[1])!==(b[1]>p[1])&&p[0]<(b[0]-a[0])*(p[1]-a[1])/(b[1]-a[1])+a[0])inside=!inside;}return inside;};
const geometryPoints=(g:PatternGeometry):Vec2[]=>g.kind==="polygon"?g.vertices:[[g.center[0]+g.radius,g.center[1]],[g.center[0]-g.radius,g.center[1]],[g.center[0],g.center[1]+g.radius],[g.center[0],g.center[1]-g.radius]];
const geometryContains=(outer:PatternGeometry,p:Vec2)=>outer.kind==="circle"?Math.hypot(p[0]-outer.center[0],p[1]-outer.center[1])<=outer.radius+EPS:polygonContains(outer.vertices,p);
const bounds=(g:PatternGeometry)=>{const p=geometryPoints(g);return {minX:Math.min(...p.map(x=>x[0])),maxX:Math.max(...p.map(x=>x[0])),minY:Math.min(...p.map(x=>x[1])),maxY:Math.max(...p.map(x=>x[1]))};};
const overlaps=(a:PatternGeometry,b:PatternGeometry)=>{if(a.kind==="circle"&&b.kind==="circle")return Math.hypot(a.center[0]-b.center[0],a.center[1]-b.center[1])<a.radius+b.radius-EPS;const ba=bounds(a),bb=bounds(b);return ba.minX<bb.maxX-EPS&&bb.minX<ba.maxX-EPS&&ba.minY<bb.maxY-EPS&&bb.minY<ba.maxY-EPS&&(geometryPoints(a).some(p=>geometryContains(b,p))||geometryPoints(b).some(p=>geometryContains(a,p)));};
const segmentKey=(points:Vec2[])=>points.length===2?[points[0].join(","),points[1].join(",")].sort().join("|"):"";

export function validatePatternSheet(sheet:PatternSheet):PatternIssue[]{const out:PatternIssue[]=[];const ids=[sheet.id,sheet.boundary.id,...sheet.shapes.map(x=>x.id),...sheet.cuts.map(x=>x.id),...sheet.creases.map(x=>x.id),...sheet.regions.map(x=>x.id)];const seen=new Set<string>();ids.forEach((id,index)=>{if(!idPattern.test(id))out.push(issue("INVALID_ID",`ids[${index}]`,`Invalid stable identifier ${id}`));if(seen.has(id))out.push(issue("DUPLICATE_ID",`ids[${index}]`,`Duplicate identifier ${id}`));seen.add(id);});
 const finitePoint=(point:Vec2)=>point.length===2&&point.every(Number.isFinite);const pointSets:[string,Vec2[]][]=[["boundary.geometry",geometryPoints(sheet.boundary.geometry)],...sheet.shapes.map((x,i)=>[`shapes[${i}].geometry`,geometryPoints(x.geometry)] as [string,Vec2[]]),...sheet.regions.map((x,i)=>[`regions[${i}].vertices`,x.vertices] as [string,Vec2[]])];for(const[path,points]of pointSets)if(!points.every(finitePoint))out.push(issue("NON_FINITE_COORDINATE",path,"Coordinates must be finite"));for(const[i,cut]of sheet.cuts.entries())if(cut.points.length<2||!cut.points.every(finitePoint))out.push(issue("INVALID_CUT",`cuts[${i}]`,"A cut requires at least two finite points"));for(const[i,crease]of sheet.creases.entries())if(!crease.points.every(finitePoint))out.push(issue("INVALID_CREASE",`creases[${i}]`,"A crease requires finite endpoints"));
 const geometries:[string,PatternGeometry][]=[["boundary.geometry",sheet.boundary.geometry],...sheet.shapes.map((x,i)=>[`shapes[${i}].geometry`,x.geometry] as [string,PatternGeometry])];for(const[path,g]of geometries){if(g.kind==="circle"){if(!Number.isFinite(g.radius)||g.radius<=EPS)out.push(issue("INVALID_RADIUS",path,"Circle radius must be positive and finite"));}else{if(g.vertices.length<3)out.push(issue("INVALID_POLYGON",path,"Polygon requires at least three vertices"));for(let i=0;i<g.vertices.length;i++){const a=g.vertices[i],b=g.vertices[(i+1)%g.vertices.length];for(let j=i+2;j<g.vertices.length;j++){if(i===0&&j===g.vertices.length-1)continue;const c=g.vertices[j],d=g.vertices[(j+1)%g.vertices.length];if(segmentsIntersect(a,b,c,d))out.push(issue("SELF_INTERSECTION",path,"Polygon boundary self-intersects"));}}}}
 const byShape=new Map(sheet.shapes.map(x=>[x.id,x]));for(const [i,shape]of sheet.shapes.entries()){const parent=shape.parentShapeId?byShape.get(shape.parentShapeId)?.geometry:sheet.boundary.geometry;if(shape.parentShapeId&&!parent)out.push(issue("UNKNOWN_PARENT",`shapes[${i}]`,`Unknown parent ${shape.parentShapeId}`));else if(parent&&!geometryPoints(shape.geometry).every(p=>geometryContains(parent,p)))out.push(issue("OUTSIDE_PARENT",`shapes[${i}]`,`${shape.id} is outside its containing boundary`));const path=new Set([shape.id]);let next=shape.parentShapeId;while(next){if(path.has(next)){out.push(issue("CONTAINMENT_CYCLE",`shapes[${i}]`,`Containment hierarchy contains a cycle`));break;}path.add(next);next=byShape.get(next)?.parentShapeId;}}
 const materialShapes=sheet.shapes.filter(x=>x.role==="CUT_OUT"||x.role==="HOLE"||x.role==="FOLD_FLAP"||x.role==="FOLD_REGION");for(let i=0;i<materialShapes.length;i++)for(let j=i+1;j<materialShapes.length;j++)if(overlaps(materialShapes[i].geometry,materialShapes[j].geometry))out.push(issue("OVERLAPPING_SHAPES","shapes",`${materialShapes[i].id} overlaps ${materialShapes[j].id}`));
 const regionIds=new Set(sheet.regions.map(x=>x.id));if(!regionIds.has(sheet.rootRegionId))out.push(issue("UNKNOWN_ROOT_REGION","rootRegionId","Root region is not defined"));const cutKeys=new Set(sheet.cuts.map(x=>segmentKey(x.points)).filter(Boolean));for(const [i,crease]of sheet.creases.entries()){if(Math.hypot(crease.points[1][0]-crease.points[0][0],crease.points[1][1]-crease.points[0][1])<EPS)out.push(issue("ZERO_LENGTH_CREASE",`creases[${i}]`,"Crease axis has zero length"));if(cutKeys.has(segmentKey(crease.points)))out.push(issue("CUT_CREASE_CONFLICT",`creases[${i}]`,"The same segment cannot be both a cut and a crease"));if(!crease.regionIds.every(x=>regionIds.has(x)))out.push(issue("UNKNOWN_CREASE_REGION",`creases[${i}]`,"Crease references an unknown region"));if(crease.targetAngleRadians!==undefined&&(!Number.isFinite(crease.targetAngleRadians)||Math.abs(crease.targetAngleRadians)>Math.PI+EPS))out.push(issue("INVALID_FOLD_ANGLE",`creases[${i}]`,"Fold angle must be finite and no greater than pi radians"));}
 const graph=new Map<string,string[]>();sheet.creases.forEach(x=>{const list=graph.get(x.regionIds[0])??[];list.push(x.regionIds[1]);graph.set(x.regionIds[0],list);});const visiting=new Set<string>(),visited=new Set<string>();const visit=(id:string)=>{if(visiting.has(id)){out.push(issue("FOLD_GRAPH_CYCLE","creases","Fold graph must be acyclic"));return;}if(visited.has(id))return;visiting.add(id);(graph.get(id)??[]).forEach(visit);visiting.delete(id);visited.add(id);};visit(sheet.rootRegionId);const reachable=visited;for(const shape of sheet.shapes.filter(x=>x.role==="FOLD_FLAP")){const region=sheet.regions.find(x=>x.id===shape.id||x.role==="FLAP"&&geometryPoints(shape.geometry).every(p=>polygonContains(x.vertices,p)));if(!region||!reachable.has(region.id))out.push(issue("DETACHED_FOLD_COMPONENT",`shapes.${shape.id}`,"Fold flap is not connected to the root by a crease"));}return out;}

export function buildPatternTopology(sheet:PatternSheet):PatternResult<PatternTopology>{const issues=validatePatternSheet(sheet);if(issues.length)return {status:"FAIL",issues};const foldEdges:PatternFoldEdge[]=sheet.creases.map((crease,index)=>({id:`fold:${crease.id}`,parentRegionId:crease.regionIds[0],childRegionId:crease.regionIds[1],creaseId:crease.id,axis:crease.points,targetAngleRadians:crease.targetAngleRadians??Math.PI/2,assignment:crease.assignment,order:crease.order??index}));return {status:"PASS",issues:[],value:{sheet,materialRegionIds:sheet.regions.map(x=>x.id),adjacency:foldEdges.map(x=>({regionIds:[x.parentRegionId,x.childRegionId],creaseId:x.creaseId})),foldEdges,holes:sheet.shapes.filter(x=>x.role==="CUT_OUT"||x.role==="HOLE"),markedShapes:sheet.shapes.filter(x=>x.role==="MARKED_REGION"||x.role==="REFERENCE_SHAPE")}};}
export const defaultFoldSequence=(topology:PatternTopology):PatternFoldSequence=>({id:`${topology.sheet.id}:sequence`,steps:[...topology.foldEdges].sort((a,b)=>a.order-b.order||a.id.localeCompare(b.id)).map(x=>({creaseId:x.creaseId}))});
export function computePatternFoldState(topology:PatternTopology,sequence=defaultFoldSequence(topology),currentStep=sequence.steps.length-1,progress=1):PatternResult<PatternFoldState>{if(!Number.isFinite(progress)||progress<0||progress>1)return {status:"FAIL",issues:[issue("INVALID_PROGRESS","progress","Progress must be in [0,1]")]};const edgeByCrease=new Map(topology.foldEdges.map(x=>[x.creaseId,x])),angles:Record<string,number>={};sequence.steps.forEach((step,index)=>{const edge=edgeByCrease.get(step.creaseId);if(!edge)return;const amount=topology.sheet.id==="SQUARE_SHEET_TO_REGULAR_SQUARE_FRUSTUM"?progress:index<currentStep?1:index===currentStep?progress:0,sign=edge.assignment==="MOUNTAIN"?-1:1;const target=topology.sheet.id==="SQUARE_SHEET_TO_REGULAR_SQUARE_FRUSTUM"?Math.atan2(2*amount,Math.sqrt(6.25-4*amount*amount)):Math.abs(step.targetAngleRadians??edge.targetAngleRadians)*amount;angles[edge.creaseId]=sign*target;});const matrices=new Map<string,Mat4>([[topology.sheet.rootRegionId,identity4()]]);const pending=[...topology.foldEdges];for(let pass=0;pass<=pending.length;pass++)for(const edge of pending){const parent=matrices.get(edge.parentRegionId);if(!parent||matrices.has(edge.childRegionId))continue;const a=transformPoint(parent,[...edge.axis[0],0] as Vec3),b=transformPoint(parent,[...edge.axis[1],0] as Vec3),rotation=rotationAroundAxis(a,[b[0]-a[0],b[1]-a[1],b[2]-a[2]],angles[edge.creaseId]??0);matrices.set(edge.childRegionId,multiply4(rotation,parent));}const disconnected=topology.sheet.regions.filter(x=>!matrices.has(x.id));if(disconnected.length)return {status:"FAIL",issues:disconnected.map(x=>issue("DETACHED_FOLD_COMPONENT",`regions.${x.id}`,"Region has no transform path from root"))};return {status:"PASS",issues:[],value:{currentStep,progress,creaseAngles:angles,regionTransforms:topology.sheet.regions.map(region=>{const matrix=matrices.get(region.id)!;return {regionId:region.id,matrix,transformedVertices:region.vertices.map(position2D=>({position2D,position3D:transformPoint(matrix,[...position2D,0] as Vec3)}))};})}};}
export function createPatternFoldScene(sheet:PatternSheet,progress=0,sequence?:PatternFoldSequence):PatternResult<PatternFoldScene>{const topology=buildPatternTopology(sheet);if(!topology.value)return {status:topology.status,issues:topology.issues};const resolved=sequence??defaultFoldSequence(topology.value),state=computePatternFoldState(topology.value,resolved,Math.max(0,resolved.steps.length-1),progress);if(!state.value)return {status:state.status,issues:state.issues};return {status:"PASS",issues:[],value:{id:`scene:${sheet.id}`,sheet,topology:topology.value,sequence:resolved,state:state.value,correspondence:sheet.regions.map(x=>({regionId:x.id,sourcePatternId:sheet.id})),metadata:{rendererNeutral:true,engine:"pattern-fold-v1"}}};}
export function updatePatternFoldScene(scene:PatternFoldScene,currentStep:number,progress:number):PatternResult<PatternFoldScene>{const state=computePatternFoldState(scene.topology,scene.sequence,currentStep,progress);return state.value?{status:"PASS",issues:[],value:{...scene,state:state.value}}:{status:state.status,issues:state.issues};}
