import type { Vec2 } from "../fold-3d/types.js";
import { addStraightCrease, addStraightCut, geometryContainsPoint, tessellateCircle } from "./authoring.js";
import type { ConstructionCircle, ConstructionPoint, ConstructionSegment, FoldAssignment, GridSettings, PatternConstruction, PatternIssue, PatternResult, PatternSheet, SymmetryGuide } from "./types.js";

const EPS=1e-8;
const issue=(code:string,path:string,message:string):PatternIssue=>({code,severity:"error",path,message});
const fail=<T>(code:string,path:string,message:string):PatternResult<T>=>({status:"FAIL",issues:[issue(code,path,message)]});
const pass=<T>(value:T):PatternResult<T>=>({status:"PASS",value,issues:[]});
export const DEFAULT_GRID:GridSettings={visible:false,type:"AUTO",spacing:1,snapGrid:false,snapVertex:true,snapMidpoint:true,snapIntersection:true,snapBoundary:true};
export const emptyConstruction=():PatternConstruction=>({grid:{...DEFAULT_GRID},points:[],segments:[],circles:[],symmetryGuides:[],symmetryPairs:[],operations:[]});
const construction=(sheet:PatternSheet):PatternConstruction=>sheet.construction??emptyConstruction();
const replaceConstruction=(sheet:PatternSheet,next:PatternConstruction):PatternSheet=>({...sheet,construction:next});
const nextId=(prefix:string,items:Array<{id:string}>)=>`${prefix}-${Math.max(0,...items.map(x=>Number(x.id.match(/(\d+)$/)?.[1]??0)))+1}`;
const nextLabel=(points:ConstructionPoint[])=>{const used=new Set(points.map(p=>p.label));for(let cycle=0;;cycle++)for(let i=0;i<26;i++){const value=String.fromCharCode(65+i)+(cycle?String(cycle):"");if(!used.has(value))return value;}};
const record=(c:PatternConstruction,type:NonNullable<PatternConstruction["operations"]>[number]["type"],inputs:string[],outputs:string[])=>({...c,operations:[...(c.operations??[]),{id:`operation-${(c.operations??[]).length+1}`,type,inputs,outputs}]});
const dist=(a:Vec2,b:Vec2)=>Math.hypot(a[0]-b[0],a[1]-b[1]);
const midpoint=(a:Vec2,b:Vec2):Vec2=>[(a[0]+b[0])/2,(a[1]+b[1])/2];
const nearest=(point:Vec2,candidates:Vec2[],tolerance:number)=>candidates.map(p=>({p,d:dist(point,p)})).sort((a,b)=>a.d-b.d)[0]?.d<=tolerance?candidates.map(p=>({p,d:dist(point,p)})).sort((a,b)=>a.d-b.d)[0].p:undefined;
export function resolveGridType(sheet:PatternSheet,requested:GridSettings["type"]):Exclude<GridSettings["type"],"AUTO">{if(requested!=="AUTO")return requested;return sheet.boundary.kind==="circle"?"POLAR_REFERENCE":sheet.boundary.kind==="triangle"?"TRIANGULAR_60":"CARTESIAN";}
export function updateGrid(sheet:PatternSheet,patch:Partial<GridSettings>):PatternResult<PatternSheet>{const current=construction(sheet),grid={...current.grid,...patch};if(!Number.isFinite(grid.spacing)||grid.spacing<=EPS)return fail("INVALID_CONSTRUCTION","grid.spacing","Grid spacing must be positive and finite");return pass(replaceConstruction(sheet,{...current,grid}));}
export function snapConstructionPoint(sheet:PatternSheet,raw:Vec2,tolerance=.18):Vec2{const c=construction(sheet),grid=c.grid;let point:[number,number]=[raw[0],raw[1]];if(grid.snapGrid){const spacing=grid.spacing,type=resolveGridType(sheet,grid.type);if(type==="CARTESIAN")point=[Math.round(point[0]/spacing)*spacing,Math.round(point[1]/spacing)*spacing];else if(type==="TRIANGULAR_60"){const row=Math.round(point[1]/(spacing*Math.sqrt(3)/2));point=[Math.round((point[0]-row*spacing/2)/spacing)*spacing+row*spacing/2,row*spacing*Math.sqrt(3)/2];}else{const radius=Math.round(Math.hypot(...point)/spacing)*spacing,angle=Math.round(Math.atan2(point[1],point[0])/(Math.PI/12))*Math.PI/12;point=[radius*Math.cos(angle),radius*Math.sin(angle)];}}
 const points=grid.snapVertex?c.points.map(x=>x.position):[],mids=grid.snapMidpoint?c.segments.map(s=>{const a=c.points.find(p=>p.id===s.pointIds[0])!,b=c.points.find(p=>p.id===s.pointIds[1])!;return a&&b?midpoint(a.position,b.position):undefined;}).filter(Boolean) as Vec2[]:[],hit=nearest(point,[...points,...mids],tolerance);return hit?[...hit] as Vec2:point;}
export function addConstructionPoint(sheet:PatternSheet,raw:Vec2):PatternResult<PatternSheet>{const c=construction(sheet),position=snapConstructionPoint(sheet,raw);if(!geometryContainsPoint(sheet.boundary.geometry,position))return fail("INVALID_POINT","point","Point must lie on source material");const existing=c.points.find(p=>dist(p.position,position)<EPS);if(existing)return pass(sheet);const point:ConstructionPoint={id:nextId("point",c.points),position,label:nextLabel(c.points),labelVisible:true,freedom:"FREE",constructionKind:"FREE_POINT",parentIds:[]};return pass(replaceConstruction(sheet,record({...c,points:[...c.points,point]},"CREATE_FREE_POINT",[],[point.id])));}
export function addConstructionSegment(sheet:PatternSheet,pointIds:[string,string]):PatternResult<PatternSheet>{const c=construction(sheet),a=c.points.find(p=>p.id===pointIds[0]),b=c.points.find(p=>p.id===pointIds[1]);if(!a||!b)return fail("INVALID_SEGMENT","pointIds","Segment endpoints must reference construction points");if(a.id===b.id||dist(a.position,b.position)<EPS)return fail("INVALID_SEGMENT","pointIds","Segment endpoints must differ");if(c.segments.some(s=>s.pointIds[0]===a.id&&s.pointIds[1]===b.id||s.pointIds[0]===b.id&&s.pointIds[1]===a.id))return fail("INVALID_SEGMENT","pointIds","Segment already exists");const segment:ConstructionSegment={id:nextId("segment",c.segments),pointIds,label:`${a.label??a.id}${b.label??b.id}`,semantic:"NEUTRAL"};return pass(replaceConstruction(sheet,record({...c,segments:[...c.segments,segment]},"CREATE_SEGMENT",pointIds,[segment.id])));}
export function addConstructionCircle(sheet:PatternSheet,centerPointId:string,radius:number):PatternResult<PatternSheet>{const c=construction(sheet),center=c.points.find(p=>p.id===centerPointId);if(!center||!Number.isFinite(radius)||radius<=EPS)return fail("INVALID_CIRCLE","circle","Circle requires a center point and positive finite radius");const circle:ConstructionCircle={id:nextId("circle",c.circles),centerPointId,radius,label:`c${c.circles.length?c.circles.length+1:""}`,semantic:"NEUTRAL"};return pass(replaceConstruction(sheet,record({...c,circles:[...c.circles,circle]},"CREATE_CIRCLE",[centerPointId],[circle.id])));}
export function assignCircleSemantic(sheet:PatternSheet,id:string,semantic:"GUIDE"|"CUT"):PatternResult<PatternSheet>{const c=construction(sheet),circle=c.circles.find(x=>x.id===id),center=c.points.find(x=>x.id===circle?.centerPointId);if(!circle||!center)return fail("INVALID_CIRCLE","circleId","Selected construction circle does not exist");if(semantic==="GUIDE")return pass(replaceConstruction(sheet,{...c,circles:c.circles.map(x=>x.id===id?{...x,semantic}:x)}));const geometry={kind:"circle" as const,center:center.position,radius:circle.radius};const source=sheet.boundary.geometry,inside=source.kind==="circle"?dist(source.center,center.position)+circle.radius<source.radius-EPS:tessellateCircle(center.position,circle.radius,48).every(p=>geometryContainsPoint(source,p));if(!inside)return fail("INVALID_CIRCLE","circle","Cut circle must lie strictly inside source material");const shapeId=`cut-circle-${sheet.shapes.length+1}`,inner={id:"region-1",vertices:tessellateCircle(center.position,circle.radius),boundarySegments:[{kind:"arc" as const,center:center.position,radius:circle.radius,startAngle:0,endAngle:Math.PI*2,counterclockwise:true}],role:"PANEL" as const,status:"KEEP" as const},outer={id:"region-2",vertices:source.kind==="circle"?tessellateCircle(source.center,source.radius):source.vertices,holeShapeIds:[shapeId],role:"PANEL" as const,status:"KEEP" as const};return pass(replaceConstruction({...sheet,shapes:[...sheet.shapes,{id:shapeId,geometry,role:"CUT_OUT"}],regions:[inner,outer],rootRegionId:outer.id},{...c,circles:c.circles.map(x=>x.id===id?{...x,semantic}:x)}));}
export function deleteConstructionCircle(sheet:PatternSheet,id:string):PatternResult<PatternSheet>{const c=construction(sheet);if(!c.circles.some(x=>x.id===id))return fail("INVALID_CIRCLE","circleId","Selected construction circle does not exist");return pass(replaceConstruction(sheet,{...c,circles:c.circles.filter(x=>x.id!==id)}));}
export function assignSegmentSemantic(sheet:PatternSheet,id:string,semantic:ConstructionSegment["semantic"],assignment:FoldAssignment="UNASSIGNED",foldSide:"A"|"B"="B"):PatternResult<PatternSheet>{const c=construction(sheet),segment=c.segments.find(s=>s.id===id);if(!segment)return fail("INVALID_SEGMENT","segmentId","Selected segment does not exist");const a=c.points.find(p=>p.id===segment.pointIds[0])!,b=c.points.find(p=>p.id===segment.pointIds[1])!;let updated=sheet;if(semantic==="CUT"){const result=addStraightCut(sheet,a.position,b.position);if(!result.value)return result;updated=result.value;}else if(semantic==="CREASE"){const result=addStraightCrease(sheet,a.position,b.position,assignment,90,foldSide);if(!result.value)return result;const crease=result.value.creases.at(-1)!,regionIds=foldSide==="B"?crease.regionIds:[crease.regionIds[1],crease.regionIds[0]] as [string,string];updated={...result.value,creases:result.value.creases.map(x=>x.id===crease.id?{...x,regionIds,foldSide,fixedRegionId:regionIds[0],movingRegionId:regionIds[1]}:x),rootRegionId:regionIds[0]};}const next=construction(updated);return pass(replaceConstruction(updated,{...next,segments:next.segments.map(s=>s.id===id?{...s,semantic}:s)}));}
export function previewDiscardRegion(sheet:PatternSheet,regionId:string):PatternResult<PatternSheet>{if(!sheet.regions.some(r=>r.id===regionId))return fail("INVALID_REGION","regionId","Region does not exist");return pass({...sheet,regions:sheet.regions.map(r=>r.id===regionId?{...r,status:"DISCARD_PREVIEW"}:r)});}
export function cancelDiscard(sheet:PatternSheet):PatternResult<PatternSheet>{return pass({...sheet,regions:sheet.regions.map(r=>({...r,status:"KEEP"}))});}
export function applyDiscard(sheet:PatternSheet):PatternResult<PatternSheet>{const discarded=sheet.regions.filter(r=>r.status==="DISCARD_PREVIEW");if(!discarded.length)return fail("INVALID_REGION","regions","No region is pending discard");const retained=sheet.regions.filter(r=>r.status!=="DISCARD_PREVIEW").map(r=>({...r,status:"KEEP" as const}));if(!retained.length)return fail("INVALID_REGION","regions","At least one material region must remain");const removed=[...(sheet.removedRegions??[]),...discarded.map(r=>({id:r.id,vertices:r.vertices,status:"DISCARDED" as const}))];const creases=sheet.creases.filter(c=>c.regionIds.every(id=>retained.some(r=>r.id===id)));return pass({...sheet,regions:retained,removedRegions:removed,creases,rootRegionId:retained.some(r=>r.id===sheet.rootRegionId)?sheet.rootRegionId:retained[0].id});}
export function addSymmetryGuide(sheet:PatternSheet,type:SymmetryGuide["type"],custom?:[Vec2,Vec2]):PatternResult<PatternSheet>{const c=construction(sheet),points:[Vec2,Vec2]|undefined=type==="VERTICAL_AXIS"?[[0,-1],[0,1]]:type==="HORIZONTAL_AXIS"?[[-1,0],[1,0]]:custom;if(!points||dist(points[0],points[1])<EPS)return fail("INVALID_SYMMETRY","guide","Custom symmetry axis requires two distinct points");const guide:SymmetryGuide={id:nextId("symmetry",c.symmetryGuides),type,points};return pass(replaceConstruction(sheet,{...c,symmetryGuides:[...c.symmetryGuides,guide]}));}
export function reflectPoint(point:Vec2,guide:SymmetryGuide):Vec2{const[a,b]=guide.points,d:[number,number]=[b[0]-a[0],b[1]-a[1]],length=d[0]**2+d[1]**2,t=((point[0]-a[0])*d[0]+(point[1]-a[1])*d[1])/length,projection:Vec2=[a[0]+t*d[0],a[1]+t*d[1]];return[2*projection[0]-point[0],2*projection[1]-point[1]];}
export function mirrorConstructionPoint(sheet:PatternSheet,pointId:string,guideId:string):PatternResult<PatternSheet>{const c=construction(sheet),source=c.points.find(p=>p.id===pointId),guide=c.symmetryGuides.find(g=>g.id===guideId);if(!source||!guide)return fail("INVALID_SYMMETRY_PAIR","pair","Point and symmetry guide must exist");const position=reflectPoint(source.position,guide);if(dist(position,source.position)<EPS)return pass(sheet);const mirrorId=nextId("point",c.points),pairId=nextId("pair",c.symmetryPairs),mirror:ConstructionPoint={id:mirrorId,position,symmetryPairId:pairId};return pass(replaceConstruction(sheet,{...c,points:[...c.points.map(p=>p.id===source.id?{...p,symmetryPairId:pairId}:p),mirror],symmetryPairs:[...c.symmetryPairs,{id:pairId,sourceId:source.id,mirrorId,guideId}]}));}
export function mirrorConstructionSegment(sheet:PatternSheet,segmentId:string,guideId:string):PatternResult<PatternSheet>{const c=construction(sheet),source=c.segments.find(s=>s.id===segmentId),guide=c.symmetryGuides.find(g=>g.id===guideId);if(!source||!guide)return fail("INVALID_SYMMETRY_PAIR","pair","Segment and symmetry guide must exist");let current=sheet;const mirroredIds:string[]=[];for(const pointId of source.pointIds){let state=construction(current),pair=state.symmetryPairs.find(p=>p.sourceId===pointId&&p.guideId===guideId);if(!pair){const mirrored=mirrorConstructionPoint(current,pointId,guideId);if(!mirrored.value)return mirrored;current=mirrored.value;state=construction(current);pair=state.symmetryPairs.find(p=>p.sourceId===pointId&&p.guideId===guideId);}mirroredIds.push(pair?.mirrorId??pointId);}if(mirroredIds[0]===source.pointIds[0]&&mirroredIds[1]===source.pointIds[1])return pass(current);const added=addConstructionSegment(current,mirroredIds as [string,string]);if(!added.value)return added;const state=construction(added.value),mirror=state.segments.at(-1)!,pairId=nextId("pair",state.symmetryPairs);return pass(replaceConstruction(added.value,{...state,segments:state.segments.map(s=>s.id===source.id||s.id===mirror.id?{...s,symmetryPairId:pairId}:s),symmetryPairs:[...state.symmetryPairs,{id:pairId,sourceId:source.id,mirrorId:mirror.id,guideId}]}));}
export function assignSymmetricSegmentSemantic(sheet:PatternSheet,segmentId:string,semantic:ConstructionSegment["semantic"],assignment:FoldAssignment="UNASSIGNED"):PatternResult<PatternSheet>{const c=construction(sheet),pair=c.symmetryPairs.find(p=>p.sourceId===segmentId||p.mirrorId===segmentId),first=assignSegmentSemantic(sheet,segmentId,semantic,assignment);if(!first.value||!pair)return first;const other=pair.sourceId===segmentId?pair.mirrorId:pair.sourceId;return assignSegmentSemantic(first.value,other,semantic,assignment);}
export function assignMirroredCrease(sheet:PatternSheet,segmentId:string,assignment:FoldAssignment="UNASSIGNED",foldSide:"A"|"B"="B"):PatternResult<PatternSheet>{const c=construction(sheet),pair=c.symmetryPairs.find(p=>p.sourceId===segmentId||p.mirrorId===segmentId);if(!pair)return fail("INVALID_SYMMETRY_PAIR","segmentId","Segment has no mirrored pair");const other=pair.sourceId===segmentId?pair.mirrorId:pair.sourceId,first=assignSegmentSemantic(sheet,segmentId,"CREASE",assignment,foldSide);if(!first.value)return first;const firstId=first.value.creases.at(-1)!.id,second=assignSegmentSemantic(first.value,other,"CREASE",assignment,foldSide);if(!second.value)return second;const secondId=second.value.creases.at(-1)!.id,pairId=`crease-pair-${Math.floor(second.value.creases.filter(x=>x.symmetryPairId).length/2)+1}`;return pass({...second.value,creases:second.value.creases.map(x=>x.id===firstId||x.id===secondId?{...x,symmetryPairId:pairId}:x)});}
export function validateSymmetricCreasePair(sheet:PatternSheet,creaseId:string):PatternResult<{status:"VALID";sourceCreaseId:string;mirrorCreaseId:string;pairId:string}>{const source=sheet.creases.find(x=>x.id===creaseId);if(!source?.symmetryPairId)return fail("INVALID_SYMMETRY_PAIR","creaseId","Crease has no symmetry pair");const paired=sheet.creases.filter(x=>x.symmetryPairId===source.symmetryPairId);if(paired.length!==2)return fail("INVALID_SYMMETRY_PAIR","symmetryPairId","Symmetry pair must reference exactly two creases");const[a,b]=paired,validRegions=paired.every(x=>x.regionIds.every(id=>sheet.regions.some(r=>r.id===id)));if(!validRegions)return fail("INVALID_SYMMETRY_PAIR","regionIds","Paired crease has invalid region references");if(Math.abs((a.targetAngleRadians??0)-(b.targetAngleRadians??0))>EPS)return fail("INVALID_SYMMETRY_PAIR","targetAngleRadians","Paired crease angles differ");if(a.foldSide!==b.foldSide||a.assignment!==b.assignment)return fail("INVALID_SYMMETRY_PAIR","semantics","Paired crease fold semantics are incompatible");return pass({status:"VALID",sourceCreaseId:a.id,mirrorCreaseId:b.id,pairId:source.symmetryPairId});}
export function updateSymmetricCreasePair(sheet:PatternSheet,creaseId:string,patch:{assignment?:FoldAssignment;targetAngleRadians?:number;foldSide?:"A"|"B"},locked=true):PatternResult<PatternSheet>{const source=sheet.creases.find(x=>x.id===creaseId);if(!source)return fail("INVALID_CREASE","creaseId","Selected crease does not exist");const ids=locked&&source.symmetryPairId?new Set(sheet.creases.filter(x=>x.symmetryPairId===source.symmetryPairId).map(x=>x.id)):new Set([creaseId]);let next=sheet;if(patch.foldSide)for(const id of ids){const changed=updateCreaseFoldSide(next,id,patch.foldSide);if(!changed.value)return changed;next=changed.value;}return pass({...next,creases:next.creases.map(x=>ids.has(x.id)?{...x,...(patch.assignment?{assignment:patch.assignment}:{}),...(patch.targetAngleRadians!==undefined?{targetAngleRadians:patch.targetAngleRadians}:{})}:x)});}
export function updateCreaseFoldSide(sheet:PatternSheet,creaseId:string,foldSide:"A"|"B"):PatternResult<PatternSheet>{const crease=sheet.creases.find(c=>c.id===creaseId);if(!crease)return fail("INVALID_CREASE","creaseId","Selected crease does not exist");const regionIds=foldSide==="B"?crease.regionIds:[crease.regionIds[1],crease.regionIds[0]] as [string,string];return pass({...sheet,creases:sheet.creases.map(c=>c.id===creaseId?{...c,regionIds,foldSide,fixedRegionId:regionIds[0],movingRegionId:regionIds[1]}:c),rootRegionId:regionIds[0]});}
export function previewSymmetricDiscard(sheet:PatternSheet,regionId:string,guideId:string):PatternResult<PatternSheet>{const c=construction(sheet),guide=c.symmetryGuides.find(g=>g.id===guideId),source=sheet.regions.find(r=>r.id===regionId);if(!guide||!source)return fail("INVALID_SYMMETRY_PAIR","region","Region and guide must exist");const center=(vertices:Vec2[]):Vec2=>[vertices.reduce((n,p)=>n+p[0],0)/vertices.length,vertices.reduce((n,p)=>n+p[1],0)/vertices.length],target=reflectPoint(center(source.vertices),guide),mirror=sheet.regions.map(r=>({r,d:dist(center(r.vertices),target)})).sort((a,b)=>a.d-b.d)[0];if(!mirror||mirror.d>1e-5)return fail("INVALID_SYMMETRY_PAIR","region","No symmetric region was found");return pass({...sheet,regions:sheet.regions.map(r=>r.id===source.id||r.id===mirror.r.id?{...r,status:"DISCARD_PREVIEW"}:r)});}
export function derivePointToPointCrease(sheet:PatternSheet,pointAId:string,pointBId:string):PatternResult<PatternSheet>{const c=construction(sheet),a=c.points.find(p=>p.id===pointAId),b=c.points.find(p=>p.id===pointBId);if(!a||!b||dist(a.position,b.position)<EPS)return fail("INVALID_FOLD_TARGET","points","Two distinct points are required");const m=midpoint(a.position,b.position),d:Vec2=[-(b.position[1]-a.position[1]),b.position[0]-a.position[0]],scale=1e4;return addStraightCrease(sheet,[m[0]-d[0]*scale,m[1]-d[1]*scale],[m[0]+d[0]*scale,m[1]+d[1]*scale]);}
export interface EdgeJoin { id:string; edgeA:[Vec2,Vec2]; edgeB:[Vec2,Vec2]; joinType:"JOIN_EXACT"; tolerance:number; status:"VALID"; }
export function createExactEdgeJoin(existing:EdgeJoin[],edgeA:[Vec2,Vec2],edgeB:[Vec2,Vec2],tolerance=1e-7):PatternResult<EdgeJoin>{if(existing.some(j=>JSON.stringify(j.edgeA)===JSON.stringify(edgeA)||JSON.stringify(j.edgeB)===JSON.stringify(edgeA)))return fail("EDGE_ALREADY_JOINED","edgeA","An edge may be joined only once");if(Math.abs(dist(...edgeA)-dist(...edgeB))>tolerance)return fail("JOIN_LENGTH_MISMATCH","edges","Joined edges must have equal length");const join:EdgeJoin={id:`join-${existing.length+1}`,edgeA,edgeB,joinType:"JOIN_EXACT",tolerance,status:"VALID"};return pass(join);}
export function deriveEdgeToEdgeFold(edgeA:[Vec2,Vec2],edgeB:[Vec2,Vec2],tolerance=1e-7):PatternResult<{targetAngleRadians:number;target:"EDGE_TO_EDGE_COINCIDENCE"}>{if(Math.abs(dist(...edgeA)-dist(...edgeB))>tolerance)return fail("EDGE_COINCIDENCE_UNRESOLVED","edges","Edges of unequal length cannot coincide rigidly");const da:Vec2=[edgeA[1][0]-edgeA[0][0],edgeA[1][1]-edgeA[0][1]],db:Vec2=[edgeB[1][0]-edgeB[0][0],edgeB[1][1]-edgeB[0][1]],cos=Math.max(-1,Math.min(1,(da[0]*db[0]+da[1]*db[1])/(dist(...edgeA)*dist(...edgeB))));return pass({targetAngleRadians:Math.acos(cos),target:"EDGE_TO_EDGE_COINCIDENCE"});}
