export const INPUT_PIPELINE_VERSION = "PIMATH_UNIFIED_INPUT_V1" as const;

export const INPUT_DIAGNOSTIC_CODES = [
  "EMPTY_SOURCE", "SOURCE_NOT_FOUND", "SOURCE_UNREADABLE", "UNSUPPORTED_INPUT", "INVALID_SIGNATURE",
  "EXTENSION_SIGNATURE_MISMATCH", "CORRUPT_DOCX", "CORRUPT_PDF", "INVALID_IMAGE", "ENCRYPTED_PDF",
  "PASSWORD_REQUIRED", "REQUIRES_LEGACY_CONVERSION", "LEGACY_CONVERSION_FAILED", "PDF_NATIVE_TEXT_UNAVAILABLE",
  "OCR_REQUIRED", "OCR_LOW_CONFIDENCE", "LAYOUT_REVIEW_REQUIRED", "READING_ORDER_REVIEW_REQUIRED",
  "MATH_REVIEW_REQUIRED", "FIGURE_REVIEW_REQUIRED", "QUESTION_BOUNDARY_REVIEW_REQUIRED", "SOURCE_CONFLICT_REVIEW_REQUIRED",
  "PROVIDER_UNAVAILABLE", "PROVIDER_TIMEOUT", "PROVIDER_FAILED", "RESOURCE_LIMIT_EXCEEDED", "UNSAFE_ARCHIVE",
  "DERIVED_SOURCE_PROVENANCE_REQUIRED"
] as const;
export type InputDiagnosticCode = typeof INPUT_DIAGNOSTIC_CODES[number] | string;

export const INPUT_LIMITS = Object.freeze({
  maxInputBytes: 100 * 1024 * 1024,
  maxArchiveEntries: 10000,
  maxDecompressedBytes: 500 * 1024 * 1024,
  maxPdfPages: 500,
  maxEmbeddedAssets: 2000,
  maxProviderExecutionMs: 120000
});

export const isInputDiagnosticCode = (value: string): value is InputDiagnosticCode => INPUT_DIAGNOSTIC_CODES.includes(value as never);
