import { createHash } from "node:crypto";
import { createMathDocument, validateMathIR, type MathExpression } from "../../math-ir/index.js";
import { parseMtefHeaderV5, scanMtefV5Records, type MtefRecord } from "./mtef-v5.js";
import { mtefV3ToMathMl, scanMtefV3Records } from "./mtef-v3-fixed.js";

export type MathMlNode =
  | { type:"math"|"row"; children:MathMlNode[] }
  | { type:"identifier"|"number"|"operator"; text:string }
  | { type:"fraction"|"root"|"sup"|"sub"|"subsup"; children:MathMlNode[] };

const esc=(s:string)=>s.replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;").replace(/"/g,"&quot;");
export function serializeMathMl(n:MathMlNode):string { switch(n.type){case "math":return `<math xmlns="http://www.w3.org/1998/Math/MathML">${n.children.map(serializeMathMl).join("")}</math>`;case "row":return `<mrow>${n.children.map(serializeMathMl).join("")}</mrow>`;case "identifier":return `<mi>${esc(n.text)}</mi>`;case "number":return `<mn>${esc(n.text)}</mn>`;case "operator":return `<mo>${esc(n.text)}</mo>`;case "fraction":return `<mfrac>${n.children.map(serializeMathMl).join("")}</mfrac>`;case "root":return `<msqrt>${n.children.map(serializeMathMl).join("")}</msqrt>`;case "sup":return `<msup>${n.children.map(serializeMathMl).join("")}</msup>`;case "sub":return `<msub>${n.children.map(serializeMathMl).join("")}</msub>`;case "subsup":return `<msubsup>${n.children.map(serializeMathMl).join("")}</msubsup>`;} }
function charText(payload:Uint8Array,r:MtefRecord){const p=r.offsetStart+1,opts=payload[p];if(opts===undefined||opts&32)return "";const code=payload[p+2]|payload[p+3]<<8;return code>=32&&code<=0x10ffff?String.fromCodePoint(code):"�";}
function token(text:string):MathMlNode {if(/^\d$/.test(text))return {type:"number",text};if(/^[A-Za-zα-ωΑ-Ω]$/.test(text))return {type:"identifier",text};return {type:"operator",text};}
export function mtefRecordsToMathMl(payload:Uint8Array, records:MtefRecord[]=scanMtefV5Records(payload).records):MathMlNode {const out:MathMlNode[]=[];for(const r of records){if(r.typeName!=="CHAR")continue;const t=charText(payload,r);if(t)out.push(token(t));}return {type:"math",children:[{type:"row",children:out}]};}
export interface BridgedMath { expression:MathExpression; mathMl:string; validation:"PASS"; provenance:Record<string,unknown>; }
const semanticCache=new Map<string,MathMlNode>();
export function clearMtefSemanticCache(){semanticCache.clear();}
export function mtefSemanticCacheSize(){return semanticCache.size;}
export function bridgeMtefV5ToMathExpression(payload:Uint8Array,source:Record<string,unknown>={}):BridgedMath {const header=parseMtefHeaderV5(payload), scan=scanMtefV5Records(payload), node=mtefRecordsToMathMl(payload,scan.records), mathMl=serializeMathMl(node), raw=node.type==="math"?mathMl:"";const id=`mtef-${createHash("sha256").update(payload).digest("hex").slice(0,16)}`;const expression:MathExpression={id,raw,normalized:mathMl,metadata:{sourceEvidence:[{id:`evidence-${id}`,origin:"imported",sourceType:"docx",sourceId:String(source.sourceObjectId??id)}],adapterMetadata:{...source,intermediateFormat:"MATHML",mtefVersion:header.mtefVersion,recordRanges:scan.records.map(r=>[r.offsetStart,r.offsetEnd])}}};const doc=createMathDocument({id:`doc-${id}`,sections:[{id:"section-1",blocks:[]}],problems:[],scenes:[],expressions:[expression],metadata:{sourceEvidence:[]}});const v=validateMathIR(doc);if(v.status==="FAIL")throw Error(`MTEF_CANONICAL_BRIDGE_INVALID:${v.issues.map(x=>x.code).join(",")}`);return {expression,mathMl,validation:"PASS",provenance:expression.metadata?.adapterMetadata??{}};}
export function bridgeMtefV3ToMathExpression(payload:Uint8Array,source:Record<string,unknown>={}):BridgedMath {const scan=scanMtefV3Records(payload),node=mtefV3ToMathMl(payload),mathMl=serializeMathMl(node),id=`mtef-v3-${createHash("sha256").update(payload).digest("hex").slice(0,16)}`;const expression:MathExpression={id,raw:mathMl,normalized:mathMl,metadata:{sourceEvidence:[{id:`evidence-${id}`,origin:"imported",sourceType:"docx",sourceId:String(source.sourceObjectId??id)}],adapterMetadata:{...source,intermediateFormat:"MATHML",mtefVersion:3,recordRanges:scan.records.map(r=>[r.offsetStart,r.offsetEnd])}}};const doc=createMathDocument({id:`doc-${id}`,sections:[{id:"section-1",blocks:[]}],problems:[],scenes:[],expressions:[expression],metadata:{sourceEvidence:[]}});const v=validateMathIR(doc);if(v.status==="FAIL")throw Error(`MTEF_V3_CANONICAL_BRIDGE_INVALID:${v.issues.map(x=>x.code).join(",")}`);return {expression,mathMl,validation:"PASS",provenance:expression.metadata?.adapterMetadata??{}};}
