import { createHash } from "node:crypto";
import { equationNativeStream, findEquationNative } from "./equation-native.js";
export interface MtefRecord { recordIndex:number; typeId:number; typeName:string; options?:number; offsetStart:number; offsetPayload:number; offsetEnd:number; depth:number; parentRecordIndex?:number; payloadHash:string; }
export interface MtefHeader { mtefVersion:number; platform:number; product:number; productVersion:number; productSubVersion:number; applicationKey:string; headerLength:number; payloadStartOffset:number; }
export interface MtefScan { version:number; records:MtefRecord[]; errors:string[]; header?:MtefHeader; }
export type MtefParserAst = { type:"Sequence"; children:{type:string; recordType:string; recordOffset:number; value?:string}[]; provenance?:Record<string,string> };
const N:Record<number,string>={0:"END",1:"LINE",2:"CHAR",3:"TMPL",4:"PILE",5:"MATRIX",6:"EMBELL",7:"RULER",8:"FONT_STYLE_DEF",9:"SIZE",10:"FULL",11:"SUB",12:"SUB2",13:"SYM",14:"SUBSYM",15:"COLOR",16:"COLOR_DEF",17:"FONT_DEF",18:"EQN_PREFS",19:"ENCODING_DEF",102:"MT_COMMENT"};
const hash=(b:Uint8Array)=>createHash("sha256").update(b).digest("hex");
class Cursor { constructor(readonly b:Uint8Array,public p=0,readonly ctx="MTEF_V5"){} remaining(){return this.b.length-this.p;} need(n:number){if(n<0||this.p+n>this.b.length)throw Error(`${this.ctx}:OUT_OF_BOUNDS_READ@${this.p}:need=${n}`);} u8(){this.need(1);return this.b[this.p++];} i8(){const v=this.u8();return v>127?v-256:v;} u16(){this.need(2);const v=this.b[this.p]|this.b[this.p+1]<<8;this.p+=2;return v;} bytes(n:number){this.need(n);const v=this.b.subarray(this.p,this.p+n);this.p+=n;return v;} mt(){const v=this.u8();return v===255?this.u16():v;} strz(){const a:number[]=[];while(this.remaining()){const v=this.u8();if(!v)break;a.push(v);}return new TextDecoder().decode(new Uint8Array(a));} }
export function parseMtefHeaderV5(payload:Uint8Array,ctx="MTEF_V5"):MtefHeader { const c=new Cursor(payload,0,ctx);const mtefVersion=c.u8();if(mtefVersion!==5)throw Error(`${ctx}:EXPECTED_V5@0`);const platform=c.u8(),product=c.u8(),productVersion=c.u8(),productSubVersion=c.u8();const applicationKey=c.strz();const headerLength=c.p;c.u8();return {mtefVersion,platform,product,productVersion,productSubVersion,applicationKey,headerLength,payloadStartOffset:c.p}; }
function nudge(c:Cursor){const x=c.i8(),y=c.i8();if(x===-128&&y===-128){c.u16();c.u16();}}
function ruler(c:Cursor){const n=Math.max(0,Math.min(64,c.i8()));for(let i=0;i<n;i++){c.i8();c.u16();}}
function nibbleDims(c:Cursor,n:number){for(let i=0;i<n;i++){let done=false;while(!done){const v=c.u8();done=(v&15)===15||(v>>4)===15;}}}
export function scanMtefV5Records(payload:Uint8Array,ctx="MTEF_V5"):MtefScan {const records:MtefRecord[]=[];const errors:string[]=[];let header:MtefHeader|undefined;try{header=parseMtefHeaderV5(payload,ctx);}catch(e){return {version:5,records,errors:[String(e)]};}const c=new Cursor(payload,header.payloadStartOffset,ctx);const list=(depth:number,parent?:number,top=false):void=>{if(depth>128)throw Error(`${ctx}:UNBOUNDED_NESTING@${c.p}`);let ended=false;while(c.remaining()){const start=c.p,typeId=c.u8();if(typeId===0){records.push({recordIndex:records.length,typeId,typeName:"END",offsetStart:start,offsetPayload:c.p,offsetEnd:c.p,depth,parentRecordIndex:parent,payloadHash:hash(payload.subarray(start,c.p))});ended=true;break;}const typeName=N[typeId]??(typeId>=100?"FUTURE":"UNKNOWN");if(typeName==="UNKNOWN")throw Error(`${ctx}:UNKNOWN_RECORD:${typeId}@${start}`);const rec:any={recordIndex:records.length,typeId,typeName,offsetStart:start,offsetPayload:c.p,depth,parentRecordIndex:parent};if([1,2,3,4,5,6,16,18].includes(typeId))rec.options=c.u8();records.push(rec);if(rec.options!==undefined&&(rec.options&8)&&[1,2,3,4,5].includes(typeId))nudge(c);if(typeId===1){if(rec.options&4)c.u16();if(rec.options&2)ruler(c);if(!(rec.options&1)||top)list(depth+1,rec.recordIndex,true);}else if(typeId===2){c.i8();if(!(rec.options&32))c.u16();if(rec.options&4)c.u8();else if(rec.options&16)c.u16();if(rec.options&1)list(depth+1,rec.recordIndex);}else if(typeId===3){c.i8();let v=c.u8();if(v&128)c.u8();c.u8();list(depth+1,rec.recordIndex);}else if(typeId===4){c.i8();c.i8();if(rec.options&2)ruler(c);list(depth+1,rec.recordIndex);}else if(typeId===5){c.i8();c.i8();c.i8();const r=c.i8(),col=c.i8();c.bytes(Math.ceil(Math.max(0,r)/4));c.bytes(Math.ceil(Math.max(0,col)/4));list(depth+1,rec.recordIndex);}else if(typeId===6){c.u8();}else if(typeId===7){ruler(c);}else if(typeId===8){c.mt();c.i8();}else if(typeId===9){const s=c.i8();if(s===101)c.u16();else if(s===100){c.u8();c.u16();}else c.u8();}else if(typeId===15){c.mt();}else if(typeId===16){c.u16();c.u16();c.u16();if(rec.options&4)c.strz();}else if(typeId===17){c.mt();c.strz();}else if(typeId===18){nibbleDims(c,c.u8());nibbleDims(c,c.u8());const st=c.u8();for(let i=0;i<st;i++){const f=c.u8();if(f)c.u8();}}else if(typeId===19){c.strz();}else if(typeId>=100){c.bytes(c.mt());}rec.offsetEnd=c.p;rec.payloadHash=hash(payload.subarray(start,c.p));}if(!ended)throw Error(`${ctx}:MISSING_END@${c.p}`);};try{list(0,undefined,true);}catch(e){errors.push(String(e));}return {version:5,records,errors,header};}
export function unwrapAndScanEquationNative(bytes:Uint8Array){const profile=findEquationNative(bytes);const stream=equationNativeStream(bytes);if(!profile||!stream)throw Error("EQUATION_NATIVE_STREAM_NOT_FOUND");const payload=stream.bytes.subarray(profile.payloadOffset,profile.payloadOffset+profile.payloadLength);return {profile,payload,scan:scanMtefV5Records(payload)};}

/** Parse the bounded V5 record tree into the internal decoder AST.  Binary
 * record validation remains authoritative; this AST deliberately keeps
 * template/container records structural until their slots are interpreted. */
export function parseMtefV5(payload:Uint8Array, context="MTEF_V5"): {scan:MtefScan; ast:MtefParserAst} {
  const scan=scanMtefV5Records(payload,context);
  if(scan.errors.length) throw Error(scan.errors.join("; "));
  const children=scan.records.filter(r=>r.typeName!=="END").map(r=>({
    type: r.typeName === "CHAR" ? "Symbol" : r.typeName === "TMPL" ? "Template" : r.typeName,
    recordType:r.typeName, recordOffset:r.offsetStart
  }));
  return {scan,ast:{type:"Sequence",children,provenance:{sourceFormat:"MATHTYPE_OLE",mtefVersion:"5",decoderVersion:"pimath-mtef-v5-1"}}};
}
