import type { EvidenceKind, EvidenceRequest, LocalDocumentEvidence, LocalDocumentEvidenceProvider, ProviderAvailability } from "./types.ts";
import { certifiedBridge, certifiedPython, jsonBridge, probe, safeProcessRunner, type ProcessRunner } from "./process.ts";
import { reviewForConfidence, sourceHash, unavailableEvidence } from "./types.ts";
const base = (name: string, version: string, request: EvidenceRequest, kind: EvidenceKind, payload: unknown, confidence?: number, issues: string[] = []): LocalDocumentEvidence => { const hash = sourceHash(request); return { provider: name, providerVersion: version, sourceDocument: request.sourceDocument, sourceHash: hash, sourceAnchor: request.sourceAnchor, assetId: request.assetId, evidenceKind: kind, confidence, payload, issues, reviewStatus: reviewForConfidence(confidence), transformationHistory: [], provenance: { sourceFile: request.sourceDocument, sourceSha256: hash, provider: name, transformations: [], authority: "EVIDENCE_ONLY" } }; };
abstract class BridgeProvider implements LocalDocumentEvidenceProvider { abstract readonly name: string; abstract readonly command: string; abstract readonly kind: EvidenceKind; constructor(protected runner: ProcessRunner = safeProcessRunner) {} capabilities() { return [this.kind] as const; } async availability(): Promise<ProviderAvailability> { const p = await probe(this.runner, this.command, this.probeArgs()); return { status: p.status, version: p.version, issues: p.issue ? [p.issue] : [] }; } protected probeArgs() { return ["--version"]; } protected request(req: EvidenceRequest) { return { sourceDocument: req.sourceDocument, sourceHash: sourceHash(req), lang: req.language ?? req.documentLanguage }; } async extractEvidence(request: EvidenceRequest) { const a = await this.availability(); if (a.status !== "AVAILABLE") return unavailableEvidence(this.name, request, `${this.name.toUpperCase()}_RUNTIME_STATUS=UNAVAILABLE`); try { const result = await jsonBridge(this.runner, this.command, this.args(), this.request(request), request.timeoutMs ?? 30000) as { payload?: unknown; confidence?: number; issues?: string[] }; return [base(this.name, a.version ?? "unknown", request, this.kind, result.payload ?? result, result.confidence, result.issues ?? [])]; } catch (e) { return unavailableEvidence(this.name, request, e instanceof Error ? e.message : "provider error"); } } abstract args(): string[]; }
abstract class PythonBridgeProvider extends BridgeProvider { protected python = certifiedPython(); args() { return [certifiedBridge(`docling-paddle/${this.name === "docling" ? "docling_bridge.py" : "paddleocr_bridge.py"}`)]; } protected probeArgs() { return ["--version"]; } }
export class DoclingProvider extends PythonBridgeProvider { readonly name = "docling"; readonly command = certifiedPython() ?? "__pimath_python_missing__"; readonly kind = "LAYOUT"; }
export class PaddleOcrProvider extends PythonBridgeProvider { readonly name = "paddleocr"; readonly command = certifiedPython() ?? "__pimath_python_missing__"; readonly kind = "OCR_TEXT"; }
export class LibreOfficeProvider extends BridgeProvider { readonly name = "libreoffice"; readonly command = process.execPath; readonly kind = "TEXT"; protected probeArgs() { return [certifiedBridge("libreoffice/libreoffice_bridge.mjs")]; } args() { return [certifiedBridge("libreoffice/libreoffice_bridge.mjs")]; } }
export class OllamaQwen3VlProvider implements LocalDocumentEvidenceProvider { readonly name = "ollama-qwen3-vl"; constructor(private runner: ProcessRunner = safeProcessRunner, private model?: string) {} capabilities() { return ["SEMANTIC_ASSIST"] as const; } async availability(): Promise<ProviderAvailability> { const executable = await probe(this.runner, "ollama", ["--version"]); if (executable.status !== "AVAILABLE") return { status: "UNAVAILABLE", issues: ["OLLAMA_MISSING"] }; try { const listing = await this.runner("ollama", ["list"], 5000); const tags = listing.stdout.split(/\r?\n/).map((line) => line.trim().split(/\s+/)[0]).filter((x): x is string => !!x && /^qwen3-vl(?::.+)?$/i.test(x)); const selected = this.model ?? process.env.PIMATH_QWEN3_VL_MODEL ?? tags.find((x) => x.toLowerCase() === "qwen3-vl:2b") ?? tags.find((x) => /^qwen3-vl:/i.test(x)); if (!selected || !tags.includes(selected)) return { status: "MODEL_MISSING", model: selected ?? "qwen3-vl", issues: ["QWEN3_VL_MODEL_MISSING"] }; return { status: "AVAILABLE", model: selected, issues: [] }; } catch (error) { return { status: "UNAVAILABLE", issues: [error instanceof Error ? error.message : "OLLAMA_LIST_FAILED"] }; } } async extractEvidence(request: EvidenceRequest) { const a = await this.availability(); if (a.status !== "AVAILABLE") return unavailableEvidence(this.name, request, a.issues[0]); try { const result = await jsonBridge(this.runner, process.execPath, [certifiedBridge("qwen3vl/ollama_bridge.mjs")], { sourceDocument: request.sourceDocument, sourceHash: sourceHash(request), model: a.model, prompt: request.prompt, includeImage: request.includeImage }, request.timeoutMs ?? 30000); return [base(this.name, "local", request, "SEMANTIC_ASSIST", result, undefined, ["AI_SEMANTIC_AUTHORITY=NO", "TEACHER_REVIEW_REQUIRED_FOR_AMBIGUOUS_AI=YES"])]; } catch (e) { return unavailableEvidence(this.name, request, e instanceof Error ? e.message : "provider error"); } } }
