import type { EvidenceKind, EvidenceRequest, LocalDocumentEvidence, LocalDocumentEvidenceProvider, ProviderAvailability } from "./types.ts";
import { jsonBridge, probe, safeProcessRunner, type ProcessRunner } from "./process.ts";
import { reviewForConfidence, sourceHash, unavailableEvidence } from "./types.ts";
const base = (name: string, version: string, request: EvidenceRequest, kind: EvidenceKind, payload: unknown, confidence?: number, issues: string[] = []): LocalDocumentEvidence => { const hash = sourceHash(request); return { provider: name, providerVersion: version, sourceDocument: request.sourceDocument, sourceHash: hash, sourceAnchor: request.sourceAnchor, assetId: request.assetId, evidenceKind: kind, confidence, payload, issues, reviewStatus: reviewForConfidence(confidence), transformationHistory: [], provenance: { sourceFile: request.sourceDocument, sourceSha256: hash, provider: name, transformations: [], authority: "EVIDENCE_ONLY" } }; };
abstract class BridgeProvider implements LocalDocumentEvidenceProvider { abstract readonly name: string; abstract readonly command: string; abstract readonly kind: EvidenceKind; constructor(protected runner: ProcessRunner = safeProcessRunner) {} capabilities() { return [this.kind] as const; } async availability(): Promise<ProviderAvailability> { const p = await probe(this.runner, this.command); return { status: p.status, version: p.version, issues: p.issue ? [p.issue] : [] }; } async extractEvidence(request: EvidenceRequest) { const a = await this.availability(); if (a.status !== "AVAILABLE") return unavailableEvidence(this.name, request, `${this.name.toUpperCase()}_RUNTIME_STATUS=UNAVAILABLE`); try { const result = await jsonBridge(this.runner, this.command, [], { sourceDocument: request.sourceDocument, sourceHash: sourceHash(request) }, request.timeoutMs ?? 30000) as { payload?: unknown; confidence?: number; issues?: string[] }; return [base(this.name, a.version ?? "unknown", request, this.kind, result.payload ?? result, result.confidence, result.issues ?? [])]; } catch (e) { return unavailableEvidence(this.name, request, e instanceof Error ? e.message : "provider error"); } } }
export class DoclingProvider extends BridgeProvider { readonly name = "docling"; readonly command = "docling"; readonly kind = "LAYOUT"; }
export class PaddleOcrProvider extends BridgeProvider { readonly name = "paddleocr"; readonly command = "paddleocr"; readonly kind = "OCR_TEXT"; }
export class LibreOfficeProvider extends BridgeProvider { readonly name = "libreoffice"; readonly command = "soffice"; readonly kind = "TEXT"; }
export class OllamaQwen3VlProvider implements LocalDocumentEvidenceProvider { readonly name = "ollama-qwen3-vl"; constructor(private runner: ProcessRunner = safeProcessRunner, private model = "qwen3-vl") {} capabilities() { return ["SEMANTIC_ASSIST"] as const; } async availability(): Promise<ProviderAvailability> { const executable = await probe(this.runner, "ollama", ["--version"]); if (executable.status !== "AVAILABLE") return { status: "UNAVAILABLE", issues: ["OLLAMA_MISSING"] }; try { const listing = await this.runner("ollama", ["list"], 5000); const modelFound = listing.stdout.split(/\r?\n/).some((line) => /(?:^|\s|\/)qwen3-vl(?::|\s|$)/i.test(line.trim().split(/\s+/)[0] ?? "")); if (!modelFound) return { status: "MODEL_MISSING", model: this.model, issues: ["QWEN3_VL_MODEL_MISSING"] }; return { status: "AVAILABLE", model: this.model, issues: [] }; } catch (error) { return { status: "UNAVAILABLE", issues: [error instanceof Error ? error.message : "OLLAMA_LIST_FAILED"] }; } } async extractEvidence(request: EvidenceRequest) { const a = await this.availability(); if (a.status !== "AVAILABLE") return unavailableEvidence(this.name, request, a.issues[0]); try { const result = await jsonBridge(this.runner, "ollama", ["run", this.model], { sourceDocument: request.sourceDocument }, request.timeoutMs ?? 30000); return [base(this.name, "local", request, "SEMANTIC_ASSIST", result, undefined, ["AI_SEMANTIC_AUTHORITY=NO", "TEACHER_REVIEW_REQUIRED_FOR_AMBIGUOUS_AI=YES"])]; } catch (e) { return unavailableEvidence(this.name, request, e instanceof Error ? e.message : "provider error"); } } }
