// Canonical generic GeoGebra runtime contracts and helpers.
// Mathematical and FOLD domain authority remain outside this layer.

export type UpdateOrigin = "CANONICAL" | "GEOGEBRA" | "UI";
export interface GeoGebraFoldApi { evalCommand(command: string): boolean; setValue(name: string, value: number): void; deleteObject(name: string): void; setVisible(name: string, visible: boolean): void; setColor(name: string, r: number, g: number, b: number): void; registerUpdateListener(listener: (name: string) => void): void; registerAddListener(listener: (name: string) => void): void; registerRemoveListener(listener: (name: string) => void): void; registerRenameListener(listener: (oldName: string, newName: string) => void): void; registerClickListener(listener: (name: string) => void): void; setLabelVisible?(name: string, visible: boolean): void; setPerspective?(perspective: string): void; setSize?(width: number, height: number): void; recalculateEnvironments?(): void; }
export interface GeoGebraIdMapping { canonicalId: string; geogebraLabel: string; }
export const createGeoGebraOriginGuard = () => { let origin: UpdateOrigin = "UI"; return { get current() { return origin; }, run<T>(next: UpdateOrigin, work: () => T) { const previous = origin; origin = next; try { return work(); } finally { origin = previous; } } }; };
export const createGeoGebraIdMapping = (entries: GeoGebraIdMapping[] = []) => new Map(entries.map(entry => [entry.canonicalId, entry.geogebraLabel]));
export const createGeoGebraSmokeConstruction = (api: GeoGebraFoldApi) => { api.evalCommand("t = 0.5"); api.evalCommand("A = (0, 0, 0)"); api.evalCommand("B = (4, 0, 0)"); api.evalCommand("C = (4, 3, 0)"); api.evalCommand("D = (0, 3, 0)"); api.evalCommand("ggb_hinge = Line(A, B)"); api.evalCommand("ggb_face = Polygon(A, B, C, D)"); api.evalCommand("ggb_rotated = Rotate(ggb_face, t * 45°, ggb_hinge)"); return { slider: "t", face: "ggb_face", rotated: "ggb_rotated", hinge: "ggb_hinge" } as const; };
