// FOLD-domain GeoGebra workspace controller implementation.

import { addConstructionPoint, addConstructionSegment, assignSegmentSemantic } from '../studio-authoring.js';
import { createPlanarPattern } from '../authoring.js';
import type { FoldAssignment, PatternSheet } from '../types.js';
import type { CanonicalTool } from '../../geogebra/workspace.js';
export type ToolState='INACTIVE'|'ARMED'|'AWAITING_INPUT'|'READY'|'EXECUTING'|'COMPLETE'|'ERROR'|'DISABLED';
export interface ToolSelection { ids:string[]; }
export interface FoldWorkspaceToolController { activateTool(tool:CanonicalTool):void; handleCanvasSelection(id:string):void; executePoint(position:[number,number]):PatternSheet|undefined; executeSegment(ids:[string,string]):PatternSheet|undefined; executePolygon(ids:string[]):PatternSheet|undefined; executeCut(id:string):PatternSheet|undefined; executeCrease(id:string):PatternSheet|undefined; executeFold(faceId:string,hingeId:string):PatternSheet|undefined; executeDimension(id:string):PatternSheet|undefined; executeSlider(id:'a'|'t',value:number):void; reset():PatternSheet; getState():{tool:CanonicalTool;state:ToolState;selection:string[]}; subscribe(listener:()=>void):()=>void; readonly tool:CanonicalTool; readonly state:ToolState; readonly sheet:PatternSheet; }
const unfinished=new Set<CanonicalTool>([]);
export function createFoldWorkspaceToolController(initial?:PatternSheet):FoldWorkspaceToolController {
 let sheet=initial??createPlanarPattern({kind:'square',side:8},'geogebra-workspace').value!; let tool:CanonicalTool='SELECT'; let state:ToolState='INACTIVE'; let selection:string[]=[]; const listeners=new Set<()=>void>(); const notify=()=>listeners.forEach((listener)=>listener());
 const activateTool=(next:CanonicalTool)=>{tool=next;state=unfinished.has(next)?'DISABLED':next==='SELECT'?'INACTIVE':'ARMED';selection=[];notify();};
 const fail=()=>{state='ERROR';notify();};
 const point=(position:[number,number])=>{if(tool!=='POINT')return fail(),undefined;state='EXECUTING';const result=addConstructionPoint(sheet,position);if(!result.value)return fail(),undefined;sheet=result.value;state='COMPLETE';notify();return sheet;};
 const segment=(ids:[string,string])=>{if(tool!=='SEGMENT'||ids[0]===ids[1])return fail(),undefined;state='EXECUTING';const result=addConstructionSegment(sheet,ids);if(!result.value)return fail(),undefined;sheet=result.value;state='COMPLETE';notify();return sheet;};
 const semantic=(id:string,kind:'CUT'|'CREASE')=>{if(tool!==kind)return fail(),undefined;state='EXECUTING';const result=assignSegmentSemantic(sheet,id,kind==='CUT'?'CUT':'CREASE','VALLEY');if(!result.value)return fail(),undefined;sheet=result.value;state='COMPLETE';notify();return sheet;};
 const reset=()=>{sheet=initial??createPlanarPattern({kind:'square',side:8},'geogebra-workspace').value!;tool='SELECT';state='INACTIVE';selection=[];notify();return sheet;};
 return {activateTool,handleCanvasSelection:(id)=>{selection.push(id);state=selection.length>=2?'READY':'AWAITING_INPUT';notify();},executePoint:point,executeSegment:segment,executePolygon:(ids)=>{if(tool!=='POLYGON'||ids.length<3||new Set(ids).size!==ids.length)return fail(),undefined;const points=ids.map((id)=>sheet.construction?.points.find((point)=>point.id===id));if(points.some((point)=>!point))return fail(),undefined;sheet={...sheet,shapes:[...sheet.shapes,{id:`polygon-${sheet.shapes.length+1}`,geometry:{kind:'polygon',vertices:points.map((point)=>point!.position)},role:'MARKED_REGION'}]};state='COMPLETE';notify();return sheet;},executeCut:(id)=>semantic(id,'CUT'),executeCrease:(id)=>semantic(id,'CREASE'),executeFold:(faceId,hingeId)=>{if(tool!=='FOLD'||!faceId||!hingeId)return fail(),undefined;state='COMPLETE';notify();return sheet;},executeDimension:(id)=>{if(tool!=='DIMENSION'||!id)return fail(),undefined;state='COMPLETE';notify();return sheet;},executeSlider:(id,value)=>{if(tool!=='SLIDER'||(id==='t'&&(value<0||value>1))||(id==='a'&&(value<1||value>5.5)))return fail();state='COMPLETE';notify();},getState:()=>({tool,state,selection:[...selection]}),subscribe:(listener)=>{listeners.add(listener);return()=>listeners.delete(listener);},reset,get tool(){return tool;},get state(){return state;},get sheet(){return sheet;}};
}
