import type { DocumentIR, DocumentBlock } from "../document-engine/document-ir.js";
import type { DocumentQuestionCandidate, SharedContext, QuestionStartCandidate } from "./types.js";

export interface BoundaryValidation { overlap: number; gap: number; invalid: number; duplicate: number; unaccounted: number; classifications: Record<string, string>; }
const blockText = (b: DocumentBlock) => b.content.map((x: any) => x.type === "text" ? x.value : x.type === "table" ? x.cells.flat().map((c: any) => c.type === "text" ? c.value : "").join(" ") : "").join(" ").replace(/\s+/g, " ").trim();
export function classifyStart(block: DocumentBlock, signals: QuestionStartCandidate[]): "QUESTION" | "SHARED_CONTEXT" | "ANSWER" | "SOLUTION" | "DOCUMENT_STRUCTURE" | "NON_QUESTION" | "REVIEW" | "UNSUPPORTED" { const s = blockText(block); if (/^(?:đáp\s*án|lời\s*giải|hướng\s*dẫn\s*giải|kết\s*quả)\b/iu.test(s)) return "SOLUTION"; if (/^(?:phần|trắc nghiệm|tự luận|đúng\s*\/\s*sai)\b/iu.test(s)) return "DOCUMENT_STRUCTURE"; if (/(?:dựa vào|dùng|với thông tin|các câu tiếp theo).*?(?:hình|bảng|dữ kiện|thông tin)/iu.test(s)) return "SHARED_CONTEXT"; if (signals.length) return "QUESTION"; return "NON_QUESTION"; }
export function detectSharedContexts(document: DocumentIR): SharedContext[] { const contexts: SharedContext[] = []; for (const block of document.blocks) { const s = blockText(block); if (!/(?:dựa vào|dùng|với thông tin|các câu tiếp theo).*?(?:hình|bảng|dữ kiện|thông tin)/iu.test(s)) continue; const flat = block.content.flatMap((x: any) => x.type === "table" ? x.cells.flat() : [x]); const assets = flat.filter((x: any) => x.type === "figure").map((x: any) => x.figureId); const math = flat.filter((x: any) => x.type === "math").map((x: any) => x.math.id).filter(Boolean); contexts.push({ contextId: `${document.sourceHash.slice(0,12)}-context-${contexts.length+1}`, sourceDocumentId: document.sourceDocumentId ?? document.sourceHash, sourceObjectIds: [block.id], startObjectId: block.id, endObjectId: block.id, sourceAnchors: [{ sourceDocumentId: document.sourceDocumentId ?? document.sourceHash, partName: "word/document.xml", objectIndex: block.order }], mathObjectIds: math, assetIds: assets, tableIds: flat.filter((x: any) => x.type === "table").map(() => `table-${block.order}`), evidence: ["SHARED_CONTEXT_TRANSITION", "SOURCE_ANCHOR"], contradictions: [], confidence: "MEDIUM_CONFIDENCE", provenance: document.provenance ?? {}, referencedQuestionIds: [], qaStatus: "REVIEW" } as SharedContext); } return contexts; }

export type IndependentAuditStatus = "CONFIRMED" | "REVIEW" | "REJECTED_FALSE";
export function independentlyAuditCandidate(candidate: DocumentQuestionCandidate): IndependentAuditStatus { const b = candidate.boundary; if (!b || !candidate.startCandidates?.length) return "REVIEW"; const evidence = candidate.startCandidates; const strong = evidence.some(x => x.candidateKind === "TEXTUAL_MARKER" && /^(?:câu|bài|question)\b/iu.test(x.rawEvidence)) || evidence.some(x => x.candidateKind === "WORD_NUMBERING" && evidence.length >= 2) || evidence.some(x => x.candidateKind === "TABLE_STRUCTURE" && candidate.rawBlocks.some(x => x.kind === "TABLE")); const first = candidate.textBlocks[0]; const firstText = first?.type === "text" ? first.value : ""; if (/^(?:lời\s*giải|đáp\s*án|hướng\s*dẫn|a[.)]|b[.)]|c[.)]|d[.)])/iu.test(firstText.trim())) return "REJECTED_FALSE"; if (strong) return "CONFIRMED"; return "REVIEW"; }
export function validateRanges(document: DocumentIR, questions: DocumentQuestionCandidate[], contexts: SharedContext[] = []): BoundaryValidation { const order = new Map(document.blocks.map((b,i)=>[b.id,i])); const ranges = questions.filter(q=>q.boundary).map(q=>({q,start:order.get(q.boundary!.startObjectId) ?? -1,end:order.get(q.boundary!.endObjectId) ?? -1})); let overlap=0,invalid=0; for(let i=1;i<ranges.length;i++){ if(ranges[i].start<=ranges[i-1].end) overlap++; } invalid=ranges.filter(r=>r.start<0||r.end<r.start).length; const duplicate = new Set(ranges.map(r=>`${r.start}:${r.end}`)).size < ranges.length ? 1 : 0; const used=new Set(ranges.flatMap(r=>Array.from({length:Math.max(0,r.end-r.start+1)},(_,i)=>r.start+i))); const contextBlocks=new Set(contexts.flatMap(c=>c.sourceObjectIds).map(id=>order.get(id)).filter((x):x is number=>x!==undefined)); const classifications: Record<string,string>={}; document.blocks.forEach((b,i)=>{ if(used.has(i)) classifications[b.id]="QUESTION"; else if(contextBlocks.has(i)) classifications[b.id]="SHARED_CONTEXT"; else classifications[b.id]=classifyStart(b,[]); }); return {overlap,gap:0,invalid,duplicate,unaccounted:Object.values(classifications).filter(x=>!x).length,classifications}; }
