import { createHash } from "node:crypto";
import { execFileSync, spawnSync } from "node:child_process";
import { existsSync, mkdirSync, mkdtempSync, readFileSync, renameSync, rmSync, writeFileSync } from "node:fs";
import { basename, extname, isAbsolute, join, resolve, sep } from "node:path";
import { tmpdir } from "node:os";
import { zipSync } from "fflate";
import type { Assessment, AssessmentAnswerManifest } from "./assessment.js";
import type { ContentBlock, FigureRecord, QuestionBankRepository, QuestionObject, QuestionType, SourceProvenance } from "./types.js";

export type ExportAudience = "STUDENT" | "TEACHER";
export type ExportFormat = "JSON" | "LATEX" | "DOCX" | "PDF";
export type ExportAssetMode = "REFERENCE" | "EMBED";
export interface ExportSpec { audience: ExportAudience; formats: ExportFormat[]; includeAnswers?: boolean; includeSolutions?: boolean; includeMetadata?: boolean; includeProvenance?: boolean; assetMode?: ExportAssetMode; outputProfile?: "NA_MATH_STANDARD"; outputDirectory: string; filename?: string }
export type ExportDiagnosticCode = "INVALID_EXPORT_SPEC" | "MISSING_QUESTION" | "MISSING_ASSET" | "UNSUPPORTED_MATH_EXPORT" | "DOCX_GENERATION_FAILED" | "LATEX_COMPILE_FAILED" | "PDF_GENERATION_FAILED" | "ANSWER_LEAK_BLOCKED" | "UNRESOLVED_SOLUTION";
export interface ExportDiagnostic { code: ExportDiagnosticCode; message: string; questionId?: string; details?: Record<string, unknown> }
export interface ExportAsset { id: string; contentHash: string; mimeType: string; filename: string; sourceRelationships: string[]; questionIds: string[]; bytes: Uint8Array }
export interface ExportFigureRef { figureId: string; assetId: string; relationshipId: string; order: number; dimensions?: FigureRecord["dimensions"] }
export interface ExportQuestion { id: string; sectionId: string; position: number; type: QuestionType; stem: ContentBlock[]; options: QuestionObject["options"]; trueFalseItems: QuestionObject["trueFalseItems"]; shortAnswer?: ContentBlock[]; subquestions: QuestionObject["subquestions"]; figures: ExportFigureRef[]; points?: number; answer?: ContentBlock[]; solution?: ContentBlock[]; metadata?: Record<string, string>; provenance?: SourceProvenance }
export interface ExportSection { id: string; title?: string; questionType: QuestionType; pointsPerQuestion?: number; questions: ExportQuestion[] }
export interface ExportAnswerEntry { questionId: string; status: "EXPLICIT" | "UNRESOLVED"; answer?: ContentBlock[] }
export interface ExportSolutionEntry { questionId: string; status: "EXPLICIT" | "UNRESOLVED"; solution?: ContentBlock[] }
export interface CanonicalExportPackage { schemaVersion: 1; id: string; kind: "ASSESSMENT_EXPORT"; audience: ExportAudience; assessment: { id: string; title?: string; seed: string; bankFingerprint: string }; sections: ExportSection[]; questionRefs: string[]; assets: ExportAsset[]; answerKey?: ExportAnswerEntry[]; solutions?: ExportSolutionEntry[]; metadata?: Record<string, string>; provenance?: { assessmentId: string; bankFingerprint: string; questionSources: Record<string, SourceProvenance> }; diagnostics: ExportDiagnostic[] }
export interface ExportArtifact { format: ExportFormat; path: string; bytes: number; sha256: string }
export type ExportDeliveryResult = { ok: true; package: CanonicalExportPackage; artifacts: ExportArtifact[] } | { ok: false; diagnostics: ExportDiagnostic[] };

const digest = (value: Uint8Array | string) => createHash("sha256").update(value).digest("hex");
const stableValue = (value: unknown): unknown => value instanceof Uint8Array ? { $type: "Uint8Array", base64: Buffer.from(value).toString("base64") } : Array.isArray(value) ? value.map(stableValue) : value && typeof value === "object" ? Object.fromEntries(Object.entries(value).sort(([a],[b]) => a.localeCompare(b)).map(([key,item]) => [key,stableValue(item)])) : value;
export const stableStringify = (value: unknown, space = 2) => JSON.stringify(stableValue(value), null, space);
const cloneBlocks = (value?: ContentBlock[]) => value ? structuredClone(value) : undefined;
const validFormats = new Set<ExportFormat>(["JSON","LATEX","DOCX","PDF"]);
const explicitAnswer = (manifest: AssessmentAnswerManifest, id: string) => manifest.entries.find((entry) => entry.questionId === id);

export function validateExportSpec(spec: ExportSpec): ExportDiagnostic[] {
  const diagnostics: ExportDiagnostic[] = [];
  if (!spec || !["STUDENT","TEACHER"].includes(spec.audience) || !Array.isArray(spec.formats) || !spec.formats.length || spec.formats.some((format) => !validFormats.has(format)) || new Set(spec.formats).size !== spec.formats.length || !spec.outputDirectory?.trim() || !isAbsolute(spec.outputDirectory) || spec.assetMode !== undefined && !["REFERENCE","EMBED"].includes(spec.assetMode) || spec.outputProfile !== undefined && spec.outputProfile !== "NA_MATH_STANDARD") diagnostics.push({ code: "INVALID_EXPORT_SPEC", message: "Audience, unique supported formats, an absolute output directory, asset mode, and output profile must be valid." });
  if (spec.audience === "STUDENT" && (spec.includeAnswers || spec.includeSolutions)) diagnostics.push({ code: "ANSWER_LEAK_BLOCKED", message: "Student exports cannot include answers or solutions." });
  return diagnostics;
}

function confirmedFigures(question: QuestionObject): FigureRecord[] {
  const confirmed = new Set(question.figureAssociations.filter((association) => association.status === "CONFIRMED" && association.questionId === question.id).map((association) => association.figureId));
  return question.figures.filter((figure) => confirmed.has(figure.id));
}
function extension(mimeType: string): string { return mimeType === "image/png" ? ".png" : mimeType === "image/jpeg" ? ".jpg" : mimeType === "image/svg+xml" ? ".svg" : mimeType === "image/gif" ? ".gif" : ".bin"; }

export function createCanonicalExportPackage(assessment: Assessment, answerManifest: AssessmentAnswerManifest, repository: QuestionBankRepository, spec: ExportSpec): { ok: true; package: CanonicalExportPackage } | { ok: false; diagnostics: ExportDiagnostic[] } {
  const diagnostics = validateExportSpec(spec);
  if (answerManifest.assessmentId !== assessment.id) diagnostics.push({ code: "INVALID_EXPORT_SPEC", message: "Answer manifest does not belong to the assessment." });
  if (diagnostics.length) return { ok: false, diagnostics };
  const bank = repository.load(); const byId = new Map(bank.questions.map((question) => [question.id,question])); const assets = new Map<string,ExportAsset>(); const sources: Record<string,SourceProvenance> = {}; const sections: ExportSection[] = [];
  for (const section of assessment.sections) {
    const specSection = assessment.spec.sections.find((candidate) => candidate.id === section.id);
    const questions: ExportQuestion[] = [];
    for (const ref of section.questionRefs) {
      const source = byId.get(ref.questionId); if (!source) { diagnostics.push({ code: "MISSING_QUESTION", message: "Assessment references a missing Question Bank entry.", questionId: ref.questionId }); continue; }
      const figureRefs: ExportFigureRef[] = []; for (const [order,figure] of confirmedFigures(source).entries()) { if (!figure.bytes?.length) { diagnostics.push({ code: "MISSING_ASSET", message: "A confirmed figure has no source bytes.", questionId: source.id, details: { figureId: figure.id } }); continue; } const contentHash = digest(figure.bytes); const assetId = `asset-${contentHash.slice(0,16)}`; const existing = assets.get(assetId); if (existing) { if (!existing.questionIds.includes(source.id)) existing.questionIds.push(source.id); if (!existing.sourceRelationships.includes(figure.relationshipId)) existing.sourceRelationships.push(figure.relationshipId); } else assets.set(assetId,{ id: assetId, contentHash, mimeType: figure.mimeType ?? "application/octet-stream", filename: `${assetId}${extension(figure.mimeType ?? "")}`, sourceRelationships: [figure.relationshipId], questionIds: [source.id], bytes: new Uint8Array(figure.bytes) }); figureRefs.push({ figureId: figure.id, assetId, relationshipId: figure.relationshipId, order, dimensions: structuredClone(figure.dimensions) }); }
      const manifest = explicitAnswer(answerManifest,source.id); const question: ExportQuestion = { id: source.id, sectionId: section.id, position: ref.position, type: source.type, stem: structuredClone(source.stem), options: structuredClone(source.options), trueFalseItems: structuredClone(source.trueFalseItems), shortAnswer: cloneBlocks(source.shortAnswer), subquestions: structuredClone(source.subquestions), figures: figureRefs, points: ref.points };
      if (spec.audience === "TEACHER") { if (spec.includeAnswers && manifest?.answer?.length) question.answer = structuredClone(manifest.answer); if (spec.includeSolutions && manifest?.solution?.length) question.solution = structuredClone(manifest.solution); if (spec.includeMetadata) question.metadata = structuredClone(source.metadata); if (spec.includeProvenance) question.provenance = structuredClone(source.source); sources[source.id] = structuredClone(source.source); }
      questions.push(question);
    }
    sections.push({ id: section.id, title: section.title, questionType: specSection?.questionType ?? questions[0]?.type ?? "UNKNOWN", pointsPerQuestion: section.pointsPerQuestion, questions: questions.sort((a,b) => a.position-b.position) });
  }
  if (diagnostics.some((entry) => entry.code === "MISSING_QUESTION" || entry.code === "MISSING_ASSET")) return { ok: false, diagnostics };
  const questionRefs = sections.flatMap((section) => section.questions.map((question) => question.id)); const answerKey = spec.audience === "TEACHER" && spec.includeAnswers ? questionRefs.map((questionId) => { const entry = explicitAnswer(answerManifest,questionId); return entry?.answer?.length ? { questionId, status: "EXPLICIT" as const, answer: structuredClone(entry.answer) } : { questionId, status: "UNRESOLVED" as const }; }) : undefined; const solutions = spec.audience === "TEACHER" && spec.includeSolutions ? questionRefs.map((questionId) => { const entry = explicitAnswer(answerManifest,questionId); return entry?.solution?.length ? { questionId, status: "EXPLICIT" as const, solution: structuredClone(entry.solution) } : { questionId, status: "UNRESOLVED" as const }; }) : undefined;
  const semantic = { assessmentId: assessment.id, audience: spec.audience, questionRefs, answerKey, solutions, assets: [...assets.values()].map(({ bytes,...asset }) => asset) }; const id = `export-${digest(stableStringify(semantic,0)).slice(0,16)}`;
  return { ok: true, package: { schemaVersion: 1, id, kind: "ASSESSMENT_EXPORT", audience: spec.audience, assessment: { id: assessment.id, title: assessment.title, seed: assessment.seed, bankFingerprint: assessment.bankFingerprint }, sections, questionRefs, assets: [...assets.values()].sort((a,b) => a.id.localeCompare(b.id)), answerKey, solutions, metadata: spec.audience === "TEACHER" && spec.includeMetadata ? structuredClone(assessment.spec.metadata ?? {}) : undefined, provenance: spec.audience === "TEACHER" && spec.includeProvenance ? { assessmentId: assessment.id, bankFingerprint: assessment.bankFingerprint, questionSources: sources } : undefined, diagnostics } };
}

const xml = (value: string) => value.replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;").replace(/"/g,"&quot;");
const latexEscape = (value: string) => value.replace(/\\/g,"\\textbackslash{}").replace(/([#$%&_{}])/g,"\\$1").replace(/~/g,"\\textasciitilde{}").replace(/\^/g,"\\textasciicircum{}");
function plain(blocks?: ContentBlock[]): string { return (blocks ?? []).map((block) => block.type === "text" ? block.value : block.type === "math" ? block.math.latex ?? block.math.sourceRaw : block.type === "figure" ? `[FIGURE:${block.figureId}]` : block.cells.map((cell) => plain(cell)).join(" | ")).join(""); }
function latexBlocks(blocks?: ContentBlock[]): string { return (blocks ?? []).map((block) => block.type === "text" ? latexEscape(block.value) : block.type === "math" ? `\\(${block.math.latex ?? latexEscape(block.math.sourceRaw)}\\)` : block.type === "figure" ? "" : block.cells.map((cell) => latexBlocks(cell)).join(" & ")).join(""); }
function wordRuns(blocks?: ContentBlock[]): string { return (blocks ?? []).map((block) => block.type === "text" ? `<w:r><w:t xml:space="preserve">${xml(block.value)}</w:t></w:r>` : block.type === "math" ? `<m:oMath><m:r><m:t>${xml(block.math.latex ?? block.math.sourceRaw)}</m:t></m:r></m:oMath>` : block.type === "table" ? `<w:r><w:t>${xml(block.cells.map((cell) => plain(cell)).join(" | "))}</w:t></w:r>` : "").join(""); }
const paragraph = (blocks?: ContentBlock[], prefix = "") => `<w:p><w:r><w:t xml:space="preserve">${xml(prefix)}</w:t></w:r>${wordRuns(blocks)}</w:p>`;

export function serializeJsonPackage(pkg: CanonicalExportPackage, assetMode: ExportAssetMode = "REFERENCE"): string { const value = { ...pkg, assets: pkg.assets.map((asset) => { const { bytes,...reference } = asset; return assetMode === "EMBED" ? { ...reference, bytesBase64: Buffer.from(bytes).toString("base64") } : reference; }) }; return stableStringify(value); }
export function deserializeJsonPackage(value: string): CanonicalExportPackage { const parsed = JSON.parse(value) as Omit<CanonicalExportPackage,"assets"> & { assets: Array<Omit<ExportAsset,"bytes"> & { bytesBase64?: string }> }; if (parsed.schemaVersion !== 1 || parsed.kind !== "ASSESSMENT_EXPORT" || !Array.isArray(parsed.sections) || !Array.isArray(parsed.questionRefs) || !Array.isArray(parsed.assets)) throw new Error("EXPORT_JSON_SCHEMA_UNSUPPORTED"); return { ...parsed, assets: parsed.assets.map((asset) => { const { bytesBase64,...rest } = asset; return { ...rest, bytes: bytesBase64 ? new Uint8Array(Buffer.from(bytesBase64,"base64")) : new Uint8Array() }; }) }; }

export function renderLatex(pkg: CanonicalExportPackage): string {
  const body: string[] = [];
  for (const section of pkg.sections) { body.push(`\\section*{${latexEscape(section.title ?? section.id)}}`); for (const question of section.questions) { body.push(`\\noindent\\textbf{Câu ${question.position}.} ${latexBlocks(question.stem)}\\par`); for (const option of question.options) body.push(`\\noindent ${latexEscape(option.label)}. ${latexBlocks(option.content)}\\par`); for (const item of question.trueFalseItems) body.push(`\\noindent ${latexEscape(item.label)}. ${latexBlocks(item.content)}\\par`); for (const sub of question.subquestions) body.push(`\\noindent ${latexEscape(sub.label)}. ${latexBlocks(sub.content)}\\par`); for (const figure of question.figures) { const asset = pkg.assets.find((candidate) => candidate.id === figure.assetId); if (asset) body.push(`\\begin{center}\\includegraphics[width=0.42\\linewidth]{assets/${latexEscape(asset.filename)}}\\end{center}`); } if (pkg.audience === "TEACHER" && question.answer) body.push(`\\noindent\\textbf{Đáp án:} ${latexBlocks(question.answer)}\\par`); if (pkg.audience === "TEACHER" && question.solution) body.push(`\\noindent\\textbf{Lời giải:} ${latexBlocks(question.solution)}\\par`); body.push("\\medskip"); } }
  return [`\\documentclass[12pt,a4paper]{article}`,`\\usepackage{fontspec}`,`\\usepackage{amsmath,amssymb,graphicx}`,`\\setlength{\\oddsidemargin}{0pt}`,`\\setlength{\\evensidemargin}{0pt}`,`\\setlength{\\textwidth}{16cm}`,`\\setlength{\\topmargin}{-1cm}`,`\\setlength{\\textheight}{24cm}`,`\\setlength{\\parindent}{0pt}`,`\\begin{document}`,`\\begin{center}\\Large\\textbf{${latexEscape(pkg.assessment.title ?? "Math AI Studio Assessment")}}\\end{center}`,...body,"\\end{document}",""].join("\n");
}

function drawing(rid: string, asset: ExportAsset, index: number): string { const cx = 2743200, cy = 1828800; return `<w:p><w:r><w:drawing><wp:inline><wp:extent cx="${cx}" cy="${cy}"/><wp:docPr id="${index}" name="${xml(asset.filename)}"/><a:graphic><a:graphicData uri="http://schemas.openxmlformats.org/drawingml/2006/picture"><pic:pic><pic:nvPicPr><pic:cNvPr id="0" name="${xml(asset.filename)}"/><pic:cNvPicPr/></pic:nvPicPr><pic:blipFill><a:blip r:embed="${rid}"/><a:stretch><a:fillRect/></a:stretch></pic:blipFill><pic:spPr><a:xfrm><a:off x="0" y="0"/><a:ext cx="${cx}" cy="${cy}"/></a:xfrm><a:prstGeom prst="rect"><a:avLst/></a:prstGeom></pic:spPr></pic:pic></a:graphicData></a:graphic></wp:inline></w:drawing></w:r></w:p>`; }
export function renderDocx(pkg: CanonicalExportPackage): Uint8Array {
  const relationships: string[] = [], media: Record<string,Uint8Array> = {}; const ridByAsset = new Map<string,string>(); pkg.assets.forEach((asset,index) => { const rid = `rId${index+1}`; ridByAsset.set(asset.id,rid); relationships.push(`<Relationship Id="${rid}" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/image" Target="media/${xml(asset.filename)}"/>`); media[`word/media/${asset.filename}`] = asset.bytes; }); const body: string[] = [];
  body.push(`<w:p><w:pPr><w:pStyle w:val="Title"/></w:pPr><w:r><w:t>${xml(pkg.assessment.title ?? "Math AI Studio Assessment")}</w:t></w:r></w:p>`);
  let drawingIndex = 1; for (const section of pkg.sections) { body.push(`<w:p><w:pPr><w:pStyle w:val="Heading1"/></w:pPr><w:r><w:t>${xml(section.title ?? section.id)}</w:t></w:r></w:p>`); for (const question of section.questions) { body.push(paragraph(question.stem,`Câu ${question.position}. `)); question.options.forEach((option) => body.push(paragraph(option.content,`${option.label}. `))); question.trueFalseItems.forEach((item) => body.push(paragraph(item.content,`${item.label}. `))); question.subquestions.forEach((sub) => body.push(paragraph(sub.content,`${sub.label}. `))); for (const figure of question.figures) { const rid = ridByAsset.get(figure.assetId), asset = pkg.assets.find((candidate) => candidate.id === figure.assetId); if (rid && asset) body.push(drawing(rid,asset,drawingIndex++)); } if (pkg.audience === "TEACHER" && question.answer) body.push(paragraph(question.answer,"Đáp án: ")); if (pkg.audience === "TEACHER" && question.solution) body.push(paragraph(question.solution,"Lời giải: ")); } }
  const documentXml = `<?xml version="1.0" encoding="UTF-8" standalone="yes"?><w:document xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main" xmlns:m="http://schemas.openxmlformats.org/officeDocument/2006/math" xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships" xmlns:wp="http://schemas.openxmlformats.org/drawingml/2006/wordprocessingDrawing" xmlns:a="http://schemas.openxmlformats.org/drawingml/2006/main" xmlns:pic="http://schemas.openxmlformats.org/drawingml/2006/picture"><w:body>${body.join("")}<w:sectPr/></w:body></w:document>`;
  const rels = `<?xml version="1.0" encoding="UTF-8"?><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships">${relationships.join("")}</Relationships>`; const rootRels = `<?xml version="1.0" encoding="UTF-8"?><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument" Target="word/document.xml"/></Relationships>`; const types = `<?xml version="1.0" encoding="UTF-8"?><Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types"><Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/><Default Extension="xml" ContentType="application/xml"/><Default Extension="png" ContentType="image/png"/><Default Extension="jpg" ContentType="image/jpeg"/><Default Extension="svg" ContentType="image/svg+xml"/><Override PartName="/word/document.xml" ContentType="application/vnd.openxmlformats-officedocument.wordprocessingml.document.main+xml"/></Types>`; const enc = new TextEncoder(); return zipSync({ "[Content_Types].xml": enc.encode(types), "_rels/.rels": enc.encode(rootRels), "word/document.xml": enc.encode(documentXml), "word/_rels/document.xml.rels": enc.encode(rels), ...media });
}

export function sanitizeExportFilename(value: string): string { const safe = value.normalize("NFKC").replace(/[<>:"/\\|?*\u0000-\u001f]/g,"-").replace(/[. ]+$/g,"").replace(/\s+/g,"-").slice(0,100); return safe || "math-ai-studio-export"; }
function inside(root: string, candidate: string): boolean { const normalizedRoot = resolve(root); const normalized = resolve(candidate); return normalized === normalizedRoot || normalized.startsWith(`${normalizedRoot}${sep}`); }
function atomicWrite(path: string, bytes: Uint8Array | string): void { mkdirSync(resolve(path,".."),{ recursive: true }); const temporary = `${path}.${process.pid}.tmp`; writeFileSync(temporary,bytes); renameSync(temporary,path); }
function artifact(format: ExportFormat, path: string): ExportArtifact { const bytes = readFileSync(path); if (!bytes.length) throw new Error(`EMPTY_EXPORT_ARTIFACT:${format}`); return { format,path,bytes: bytes.length,sha256: digest(bytes) }; }
function writeAssets(directory: string, assets: ExportAsset[]): void { mkdirSync(directory,{ recursive: true }); for (const asset of assets) atomicWrite(join(directory,asset.filename),asset.bytes); }
export function latexRuntimeAvailable(): boolean { return spawnSync("lualatex",["--version"],{ stdio: "ignore",windowsHide: true }).status === 0; }

export class QuestionBankExportService {
  deliver(assessment: Assessment, answerManifest: AssessmentAnswerManifest, repository: QuestionBankRepository, spec: ExportSpec): ExportDeliveryResult {
    const created = createCanonicalExportPackage(assessment,answerManifest,repository,spec); if ("diagnostics" in created) return { ok: false, diagnostics: created.diagnostics }; const pkg = created.package; const outputRoot = resolve(spec.outputDirectory); mkdirSync(outputRoot,{ recursive: true }); const base = sanitizeExportFilename(spec.filename ?? assessment.title ?? assessment.id); const artifacts: ExportArtifact[] = []; const temp = mkdtempSync(join(tmpdir(),"math-ai-export-"));
    try { writeAssets(join(temp,"assets"),pkg.assets); const pending: Array<{ format: ExportFormat; temporary: string; final: string }> = []; for (const format of spec.formats) { const extensionName = format === "JSON" ? ".json" : format === "LATEX" ? ".tex" : format === "DOCX" ? ".docx" : ".pdf"; const finalPath = join(outputRoot,`${base}${extensionName}`); const temporaryPath = join(temp,`export${extensionName}`); if (!inside(outputRoot,finalPath)) return { ok: false, diagnostics: [{ code: "INVALID_EXPORT_SPEC", message: "Resolved output path escaped the requested directory." }] };
        try { if (format === "JSON") writeFileSync(temporaryPath,serializeJsonPackage(pkg,spec.assetMode)); else if (format === "LATEX") writeFileSync(temporaryPath,renderLatex(pkg)); else if (format === "DOCX") writeFileSync(temporaryPath,renderDocx(pkg)); else { if (!latexRuntimeAvailable()) return { ok: false, diagnostics: [{ code: "LATEX_COMPILE_FAILED", message: "LuaLaTeX is not available for the authoritative PDF path." }] }; const texPath = join(temp,"assessment.tex"); writeFileSync(texPath,renderLatex(pkg),"utf8"); execFileSync("lualatex",["--disable-installer","-interaction=nonstopmode","-halt-on-error","-output-directory",temp,texPath],{ cwd: temp,stdio: "pipe",windowsHide: true }); const generated = join(temp,"assessment.pdf"); if (!existsSync(generated) || !readFileSync(generated).subarray(0,4).equals(Buffer.from("%PDF"))) throw new Error("PDF_SIGNATURE_INVALID"); writeFileSync(temporaryPath,readFileSync(generated)); }
          if (!readFileSync(temporaryPath).length) throw new Error(`EMPTY_EXPORT_ARTIFACT:${format}`); pending.push({ format,temporary: temporaryPath,final: finalPath });
        } catch (error) { const code: ExportDiagnosticCode = format === "DOCX" ? "DOCX_GENERATION_FAILED" : format === "PDF" ? "PDF_GENERATION_FAILED" : format === "LATEX" ? "LATEX_COMPILE_FAILED" : "INVALID_EXPORT_SPEC"; const logPath = join(temp,"assessment.log"); const log = existsSync(logPath) ? readFileSync(logPath,"utf8").slice(-4000) : ""; return { ok: false, diagnostics: [{ code,message: `${error instanceof Error ? error.message : String(error)}${log ? `\n${log}` : ""}` }] }; }
      } for (const item of pending) { atomicWrite(item.final,readFileSync(item.temporary)); artifacts.push(artifact(item.format,item.final)); } if (spec.formats.includes("LATEX")) writeAssets(join(outputRoot,"assets"),pkg.assets); return { ok: true,package: pkg,artifacts };
    } finally { rmSync(temp,{ recursive: true,force: true }); }
  }
}
