import { normalizeBlocks } from "./normalization.js";
import { validateQuestion } from "./schema.js";
import type { ContentBlock, DocumentIR, DocumentQuestionCandidate, FigureAssociation, QuestionObject } from "./types.js";
const textOf = (block: ContentBlock) => block.type === "text" ? block.value : "";
const splitLabels = (blocks: ContentBlock[], pattern: RegExp): Array<{ label: string; content: ContentBlock[] }> => {
  const result: Array<{ label: string; content: ContentBlock[] }> = []; for (const block of blocks) { if (block.type !== "text") { result.at(-1)?.content.push(block); continue; } const matches = [...block.value.matchAll(pattern)]; if (!matches.length) { result.at(-1)?.content.push(block); continue; } matches.forEach((match, i) => result.push({ label: match[1], content: [{ ...block, value: block.value.slice((match.index ?? 0) + match[0].length, matches[i + 1]?.index ?? block.value.length).trim() }] })); } return result.filter((x) => x.content.some((b) => b.type !== "text" || b.value));
};
export function normalizeCandidate(candidate: DocumentQuestionCandidate, document: DocumentIR): QuestionObject {
  const all = normalizeBlocks(candidate.textBlocks.flatMap((block) => block.type === "table" ? block.cells.flat() : [block])); const optionSource = all.filter((block) => block.type === "text" && /(?:^|\s)[A-H][.)]\s/u.test(block.value)); const statementSource = all.filter((block) => block.type === "text" && /(?:^|\s)[a-h][.)]\s/u.test(block.value)); const solutionSource = all.filter((block) => block.type === "text" && /^(?:Lời giải|Hướng dẫn giải)\s*:/iu.test(block.value)); const options = splitLabels(optionSource, /(?:^|\s)([A-H])[.)]\s*/gu); const statements = candidate.questionTypeCandidate === "TRUE_FALSE" ? splitLabels(statementSource, /(?:^|\s)([a-h])[.)]\s*/gu) : [];
  const stem = all.filter((block) => block.type !== "figure" && !optionSource.includes(block) && !statementSource.includes(block) && !solutionSource.includes(block)).map((block) => block.type === "text" ? { ...block, value: block.value.replace(/^(?:(?:Câu|Bài)\s*)?\d+\s*[.:)]\s*/iu, "") } : block).filter((b) => b.type !== "text" || b.value.trim());
  const id = `${document.sourceHash.slice(0, 12)}-q${candidate.questionIndex ?? candidate.id}`; const associations: FigureAssociation[] = candidate.figureAnchors.map((figureId) => ({ figureId, questionId: id, status: "CONFIRMED", confidence: 1, evidence: ["QUESTION_BLOCK_CONTAINMENT", document.figures.find((f) => f.id === figureId)?.tableCell ? "SAME_TABLE_CELL" : "PARAGRAPH_ANCHOR_OWNERSHIP"] }));
  const result: QuestionObject = { id, source: { document: document.sourceDocument, sourceHash: document.sourceHash, blockIds: candidate.rawBlocks.map((b) => b.id), sourceLocations: candidate.sourceLocations }, section: candidate.section, index: candidate.questionIndex, type: candidate.questionTypeCandidate, stem, options: candidate.questionTypeCandidate === "MULTIPLE_CHOICE" ? options : [], trueFalseItems: statements, solution: solutionSource.map((block) => block.type === "text" ? { ...block, value: block.value.replace(/^(?:Lời giải|Hướng dẫn giải)\s*:\s*/iu, "") } : block), subquestions: candidate.questionTypeCandidate === "ESSAY" ? splitLabels(all.filter((block) => !solutionSource.includes(block)), /(?:^|\s)([a-h])[.)]\s*/gu) : [], figures: document.figures.filter((f) => candidate.figureAnchors.includes(f.id)), figureAssociations: associations, metadata: { questionLabel: candidate.questionLabel ?? "UNRESOLVED" }, warnings: [...candidate.parseWarnings], validationStatus: "VALID" };
  const qa = validateQuestion(result); result.warnings.push(...qa.filter((x) => x.level !== "PASS").map((x) => x.code)); result.validationStatus = qa.some((x) => x.level === "FAIL") ? "INVALID" : qa.some((x) => x.level === "WARNING") ? "REVIEW_REQUIRED" : "VALID"; return result;
}
