import type { ContentBlock, DocumentBlock, DocumentIR, DocumentQuestionCandidate, MathNode, QuestionType } from "./types.js";
const textOf = (blocks: ContentBlock[]): string => blocks.map((b) => b.type === "text" ? b.value : b.type === "table" ? b.cells.flat().map((x) => textOf([x])).join(" ") : "").join("");
const question = /^(?:(Câu|Bài)\s*)?(\d+)\s*[.:)]\s*/iu;
const section = /^(PHẦN\s+(?:I|II|III|IV|V)|TRẮC NGHIỆM|ĐÚNG\s*\/\s*SAI|TRẢ LỜI NGẮN|TỰ LUẬN)/iu;
function typeFor(sectionName: string | undefined, content: ContentBlock[]): QuestionType { const value = `${sectionName ?? ""} ${textOf(content)}`; if (/đúng\s*\/\s*sai/iu.test(value)) return "TRUE_FALSE"; if (/trả lời ngắn/iu.test(value)) return "SHORT_ANSWER"; if (/tự luận/iu.test(value)) return "ESSAY"; const labels = [...value.matchAll(/(?:^|\s)([A-H])[.)]\s/gu)].map((x) => x[1]); return new Set(labels).size >= 2 ? "MULTIPLE_CHOICE" : "UNKNOWN"; }
export function segmentQuestions(document: DocumentIR): DocumentQuestionCandidate[] {
  const candidates: DocumentQuestionCandidate[] = []; let current: DocumentBlock[] = [], currentSection: string | undefined, label: string | undefined, index: number | undefined;
  const flush = () => { if (!current.length) return; const flat = current.flatMap((b) => b.content); const math = flat.flatMap((b): MathNode[] => b.type === "math" ? [b.math] : b.type === "table" ? b.cells.flat().flatMap((c) => c.type === "math" ? [c.math] : []) : []); const figures = flat.flatMap((b) => b.type === "figure" ? [b.figureId] : b.type === "table" ? b.cells.flat().flatMap((c) => c.type === "figure" ? [c.figureId] : []) : []); candidates.push({ id: `candidate-${candidates.length + 1}`, questionIndex: index, questionLabel: label, section: currentSection, rawBlocks: current, textBlocks: flat, mathBlocks: math, figureAnchors: figures, questionTypeCandidate: typeFor(currentSection, flat), sourceLocations: current.map((b) => b.sourceLocation), parseWarnings: math.flatMap((m) => m.warnings) }); current = []; };
  for (const block of document.blocks) { const value = textOf(block.content).trim(); const sectionMatch = section.exec(value); if (sectionMatch && (block.kind === "SECTION" || !question.test(value))) { flush(); currentSection = value; continue; } const marker = question.exec(value); const structuralStart = Boolean(marker && (marker[1] || block.boldLabel || block.numbering || (!current.length && Number(marker[2]) === 1))); if (structuralStart) { flush(); label = marker![0].trim(); index = Number(marker![2]); } if (current.length || structuralStart) current.push(block); }
  flush(); return candidates;
}
