import type { ContentBlock, DocumentBlock, DocumentIR, DocumentQuestionCandidate, MathNode, QuestionStartCandidate, QuestionType, BoundaryEvidence, BoundaryConfidence } from "./types.js";
const textOf = (blocks: ContentBlock[]): string => blocks.map((b) => b.type === "text" ? b.value : b.type === "table" ? b.cells.flat().map((x) => textOf([x])).join(" ") : "").join("");
const question = /^(?:(Câu|Bài|Question)\s*)?(\d+)\s*[.:)]\s*/iu;
const section = /^(PHẦN\s+(?:I|II|III|IV|V)|TRẮC NGHIỆM|ĐÚNG\s*\/\s*SAI|TRẢ LỜI NGẮN|TỰ LUẬN)/iu;
const semantic = /^(?:cho|tính|tìm|xác định|chứng minh|giải|hãy|một|trong|tại|người ta|một người|một công ty|một vật)\b/iu;
const answerSolution = /^(?:đáp\s*án|lời\s*giải|hướng\s*dẫn\s*giải|kết\s*quả)\b/iu;
const evidenceFor = (block: DocumentBlock, document: DocumentIR, kind: QuestionStartCandidate["candidateKind"], raw: string, confidence: BoundaryConfidence): QuestionStartCandidate => ({ candidateId: `${block.id}:${kind}`, sourceDocumentId: document.sourceDocumentId ?? document.id ?? document.sourceHash, sourceObjectId: block.id, sourceAnchor: { sourceDocumentId: document.sourceDocumentId ?? document.sourceHash, partName: "word/document.xml", objectIndex: block.order, ...(block.paragraphIndex === undefined ? {} : { paragraphIndex: block.paragraphIndex }) }, documentOrder: block.order, candidateKind: kind, rawEvidence: raw, normalizedEvidence: raw.normalize("NFC").toLocaleLowerCase("vi"), confidence, contradictions: [], qaStatus: confidence === "HIGH_CONFIDENCE" ? "AUTO_ACCEPT" : "REVIEW" });
function typeFor(sectionName: string | undefined, content: ContentBlock[]): QuestionType { const value = `${sectionName ?? ""} ${textOf(content)}`; if (/đúng\s*\/\s*sai/iu.test(value)) return "TRUE_FALSE"; if (/trả lời ngắn/iu.test(value)) return "SHORT_ANSWER"; if (/tự luận/iu.test(value)) return "ESSAY"; const labels = [...value.matchAll(/([A-H])[.)](?:\s|$)/gu)].map((x) => x[1]); return new Set(labels).size >= 2 ? "MULTIPLE_CHOICE" : "UNKNOWN"; }
export function segmentQuestions(document: DocumentIR): DocumentQuestionCandidate[] {
  const candidates: DocumentQuestionCandidate[] = []; let current: DocumentBlock[] = [], currentSection: string | undefined, label: string | undefined, index: number | undefined; let starts: QuestionStartCandidate[] = [];
  const flush = (endEvidence: BoundaryEvidence[] = [{ kind: "DOCUMENT_END", detail: "ordered document sequence ended" }]) => { if (!current.length) return; const flat = current.flatMap((b) => b.content); const math = flat.flatMap((b): MathNode[] => b.type === "math" ? [b.math] : b.type === "table" ? b.cells.flat().flatMap((c) => c.type === "math" ? [c.math] : []) : []); const figures = [...new Set(flat.flatMap((b) => b.type === "figure" ? [b.figureId] : b.type === "table" ? b.cells.flatMap(row => row.flatMap(c => c.type === "figure" ? [c.figureId] : [])) : []))]; const start = current[0], end = current.at(-1)!; const confidence: BoundaryConfidence = starts.some(x => x.confidence === "HIGH_CONFIDENCE") ? "HIGH_CONFIDENCE" : "MEDIUM_CONFIDENCE"; candidates.push({ id: `candidate-${candidates.length + 1}`, questionIndex: index, questionLabel: label, section: currentSection, rawBlocks: current, textBlocks: flat, mathBlocks: math, figureAnchors: figures, questionTypeCandidate: typeFor(currentSection, flat), sourceLocations: current.map((b) => b.sourceLocation), parseWarnings: math.flatMap((m) => m.warnings), startCandidates: starts, semanticRoles: ["QUESTION_STEM"], boundary: { startObjectId: start.id, endObjectId: end.id, startAnchor: starts[0]?.sourceAnchor, endAnchor: { sourceDocumentId: document.sourceDocumentId ?? document.sourceHash, partName: "word/document.xml", objectIndex: end.order }, startEvidence: starts.map(x => ({ kind: x.candidateKind, detail: x.rawEvidence, objectId: x.sourceObjectId })), endEvidence, confidence, contradictions: [], qaStatus: confidence === "HIGH_CONFIDENCE" ? "AUTO_ACCEPT" : "REVIEW" } }); current = []; starts = []; };
  for (const block of document.blocks) { const value = textOf(block.content).trim(); const sectionMatch = section.exec(value); if (sectionMatch && (block.kind === "SECTION" || !question.test(value))) { flush([{ kind: answerSolution.test(value) ? "ANSWER_SOLUTION_TRANSITION" : "SECTION_TRANSITION", detail: value, objectId: block.id }]); currentSection = value; continue; } const marker = question.exec(value); const signals: QuestionStartCandidate[] = []; if (marker) signals.push(evidenceFor(block, document, "TEXTUAL_MARKER", marker[0].trim(), marker[1] ? "HIGH_CONFIDENCE" : "MEDIUM_CONFIDENCE")); if (block.numbering) signals.push(evidenceFor(block, document, "WORD_NUMBERING", block.numbering, "HIGH_CONFIDENCE")); if (semantic.test(value) && value.length >= 12 && (/[?]|\b(?:tính|tìm|giải|chứng minh|xác định)\b/iu.test(value) || block.kind === "TABLE")) signals.push(evidenceFor(block, document, "SEMANTIC_STEM", value.slice(0, 180), "MEDIUM_CONFIDENCE")); if (block.kind === "TABLE") signals.push(evidenceFor(block, document, "TABLE_STRUCTURE", "table contains question-capable content", "MEDIUM_CONFIDENCE")); const start = signals.some(x => x.confidence === "HIGH_CONFIDENCE") || signals.length >= 2; if (start && current.length) flush([{ kind: "NEXT_QUESTION_START", detail: "global sequence transition", objectId: block.id }]); if (start) { starts = signals; label = marker?.[0]?.trim(); index = marker?.[2] ? Number(marker[2]) : undefined; } if (current.length || start) current.push(block); }
  flush(); return candidates;
}
