export const EXAM_QA_ISSUE_CODES = {
  EXAM_STRUCTURE_SECTION_COUNT_MISMATCH: "EXAM_STRUCTURE_SECTION_COUNT_MISMATCH",
  EXAM_STRUCTURE_QUESTION_TYPE_INVALID: "EXAM_STRUCTURE_QUESTION_TYPE_INVALID",
  QUESTION_ID_MISSING: "QUESTION_ID_MISSING",
  QUESTION_TYPE_UNKNOWN: "QUESTION_TYPE_UNKNOWN",
  QUESTION_NUMBER_DUPLICATE: "QUESTION_NUMBER_DUPLICATE",
  QUESTION_NUMBER_INVALID: "QUESTION_NUMBER_INVALID",
  QUESTION_MISSING_STEM: "QUESTION_MISSING_STEM",
  MCQ_OPTION_COUNT_INVALID: "MCQ_OPTION_COUNT_INVALID",
  MCQ_OPTION_KEY_DUPLICATE: "MCQ_OPTION_KEY_DUPLICATE",
  MCQ_NO_EXPECTED_ANSWER: "MCQ_NO_EXPECTED_ANSWER",
  MCQ_MULTIPLE_EXPECTED_ANSWERS: "MCQ_MULTIPLE_EXPECTED_ANSWERS",
  MCQ_EXPECTED_ANSWER_NOT_FOUND: "MCQ_EXPECTED_ANSWER_NOT_FOUND",
  TRUE_FALSE_STATEMENT_COUNT_INVALID: "TRUE_FALSE_STATEMENT_COUNT_INVALID",
  TRUE_FALSE_STATEMENT_INVALID: "TRUE_FALSE_STATEMENT_INVALID",
  SHORT_ANSWER_FORMAT_INVALID: "SHORT_ANSWER_FORMAT_INVALID",
  UNDEFINED_SYMBOL_REFERENCE: "UNDEFINED_SYMBOL_REFERENCE",
  MATH_PARSE_WARNING: "MATH_PARSE_WARNING",
  LANGUAGE_REVIEW_REQUIRED: "LANGUAGE_REVIEW_REQUIRED",
  MARKER_UNSUPPORTED_TYPE: "MARKER_UNSUPPORTED_TYPE",
  REQUIRED_VALIDATOR_NOT_TESTED: "REQUIRED_VALIDATOR_NOT_TESTED",
} as const;

export type ExamQAIssueCode = (typeof EXAM_QA_ISSUE_CODES)[keyof typeof EXAM_QA_ISSUE_CODES];

