import {useEffect,useMemo,useState,type PointerEvent as ReactPointerEvent} from "react";
import {createMathScene,type MathEntity} from "../../modules/math-ir/index.js";
import {WORKSPACE_TOOL_REGISTRY,acceptToolInput,createDynamicMathWorkspace,executeContextAction,executeWorkspaceCommand,handleWorkspaceKey,inspectWorkspaceObject,pickSemanticObject,redoWorkspace,selectObjects,serializeWorkspace,setActiveTool,setWorkspaceInspectorTab,setWorkspaceMode,undoWorkspace,type DynamicMathWorkspace} from "../../modules/dynamic-workspace/index.js";
import type {Vec2} from "../../modules/dynamic-geometry/index.js";
import {executeMathIntent,routeRuntime,type PlanDiagnostics} from "../../modules/intelligent-math-runtime/index.js";

const STORAGE_KEY="math-ai-studio:dynamic-workspace:v1";
const initial=()=>createDynamicMathWorkspace(createMathScene({id:"mv3-browser",name:"Universal Dynamic Math Workspace",dimension:"2d",entities:[],constraints:[]}));
const coordinate=(entity:MathEntity):Vec2|undefined=>entity.semanticCoordinate?.dimension==="2d"?[entity.semanticCoordinate.x,entity.semanticCoordinate.y]:undefined;
const screen=(point:Vec2):Vec2=>[400+point[0]*40,300-point[1]*40];
const world=(event:ReactPointerEvent<SVGSVGElement>):Vec2=>{const box=event.currentTarget.getBoundingClientRect();return[(event.clientX-box.left-box.width/2)/(box.width/20),(box.height/2-(event.clientY-box.top))/(box.height/20)];};

export default function DynamicMathWorkspacePanel(){
 const[workspace,setWorkspace]=useState<DynamicMathWorkspace>(initial),[exportKind,setExportKind]=useState("studio"),[mv4Diagnostics,setMv4Diagnostics]=useState<PlanDiagnostics>();
 const selected=workspace.view.selection[0],inspected=selected?inspectWorkspaceObject(workspace,selected):undefined;
 const entities=workspace.session.scene.entities,byId=useMemo(()=>new Map(entities.map(entity=>[entity.id,entity])),[entities]);
 const apply=(next:ReturnType<typeof executeWorkspaceCommand>)=>setWorkspace(next.workspace);
 useEffect(()=>{const listener=(event:KeyboardEvent)=>{if((event.target as HTMLElement)?.matches("input,textarea,select"))return;const next=handleWorkspaceKey(workspace,event.key,event);if(next.status==="PASS"){event.preventDefault();setWorkspace(next.workspace);}};window.addEventListener("keydown",listener);return()=>window.removeEventListener("keydown",listener);},[workspace]);
 const canvasClick=(event:ReactPointerEvent<SVGSVGElement>)=>{const point=world(event);if(workspace.view.activeToolId==="CREATE_FREE_POINT")apply(executeWorkspaceCommand(workspace,{id:"CREATE_FREE_POINT",parameters:{position:point}}));else if(workspace.view.activeToolId==="SELECT")setWorkspace(selectObjects(workspace,[],"CLEAR"));};
 const entityClick=(event:ReactPointerEvent,entity:MathEntity)=>{event.stopPropagation();if(workspace.view.activeToolId==="SELECT")setWorkspace(pickSemanticObject(workspace,{semanticObjectId:entity.id}));else apply(acceptToolInput(workspace,entity.id));};
 const rename=()=>{if(!selected)return;const value=window.prompt("Object name",inspected?.label??"");if(value)apply(executeContextAction(workspace,"RENAME_OBJECT",{label:value}));};
 const persist=()=>{localStorage.setItem(STORAGE_KEY,serializeWorkspace(workspace));setWorkspace({...workspace,view:{...workspace.view,message:"Workspace saved"}});};
 const loadMv4Fixture=()=>{let next=executeWorkspaceCommand(initial(),{id:"CREATE_FREE_POINT",parameters:{position:[-3,0]}}).workspace;next=executeWorkspaceCommand(next,{id:"CREATE_FREE_POINT",parameters:{position:[3,0]}}).workspace;setWorkspace(next);setMv4Diagnostics(undefined);};
 const runMv4Midpoint=()=>{const executed=executeMathIntent(workspace.session.scene,{intentId:"browser-midpoint",type:"CREATE_OBJECT",operation:"MIDPOINT",targets:["A","B"]});setMv4Diagnostics(executed.diagnostics);if(executed.status==="PASS")setWorkspace(createDynamicMathWorkspace(executed.scene,{...workspace.view,message:"MV-4 midpoint plan: PASS"}));};
 const runMv4Ambiguous=()=>{const executed=executeMathIntent(workspace.session.scene,{intentId:"browser-ambiguous",type:"CREATE_OBJECT",operation:"PARALLEL_LINE",targets:[]});setMv4Diagnostics(executed.diagnostics);setWorkspace({...workspace,view:{...workspace.view,message:executed.issues[0]?.code??"MV-4 intent rejected"}});};
 const moveMv4A=()=>{const point=workspace.session.scene.entities.find(entity=>entity.label==="A");if(point)apply(executeWorkspaceCommand(workspace,{id:"MOVE_POINT",inputIds:[point.id],parameters:{position:[-1,2]}}));};
 const categories=[...new Set(WORKSPACE_TOOL_REGISTRY.map(tool=>tool.category))];
 return <main data-mv3-workspace style={{height:"100vh",display:"grid",gridTemplateRows:"auto 1fr auto",background:"#07111f",color:"#e5eefb",fontFamily:"Inter,system-ui,sans-serif"}}>
  <header style={{display:"flex",alignItems:"center",gap:12,padding:"10px 16px",borderBottom:"1px solid #29405f",background:"#0c1b2d"}}><strong>Universal Dynamic Math Workspace</strong><span data-workspace-status style={{color:"#7dd3fc"}}>{workspace.view.message}</span><span style={{marginLeft:"auto"}}>Math ownership: MV-0 · Renderer math: none</span></header>
  <section style={{display:"grid",gridTemplateColumns:"230px minmax(420px,1fr) 290px",minHeight:0}}>
   <nav aria-label="Workspace tools" style={{overflow:"auto",padding:12,borderRight:"1px solid #29405f"}}>{categories.map(category=><section key={category}><h2 style={{fontSize:11,color:"#94a3b8",letterSpacing:1}}>{category}</h2><div style={{display:"grid",gridTemplateColumns:"1fr 1fr",gap:6}}>{WORKSPACE_TOOL_REGISTRY.filter(tool=>tool.category===category).map(tool=><button key={tool.id} aria-pressed={workspace.view.activeToolId===tool.id} disabled={tool.dimension==="3d"&&workspace.view.mode==="2D"} onClick={()=>apply(setActiveTool(workspace,tool.id))} title={tool.helpKey} style={{padding:7,border:"1px solid #36516f",borderRadius:5,background:workspace.view.activeToolId===tool.id?"#0369a1":"#10233a",color:"white",fontSize:11}}>{tool.label}</button>)}</div></section>)}</nav>
   <section style={{display:"grid",gridTemplateRows:"auto 1fr",minWidth:0}}><div style={{padding:8,display:"flex",gap:6,borderBottom:"1px solid #29405f"}}><button onClick={()=>setWorkspace(undoWorkspace(workspace))}>Undo</button><button onClick={()=>setWorkspace(redoWorkspace(workspace))}>Redo</button>{(["2D","3D","LINKED","FOLD"] as const).map(mode=><button key={mode} aria-pressed={workspace.view.mode===mode} onClick={()=>setWorkspace(setWorkspaceMode(workspace,mode))}>{mode}</button>)}<button style={{marginLeft:"auto"}} onClick={persist}>Save</button></div>
    <svg aria-label="Dynamic math canvas" viewBox="0 0 800 600" onPointerDown={canvasClick} style={{width:"100%",height:"100%",background:"#f8fafc",touchAction:"none"}}><defs><pattern id="mv3-grid" width="40" height="40" patternUnits="userSpaceOnUse"><path d="M 40 0 L 0 0 0 40" fill="none" stroke="#dbeafe" strokeWidth="1"/></pattern></defs><rect width="800" height="600" fill="url(#mv3-grid)"/><path d="M0 300H800M400 0V600" stroke="#94a3b8"/>
    {entities.filter(entity=>entity.type==="line"||entity.type==="segment"||entity.type==="ray").map(entity=>{const ids=entity.type==="line"?entity.pointIds:entity.type==="segment"?[entity.startPointId,entity.endPointId]:[entity.startPointId,entity.throughPointId],a=coordinate(byId.get(ids[0])!),b=coordinate(byId.get(ids[1])!);if(!a||!b)return null;const[x1,y1]=screen(a),[x2,y2]=screen(b);return <line key={entity.id} data-semantic-id={entity.id} x1={x1} y1={y1} x2={x2} y2={y2} stroke="#0f4c81" strokeWidth="3" onPointerDown={event=>entityClick(event,entity)}/>;})}
    {entities.filter(entity=>entity.type==="point").map(entity=>{const p=coordinate(entity);if(!p)return null;const[x,y]=screen(p),active=workspace.view.selection.includes(entity.id);return <g key={entity.id} data-semantic-id={entity.id} onPointerDown={event=>entityClick(event,entity)}><circle cx={x} cy={y} r={active?8:6} fill={active?"#f97316":"#0284c7"}/><text x={x+10} y={y-10} fill="#0f172a" fontSize="16">{entity.label}</text></g>;})}</svg>
   </section>
   <aside data-workspace-inspector style={{overflow:"auto",padding:12,borderLeft:"1px solid #29405f",background:"#0c1b2d"}}><div role="tablist" style={{display:"flex",flexWrap:"wrap",gap:4}}>{(["PROPERTIES","DEPENDENCIES","CONSTRAINTS","EXPORT"] as const).map(tab=><button key={tab} role="tab" aria-selected={workspace.view.activeInspectorTab===tab} onClick={()=>setWorkspace(setWorkspaceInspectorTab(workspace,tab))}>{tab}</button>)}</div>
   {workspace.view.activeInspectorTab==="PROPERTIES"&&<section><h2>Properties</h2>{inspected?<><p data-selected-object>{inspected.label??inspected.id} · {inspected.type}</p><p>Freedom: {inspected.freedom}</p><p>DOF: {inspected.dof.classification} ({inspected.dof.positionalDof})</p><button onClick={rename}>Rename</button> <button onClick={()=>apply(executeContextAction(workspace,"SET_VISIBILITY",{visible:!inspected.visible}))}>{inspected.visible?"Hide":"Show"}</button> <button onClick={()=>apply(executeContextAction(workspace,"DELETE_OBJECT"))}>Delete</button></>:<p>Select a semantic object.</p>}</section>}
   {workspace.view.activeInspectorTab==="DEPENDENCIES"&&<section><h2>Dependency Inspector</h2><p>Parents: {inspected?.parents.join(", ")||"none"}</p><p>Children: {inspected?.children.join(", ")||"none"}</p></section>}
   {workspace.view.activeInspectorTab==="CONSTRAINTS"&&<section><h2>Constraint Editor</h2><p>{inspected?.constraints.length??0} linked constraints</p><p>Diagnostics: {workspace.view.lastDiagnostics.map(x=>`${x.constraintId}:${x.status}`).join(", ")||"none"}</p></section>}
   {workspace.view.activeInspectorTab==="EXPORT"&&<section><h2>Workspace Adapters</h2><select value={exportKind} onChange={event=>setExportKind(event.target.value)}>{["studio","three","geogebra","luadraw","manim"].map(kind=><option key={kind}>{kind}</option>)}</select><p>Adapter: {exportKind}</p><p>Renderer owns math: false</p></section>}
   <hr/><section data-mv4-intelligent-construction><h2>MV-4 Intelligent Construction</h2><p><button onClick={loadMv4Fixture}>Load MV-4 Fixture</button> <button onClick={runMv4Midpoint}>Run Midpoint Intent</button> <button onClick={moveMv4A}>Move A</button> <button onClick={runMv4Ambiguous}>Test Ambiguous Intent</button></p><p>Runtime route: {routeRuntime({capability:workspace.view.mode==="3D"?"interactive_3d":"interactive_2d"}).bridge?.bridgeId??"none"}</p><p data-mv4-plan-status>{mv4Diagnostics?.failureReason?.code??(mv4Diagnostics?.semanticResult?"PLAN_EXECUTED":"Ready")}</p><details><summary>Planner diagnostics</summary><pre style={{whiteSpace:"pre-wrap",fontSize:10}}>{mv4Diagnostics?JSON.stringify({intent:mv4Diagnostics.normalizedIntent,plan:mv4Diagnostics.plan,commands:mv4Diagnostics.commandsExecuted,result:mv4Diagnostics.semanticResult,failure:mv4Diagnostics.failureReason},null,2):"No plan executed"}</pre></details></section><hr/><h2>Objects</h2><ul>{entities.map(entity=><li key={entity.id}><button onClick={()=>setWorkspace(selectObjects(workspace,[entity.id]))}>{entity.label??entity.id} · {entity.type}</button></li>)}</ul></aside>
  </section><footer style={{padding:"7px 16px",borderTop:"1px solid #29405f"}}>Selection: {workspace.view.selection.join(", ")||"none"} · Tool: {workspace.view.activeToolId} · Mode: {workspace.view.mode}</footer>
 </main>;
}
