import { useMemo, useState } from "react";
import type { MouseEvent as ReactMouseEvent } from "react";
import { createMathScene } from "../../modules/math-ir/index.js";
import { applySessionCommand, createConstructionSession, eligibleTools, inferSnaps, redoSession, rendererSnapshot, undoSession, type ConstructionCommandId } from "../../modules/dynamic-geometry/index.js";
import { analyzeDegreesOfFreedom, createRenderSnapshot } from "../../modules/constraint-orchestration/index.js";

export default function DynamicGeometryDevPanel({onExit}:{onExit:()=>void}){
  const[session,setSession]=useState(()=>createConstructionSession(createMathScene({id:"dynamic-geometry-dev",name:"MV-1 Developer Surface",dimension:"2d",entities:[],constraints:[]}))),[message,setMessage]=useState("Click the canvas to create free points."),[selected,setSelected]=useState<string[]>([]);
  const snapshot=useMemo(()=>rendererSnapshot(session.scene),[session.scene]),renderSnapshot=useMemo(()=>createRenderSnapshot(session.scene),[session.scene]),tools=eligibleTools(session.scene,selected),inspected=selected[0]?analyzeDegreesOfFreedom(session.scene,selected[0]):undefined;
  const command=(id:ConstructionCommandId,inputIds=selected,parameters?:Record<string,unknown>)=>{const applied=applySessionCommand(session,{id,inputIds,parameters});if(applied.result.status==="PASS"){setSession(applied.session);setSelected(applied.result.createdIds.length?applied.result.createdIds.slice(-2):inputIds);setMessage(`${id}: ${applied.result.createdIds.join(", ")||"updated"}`);}else setMessage(`${applied.result.issues[0].code}: ${applied.result.issues[0].message}`);};
  const point=(event:ReactMouseEvent<SVGSVGElement>)=>{const box=event.currentTarget.getBoundingClientRect(),position:[number,number]=[(event.clientX-box.left)/box.width*20-10,10-(event.clientY-box.top)/box.height*20],snap=inferSnaps(session.scene,position,.35)[0];command("CREATE_FREE_POINT",[],{position:snap?.position??position});};
  const selectedPoint=selected.length===1&&session.scene.entities.find(x=>x.id===selected[0])?.type==="point";
  return <main style={{minHeight:"100vh",padding:20,background:"#101b3d",color:"white",fontFamily:"system-ui"}} data-mv1-dev-surface>
    <h1>MV-1 Dynamic Geometry — Developer Surface</h1><button onClick={onExit}>Back to Fold</button>
    <div style={{display:"grid",gridTemplateColumns:"minmax(0,1fr) 340px",gap:16,marginTop:12}}>
      <svg aria-label="Dynamic geometry canvas" viewBox="-10 -10 20 20" onClick={point} style={{width:"100%",height:650,background:"#172554",border:"1px solid #4f6694"}}>
        {session.scene.entities.map(item=>{if(item.type==="point"&&item.semanticCoordinate?.dimension==="2d")return <g key={item.id} data-semantic-id={item.id} onClick={event=>{event.stopPropagation();setSelected(current=>event.shiftKey?[...new Set([...current,item.id])]:[item.id]);}}><circle cx={item.semanticCoordinate.x} cy={-item.semanticCoordinate.y} r={selected.includes(item.id)?.18:.12} fill={selected.includes(item.id)?"#ffe45e":"white"}/><text x={item.semanticCoordinate.x+.2} y={-item.semanticCoordinate.y-.2} fontSize=".45" fill="white">{item.label}</text></g>;if(item.type==="line"||item.type==="ray"||item.type==="segment"){const ids=item.type==="line"?item.pointIds:item.type==="ray"?[item.startPointId,item.throughPointId]:[item.startPointId,item.endPointId],points=ids.map(id=>session.scene.entities.find(x=>x.id===id)?.semanticCoordinate).filter(x=>x?.dimension==="2d");if(points.length!==2)return null;const[a,b]=points as Array<{dimension:"2d";x:number;y:number}>,dx=b.x-a.x,dy=b.y-a.y,k=item.type==="segment"?1:20,start=item.type==="line"?{x:a.x-dx*k,y:a.y-dy*k}:a,end={x:a.x+dx*k,y:a.y+dy*k};return <line key={item.id} data-semantic-id={item.id} x1={start.x} y1={-start.y} x2={end.x} y2={-end.y} stroke={selected.includes(item.id)?"#ffe45e":"#4de3ff"} strokeWidth=".06" onClick={event=>{event.stopPropagation();setSelected(current=>event.shiftKey?[...new Set([...current,item.id])]:[item.id]);}}/>;}if(item.type==="circle"){const center=session.scene.entities.find(x=>x.id===item.centerPointId)?.semanticCoordinate,radius=Number(item.metadata?.adapterMetadata?.construction&&((item.metadata.adapterMetadata.construction as Record<string,unknown>).parameters as Record<string,unknown>)?.radius);return center?.dimension==="2d"?<circle key={item.id} data-semantic-id={item.id} cx={center.x} cy={-center.y} r={radius} fill="none" stroke="#6ee7a8" strokeWidth=".06"/>:null;}return null;})}
      </svg>
      <aside style={{background:"#172554",padding:14}}><strong>CONSTRUCTION COMMANDS</strong><p>Shift-click to multi-select inputs in order.</p>
        <p>{(["CREATE_LINE","CREATE_RAY","CREATE_SEGMENT","CREATE_MIDPOINT","CREATE_CIRCLE_CENTER_POINT","CREATE_POLYGON","CREATE_INTERSECTION","CREATE_PROJECTION","CREATE_PARALLEL_LINE","CREATE_PERPENDICULAR_LINE"] as ConstructionCommandId[]).map(id=><button key={id} disabled={!tools.find(x=>x.id===id)?.available} title={tools.find(x=>x.id===id)?.reason} onClick={()=>command(id)}>{id.replaceAll("_"," ")}</button>)}</p>
        <button disabled={!selectedPoint} onClick={()=>{const point=session.scene.entities.find(x=>x.id===selected[0])?.semanticCoordinate;if(point?.dimension==="2d")command("MOVE_POINT",selected,{position:[point.x+1,point.y+1]});}}>Move +1,+1</button> <button disabled={!selectedPoint} onClick={()=>command("TRANSLATE_OBJECT",selected,{vector:[1,1]})}>Translate +1,+1</button> <button disabled={!selectedPoint} onClick={()=>command("ROTATE_OBJECT",selected,{center:[0,0],angle:Math.PI/2})}>Rotate 90°</button> <button disabled={!selectedPoint} onClick={()=>command("REFLECT_OBJECT",selected,{axisA:[0,-1],axisB:[0,1]})}>Reflect Y</button> <button disabled={!selectedPoint} onClick={()=>command("SCALE_OBJECT",selected,{center:[0,0],factor:2})}>Scale ×2</button>
        <p><button disabled={!selectedPoint} onClick={()=>command("CREATE_SEGMENT",[selected[0],selected[0]])}>Try Invalid Segment</button></p>
        <p><button disabled={!selected.length} onClick={()=>command("RENAME_OBJECT",[selected[0]],{label:prompt("Label")??""})}>Rename</button> <button disabled={!selected.length} onClick={()=>command("SET_VISIBILITY",[selected[0]],{visible:false})}>Hide</button> <button disabled={!selected.length} onClick={()=>command("DELETE_OBJECT",[selected[0]],{cascade:true})}>Delete</button></p>
        <p><button disabled={!session.history.length} onClick={()=>setSession(undoSession(session))}>Undo</button> <button disabled={!session.future.length} onClick={()=>setSession(redoSession(session))}>Redo</button></p>
        <p role="status">{message}</p><section data-mv2-constraint-inspector><strong>CONSTRAINT INSPECTOR</strong><p>Selected: {selected[0]??"none"}<br/>Degrees of freedom: {inspected?.classification??"none"}<br/>Positional DOF: {inspected?.positionalDof??"—"}<br/>Active constraints: {inspected?.constraintIds.join(", ")||"none"}</p><pre style={{whiteSpace:"pre-wrap"}} data-semantic-update>{JSON.stringify({createdIds:renderSnapshot.createdIds,updatedIds:renderSnapshot.updatedIds,removedIds:renderSnapshot.removedIds,lastSemanticUpdate:session.scene.semantics?.events?.at(-1)??null},null,2)}</pre></section><details><summary>Semantic objects</summary><pre style={{whiteSpace:"pre-wrap"}}>{JSON.stringify(snapshot,null,2)}</pre></details>
      </aside>
    </div>
  </main>;
}
