import { useEffect, useMemo, useRef, useState } from "react";
import * as THREE from "three";
import { OrbitControls } from "three/examples/jsm/controls/OrbitControls.js";
import { FOLD_FIXTURES, createDevelopableFoldScene, createFoldScene, createNGonalSolidScene, updateDevelopableFoldScene, updateFoldScene } from "../../modules/fold-3d/index.js";
import type { DevelopableFoldScene, FoldScene } from "../../modules/fold-3d/index.js";
import { createDevelopableThreeMapping } from "../../modules/fold-3d/developable-three-adapter.js";
import { createFoldThreeMapping, setFoldFaceHighlighted } from "../../modules/fold-3d/three-viewer-adapter.js";

type FixtureName=keyof typeof FOLD_FIXTURES;
type ViewerSolid=FixtureName|"nGonalPrism"|"nGonalPyramid"|"cylinder"|"cone"|"conicalFrustum";
type ViewerMapping=ReturnType<typeof createFoldThreeMapping>|ReturnType<typeof createDevelopableThreeMapping>;
const choices:Array<[ViewerSolid,string]>=[["cube","Cube"],["rectangularPrism","Rectangular prism 2×3×5"],["triangularPrism","Triangular prism (legacy)"],["tetrahedron","Tetrahedron"],["squarePyramid","Square pyramid (legacy)"],["nGonalPrism","Prism"],["nGonalPyramid","Pyramid"],["cylinder","Cylinder r=2, h=5"],["cone","Cone r=3, h=4"],["conicalFrustum","Conical frustum R=4, r=2, h=3"]];
const isCurved=(scene:FoldScene|DevelopableFoldScene):scene is DevelopableFoldScene=>"model" in scene.metadata&&scene.metadata.model==="developable";

export default function Fold3DViewer(){
  const[solid,setSolid]=useState<ViewerSolid>("cube"),[baseSides,setBaseSides]=useState(5),[progress,setProgress]=useState(0),[edges,setEdges]=useState(true),[showSeam,setShowSeam]=useState(true),[selectedId,setSelectedId]=useState<string>();
  const host=useRef<HTMLDivElement>(null),resetCamera=useRef<()=>void>(()=>{}),mappingRef=useRef<ViewerMapping>();
  const sceneModel=useMemo<FoldScene|DevelopableFoldScene>(()=>{
    if(solid==="cylinder")return createDevelopableFoldScene({solidType:"cylinder",radius:2,height:5},0).value!;
    if(solid==="cone")return createDevelopableFoldScene({solidType:"cone",radius:3,height:4},0).value!;
    if(solid==="conicalFrustum")return createDevelopableFoldScene({solidType:"conical_frustum",largeRadius:4,smallRadius:2,height:3},0).value!;
    const source=solid==="nGonalPrism"||solid==="nGonalPyramid"?createNGonalSolidScene({kind:solid==="nGonalPrism"?"prism":"pyramid",baseSides}).value!:FOLD_FIXTURES[solid];return createFoldScene(source,0).value!;
  },[solid,baseSides]);

  useEffect(()=>{const container=host.current;if(!container)return;const scene=new THREE.Scene();scene.background=new THREE.Color(0xf8fafc);const camera=new THREE.PerspectiveCamera(45,1,.01,1000),renderer=new THREE.WebGLRenderer({antialias:true});renderer.setPixelRatio(Math.min(window.devicePixelRatio,2));container.appendChild(renderer.domElement);const controls=new OrbitControls(camera,renderer.domElement);controls.enableDamping=true;controls.minDistance=2;controls.maxDistance=80;
    const mapping:ViewerMapping=isCurved(sceneModel)?createDevelopableThreeMapping(sceneModel):createFoldThreeMapping(sceneModel);mappingRef.current=mapping;scene.add(mapping.group);scene.add(new THREE.HemisphereLight(0xffffff,0x334155,2.1));const light=new THREE.DirectionalLight(0xffffff,2.2);light.position.set(5,8,7);scene.add(light);
    const reset=()=>{const box=new THREE.Box3().setFromObject(mapping.group),center=box.getCenter(new THREE.Vector3()),size=Math.max(box.getSize(new THREE.Vector3()).length(),2);controls.target.copy(center);camera.position.set(center.x+size,center.y+size*.8,center.z+size*1.2);camera.near=size/100;camera.far=size*100;camera.updateProjectionMatrix();controls.update();};resetCamera.current=reset;reset();
    const resize=()=>{const width=Math.max(container.clientWidth,1),height=Math.max(container.clientHeight,1);renderer.setSize(width,height,false);camera.aspect=width/height;camera.updateProjectionMatrix();};const observer=new ResizeObserver(resize);observer.observe(container);resize();const raycaster=new THREE.Raycaster(),pointer=new THREE.Vector2();const targets="meshes" in mapping?[...mapping.meshes.values()]:[...mapping.components.values()].filter(item=>item instanceof THREE.Mesh);const click=(event:MouseEvent)=>{const rect=renderer.domElement.getBoundingClientRect();pointer.set(((event.clientX-rect.left)/rect.width)*2-1,-((event.clientY-rect.top)/rect.height)*2+1);raycaster.setFromCamera(pointer,camera);const hit=raycaster.intersectObjects(targets,false)[0],id=hit&&(hit.object.userData.faceId||hit.object.userData.surfaceId) as string|undefined;setSelectedId(id);if("meshes" in mapping)setFoldFaceHighlighted(mapping,id);};renderer.domElement.addEventListener("click",click);
    let frame=0,active=true;const animate=()=>{if(!active)return;controls.update();renderer.render(scene,camera);frame=requestAnimationFrame(animate);};animate();return()=>{active=false;cancelAnimationFrame(frame);observer.disconnect();renderer.domElement.removeEventListener("click",click);controls.dispose();mapping.dispose();renderer.dispose();renderer.forceContextLoss();renderer.domElement.remove();mappingRef.current=undefined;};
  },[sceneModel]);
  useEffect(()=>{const mapping=mappingRef.current;if(!mapping)return;if(isCurved(sceneModel)){const next=updateDevelopableFoldScene(sceneModel,progress);if(next.value&&"components" in mapping)mapping.apply(next.value);}else{const next=updateFoldScene(sceneModel,progress);if(next.value&&"faces" in mapping)mapping.apply(next.value);}},[sceneModel,progress]);
  useEffect(()=>{const mapping=mappingRef.current;if(!mapping)return;if("setEdgesVisible" in mapping)mapping.setEdgesVisible(edges);if("setSeamVisible" in mapping)mapping.setSeamVisible(showSeam);},[edges,showSeam,sceneModel]);
  const curved=isCurved(sceneModel),dimensions=curved?Object.entries(sceneModel.dimensions).map(([key,value])=>`${key}=${Number(value.toFixed(4))}`).join(", "):"";
  return <main style={{minHeight:"100vh",padding:20,background:"#e2e8f0",color:"#0f172a",fontFamily:"system-ui"}}><h1 style={{margin:"0 0 12px"}}>Fold 3D Viewer — Developer Smoke Test</h1><div style={{display:"grid",gridTemplateColumns:"minmax(0, 1fr) 300px",gap:16}}><div ref={host} style={{minHeight:620,border:"1px solid #94a3b8",borderRadius:8,overflow:"hidden",background:"#f8fafc"}}/><aside style={{background:"white",padding:16,borderRadius:8}}>
    <label>Solid<br/><select value={solid} onChange={event=>{setSolid(event.target.value as ViewerSolid);setProgress(0);setSelectedId(undefined);}} style={{width:"100%"}}>{choices.map(([value,label])=><option key={value} value={value}>{label}</option>)}</select></label>
    {(solid==="nGonalPrism"||solid==="nGonalPyramid")&&<p><label>Base sides<br/><select value={baseSides} onChange={event=>{setBaseSides(Number(event.target.value));setProgress(0);setSelectedId(undefined);}} style={{width:"100%"}}>{Array.from({length:8},(_,index)=>index+3).map(value=><option key={value} value={value}>{value}</option>)}</select></label></p>}
    <p><label>Fold progress: <strong>{Math.round(progress*100)}%</strong><input aria-label="Fold progress" type="range" min="0" max="1" step="0.01" value={progress} onChange={event=>setProgress(Number(event.target.value))} style={{width:"100%"}}/></label></p><div style={{display:"flex",justifyContent:"space-between",fontSize:12}}><span>0%</span><span>25%</span><span>50%</span><span>75%</span><span>100%</span></div>
    {!curved&&<p><label><input type="checkbox" checked={edges} onChange={event=>setEdges(event.target.checked)}/> Show Edges</label></p>}{curved&&<p><label><input type="checkbox" checked={showSeam} onChange={event=>setShowSeam(event.target.checked)}/> Show Seam</label></p>}<button type="button" onClick={()=>resetCamera.current()}>Reset Camera</button><hr/><div><strong>FoldScene debug</strong>{curved?<p>Type: {sceneModel.solidType}<br/>Model: developable<br/>Progress: {Math.round(progress*100)}%<br/>Surface: {sceneModel.lateralSurfaceId}<br/>Net primitives: {sceneModel.net.primitives.length}<br/>Dimensions: {dimensions}<br/>Selected Surface: {selectedId??"none"}</p>:<p>Type: {sceneModel.solidType}<br/>Base Sides: {sceneModel.topology.metadata.baseSides??"n/a"}<br/>Progress: {Math.round(progress*100)}%<br/>Root Face: {sceneModel.net.rootFaceId}<br/>Vertices: {sceneModel.topology.vertices.length}<br/>Edges: {sceneModel.topology.edges.length}<br/>Faces: {sceneModel.topology.faces.length}<br/>Hinges: {sceneModel.net.hinges.length}<br/>Selected Face: {selectedId??"none"}</p>}</div><small>Drag to orbit. Scroll or pinch to zoom. Curved GPU triangles are visual-only tessellation.</small>
  </aside></div></main>;
}
