import { useEffect, useMemo, useRef, useState } from "react";
import * as THREE from "three";
import { OrbitControls } from "three/examples/jsm/controls/OrbitControls.js";
import { createPatternFoldScene, createPatternThreeMapping, PATTERN_FOLD_FIXTURES, updatePatternFoldScene } from "../../modules/pattern-fold/index.js";

export default function PatternFoldViewerPanel({onExit}:{onExit:()=>void}){
 const[fixture,setFixture]=useState("P01"),[progress,setProgress]=useState(0),[step,setStep]=useState(0),[showCuts,setShowCuts]=useState(true),[showCreases,setShowCreases]=useState(true),[showRegions,setShowRegions]=useState(true);const host=useRef<HTMLDivElement>(null),mappingRef=useRef<ReturnType<typeof createPatternThreeMapping>>();
 const model=useMemo(()=>createPatternFoldScene(PATTERN_FOLD_FIXTURES[fixture],0).value!,[fixture]);
 useEffect(()=>{const container=host.current;if(!container)return;const scene=new THREE.Scene();scene.background=new THREE.Color(0xf8fafc);const camera=new THREE.PerspectiveCamera(45,1,.01,1000),renderer=new THREE.WebGLRenderer({antialias:true});container.appendChild(renderer.domElement);const controls=new OrbitControls(camera,renderer.domElement);controls.enableDamping=true;const mapping=createPatternThreeMapping(model);mappingRef.current=mapping;scene.add(mapping.group,new THREE.HemisphereLight(0xffffff,0x334155,2));const lines=new THREE.Group();lines.name="pattern-guides";for(const cut of model.sheet.cuts){const geometry=new THREE.BufferGeometry().setFromPoints(cut.points.map(p=>new THREE.Vector3(p[0],p[1],.015))),line=new THREE.Line(geometry,new THREE.LineBasicMaterial({color:0xdc2626}));line.userData.kind="cut";lines.add(line);}for(const crease of model.sheet.creases){const geometry=new THREE.BufferGeometry().setFromPoints(crease.points.map(p=>new THREE.Vector3(p[0],p[1],.02))),line=new THREE.Line(geometry,new THREE.LineDashedMaterial({color:crease.assignment==="MOUNTAIN"?0x7c3aed:0x0284c7,dashSize:.12,gapSize:.08}));line.computeLineDistances();line.userData.kind="crease";lines.add(line);}scene.add(lines);camera.position.set(7,7,8);controls.target.set(0,0,0);controls.update();const resize=()=>{renderer.setSize(Math.max(container.clientWidth,1),Math.max(container.clientHeight,1),false);camera.aspect=Math.max(container.clientWidth,1)/Math.max(container.clientHeight,1);camera.updateProjectionMatrix();};const observer=new ResizeObserver(resize);observer.observe(container);resize();let frame=0,active=true;const animate=()=>{if(!active)return;controls.update();renderer.render(scene,camera);frame=requestAnimationFrame(animate);};animate();return()=>{active=false;cancelAnimationFrame(frame);observer.disconnect();controls.dispose();mapping.dispose();lines.traverse(x=>{const object=x as THREE.Line;object.geometry?.dispose();(object.material as THREE.Material|undefined)?.dispose();});renderer.dispose();renderer.forceContextLoss();renderer.domElement.remove();mappingRef.current=undefined;};},[model]);
 useEffect(()=>{const next=updatePatternFoldScene(model,step,progress).value;if(next&&mappingRef.current)mappingRef.current.apply(next);},[model,step,progress]);
 useEffect(()=>{mappingRef.current?.regions.forEach(mesh=>mesh.visible=showRegions);const parent=mappingRef.current?.group.parent;parent?.getObjectByName("pattern-guides")?.traverse(x=>{if(x.userData.kind==="cut")x.visible=showCuts;if(x.userData.kind==="crease")x.visible=showCreases;});},[showCuts,showCreases,showRegions,model]);
 return <main style={{minHeight:"100vh",padding:20,background:"#e2e8f0",color:"#0f172a",fontFamily:"system-ui"}}><h1>Fold 3D Viewer — Pattern Mode</h1><button onClick={onExit}>Solid / Surface mode</button><div style={{display:"grid",gridTemplateColumns:"minmax(0, 1fr) 300px",gap:16,marginTop:12}}><div ref={host} style={{minHeight:620,border:"1px solid #94a3b8",borderRadius:8,background:"#f8fafc"}}/><aside style={{background:"white",padding:16,borderRadius:8}}><label>Fixture<br/><select aria-label="Pattern fixture" value={fixture} onChange={event=>{setFixture(event.target.value);setProgress(0);setStep(0);}}>{Object.keys(PATTERN_FOLD_FIXTURES).map(id=><option key={id}>{id}</option>)}</select></label><p><label>Fold step<br/><input type="number" min="0" max={Math.max(0,model.sequence.steps.length-1)} value={step} onChange={event=>setStep(Number(event.target.value))}/></label></p><p><label>Fold progress {Math.round(progress*100)}%<input aria-label="Pattern fold progress" type="range" min="0" max="1" step=".01" value={progress} onChange={event=>setProgress(Number(event.target.value))}/></label></p><p><label><input type="checkbox" checked={showRegions} onChange={event=>setShowRegions(event.target.checked)}/> Regions</label><br/><label><input type="checkbox" checked={showCuts} onChange={event=>setShowCuts(event.target.checked)}/> Cuts</label><br/><label><input type="checkbox" checked={showCreases} onChange={event=>setShowCreases(event.target.checked)}/> Creases</label></p><hr/><strong>Pattern debug</strong><p>Pattern: {model.sheet.id}<br/>Regions: {model.sheet.regions.length}<br/>Cuts: {model.sheet.cuts.length}<br/>Creases: {model.sheet.creases.length}<br/>Holes: {model.topology.holes.length}<br/>Fold edges: {model.topology.foldEdges.length}</p><small>Mountain creases are purple; valley/unassigned creases are blue; cuts are red. Progress is reversible.</small></aside></div></main>;
}
