import {
  DependencyGraph,
  emptySemanticUpdate,
  type MathDependency,
  type MathEntity,
  type MathEvent,
  type MathScene,
  type SemanticUpdateResult,
} from "../math-ir/index.js";

export const DYNAMIC_GEOMETRY_EPSILON = 1e-9;
export type Vec2 = [number, number];
export type Vec3 = [number, number, number];
export type ConstructionCommandId =
  | "CREATE_FREE_POINT" | "CREATE_POINT_ON_OBJECT" | "CREATE_LINE" | "CREATE_RAY" | "CREATE_SEGMENT"
  | "CREATE_CIRCLE_CENTER_RADIUS" | "CREATE_CIRCLE_CENTER_POINT" | "CREATE_POLYGON" | "CREATE_MIDPOINT"
  | "CREATE_INTERSECTION" | "CREATE_PROJECTION" | "CREATE_PARALLEL_LINE" | "CREATE_PERPENDICULAR_LINE"
  | "TRANSLATE_OBJECT" | "ROTATE_OBJECT" | "REFLECT_OBJECT" | "SCALE_OBJECT" | "DELETE_OBJECT"
  | "RENAME_OBJECT" | "SET_VISIBILITY" | "MOVE_POINT" | "CREATE_FREE_POINT_3D" | "CREATE_LINE_3D"
  | "CREATE_SEGMENT_3D" | "CREATE_PLANE" | "PROJECT_POINT_TO_PLANE" | "CREATE_LINE_PLANE_INTERSECTION";
export type ConstructionIssueCode = "INVALID_INPUT" | "INVALID_REFERENCE" | "INVALID_DEPENDENCY" | "DEPENDENCY_CYCLE" | "DEGENERATE_GEOMETRY" | "CONSTRUCTION_UNRESOLVED" | "CONSTRAINT_VIOLATION" | "UNSUPPORTED_OPERATION" | "NON_UNIQUE_SOLUTION" | "DUPLICATE_LABEL";
export interface ConstructionIssue { code: ConstructionIssueCode; path: string; message: string; }
export interface ConstructionCommand { id: ConstructionCommandId; inputIds?: string[]; parameters?: Record<string, unknown>; }
export interface ConstructionCommandResult { status:"PASS"|"FAIL"; scene?:MathScene; createdIds:string[]; updatedIds:string[]; removedIds:string[]; events:MathEvent[]; update:SemanticUpdateResult; issues:ConstructionIssue[]; }
export interface ToolDefinition { id:ConstructionCommandId; name:string; requiredInputs:number; allowedInputTypes:string[][]; outputTypes:string[]; }
export interface ConstructionSession { scene:MathScene; selectedIds:string[]; activeTool?:ConstructionCommandId; toolInputs:string[]; hoverCandidate?:{objectId?:string;position?:Vec2|Vec3}; history:MathScene[]; future:MathScene[]; }
export interface RendererSnapshot { sceneId:string; objects:Array<{id:string;type:string;label?:string;visible:boolean;coordinate?:Vec2|Vec3;definition?:Record<string,unknown>}>; }
export interface IntersectionResult { classification:"NONE"|"POINT"|"TANGENT"|"TWO_POINTS"|"PARALLEL"|"COINCIDENT"|"CONTAINED"; points:Array<Vec2|Vec3>; }
export interface SnapCandidate { kind:"EXISTING_POINT"|"POINT_ON_LINE"|"POINT_ON_SEGMENT"|"POINT_ON_CIRCLE"|"INTERSECTION"; objectIds:string[]; position:Vec2; distance:number; createsConstraint:false; }

type Definition={kind:string;sourceIds:string[];parameters?:Record<string,unknown>;freedom?:"FREE"|"DEPENDENT"|"PATH_BOUND"|"FIXED";resolved?:boolean};
const ok=(scene:MathScene,createdIds:string[]=[],updatedIds:string[]=[],removedIds:string[]=[],events:MathEvent[]=[]):ConstructionCommandResult=>({status:"PASS",scene,createdIds,updatedIds,removedIds,events,update:emptySemanticUpdate({changedObjectIds:[...createdIds,...updatedIds],affectedDependentIds:updatedIds,events}),issues:[]});
const bad=(code:ConstructionIssueCode,path:string,message:string):ConstructionCommandResult=>({status:"FAIL",createdIds:[],updatedIds:[],removedIds:[],events:[],update:emptySemanticUpdate(),issues:[{code,path,message}]});
const clone=<T>(value:T):T=>structuredClone(value);
const entity=(scene:MathScene,id:string)=>scene.entities.find(item=>item.id===id);
const finite=(values:number[])=>values.every(Number.isFinite);
const sub2=(a:Vec2,b:Vec2):Vec2=>[a[0]-b[0],a[1]-b[1]], add2=(a:Vec2,b:Vec2):Vec2=>[a[0]+b[0],a[1]+b[1]], mul2=(a:Vec2,k:number):Vec2=>[a[0]*k,a[1]*k];
const dot2=(a:Vec2,b:Vec2)=>a[0]*b[0]+a[1]*b[1], cross2=(a:Vec2,b:Vec2)=>a[0]*b[1]-a[1]*b[0], norm2=(a:Vec2)=>Math.hypot(...a);
const sub3=(a:Vec3,b:Vec3):Vec3=>[a[0]-b[0],a[1]-b[1],a[2]-b[2]], add3=(a:Vec3,b:Vec3):Vec3=>[a[0]+b[0],a[1]+b[1],a[2]+b[2]], mul3=(a:Vec3,k:number):Vec3=>[a[0]*k,a[1]*k,a[2]*k];
const dot3=(a:Vec3,b:Vec3)=>a[0]*b[0]+a[1]*b[1]+a[2]*b[2], cross3=(a:Vec3,b:Vec3):Vec3=>[a[1]*b[2]-a[2]*b[1],a[2]*b[0]-a[0]*b[2],a[0]*b[1]-a[1]*b[0]], norm3=(a:Vec3)=>Math.hypot(...a);
const near=(a:number,b:number,t=DYNAMIC_GEOMETRY_EPSILON)=>Math.abs(a-b)<=t;
function transformCoordinate(value:Vec2,kind:string,parameters:Record<string,unknown>):Vec2|undefined{if(kind==="TRANSLATE_OBJECT"){const vector=parameters.vector as Vec2;return Array.isArray(vector)&&vector.length===2?add2(value,vector):undefined;}if(kind==="ROTATE_OBJECT"){const center=(parameters.center??[0,0]) as Vec2,angle=Number(parameters.angle),d=sub2(value,center);return finite([...center,angle])?add2(center,[d[0]*Math.cos(angle)-d[1]*Math.sin(angle),d[0]*Math.sin(angle)+d[1]*Math.cos(angle)]):undefined;}if(kind==="SCALE_OBJECT"){const center=(parameters.center??[0,0]) as Vec2,factor=Number(parameters.factor);return finite([...center,factor])?add2(center,mul2(sub2(value,center),factor)):undefined;}if(kind==="REFLECT_OBJECT"){const a=parameters.axisA as Vec2,b=parameters.axisB as Vec2;if(!Array.isArray(a)||!Array.isArray(b)||norm2(sub2(b,a))<=DYNAMIC_GEOMETRY_EPSILON)return;const projection=projectionPointToLine(value,a,b);return sub2(mul2(projection,2),value);}return;}
const coordinate=(item:MathEntity):Vec2|Vec3|undefined=>item.semanticCoordinate?.dimension==="2d"?[item.semanticCoordinate.x,item.semanticCoordinate.y]:item.semanticCoordinate?.dimension==="3d"?[item.semanticCoordinate.x,item.semanticCoordinate.y,item.semanticCoordinate.z]:undefined;
const definition=(item:MathEntity):Definition|undefined=>item.metadata?.adapterMetadata?.construction as Definition|undefined;
export function canonicalPersistentValue<T>(value:T,path="semantic"):T{
  if(Array.isArray(value))return value.map((entry,index)=>{if(entry===undefined)throw new Error(`INVALID_PERSISTENT_VALUE:${path}[${index}]`);return canonicalPersistentValue(entry,`${path}[${index}]`);}) as T;
  if(value!==null&&typeof value==="object"){const output:Record<string,unknown>={};for(const [key,entry] of Object.entries(value as Record<string,unknown>))if(entry!==undefined)output[key]=canonicalPersistentValue(entry,`${path}.${key}`);return output as T;}
  return value;
}
const withDefinition=(item:MathEntity,value:Definition):MathEntity=>({...item,metadata:{...item.metadata,adapterMetadata:{...item.metadata?.adapterMetadata,construction:canonicalPersistentValue(value,"construction")}}});
const withCoordinate=(item:MathEntity,value:Vec2|Vec3):MathEntity=>({...item,semanticCoordinate:value.length===2?{dimension:"2d",x:value[0],y:value[1]}:{dimension:"3d",x:value[0],y:value[1],z:value[2]}} as MathEntity);
const nextId=(scene:MathScene,prefix:string)=>{const used=new Set(scene.entities.map(x=>x.id));let n=1;while(used.has(`${prefix}-${n}`))n++;return `${prefix}-${n}`;};
export function nextPointLabel(scene:MathScene):string{const used=new Set(scene.entities.filter(x=>x.type==="point").map(x=>x.label));for(let n=0;;n++){const base=String.fromCharCode(65+n%26),suffix=n<26?"":String(Math.floor(n/26));const label=base+suffix;if(!used.has(label))return label;}}
const dependencyFor=(item:MathEntity):MathDependency|undefined=>{const d=definition(item);return d?.sourceIds.length?{id:`dependency:${item.id}`,dependentId:item.id,sourceIds:[...d.sourceIds],kind:d.kind,evaluatorRef:`dynamic-geometry:${d.kind}`} : undefined;};
function rebuildDependencies(scene:MathScene):MathScene{const owned=scene.entities.map(dependencyFor).filter(Boolean) as MathDependency[],others=(scene.semantics?.dependencies??[]).filter(x=>!x.evaluatorRef.startsWith("dynamic-geometry:"));return{...scene,semantics:{...scene.semantics,dependencies:[...others,...owned]}};}
const event=(id:string,kind:MathEvent["kind"],objectIds:string[],sequence=0):MathEvent=>({id,kind,objectIds,sequence,changeKind:"SEMANTIC_CHANGE"});
const append=(scene:MathScene,item:MathEntity):MathScene=>rebuildDependencies({...scene,entities:[...scene.entities,item]});
const linePoints=(scene:MathScene,item:MathEntity):[Vec2,Vec2]|undefined=>{if(!(item.type==="line"||item.type==="ray"||item.type==="segment"))return;const ids=item.type==="line"?item.pointIds:item.type==="ray"?[item.startPointId,item.throughPointId]:[item.startPointId,item.endPointId],a=coordinate(entity(scene,ids[0])!),b=coordinate(entity(scene,ids[1])!);return a?.length===2&&b?.length===2?[a as Vec2,b as Vec2]:undefined;};
const linePoints3=(scene:MathScene,item:MathEntity):[Vec3,Vec3]|undefined=>{if(!(item.type==="line"||item.type==="segment"))return;const ids=item.type==="line"?item.pointIds:[item.startPointId,item.endPointId],a=coordinate(entity(scene,ids[0])!),b=coordinate(entity(scene,ids[1])!);return a?.length===3&&b?.length===3?[a as Vec3,b as Vec3]:undefined;};
const projectionPointToLine3=(point:Vec3,a:Vec3,b:Vec3,clamp=false):Vec3=>{const direction=sub3(b,a),denominator=dot3(direction,direction);let t=denominator<=DYNAMIC_GEOMETRY_EPSILON?0:dot3(sub3(point,a),direction)/denominator;if(clamp)t=Math.max(0,Math.min(1,t));return add3(a,mul3(direction,t));};
const circleData=(scene:MathScene,item:MathEntity):{center:Vec2;radius:number}|undefined=>{if(item.type!=="circle")return;const center=coordinate(entity(scene,item.centerPointId)!);if(center?.length!==2)return;const d=definition(item),radius=Number(d?.parameters?.radius??0);return Number.isFinite(radius)&&radius>0?{center:center as Vec2,radius}:undefined;};
export function projectionPointToLine(point:Vec2,a:Vec2,b:Vec2,clamp?:"RAY"|"SEGMENT"):Vec2{const d=sub2(b,a),den=dot2(d,d);let t=den<=DYNAMIC_GEOMETRY_EPSILON?0:dot2(sub2(point,a),d)/den;if(clamp==="RAY")t=Math.max(0,t);if(clamp==="SEGMENT")t=Math.max(0,Math.min(1,t));return add2(a,mul2(d,t));}
export const distancePointToLine=(p:Vec2,a:Vec2,b:Vec2)=>norm2(sub2(p,projectionPointToLine(p,a,b)));
export const pointOnLine=(p:Vec2,a:Vec2,b:Vec2,t=DYNAMIC_GEOMETRY_EPSILON)=>distancePointToLine(p,a,b)<=t;
export function lineIntersection(a:Vec2,b:Vec2,c:Vec2,d:Vec2):IntersectionResult{const u=sub2(b,a),v=sub2(d,c),den=cross2(u,v);if(Math.abs(den)<=DYNAMIC_GEOMETRY_EPSILON)return{classification:Math.abs(cross2(sub2(c,a),u))<=DYNAMIC_GEOMETRY_EPSILON?"COINCIDENT":"PARALLEL",points:[]};const t=cross2(sub2(c,a),v)/den;return{classification:"POINT",points:[add2(a,mul2(u,t))]};}
export function lineCircleIntersections(a:Vec2,b:Vec2,center:Vec2,radius:number):IntersectionResult{const d=sub2(b,a),f=sub2(a,center),aa=dot2(d,d);if(aa<=DYNAMIC_GEOMETRY_EPSILON)return{classification:"NONE",points:[]};const bb=2*dot2(f,d),cc=dot2(f,f)-radius*radius,disc=bb*bb-4*aa*cc;if(disc<-DYNAMIC_GEOMETRY_EPSILON)return{classification:"NONE",points:[]};if(Math.abs(disc)<=DYNAMIC_GEOMETRY_EPSILON){const t=-bb/(2*aa);return{classification:"TANGENT",points:[add2(a,mul2(d,t))]};}const root=Math.sqrt(Math.max(0,disc)),ts=[(-bb-root)/(2*aa),(-bb+root)/(2*aa)];return{classification:"TWO_POINTS",points:ts.map(t=>add2(a,mul2(d,t)))};}
export function circleCircleIntersections(a:Vec2,ra:number,b:Vec2,rb:number):IntersectionResult{const delta=sub2(b,a),d=norm2(delta);if(d<=DYNAMIC_GEOMETRY_EPSILON)return{classification:near(ra,rb)?"COINCIDENT":"NONE",points:[]};if(d>ra+rb+DYNAMIC_GEOMETRY_EPSILON||d<Math.abs(ra-rb)-DYNAMIC_GEOMETRY_EPSILON)return{classification:"NONE",points:[]};const x=(ra*ra-rb*rb+d*d)/(2*d),h2=ra*ra-x*x,base=add2(a,mul2(delta,x/d));if(Math.abs(h2)<=DYNAMIC_GEOMETRY_EPSILON)return{classification:"TANGENT",points:[base]};const h=Math.sqrt(Math.max(0,h2)),normal:Vec2=[-delta[1]/d,delta[0]/d];return{classification:"TWO_POINTS",points:[add2(base,mul2(normal,h)),add2(base,mul2(normal,-h))]};}
export const parallelClassification=(a:Vec2,b:Vec2,c:Vec2,d:Vec2)=>Math.abs(cross2(sub2(b,a),sub2(d,c)))<=DYNAMIC_GEOMETRY_EPSILON;
export const perpendicularClassification=(a:Vec2,b:Vec2,c:Vec2,d:Vec2)=>Math.abs(dot2(sub2(b,a),sub2(d,c)))<=DYNAMIC_GEOMETRY_EPSILON;
export function planeRelation(aNormal:Vec3,bNormal:Vec3):"PARALLEL"|"PERPENDICULAR"|"INTERSECTING"{if(norm3(cross3(aNormal,bNormal))<=DYNAMIC_GEOMETRY_EPSILON)return"PARALLEL";if(Math.abs(dot3(aNormal,bNormal))<=DYNAMIC_GEOMETRY_EPSILON)return"PERPENDICULAR";return"INTERSECTING";}
function polygonMetrics(points:Vec2[]){let twice=0,perimeter=0;for(let i=0;i<points.length;i++){const a=points[i],b=points[(i+1)%points.length];twice+=cross2(a,b);perimeter+=norm2(sub2(b,a));}return{signedArea:twice/2,area:Math.abs(twice)/2,perimeter,orientation:twice>=0?"CCW":"CW"};}
function simplePolygon(points:Vec2[]){for(let i=0;i<points.length;i++)for(let j=i+1;j<points.length;j++){if(Math.abs(i-j)<=1||i===0&&j===points.length-1)continue;const hit=lineIntersection(points[i],points[(i+1)%points.length],points[j],points[(j+1)%points.length]);if(hit.classification==="POINT"){const p=hit.points[0] as Vec2,within=(p:Vec2,a:Vec2,b:Vec2)=>p[0]>=Math.min(a[0],b[0])-DYNAMIC_GEOMETRY_EPSILON&&p[0]<=Math.max(a[0],b[0])+DYNAMIC_GEOMETRY_EPSILON&&p[1]>=Math.min(a[1],b[1])-DYNAMIC_GEOMETRY_EPSILON&&p[1]<=Math.max(a[1],b[1])+DYNAMIC_GEOMETRY_EPSILON;if(within(p,points[i],points[(i+1)%points.length])&&within(p,points[j],points[(j+1)%points.length]))return false;}}return true;}

export const CONSTRUCTION_TOOLS:readonly ToolDefinition[]=[
  ["CREATE_FREE_POINT","Point",0,[],["point"]],["CREATE_POINT_ON_OBJECT","Point on object",1,[["line","ray","segment","circle","plane"]],["point"]],
  ["CREATE_LINE","Line",2,[["point"],["point"]],["line"]],["CREATE_RAY","Ray",2,[["point"],["point"]],["ray"]],["CREATE_SEGMENT","Segment",2,[["point"],["point"]],["segment"]],
  ["CREATE_CIRCLE_CENTER_RADIUS","Circle",1,[["point"]],["circle"]],["CREATE_CIRCLE_CENTER_POINT","Circle through point",2,[["point"],["point"]],["circle"]],
  ["CREATE_POLYGON","Polygon",3,[["point"]],["polygon"]],["CREATE_MIDPOINT","Midpoint",2,[["point"],["point"]],["point"]],
  ["CREATE_INTERSECTION","Intersection",2,[["line","ray","segment","circle"],["line","ray","segment","circle"]],["point"]],
  ["CREATE_PROJECTION","Projection",2,[["point"],["line"]],["point"]],["CREATE_PARALLEL_LINE","Parallel",2,[["point"],["line"]],["line"]],
  ["CREATE_PERPENDICULAR_LINE","Perpendicular",2,[["point"],["line"]],["line"]],
  ["TRANSLATE_OBJECT","Translate",1,[[]],[]],["ROTATE_OBJECT","Rotate",1,[[]],[]],["REFLECT_OBJECT","Reflect",1,[[]],[]],["SCALE_OBJECT","Scale",1,[[]],[]],
  ["DELETE_OBJECT","Delete",1,[[]],[]],["RENAME_OBJECT","Rename",1,[[]],[]],["SET_VISIBILITY","Visibility",1,[[]],[]],["MOVE_POINT","Move point",1,[["point"]],["point"]],
  ["CREATE_FREE_POINT_3D","Point 3D",0,[],["point"]],["CREATE_LINE_3D","Line 3D",2,[["point"],["point"]],["line"]],["CREATE_SEGMENT_3D","Segment 3D",2,[["point"],["point"]],["segment"]],
  ["CREATE_PLANE","Plane",3,[["point"],["point"],["point"]],["plane"]],["PROJECT_POINT_TO_PLANE","Project to plane",2,[["point"],["plane"]],["point"]],["CREATE_LINE_PLANE_INTERSECTION","Line-plane intersection",2,[["line"],["plane"]],["point"]],
].map(([id,name,requiredInputs,allowedInputTypes,outputTypes])=>({id:id as ConstructionCommandId,name:name as string,requiredInputs:requiredInputs as number,allowedInputTypes:allowedInputTypes as string[][],outputTypes:outputTypes as string[]}));

function makePoint(scene:MathScene,p:Vec2|Vec3,kind:string,sourceIds:string[]=[],parameters?:Record<string,unknown>,freedom:Definition["freedom"]="FREE",id=nextId(scene,"point")){const base:MathEntity={id,type:"point",label:nextPointLabel(scene),semanticCoordinate:p.length===2?{dimension:"2d",x:p[0],y:p[1]}:{dimension:"3d",x:p[0],y:p[1],z:p[2]}};return withDefinition(base,{kind,sourceIds,parameters,freedom,resolved:true});}
function requirePoints(scene:MathScene,ids:string[],dimension:2|3=2):(Vec2|Vec3)[]|undefined{return ids.map(id=>entity(scene,id)).map(x=>x&&coordinate(x)).filter(x=>x?.length===dimension) as (Vec2|Vec3)[]|undefined;}
function addDefined(scene:MathScene,item:MathEntity){const next=append(scene,item),e=event(`object:${item.id}:created`,"OBJECT_CHANGED",[item.id]);return ok({...next,semantics:{...next.semantics,events:[...(next.semantics?.events??[]),e]}},[item.id],[],[],[e]);}

export function executeConstructionCommand(input:MathScene,command:ConstructionCommand):ConstructionCommandResult{
  const scene=clone(input),ids=command.inputIds??[],p=command.parameters??{},id=String(p.id??"");
  if(command.id==="CREATE_FREE_POINT"||command.id==="CREATE_FREE_POINT_3D"){const value=p.position as number[];if(!Array.isArray(value)||value.length!==(command.id.endsWith("3D")?3:2)||!finite(value))return bad("INVALID_INPUT","parameters.position","A finite coordinate is required");return addDefined(scene,makePoint(scene,value as Vec2|Vec3,command.id));}
  if(command.id==="CREATE_LINE"||command.id==="CREATE_RAY"||command.id==="CREATE_SEGMENT"||command.id==="CREATE_LINE_3D"||command.id==="CREATE_SEGMENT_3D"){if(ids.length!==2||ids[0]===ids[1])return bad("DEGENERATE_GEOMETRY","inputIds","Two distinct points are required");const dimension=command.id.endsWith("3D")?3:2,points=requirePoints(scene,ids,dimension),separation=points?.length===2?(dimension===3?norm3(sub3(points[1] as Vec3,points[0] as Vec3)):norm2(sub2(points[1] as Vec2,points[0] as Vec2))):0;if(!points||points.length!==2||separation<=DYNAMIC_GEOMETRY_EPSILON)return bad("DEGENERATE_GEOMETRY","inputIds","Defining points must differ");const type=command.id.includes("LINE")?"line":command.id==="CREATE_RAY"?"ray":"segment",base=type==="line"?{id:nextId(scene,"line"),type,pointIds:ids as [string,string]}:type==="ray"?{id:nextId(scene,"ray"),type,startPointId:ids[0],throughPointId:ids[1]}:{id:nextId(scene,"segment"),type,startPointId:ids[0],endPointId:ids[1]};return addDefined(scene,withDefinition(base as MathEntity,{kind:command.id,sourceIds:ids,freedom:"DEPENDENT",resolved:true}));}
  if(command.id==="CREATE_CIRCLE_CENTER_RADIUS"||command.id==="CREATE_CIRCLE_CENTER_POINT"){const center=entity(scene,ids[0]);if(!center||coordinate(center)?.length!==2)return bad("INVALID_REFERENCE","inputIds.0","Circle center must be a 2D point");let radius=Number(p.radius),sources=[ids[0]];if(command.id.endsWith("POINT")){const edge=entity(scene,ids[1]),a=coordinate(center),b=edge&&coordinate(edge);if(!a||!b||b.length!==2)return bad("INVALID_REFERENCE","inputIds.1","Defining point is invalid");radius=norm2(sub2(b as Vec2,a as Vec2));sources.push(ids[1]);}if(!Number.isFinite(radius)||radius<=DYNAMIC_GEOMETRY_EPSILON)return bad("DEGENERATE_GEOMETRY","parameters.radius","Radius must be positive");const circle:MathEntity={id:nextId(scene,"circle"),type:"circle",centerPointId:ids[0]};return addDefined(scene,withDefinition(circle,{kind:command.id,sourceIds:sources,parameters:{radius},freedom:"DEPENDENT",resolved:true}));}
  if(command.id==="CREATE_MIDPOINT"){const points=requirePoints(scene,ids) as Vec2[];if(!points||points.length!==2||ids[0]===ids[1])return bad("INVALID_INPUT","inputIds","Midpoint requires two distinct 2D points");return addDefined(scene,makePoint(scene,mul2(add2(points[0],points[1]),.5),command.id,ids,undefined,"DEPENDENT"));}
  if(command.id==="CREATE_POINT_ON_OBJECT"){const target=entity(scene,ids[0]),candidate=p.position as Vec2|Vec3;if(!target||!Array.isArray(candidate)||![2,3].includes(candidate.length)||!finite(candidate))return bad("INVALID_INPUT","parameters.position","Path and finite candidate are required");let projected:Vec2|Vec3|undefined;if((target.type==="line"||target.type==="ray"||target.type==="segment")&&candidate.length===2){const points=linePoints(scene,target)!;projected=projectionPointToLine(candidate,...points,target.type==="ray"?"RAY":target.type==="segment"?"SEGMENT":undefined);}else if((target.type==="line"||target.type==="segment")&&candidate.length===3){const points=linePoints3(scene,target);if(points)projected=projectionPointToLine3(candidate,...points,target.type==="segment");}else if(target.type==="circle"&&candidate.length===2){const circle=circleData(scene,target)!;const d=sub2(candidate,circle.center),n=norm2(d);if(n<=DYNAMIC_GEOMETRY_EPSILON)return bad("CONSTRAINT_VIOLATION","parameters.position","Circle direction is undefined");projected=add2(circle.center,mul2(d,circle.radius/n));}else if(target.type==="plane"&&candidate.length===3){const pd=definition(target),normal=pd?.parameters?.normal as Vec3,offset=Number(pd?.parameters?.offset);if(!normal)return bad("CONSTRUCTION_UNRESOLVED","inputIds.0","Plane is unresolved");const t=(dot3(normal,candidate)+offset)/dot3(normal,normal);projected=sub3(candidate,mul3(normal,t));}if(!projected)return bad("UNSUPPORTED_OPERATION","inputIds.0","Path and candidate dimensions are incompatible");return addDefined(scene,makePoint(scene,projected,command.id,ids,undefined,"PATH_BOUND"));}
  if(command.id==="CREATE_POLYGON"){if(ids.length<3)return bad("INVALID_INPUT","inputIds","Polygon requires at least three points");const points=requirePoints(scene,ids) as Vec2[],metrics=points?.length===ids.length?polygonMetrics(points):undefined;if(!points||points.length!==ids.length||new Set(ids).size!==ids.length||!metrics||metrics.area<=DYNAMIC_GEOMETRY_EPSILON||!simplePolygon(points))return bad("DEGENERATE_GEOMETRY","inputIds","Polygon must be non-degenerate, simple, and preserve supplied vertex order");const polygon:MathEntity={id:nextId(scene,"polygon"),type:"polygon",vertexIds:[...ids]};return addDefined(scene,withDefinition(polygon,{kind:command.id,sourceIds:ids,parameters:metrics,freedom:"DEPENDENT",resolved:true}));}
  if(command.id==="CREATE_PARALLEL_LINE"||command.id==="CREATE_PERPENDICULAR_LINE"){const point=entity(scene,ids[0]),line=entity(scene,ids[1]),origin=point&&coordinate(point),ends=line&&linePoints(scene,line);if(!origin||origin.length!==2||!ends)return bad("INVALID_REFERENCE","inputIds","Point and line are required");const d=sub2(ends[1],ends[0]),v=command.id.includes("PERPENDICULAR")?[-d[1],d[0]] as Vec2:d,helper=makePoint(scene,add2(origin as Vec2,v),`${command.id}_DIRECTION`,ids,undefined,"DEPENDENT"),withHelper=append(scene,helper),result:MathEntity={id:nextId(withHelper,"line"),type:"line",pointIds:[ids[0],helper.id]};const final=append(withHelper,withDefinition(result,{kind:command.id,sourceIds:ids,freedom:"DEPENDENT",resolved:true}));return ok(final,[helper.id,result.id]);}
  if(command.id==="CREATE_PROJECTION"){const point=entity(scene,ids[0]),line=entity(scene,ids[1]),value=point&&coordinate(point),ends=line&&linePoints(scene,line);if(!value||value.length!==2||!ends)return bad("INVALID_REFERENCE","inputIds","Point and line are required");return addDefined(scene,makePoint(scene,projectionPointToLine(value as Vec2,...ends),command.id,ids,undefined,"DEPENDENT"));}
  if(command.id==="CREATE_INTERSECTION"){const a=entity(scene,ids[0]),b=entity(scene,ids[1]);if(!a||!b)return bad("INVALID_REFERENCE","inputIds","Two objects are required");let result:IntersectionResult|undefined;if(a.type==="circle"&&b.type==="circle"){const x=circleData(scene,a),y=circleData(scene,b);if(x&&y)result=circleCircleIntersections(x.center,x.radius,y.center,y.radius);}else if(a.type==="circle"||b.type==="circle"){const circle=a.type==="circle"?circleData(scene,a):circleData(scene,b),line=a.type==="circle"?linePoints(scene,b):linePoints(scene,a);if(circle&&line)result=lineCircleIntersections(...line,circle.center,circle.radius);}else{const x=linePoints(scene,a),y=linePoints(scene,b);if(x&&y)result=lineIntersection(...x,...y);}if(!result)return bad("UNSUPPORTED_OPERATION","inputIds","Intersection pair is unsupported");if(!result.points.length)return bad(result.classification==="COINCIDENT"?"NON_UNIQUE_SOLUTION":"CONSTRUCTION_UNRESOLVED","inputIds",result.classification);const branch=Math.max(0,Math.min(result.points.length-1,Number(p.branch??0))),point=makePoint(scene,result.points[branch] as Vec2,"CREATE_INTERSECTION",ids,{branch,classification:result.classification},"DEPENDENT");return addDefined(scene,point);}
  if(["TRANSLATE_OBJECT","ROTATE_OBJECT","REFLECT_OBJECT","SCALE_OBJECT"].includes(command.id)){const source=entity(scene,ids[0]),value=source&&coordinate(source);if(!source)return bad("INVALID_REFERENCE","inputIds.0","Source object does not exist");if(value?.length===2){const output=transformCoordinate(value as Vec2,command.id,p);if(!output||!finite(output))return bad("INVALID_INPUT","parameters","Transformation parameters must be finite and non-degenerate");return addDefined(scene,makePoint(scene,output,command.id,ids,p,"DEPENDENT"));}const sourcePointIds=source.type==="line"?source.pointIds:source.type==="ray"?[source.startPointId,source.throughPointId]:source.type==="segment"?[source.startPointId,source.endPointId]:source.type==="circle"?[source.centerPointId]:source.type==="polygon"?source.vertexIds:undefined;if(!sourcePointIds)return bad("UNSUPPORTED_OPERATION","inputIds.0",`Transformation does not support ${source.type}`);let current=scene;const transformedIds:string[]=[];for(const sourcePointId of sourcePointIds){const point=entity(current,sourcePointId),position=point&&coordinate(point),output=position?.length===2&&transformCoordinate(position as Vec2,command.id,p);if(!output)return bad("CONSTRUCTION_UNRESOLVED",sourcePointId,"Transformation input is unresolved");const transformed=makePoint(current,output,command.id,[sourcePointId],p,"DEPENDENT");current=append(current,transformed);transformedIds.push(transformed.id);}let output:MathEntity;if(source.type==="line")output={id:nextId(current,"line"),type:"line",pointIds:transformedIds as [string,string]};else if(source.type==="ray")output={id:nextId(current,"ray"),type:"ray",startPointId:transformedIds[0],throughPointId:transformedIds[1]};else if(source.type==="segment")output={id:nextId(current,"segment"),type:"segment",startPointId:transformedIds[0],endPointId:transformedIds[1]};else if(source.type==="polygon")output={id:nextId(current,"polygon"),type:"polygon",vertexIds:transformedIds};else{const sourceCircle=circleData(scene,source)!,factor=command.id==="SCALE_OBJECT"?Math.abs(Number(p.factor)):1;output=withDefinition({id:nextId(current,"circle"),type:"circle",centerPointId:transformedIds[0]},{kind:command.id,sourceIds:[source.id,...transformedIds],parameters:{...p,radius:sourceCircle.radius*factor},freedom:"DEPENDENT",resolved:true});return ok(append(current,output),[...transformedIds,output.id]);}return ok(append(current,withDefinition(output,{kind:command.id,sourceIds:[source.id,...transformedIds],parameters:p,freedom:"DEPENDENT",resolved:true})),[...transformedIds,output.id]);}
  if(command.id==="MOVE_POINT"){const target=entity(scene,ids[0]),d=target&&definition(target),candidate=p.position as Vec2|Vec3;if(!target||target.type!=="point"||!Array.isArray(candidate)||!finite(candidate))return bad("INVALID_INPUT","parameters.position","Point and finite candidate required");if(d?.freedom==="FIXED"||d?.freedom==="DEPENDENT")return bad("CONSTRAINT_VIOLATION",ids[0],`${d.freedom} point cannot be dragged directly`);let position=candidate;const locked=scene.constraints.find(x=>x.mode==="LOCKED"&&x.entityIds[0]===target.id&&["point_on_line","point_on_segment","point_on_circle","point_on_plane"].includes(x.type)),pathId=d?.freedom==="PATH_BOUND"?d.sourceIds[0]:locked?.entityIds[1];if(pathId){const path=entity(scene,pathId);if(!path)return bad("INVALID_DEPENDENCY",ids[0],"Path is missing");if(path.type==="circle"){const circle=circleData(scene,path)!,delta=sub2(candidate as Vec2,circle.center),n=norm2(delta);if(n<=DYNAMIC_GEOMETRY_EPSILON)return bad("CONSTRAINT_VIOLATION",ids[0],"Circle projection is undefined");position=add2(circle.center,mul2(delta,circle.radius/n));}else if(path.type==="plane"&&candidate.length===3){const pd=definition(path),normal=pd?.parameters?.normal as Vec3,offset=Number(pd?.parameters?.offset),t=(dot3(normal,candidate as Vec3)+offset)/dot3(normal,normal);position=sub3(candidate as Vec3,mul3(normal,t));}else{const points=linePoints(scene,path);if(!points)return bad("INVALID_DEPENDENCY",ids[0],"Path is unresolved");position=projectionPointToLine(candidate as Vec2,...points,path.type==="segment"?"SEGMENT":path.type==="ray"?"RAY":undefined);}}const changed={...scene,entities:scene.entities.map(x=>x.id===target.id?withCoordinate(x,position):x)};return recomputeScene(changed,[target.id]);}
  if(command.id==="RENAME_OBJECT"){const target=entity(scene,ids[0]),label=String(p.label??"").trim();if(!target||!label)return bad("INVALID_INPUT","parameters.label","Object and label required");if(scene.entities.some(x=>x.id!==target.id&&x.label===label))return bad("DUPLICATE_LABEL","parameters.label",`Label ${label} already exists`);return ok({...scene,entities:scene.entities.map(x=>x.id===target.id?{...x,label}:x)},[],[target.id]);}
  if(command.id==="SET_VISIBILITY"){const target=entity(scene,ids[0]);if(!target)return bad("INVALID_REFERENCE","inputIds.0","Object does not exist");const visible=Boolean(p.visible),entities=scene.entities.map(x=>x.id===target.id?{...x,metadata:{...x.metadata,adapterMetadata:{...x.metadata?.adapterMetadata,visible}}}:x),e=event(`visibility:${target.id}`,"OBJECT_CHANGED",[target.id]);return ok({...scene,entities},[],[target.id],[],[e]);}
  if(command.id==="DELETE_OBJECT"){if(!entity(scene,ids[0]))return bad("INVALID_REFERENCE","inputIds.0","Object does not exist");const graph=new DependencyGraph(scene.semantics?.dependencies??[]),dependents=graph.recomputationOrder([ids[0]]),cascade=Boolean(p.cascade);if(dependents.length&&!cascade)return bad("INVALID_DEPENDENCY",ids[0],`Object has dependents: ${dependents.join(", ")}`);const removedIds=cascade?[ids[0],...dependents]:[ids[0]],removed=new Set(removedIds);return ok(rebuildDependencies({...scene,entities:scene.entities.filter(x=>!removed.has(x.id))}),[],[],removedIds);}
  if(command.id==="CREATE_PLANE"){const points=requirePoints(scene,ids,3) as Vec3[];if(!points||points.length!==3)return bad("INVALID_REFERENCE","inputIds","Three 3D points are required");const normal=cross3(sub3(points[1],points[0]),sub3(points[2],points[0]));if(norm3(normal)<=DYNAMIC_GEOMETRY_EPSILON)return bad("DEGENERATE_GEOMETRY","inputIds","Plane points must be non-collinear");const plane:MathEntity={id:nextId(scene,"plane"),type:"plane",pointIds:[...ids]};return addDefined(scene,withDefinition(plane,{kind:command.id,sourceIds:ids,parameters:{normal,offset:-dot3(normal,points[0])},freedom:"DEPENDENT",resolved:true}));}
  if(command.id==="PROJECT_POINT_TO_PLANE"||command.id==="CREATE_LINE_PLANE_INTERSECTION"){const source=entity(scene,ids[0]),plane=entity(scene,ids[1]),pd=plane&&definition(plane),normal=pd?.parameters?.normal as Vec3,offset=Number(pd?.parameters?.offset);if(!source||plane?.type!=="plane"||!normal)return bad("INVALID_REFERENCE","inputIds","Valid source and plane required");let output:Vec3;if(command.id==="PROJECT_POINT_TO_PLANE"){const q=coordinate(source) as Vec3,t=(dot3(normal,q)+offset)/dot3(normal,normal);output=sub3(q,mul3(normal,t));}else{const points=(source.type==="line"&&source.pointIds.map(x=>coordinate(entity(scene,x)!))) as Vec3[],direction=sub3(points[1],points[0]),den=dot3(normal,direction);if(Math.abs(den)<=DYNAMIC_GEOMETRY_EPSILON)return bad(Math.abs(dot3(normal,points[0])+offset)<=DYNAMIC_GEOMETRY_EPSILON?"NON_UNIQUE_SOLUTION":"CONSTRUCTION_UNRESOLVED","inputIds","Line is contained in or parallel to plane");output=add3(points[0],mul3(direction,-(dot3(normal,points[0])+offset)/den));}return addDefined(scene,makePoint(scene,output,command.id,ids,undefined,"DEPENDENT"));}
  return bad("UNSUPPORTED_OPERATION","command.id",command.id);
}

function evaluate(scene:MathScene,item:MathEntity):MathEntity{const d=definition(item);if(!d)return item;const command:ConstructionCommand={id:d.kind as ConstructionCommandId,inputIds:d.sourceIds,parameters:{...d.parameters,id:item.id}};if(d.kind==="CREATE_MIDPOINT"){const pts=requirePoints(scene,d.sourceIds) as Vec2[];return pts?.length===2?withCoordinate(item,mul2(add2(pts[0],pts[1]),.5)):withDefinition(item,{...d,resolved:false});}if(d.kind==="CREATE_PROJECTION"){const q=coordinate(entity(scene,d.sourceIds[0])!),line=linePoints(scene,entity(scene,d.sourceIds[1])!);return q&&line?withCoordinate(item,projectionPointToLine(q as Vec2,...line)):withDefinition(item,{...d,resolved:false});}if(d.kind==="CREATE_CIRCLE_CENTER_POINT"){const a=coordinate(entity(scene,d.sourceIds[0])!),b=coordinate(entity(scene,d.sourceIds[1])!);return a&&b?withDefinition(item,{...d,parameters:{...d.parameters,radius:norm2(sub2(b as Vec2,a as Vec2))},resolved:true}):withDefinition(item,{...d,resolved:false});}if(["TRANSLATE_OBJECT","ROTATE_OBJECT","REFLECT_OBJECT","SCALE_OBJECT"].includes(d.kind)&&item.type==="point"){const source=coordinate(entity(scene,d.sourceIds[0])!),output=source?.length===2&&transformCoordinate(source as Vec2,d.kind,d.parameters??{});return output?withCoordinate(item,output):withDefinition(item,{...d,resolved:false});}if(d.kind.endsWith("_DIRECTION")){const origin=coordinate(entity(scene,d.sourceIds[0])!),line=linePoints(scene,entity(scene,d.sourceIds[1])!);if(origin?.length===2&&line){const delta=sub2(line[1],line[0]),vector=d.kind.includes("PERPENDICULAR")?[-delta[1],delta[0]] as Vec2:delta;return withCoordinate(item,add2(origin as Vec2,vector));}return withDefinition(item,{...d,resolved:false});}if(d.kind==="CREATE_POINT_ON_OBJECT"){const candidate=coordinate(item);const temporary=candidate&&executeConstructionCommand({...scene,entities:scene.entities.filter(x=>x.id!==item.id)},{...command,parameters:{position:candidate}}),made=temporary&&temporary.scene?.entities.at(-1);return made&&coordinate(made)?withCoordinate(item,coordinate(made)!):withDefinition(item,{...d,resolved:false});}if(d.kind==="CREATE_INTERSECTION"){const temporary=executeConstructionCommand({...scene,entities:scene.entities.filter(x=>x.id!==item.id)},command),made=temporary.scene?.entities.at(-1);return made&&coordinate(made)?withCoordinate(withDefinition(item,{...d,resolved:true}),coordinate(made)!):withDefinition(item,{...d,resolved:false});}return item;}
export function evaluateConstraintStatuses(scene:MathScene):MathScene{const constraints=scene.constraints.map(constraint=>{if(!["point_on_line","point_on_segment","point_on_circle","point_on_plane"].includes(constraint.type))return constraint;const point=entity(scene,constraint.entityIds[0]),target=entity(scene,constraint.entityIds[1]),q=point&&coordinate(point);let satisfied=false;if(q&&target){if(target.type==="circle"&&q.length===2){const circle=circleData(scene,target);satisfied=!!circle&&near(norm2(sub2(q as Vec2,circle.center)),circle.radius);}else if((target.type==="line"||target.type==="segment")&&q.length===2){const points=linePoints(scene,target);if(points){const projection=projectionPointToLine(q as Vec2,...points,target.type==="segment"?"SEGMENT":undefined);satisfied=norm2(sub2(q as Vec2,projection))<=DYNAMIC_GEOMETRY_EPSILON;}}else if(target.type==="plane"&&q.length===3){const pd=definition(target),normal=pd?.parameters?.normal as Vec3,offset=Number(pd?.parameters?.offset);satisfied=!!normal&&Math.abs(dot3(normal,q as Vec3)+offset)<=DYNAMIC_GEOMETRY_EPSILON;}}return{...constraint,status:satisfied?"SATISFIED" as const:"VIOLATED" as const};});return{...scene,constraints};}
export function recomputeScene(input:MathScene,changedIds:string[]):ConstructionCommandResult{const scene=rebuildDependencies(clone(input));let graph:DependencyGraph;try{graph=new DependencyGraph(scene.semantics?.dependencies??[]);}catch{return bad("DEPENDENCY_CYCLE","semantics.dependencies","Dependency cycle rejected");}const order=graph.recomputationOrder(changedIds);let entities=scene.entities;for(const id of order){const current=entities.find(x=>x.id===id);if(current)entities=entities.map(x=>x.id===id?evaluate({...scene,entities},current):x);}const events=order.map((id,index)=>event(`recompute:${id}:${index}`,"DEPENDENCY_RECALCULATED",[id],index)),evaluated=evaluateConstraintStatuses({...scene,entities,semantics:{...scene.semantics,events:[...(scene.semantics?.events??[]),...events]}});return ok(evaluated,[],[...order],[],events);}
export function createConstructionSession(scene:MathScene):ConstructionSession{return{scene:clone(scene),selectedIds:[],toolInputs:[],history:[],future:[]};}
export function applySessionCommand(session:ConstructionSession,command:ConstructionCommand):{session:ConstructionSession;result:ConstructionCommandResult}{const result=executeConstructionCommand(session.scene,command);return result.scene?{result,session:{...session,scene:result.scene,history:[...session.history,clone(session.scene)],future:[],toolInputs:[]}}:{result,session};}
export function undoSession(session:ConstructionSession):ConstructionSession{const previous=session.history.at(-1);return previous?{...session,scene:clone(previous),history:session.history.slice(0,-1),future:[clone(session.scene),...session.future]}:session;}
export function redoSession(session:ConstructionSession):ConstructionSession{const next=session.future[0];return next?{...session,scene:clone(next),history:[...session.history,clone(session.scene)],future:session.future.slice(1)}:session;}
export function eligibleTools(scene:MathScene,selectedIds:string[]){const selected=selectedIds.map(id=>entity(scene,id)).filter(Boolean) as MathEntity[];return CONSTRUCTION_TOOLS.map(tool=>{const valid=selected.length===tool.requiredInputs&&tool.allowedInputTypes.every((types,index)=>!types.length||types.includes(selected[index]?.type));return{...tool,available:valid,reason:valid?undefined:`Requires ${tool.requiredInputs} input(s): ${tool.allowedInputTypes.map(x=>x.join("|")||"object").join(", ")}`};});}
export function inferSnaps(scene:MathScene,candidate:Vec2,tolerance:number):SnapCandidate[]{const result:SnapCandidate[]=[];for(const item of scene.entities){const q=coordinate(item);if(item.type==="point"&&q?.length===2){const distance=norm2(sub2(candidate,q as Vec2));if(distance<=tolerance)result.push({kind:"EXISTING_POINT",objectIds:[item.id],position:q as Vec2,distance,createsConstraint:false});}const line=linePoints(scene,item);if(line){const position=projectionPointToLine(candidate,...line,item.type==="segment"?"SEGMENT":item.type==="ray"?"RAY":undefined),distance=norm2(sub2(candidate,position));if(distance<=tolerance)result.push({kind:item.type==="segment"?"POINT_ON_SEGMENT":"POINT_ON_LINE",objectIds:[item.id],position,distance,createsConstraint:false});}const circle=circleData(scene,item);if(circle){const delta=sub2(candidate,circle.center),n=norm2(delta);if(n>DYNAMIC_GEOMETRY_EPSILON){const position=add2(circle.center,mul2(delta,circle.radius/n)),distance=Math.abs(n-circle.radius);if(distance<=tolerance)result.push({kind:"POINT_ON_CIRCLE",objectIds:[item.id],position,distance,createsConstraint:false});}}}return result.sort((a,b)=>a.distance-b.distance||a.objectIds.join().localeCompare(b.objectIds.join()));}
export function rendererSnapshot(scene:MathScene):RendererSnapshot{return{sceneId:scene.id,objects:scene.entities.map(item=>({id:item.id,type:item.type,label:item.label,visible:item.metadata?.adapterMetadata?.visible!==false,coordinate:coordinate(item),definition:item.metadata?.adapterMetadata?.construction as Record<string,unknown>|undefined}))};}
export function serializeConstructionSession(session:ConstructionSession):string{return JSON.stringify({scene:session.scene,selectedIds:session.selectedIds,activeTool:session.activeTool,toolInputs:session.toolInputs});}
export function deserializeConstructionSession(value:string):ConstructionSession{const parsed=JSON.parse(value) as Pick<ConstructionSession,"scene"|"selectedIds"|"activeTool"|"toolInputs">;return{...parsed,history:[],future:[]};}
