import * as THREE from "three";
import type { MathScene } from "../math-ir/index.js";
import { rendererSnapshot } from "./construction-engine.js";

export interface DynamicGeometryThreeMapping { group:THREE.Group; objects:Map<string,THREE.Object3D>; apply(scene:MathScene):void; dispose():void; }
export function createDynamicGeometryThreeMapping(initial:MathScene):DynamicGeometryThreeMapping{
  const group=new THREE.Group(),objects=new Map<string,THREE.Object3D>();group.name="mv1-dynamic-geometry";
  const clear=()=>{group.traverse(item=>{const mesh=item as THREE.Mesh;mesh.geometry?.dispose();const material=mesh.material as THREE.Material|THREE.Material[]|undefined;if(Array.isArray(material))material.forEach(x=>x.dispose());else material?.dispose();});group.clear();objects.clear();};
  const apply=(scene:MathScene)=>{clear();const snapshot=rendererSnapshot(scene),coordinates=new Map(snapshot.objects.filter(x=>x.coordinate).map(x=>[x.id,x.coordinate!]));for(const item of snapshot.objects){let object:THREE.Object3D|undefined;if(item.type==="point"&&item.coordinate){object=new THREE.Mesh(new THREE.SphereGeometry(.065,12,8),new THREE.MeshStandardMaterial({color:0xffd54f}));object.position.set(item.coordinate[0],item.coordinate[1],item.coordinate[2]??0);}else if(["line","ray","segment"].includes(item.type)){const source=scene.entities.find(x=>x.id===item.id) as Extract<MathScene["entities"][number],{type:"line"|"ray"|"segment"}>|undefined;if(!source)continue;const ids=source.type==="line"?source.pointIds:source.type==="ray"?[source.startPointId,source.throughPointId]:[source.startPointId,source.endPointId],a=coordinates.get(ids[0]),b=coordinates.get(ids[1]);if(a&&b){const start=new THREE.Vector3(a[0],a[1],a[2]??0),end=new THREE.Vector3(b[0],b[1],b[2]??0),direction=end.clone().sub(start).normalize(),extent=item.type==="segment"?end.distanceTo(start):20,from=item.type==="line"?start.clone().addScaledVector(direction,-extent):start,to=start.clone().addScaledVector(direction,extent);object=new THREE.Line(new THREE.BufferGeometry().setFromPoints(item.type==="segment"?[start,end]:[from,to]),new THREE.LineBasicMaterial({color:0x4fc3f7}));}}if(object){object.name=item.id;object.userData={semanticId:item.id,rendererOwnsMath:false};object.visible=item.visible;objects.set(item.id,object);group.add(object);}}};
  apply(initial);return{group,objects,apply,dispose:clear};
}
