import { readFileSync, writeFileSync } from "node:fs";
import { resolve } from "node:path";
import type { StructureManifest, StructureNode } from "../src/modules/nls-source-registry/structure.js";
import { validateStructureManifest } from "../src/modules/nls-source-registry/structure.js";

const manifestPath = resolve("docs/nls/na-math-kntt-structure.manifest.json");
const decisionPath = resolve(process.argv[2] ?? "docs/nls/NLS-SOURCE-02H-review-decisions.json");
const manifest = JSON.parse(readFileSync(manifestPath, "utf8")) as StructureManifest;
const decisions = JSON.parse(readFileSync(decisionPath, "utf8")) as Array<{ nodeId: string; decision: "APPROVE" | "CORRECT" | "REJECT" | "DEFER"; confirmedTitle?: string; confirmedPdfStartPage?: number; confirmedPrintedStartPage?: number; notes?: string }>;
const nodes = new Map<string, StructureNode>(); for (const book of manifest.books) for (const chapter of book.chapters) { nodes.set(chapter.id, chapter); for (const lesson of chapter.lessons ?? []) nodes.set(lesson.id, lesson); }
const seen = new Set<string>();
for (const item of decisions) { if (seen.has(item.nodeId)) throw new Error(`DUPLICATE_DECISION:${item.nodeId}`); seen.add(item.nodeId); const node = nodes.get(item.nodeId); if (!node || node.structureUsable !== false) throw new Error(`NODE_NOT_REVIEWABLE:${item.nodeId}`); if (!["APPROVE", "CORRECT", "REJECT", "DEFER"].includes(item.decision)) throw new Error(`INVALID_DECISION:${item.nodeId}`); if (["APPROVE", "CORRECT"].includes(item.decision) && (!item.confirmedTitle?.trim() || !Number.isInteger(item.confirmedPdfStartPage) || (item.confirmedPdfStartPage as number) < 1)) throw new Error(`CONFIRMATION_FIELDS_REQUIRED:${item.nodeId}`); if (item.decision === "CORRECT" && item.confirmedPrintedStartPage != null && (!Number.isInteger(item.confirmedPrintedStartPage) || item.confirmedPrintedStartPage < 1)) throw new Error(`PRINTED_PAGE_INVALID:${item.nodeId}`); }
if (decisions.length === 0) throw new Error("NO_HUMAN_DECISIONS");
for (const item of decisions) { const node = nodes.get(item.nodeId)!; if (item.decision === "DEFER") continue; if (item.decision === "REJECT") { node.structureUsable = false; node.verificationStatus = "NEEDS_REVIEW"; continue; } const previous = { title: node.title, pdfStartPage: node.pdfStartPage, printedStartPage: node.printedStartPage }; node.title = item.confirmedTitle!; node.pdfStartPage = item.confirmedPdfStartPage!; if (item.confirmedPrintedStartPage != null) node.printedStartPage = item.confirmedPrintedStartPage; node.titleStatus = "VERIFIED"; node.startBoundaryStatus = "VERIFIED"; node.sourceTraceabilityStatus = "VERIFIED"; node.orderStatus = "VERIFIED"; node.structureUsable = true; node.verificationStatus = "VERIFIED"; node.evidence.push({ sourceId: node.sourceId, pdfPageNumber: node.pdfStartPage, ...(node.printedStartPage != null ? { printedPageNumber: node.printedStartPage } : {}), evidenceType: "BOUNDARY_OCR", ocrConfidence: "HIGH_CONFIDENCE", detectedHeading: `HUMAN_SOURCE_REVIEW:${item.decision}:${JSON.stringify({ previous, confirmed: { title: node.title, pdfStartPage: node.pdfStartPage, printedStartPage: node.printedStartPage } })}` }); }
validateStructureManifest(manifest); writeFileSync(manifestPath, `${JSON.stringify(manifest, null, 2)}\n`, "utf8"); console.log("HUMAN_DECISIONS_APPLIED=PASS");
