import { readFileSync, renameSync, writeFileSync } from "node:fs";
import { resolve } from "node:path";
import { registerKnttSources } from "../src/modules/nls-source-registry/index.js";
import { validateStructureManifest, type StructureManifest, type StructureNode } from "../src/modules/nls-source-registry/structure.js";

export type ReviewDecision = { nodeId: string; decision: "APPROVE" | "CORRECT" | "REJECT" | "DEFER"; confirmedTitle?: string | null; confirmedPdfStartPage?: number | null; confirmedPrintedStartPage?: number | null; notes?: string };
const nodeMap = (m: StructureManifest) => { const r = new Map<string, StructureNode>(); for (const b of m.books) for (const c of b.chapters) { r.set(c.id, c); for (const l of c.lessons ?? []) r.set(l.id, l); } return r; };

export function applyReviewDecisions(input: StructureManifest, decisions: ReviewDecision[], pageCounts: ReadonlyMap<string, number>) {
  const m = JSON.parse(JSON.stringify(input)) as StructureManifest; if (!decisions.length) throw new Error("NO_HUMAN_DECISIONS");
  const nodes = nodeMap(m); const seen = new Set<string>(); const counts = { APPROVE: 0, CORRECT: 0, REJECT: 0, DEFER: 0 }; let startsChanged = false;
  for (const d of decisions) { if (seen.has(d.nodeId)) throw new Error(`DUPLICATE_DECISION:${d.nodeId}`); seen.add(d.nodeId); counts[d.decision]++; const n = nodes.get(d.nodeId); if (!n || n.structureUsable !== false) throw new Error(`NODE_NOT_REVIEWABLE:${d.nodeId}`); if (d.decision === "APPROVE" || d.decision === "CORRECT") { if (!d.confirmedTitle?.trim() || !Number.isInteger(d.confirmedPdfStartPage) || (d.confirmedPdfStartPage as number) < 1) throw new Error(`CONFIRMATION_FIELDS_REQUIRED:${d.nodeId}`); if ((d.confirmedPdfStartPage as number) > (pageCounts.get(n.sourceId) ?? 0)) throw new Error(`PDF_PAGE_OUT_OF_RANGE:${d.nodeId}`); } if (d.confirmedPrintedStartPage != null && (!Number.isInteger(d.confirmedPrintedStartPage) || d.confirmedPrintedStartPage < 1)) throw new Error(`PRINTED_PAGE_INVALID:${d.nodeId}`); }
  for (const d of decisions) { const n = nodes.get(d.nodeId)!; if (d.decision === "DEFER") continue; if (d.decision === "REJECT") { n.structureUsable = false; n.verificationStatus = "NEEDS_REVIEW"; n.evidence.push({ sourceId: n.sourceId, pdfPageNumber: n.pdfStartPage ?? 1, evidenceType: "HUMAN_SOURCE_REVIEW", detectedHeading: `REJECT:${d.nodeId}${d.notes ? `:${d.notes}` : ""}` }); continue; } const previous = { title: n.title, pdfStartPage: n.pdfStartPage, printedStartPage: n.printedStartPage }; n.title = d.confirmedTitle!; n.pdfStartPage = d.confirmedPdfStartPage!; if (d.confirmedPrintedStartPage != null) n.printedStartPage = d.confirmedPrintedStartPage; startsChanged = true; n.titleStatus = "VERIFIED"; n.startBoundaryStatus = "VERIFIED"; n.sourceTraceabilityStatus = "VERIFIED"; n.orderStatus = "VERIFIED"; n.structureUsable = true; n.verificationStatus = "VERIFIED"; n.evidence.push({ sourceId: n.sourceId, pdfPageNumber: n.pdfStartPage, ...(n.printedStartPage != null ? { printedPageNumber: n.printedStartPage } : {}), evidenceType: "HUMAN_SOURCE_REVIEW", detectedHeading: JSON.stringify({ verificationMethod: "HUMAN_SOURCE_REVIEW", reviewDecision: d.decision, reviewedNodeId: n.id, previousValue: previous, confirmedValue: { title: n.title, pdfStartPage: n.pdfStartPage, printedStartPage: n.printedStartPage }, notes: d.notes ?? "" }) }); }
  if (startsChanged) for (const b of m.books) for (const c of b.chapters) { const s = [c, ...(c.lessons ?? [])]; for (let i = 0; i < s.length; i++) { const cur = s[i], next = s[i + 1]; if (cur.pdfStartPage != null && next?.pdfStartPage != null && next.pdfStartPage > cur.pdfStartPage) { cur.pdfEndPage = next.pdfStartPage - 1; cur.endBoundaryStatus = "DERIVED"; } else if (cur.pdfStartPage != null && b.pageCount >= cur.pdfStartPage) { cur.pdfEndPage = b.pageCount; cur.endBoundaryStatus = "DERIVED"; } } }
  validateStructureManifest(m); return { manifest: m, counts };
}

if (process.argv[1]?.match(/apply-nls-review-decisions\.(ts|js)$/)) { const p = resolve("docs/nls/na-math-kntt-structure.manifest.json"); const input = JSON.parse(readFileSync(p, "utf8")) as StructureManifest; const decisions = JSON.parse(readFileSync(resolve(process.argv[2] ?? "docs/nls/NLS-SOURCE-02H-review-decisions.json"), "utf8")) as ReviewDecision[]; const reg = registerKnttSources(process.env.NA_MATH_NLS_SOURCE_ROOT ?? "D:\\NA-MATH-NLS-AI-SOURCES"); const r = applyReviewDecisions(input, decisions, new Map(reg.sources.map((s) => [s.sourceId, s.pageCount]))); const tmp = `${p}.tmp`; writeFileSync(tmp, `${JSON.stringify(r.manifest, null, 2)}\n`, "utf8"); renameSync(tmp, p); const ns = [...nodeMap(r.manifest).values()]; console.log(`HUMAN_DECISIONS_APPLIED=PASS\nAPPROVED_DECISIONS=${r.counts.APPROVE}\nCORRECTED_DECISIONS=${r.counts.CORRECT}\nREJECTED_DECISIONS=${r.counts.REJECT}\nDEFERRED_DECISIONS=${r.counts.DEFER}\nREMAINING_REVIEW_NODES=${ns.filter((n) => n.structureUsable === false).length}\nSTRUCTURE_USABLE_CHAPTERS=${ns.filter((n) => n.nodeType === "CHAPTER" && n.structureUsable).length}\nSTRUCTURE_USABLE_LESSONS=${ns.filter((n) => n.nodeType === "LESSON" && n.structureUsable).length}`); }
