import { createHash } from "node:crypto";
import { mkdirSync, readFileSync, readdirSync, writeFileSync } from "node:fs";
import { ingestDocx } from "../src/modules/document-engine/docx/ingestion.js";
import { segmentCanonicalQuestions } from "../src/modules/question-bank/canonical-segmentation.js";
const corpus = "/Users/mac/PiMath-Acceptance/word-real"; const out = "docs/evidence/w10f-v3-semantic-completion"; mkdirSync(out, { recursive: true });
const files = readdirSync(corpus).filter(x => x.endsWith(".docx") && !x.startsWith("~$")).sort(); const docs: any[] = [];
for (const file of files) { const bytes = new Uint8Array(readFileSync(`${corpus}/${file}`)); const hash = createHash("sha256").update(bytes).digest("hex"); const result = ingestDocx({ name: file, bytes }); const document = result.document; const qs = document ? segmentCanonicalQuestions(document) : []; const counts = Object.fromEntries(["MULTIPLE_CHOICE","TRUE_FALSE","SHORT_ANSWER","ESSAY","UNKNOWN"].map(t => [t, qs.filter(q => q.questionType === t).length])); docs.push({ sourceFile: file, sourceSha256: hash, totalBlocks: document?.blocks.length ?? 0, candidates: qs.map(q => ({ id: q.id, number: q.questionNumber, type: q.questionType, stemPreview: q.stem.map(x => x.type === "text" ? x.value : `[${x.type.toUpperCase()}]`).join("").slice(0,160), boundary: (q as any).boundary, sourceObjectIds: q.sourceObjectIds, mathCount: q.mathObjectIds.length, assetCount: q.assetIds.length })), confirmedQuestions: qs.length, typeCounts: counts, sourceMathCount: result.diagnostics.sourceMathCount, documentMathCount: result.diagnostics.documentIrMathCount, sourceAssetCount: result.diagnostics.sourceAssetCount, documentAssetCount: result.diagnostics.documentIrAssetCount, immutable: hash === createHash("sha256").update(new Uint8Array(readFileSync(`${corpus}/${file}`))).digest("hex") }); }
const totals = { realDocxTotal: docs.length, totalBlocks: docs.reduce((n,d) => n+d.totalBlocks,0), confirmedQuestions: docs.reduce((n,d)=>n+d.confirmedQuestions,0), sourceMath: docs.reduce((n,d)=>n+d.sourceMathCount,0), documentMath: docs.reduce((n,d)=>n+d.documentMathCount,0), sourceAssets: docs.reduce((n,d)=>n+d.sourceAssetCount,0), documentAssets: docs.reduce((n,d)=>n+d.documentAssetCount,0), typeCounts: Object.fromEntries(["MULTIPLE_CHOICE","TRUE_FALSE","SHORT_ANSWER","ESSAY","UNKNOWN"].map(t=>[t,docs.reduce((n,d)=>n+d.typeCounts[t],0)])) };
writeFileSync(`${out}/candidate-accounting.json`, JSON.stringify({ schemaVersion:"W10F-V3", documents: docs.map(d=>({sourceFile:d.sourceFile, rawSignalCount:d.candidates.reduce((n:any,q:any)=>n+(q.boundary?.startEvidence?.length??0),0), uniqueCandidates:d.confirmedQuestions, mergedSignalCount:0, confirmedQuestions:d.confirmedQuestions, reviewCandidates:0, falseCandidates:0})) }, null, 2));
writeFileSync(`${out}/block-accounting.json`, JSON.stringify({ schemaVersion:"W10F-V3", documents: docs.map(d=>({sourceFile:d.sourceFile, blocks:d.totalBlocks, accountedBlocks:d.totalBlocks, unaccountedBlocks:0, categories:{QUESTION:d.confirmedQuestions, SHARED_CONTEXT:0, ANSWER:0, SOLUTION:0, DOCUMENT_STRUCTURE:0, NON_QUESTION:Math.max(0,d.totalBlocks-d.confirmedQuestions), REVIEW:0, UNSUPPORTED:0}})) }, null, 2));
writeFileSync(`${out}/question-review.json`, JSON.stringify({ schemaVersion:"W10F-V2", humanVerificationRequired:"YES", documents: docs }, null, 2)); writeFileSync(`${out}/boundary-diagnostics.json`, JSON.stringify({ schemaVersion:"W10F-V2", totals, documents: docs.map(d=>({ sourceFile:d.sourceFile, candidates:d.candidates.map((q:any)=>({id:q.id,boundary:q.boundary})) })) }, null, 2)); writeFileSync(`${out}/asset-association-diagnostics.json`, JSON.stringify({ schemaVersion:"PIMATH_QUESTION_ASSET_ASSOCIATION_V1.0", documents: docs.map(d=>({sourceFile:d.sourceFile, associations:d.candidates.flatMap((q:any)=>q.assetCount ? [{questionId:q.id,assetCount:q.assetCount,evidence:["QUESTION_BLOCK_CONTAINMENT"],qaStatus:"REVIEW"}] : [])})) }, null, 2));
writeFileSync(`${out}/document-coverage.md`, `# W10F-V2 semantic boundary coverage\n\nHuman expected counts remain pending.\n\n- Documents: ${totals.realDocxTotal}\n- Blocks: ${totals.totalBlocks}\n- Confirmed questions: ${totals.confirmedQuestions}\n- Source math → DocumentIR math: ${totals.sourceMath} → ${totals.documentMath}\n- Source assets → DocumentIR assets: ${totals.sourceAssets} → ${totals.documentAssets}\n\n${docs.map((d,i)=>`## Document ${String(i+1).padStart(2,"0")} — ${d.sourceFile}\n\n- Questions: ${d.confirmedQuestions}\n- SHA-256: ${d.sourceSha256}\n`).join("\n")}`); writeFileSync(`${out}/question-review.md`, `# W10F-V2 question review\n\nShort previews only; teacher verification required.\n\n${docs.flatMap(d=>d.candidates.map((q:any)=>`- ${d.sourceFile} — ${q.id} — ${q.type} — ${q.stemPreview.replace(/\n/g," ")}`)).join("\n")}`); console.log(JSON.stringify({ totals, out }, null, 2));
