import { execFileSync } from "node:child_process";
import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { join, resolve } from "node:path";
import { registerKnttSources } from "../src/modules/nls-source-registry/index.js";
import type { StructureManifest, StructureNode } from "../src/modules/nls-source-registry/structure.js";

const root = resolve(".nls-review", "source-02h");
const manifest = JSON.parse(readFileSync(resolve("docs/nls/na-math-kntt-structure.manifest.json"), "utf8")) as StructureManifest & { pageMappingRegions?: unknown[] };
const sourceRoot = process.env.NA_MATH_NLS_SOURCE_ROOT ?? "D:\\NA-MATH-NLS-AI-SOURCES";
const registry = registerKnttSources(sourceRoot);
const byId = new Map<string, (typeof registry.sources)[number]>(registry.sources.map((source) => [source.sourceId, source]));
const nodes: StructureNode[] = manifest.books.flatMap((book) => book.chapters.flatMap((chapter) => [chapter, ...(chapter.lessons ?? [])])).filter((node) => node.structureUsable === false);
if (nodes.length !== 27) throw new Error(`REVIEW_NODE_SCOPE_INVALID:${nodes.length}`);
mkdirSync(root, { recursive: true });
const pageSet = new Map<string, Set<number>>();
for (const node of nodes) if (node.pdfStartPage != null) { const pages = pageSet.get(node.sourceId) ?? new Set<number>(); for (const page of [node.pdfStartPage - 1, node.pdfStartPage, node.pdfStartPage + 1]) if (page >= 1) pages.add(page); pageSet.set(node.sourceId, pages); }
const files = new Map<string, string[]>();
for (const [sourceId, pages] of pageSet) { const source = byId.get(sourceId); if (!source) throw new Error(`SOURCE_NOT_REGISTERED:${sourceId}`); const dir = join(root, sourceId); mkdirSync(dir, { recursive: true }); const paths: string[] = []; for (const page of [...pages].sort((a, b) => a - b)) { const base = join(dir, `pdf-page-${String(page).padStart(4, "0")}`); const out = `${base}.jpg`; if (!existsSync(out)) execFileSync("pdftoppm", ["-f", String(page), "-l", String(page), "-singlefile", "-jpeg", "-r", "150", join(sourceRoot, source.filename), base], { windowsHide: true, stdio: "ignore" }); paths.push(out.replaceAll("\\", "/")); } files.set(sourceId, paths); }
const packet = nodes.map((node) => ({ nodeId: node.id, sourceId: node.sourceId, nodeType: node.nodeType, parentId: node.parentId, order: node.order, currentTitle: node.title, tocTitle: node.evidence.find((e) => e.evidenceType === "TOC_OCR")?.detectedHeading ?? null, titleStatus: node.titleStatus ?? "UNKNOWN", orderStatus: node.orderStatus ?? "UNKNOWN", startBoundaryStatus: node.startBoundaryStatus ?? "UNKNOWN", endBoundaryStatus: node.endBoundaryStatus ?? "UNKNOWN", printedStartPage: node.printedStartPage, predictedPdfPage: node.pdfStartPage, currentPdfStartPage: node.pdfStartPage, reviewReason: node.structureUsable ? null : "Human confirmation required for title/start boundary", tocEvidence: node.evidence.filter((e) => e.evidenceType === "TOC_OCR"), directHeadingEvidence: node.evidence.filter((e) => e.evidenceType === "BOUNDARY_OCR"), pageMappingEvidence: manifest.pageMappingRegions ?? [], recommendedDecision: "VISUALLY_REVIEW", localReviewFiles: files.get(node.sourceId) ?? [] }));
writeFileSync(resolve("docs/nls/NLS-SOURCE-02H-review-decisions.template.json"), `${JSON.stringify(packet.map((item) => ({ nodeId: item.nodeId, decision: null, confirmedTitle: null, confirmedPdfStartPage: null, confirmedPrintedStartPage: null, notes: "" })), null, 2)}\n`, "utf8");
const lines = ["# NLS-SOURCE-02H local visual review index", "", "Generated from exactly 27 blocked nodes. Images are local and ignored; no OCR or approvals were performed.", "", ...packet.map((item) => `## ${item.nodeId}\n- Source: ${item.sourceId}; type: ${item.nodeType}; parent: ${item.parentId}; order: ${item.order}\n- Current title: ${item.currentTitle}\n- TOC evidence: ${item.tocTitle ?? "UNKNOWN"}\n- Printed/PDF start: ${item.printedStartPage ?? "UNKNOWN"} / ${item.predictedPdfPage ?? "UNKNOWN"}\n- Reason: ${item.reviewReason}\n- Review files: ${item.localReviewFiles.length ? item.localReviewFiles.map((file) => `[${file.split("/").pop()}](../../${file})`).join(", ") : "No candidate page available; inspect source PDF manually."}`)];
writeFileSync(join(root, "REVIEW-INDEX.md"), `${lines.join("\n\n")}\n`, "utf8");
writeFileSync(resolve("docs/nls/NLS-SOURCE-02H-QA.md"), `# NLS-SOURCE-02H human review package\n\nPhase A only: exactly 27 blocked nodes were packaged for visual review. No nodes were approved and no OCR was run.\n\nReview images: local \`.nls-review/source-02h/\` (ignored, not committed).\nDecision template: \`docs/nls/NLS-SOURCE-02H-review-decisions.template.json\`.\nReview index: local \`.nls-review/source-02h/REVIEW-INDEX.md\`.\n\n| SOURCE_ID | BLOCKED_CHAPTERS | BLOCKED_LESSONS | REVIEW_NODES | REVIEW_PAGES_REQUIRED | STATUS |\n|---|---:|---:|---:|---:|---|\n${manifest.books.map((book) => { const ns = nodes.filter((n) => n.sourceId === book.sourceId); return `| ${book.sourceId} | ${ns.filter((n) => n.nodeType === "CHAPTER").length} | ${ns.filter((n) => n.nodeType === "LESSON").length} | ${ns.length} | ${(files.get(book.sourceId) ?? []).length} | REVIEW_REQUIRED |`; }).join("\n")}\n\nGlobal: total review nodes=27; unique review pages=${[...files.values()].reduce((n, f) => n + f.length, 0)}; decision template=UNPOPULATED; apply script=READY; new OCR pages=0; full-book OCR=NO.\n`, "utf8");
console.log(`REVIEW_NODE_SCOPE_QA=PASS\nTOTAL_REVIEW_NODES=${nodes.length}\nTOTAL_UNIQUE_REVIEW_PAGES=${[...files.values()].reduce((n, f) => n + f.length, 0)}\nNEW_OCR_PAGES=0\nREVIEW_IMAGES_COMMITTED=0`);
