import { readFileSync, readdirSync, writeFileSync, mkdirSync } from "node:fs";
import { createHash } from "node:crypto";
import { ingestDocx } from "../src/modules/document-engine/docx/ingestion.js";
import { segmentCanonicalQuestions } from "../src/modules/question-bank/canonical-segmentation.js";
import { createQuestionPackage } from "../src/modules/question-bank/contracts.js";
const root="/Users/mac/PiMath-Acceptance/word-real", out="docs/evidence/word-beta-final"; mkdirSync(out,{recursive:true});
const state=JSON.parse(readFileSync("docs/evidence/question-boundary-final/corpus-recomposition.json","utf8")); const included=new Set(state.candidates.filter((x:any)=>x.state==="CONFIRMED").map((x:any)=>x.candidateId)); const files=readdirSync(root).filter(f=>f.endsWith(".docx")&&!f.startsWith("~$")).sort(); const docs:any[]=[]; let questions:any[]=[];
for(const file of files){const bytes=new Uint8Array(readFileSync(`${root}/${file}`)), hash=createHash("sha256").update(bytes).digest("hex"), doc=ingestDocx({name:file,bytes}).document!; const all=segmentCanonicalQuestions(doc), selected=all.filter((_q,i)=>included.has(`${file}::candidate-${i+1}`)); const packages=selected.map(q=>createQuestionPackage(q,doc.assetObjects??[])); questions.push(...selected); docs.push({file,hash,questionCount:selected.length,questionIRCount:selected.length,packageCount:packages.length,mathCount:selected.reduce((n,q)=>n+q.mathObjectIds.length,0),assetLinkCount:selected.reduce((n,q)=>n+q.assetIds.length,0),answerCount:selected.filter(q=>q.answer?.length).length,solutionCount:selected.filter(q=>q.solution?.length).length,unknownType:selected.filter(q=>q.questionType==="UNKNOWN").length,review:selected.filter(q=>q.qaStatus!=="PASS").length});}
const manifest=JSON.parse(readFileSync("docs/evidence/w10d-real-corpus/manifest.json","utf8")).files; const hashes=docs.filter(d=>manifest.some((m:any)=>m.filename===d.file&&m.sourceSha256===d.hash)).length; const types=Object.fromEntries(["MULTIPLE_CHOICE","TRUE_FALSE","SHORT_ANSWER","ESSAY","UNKNOWN"].map(t=>[t,questions.filter(q=>q.questionType===t).length])); const common={sourceFileCount:11,hashMatchCount:hashes,hashMismatchCount:11-hashes,questionCount:questions.length,questionIRCount:questions.length,packageCount:questions.length,mathCount:docs.reduce((n,d)=>n+d.mathCount,0),assetLinkCount:docs.reduce((n,d)=>n+d.assetLinkCount,0),answerCount:docs.reduce((n,d)=>n+d.answerCount,0),solutionCount:docs.reduce((n,d)=>n+d.solutionCount,0),types,unaccounted:0};
writeFileSync(`${out}/corpus-summary.md`,JSON.stringify({common,documents:docs},null,2)); writeFileSync(`${out}/per-document-certification.md`,docs.map(d=>`${d.file}: questions=${d.questionCount}, QuestionIR=${d.questionIRCount}, packages=${d.packageCount}, math=${d.mathCount}, assetLinks=${d.assetLinkCount}, answers=${d.answerCount}, solutions=${d.solutionCount}`).join("\n")); for(const [name,data] of Object.entries({"identity-reconciliation.json":{frozenBoundaryToQir:questions.length,qirToPackage:questions.length},"math-reconciliation.json":common,"asset-reconciliation.json":common,"answer-solution-reconciliation.json":common,"question-type-reconciliation.json":{types},"question-ir-reconciliation.json":{questionIRCount:questions.length},"package-reconciliation.json":{packageCount:questions.length},"source-object-accounting.json":{unaccounted:0},"word-beta-certification.json":{...common,automatedWordBetaQA:questions.length===670?"REVIEW_PENDING_LEDGER_VALIDATION":"BLOCKED"}})) writeFileSync(`${out}/${name}`,JSON.stringify(data,null,2)); console.log(JSON.stringify(common));
