import { readFileSync } from "node:fs";
import { join } from "node:path";
import { ingestDocx } from "../src/modules/document-engine/docx/ingestion.js";
import { segmentCanonicalQuestions } from "../src/modules/question-bank/canonical-segmentation.js";
import { createQuestionPackage } from "../src/modules/question-bank/contracts.js";

export interface W10QuestionPreview { id: string; questionNumber?: string | number; questionType: string; stemPreview: string; mathCount: number; assetCount: number; tableCount: number; answerStatus: string; solutionStatus: string; qaStatus: string; issues: string[] }
export interface W10DocumentReport { sourceFile: string; sourceSha256: string; docxIngestStatus: string; paragraphCount: number; tableCount: number; sourceMathCount: number; extractedMathCount: number; documentIrMathCount: number; questionIrMathCount: number; questionPackageMathCount: number; sourceAssetCount: number; extractedAssetCount: number; documentIrAssetCount: number; questionIrAssetCount: number; questionPackageAssetCount: number; detectedQuestionCount: number; questionTypeCounts: Record<string, number>; answerCount: number; solutionCount: number; reviewCount: number; quarantinedCount: number; unsupportedCount: number; qaStatus: string; questions: W10QuestionPreview[] }

export function runW10Acceptance(fileNames: string[]): W10DocumentReport[] {
  return fileNames.map(sourceFile => {
    const result = ingestDocx({ name: sourceFile, bytes: new Uint8Array(readFileSync(join("tests/golden/docx", sourceFile))) });
    const questions = result.document ? segmentCanonicalQuestions(result.document) : [];
    const packages = questions.map(question => createQuestionPackage(question, result.assetLedger.assets));
    const questionTypeCounts = Object.fromEntries(["MULTIPLE_CHOICE", "TRUE_FALSE", "SHORT_ANSWER", "ESSAY", "UNKNOWN"].map(type => [type, questions.filter(question => question.questionType === type).length]));
    const previews = questions.map((question, index) => ({ id: question.id, questionNumber: question.questionNumber, questionType: question.questionType, stemPreview: question.stem.map(block => block.type === "text" ? block.value : block.type === "math" ? `[MATH:${block.math.id ?? "unknown"}]` : block.type === "figure" ? `[FIGURE:${block.figureId}]` : "[TABLE]").join("").slice(0, 240), mathCount: question.mathObjectIds.length, assetCount: question.assetIds.length, tableCount: question.tableIds.length, answerStatus: question.answer?.length ? "MAPPED" : "NONE", solutionStatus: question.solution?.length ? "MAPPED" : "NONE", qaStatus: packages[index]?.qaStatus ?? question.qaStatus, issues: question.issues.map(issue => issue.code) }));
    const issueCounts = { reviewCount: result.issues.filter(issue => issue.status === "REVIEW").length, quarantinedCount: result.issues.filter(issue => issue.status === "QUARANTINED").length, unsupportedCount: result.issues.filter(issue => issue.status === "UNSUPPORTED").length };
    return { sourceFile, sourceSha256: result.provenance.sourceSha256 ?? "", docxIngestStatus: result.document ? "PARSED" : "FAILED", paragraphCount: result.diagnostics.paragraphCount, tableCount: result.diagnostics.tableCount, sourceMathCount: result.diagnostics.sourceMathCount, extractedMathCount: result.diagnostics.extractedMathCount, documentIrMathCount: result.diagnostics.documentIrMathCount, questionIrMathCount: questions.reduce((count, question) => count + question.mathObjectIds.length, 0), questionPackageMathCount: packages.reduce((count, pkg) => count + pkg.mathObjectIds.length, 0), sourceAssetCount: result.diagnostics.sourceAssetCount, extractedAssetCount: result.diagnostics.extractedAssetCount, documentIrAssetCount: result.diagnostics.documentIrAssetCount, questionIrAssetCount: questions.reduce((count, question) => count + question.assetIds.length + question.tableIds.length, 0), questionPackageAssetCount: packages.reduce((count, pkg) => count + pkg.assets.length, 0), detectedQuestionCount: questions.length, questionTypeCounts, answerCount: questions.filter(question => question.answer?.length).length, solutionCount: questions.filter(question => question.solution?.length).length, ...issueCounts, qaStatus: result.qaStatus, questions: previews };
  });
}

if (process.argv[1]?.endsWith("run-w10-real-word-acceptance.ts")) console.log(JSON.stringify(runW10Acceptance(["GOLDEN_00_FOUNDATION.docx", "GOLDEN_01_TEXT_STYLES.docx", "GOLDEN_02_NATIVE_MATH.docx", "GOLDEN_03_GEOMETRY_SVG.docx", "GOLDEN_04_LAYOUT_PAGINATION.docx", "GOLDEN_05_COMBINED_MATH_DOCUMENT.docx"]), null, 2));
