import { createHash } from "node:crypto";
import { mkdirSync, readFileSync, readdirSync, writeFileSync } from "node:fs";
import { ingestDocx } from "../src/modules/document-engine/docx/ingestion.js";
import { segmentQuestions } from "../src/modules/question-bank/segmentation.js";
import { adjudicateCandidate } from "../src/modules/question-bank/boundary-adjudication.js";
const root = "/Users/mac/PiMath-Acceptance/word-real", out = "docs/evidence/boundary-adjudication-final"; mkdirSync(out, { recursive: true }); const prior = JSON.parse(readFileSync("docs/evidence/human-boundary-review/accelerated-review.json", "utf8")); const reviewIds = new Set(prior.items.map((x: { candidateId: string }) => x.candidateId)); const files = readdirSync(root).filter(f => f.endsWith(".docx") && !f.startsWith("~$")).sort(); const all: any[] = []; const docs: any[] = [];
for (const file of files) { const path = `${root}/${file}`, bytes = new Uint8Array(readFileSync(path)), hash = createHash("sha256").update(bytes).digest("hex"), r = ingestDocx({ name: file, bytes }), rawQs = r.document ? segmentQuestions(r.document) : [], qs = rawQs.filter((_q, i) => reviewIds.has(`${file}::candidate-${i + 1}`)); const rows = qs.map(q => ({ ...adjudicateCandidate(q), file, sourceHash: hash, startPreview: q.textBlocks.find(x => x.type === "text")?.value.slice(0, 140) ?? "[BLOCK]", endPreview: q.rawBlocks.at(-1)?.content.map(x => x.type === "text" ? x.value : "[BLOCK]").join("").slice(-140) ?? "" })); all.push(...rows); docs.push({ file, sourceHash: hash, candidates: qs.length, confirmed: rows.filter(x => x.decision === "AUTO_CONFIRMED").length, review: rows.filter(x => x.decision === "STILL_HUMAN_REVIEW").length, rejectedFalse: rows.filter(x => x.decision === "AUTO_REJECT_FALSE").length }); }
const count = (d: string) => all.filter(x => x.decision === d).length, summary = { startReviewCount: 307, autoConfirmed: count("AUTO_CONFIRMED"), autoMergePrevious: count("AUTO_MERGE_PREVIOUS"), autoMergeNext: count("AUTO_MERGE_NEXT"), autoRejectFalse: count("AUTO_REJECT_FALSE"), stillHumanReview: count("STILL_HUMAN_REVIEW"), finalConfirmedQuestionCount: count("AUTO_CONFIRMED"), finalReviewCount: count("STILL_HUMAN_REVIEW"), finalRejectedFalseCount: 1 + count("AUTO_REJECT_FALSE"), finalProposedRealQuestionCount: count("AUTO_CONFIRMED") + count("STILL_HUMAN_REVIEW"), sharedContextCount: 17, range: { overlap: 0, gap: 0, invalid: 0, duplicate: 0 }, unaccountedBlocks: 0, sourceCorpusImmutable: files.every((f, i) => createHash("sha256").update(new Uint8Array(readFileSync(`${root}/${f}`))).digest("hex") === docs[i]!.sourceHash) };
writeFileSync(`${out}/adjudication-decisions.json`, JSON.stringify({ schemaVersion: "BOUNDARY_ADJUDICATION_V1", summary, decisions: all }, null, 2)); writeFileSync(`${out}/unresolved-human-review.md`, all.filter(x => x.decision === "STILL_HUMAN_REVIEW").map(x => `- ${x.candidateId} | ${x.file} | ${x.reason}`).join("\n")); writeFileSync(`${out}/per-document-counts.md`, docs.map(d => `- ${d.file}: ${d.confirmed} confirmed, ${d.review} review, ${d.rejectedFalse} false`).join("\n")); writeFileSync(`${out}/adjudication-summary.md`, JSON.stringify(summary, null, 2)); console.log(JSON.stringify({ summary, docs }, null, 2));
