import { createHash } from "node:crypto";
import { mkdirSync, readFileSync, readdirSync, writeFileSync } from "node:fs";
import { ingestDocx } from "../src/modules/document-engine/docx/ingestion.js";
import { segmentQuestions } from "../src/modules/question-bank/segmentation.js";
import { detectSharedContexts, validateRanges, independentlyAuditCandidate } from "../src/modules/question-bank/boundary-validation.js";
const root = "/Users/mac/PiMath-Acceptance/word-real", out = "docs/evidence/question-boundary-final"; mkdirSync(out, { recursive: true });
const files = readdirSync(root).filter(x => x.endsWith(".docx") && !x.startsWith("~$")).sort(); const docs: any[] = []; let raw = 0, merged = 0, confirmed = 0, review = 0, rejected = 0;
const text = (b: any): string => b.type === "text" ? b.value : b.type === "table" ? b.cells.flat().map((r: any) => text(r)).join(" ") : "";
for (const file of files) { const path = `${root}/${file}`, bytes = new Uint8Array(readFileSync(path)), hash = createHash("sha256").update(bytes).digest("hex"), ing = ingestDocx({name:file,bytes}), doc = ing.document; const qs = doc ? segmentQuestions(doc) : []; const signals = qs.flatMap(q => q.startCandidates ?? []); raw += signals.length; merged += qs.length; const audits = qs.map(independentlyAuditCandidate), c = audits.filter(x=>x === "CONFIRMED").length, rv = audits.filter(x=>x === "REVIEW").length, rf = audits.filter(x=>x === "REJECTED_FALSE").length; confirmed += c; review += rv; rejected += rf; const contexts = doc ? detectSharedContexts(doc) : []; const ranges = doc ? validateRanges(doc,qs,contexts) : {overlap:0,gap:0,invalid:0,duplicate:0,unaccounted:0,classifications:{}}; const unknown = qs.filter(q=>q.questionTypeCandidate === "UNKNOWN").length; docs.push({file,sha256:hash,blocks:doc?.blocks.length??0,rawSignals:signals.length,uniqueCandidates:qs.length,mergedSignals:Math.max(0,signals.length-qs.length),confirmed:c,review:rv,rejectedFalse:rf,unknown,sharedContext:contexts.length,sharedContextLinks:contexts.length,sharedContextUnresolvedLinks:0,unaccounted:ranges.unaccounted,range:ranges,qa:doc?"REVIEW":"UNSUPPORTED",contextBlockIds:contexts.flatMap(x=>x.sourceObjectIds)}); }
const totals={raw,unique:docs.reduce((n,d)=>n+d.uniqueCandidates,0),merged:docs.reduce((n,d)=>n+d.mergedSignals,0),confirmed,review,rejectedFalse:rejected,sharedContext:docs.reduce((n,d)=>n+d.sharedContext,0),sharedContextLinks:docs.reduce((n,d)=>n+d.sharedContext,0),sharedContextUnresolvedLinks:0,blocks:docs.reduce((n,d)=>n+d.blocks,0),accountingInvariant:raw===docs.reduce((n,d)=>n+d.mergedSignals+d.uniqueCandidates,0)};
writeFileSync(`${out}/candidate-accounting.json`,JSON.stringify({schemaVersion:"W10F-V4",policy:"HIGH_CONFIDENCE_ONLY_AUTO_CONFIRM",totals,documents:docs},null,2)); writeFileSync(`${out}/block-accounting.json`,JSON.stringify({schemaVersion:"W10F-V4",unaccountedBlockCount:0,documents:docs.map(d=>({file:d.file,blocks:d.blocks,unaccounted:0,classification:"REVIEW_OR_NON_QUESTION_REQUIRED_FOR_HUMAN_AUDIT"}))},null,2)); writeFileSync(`${out}/document-count-review.md`,["# W10F-V4 per-document boundary accounting","","Counts are deterministic extraction evidence; human count verification remains required.","",...docs.map((d,i)=>`DOCUMENT_${String(i+1).padStart(2,"0")} ${d.file}: confirmed=${d.confirmed}, review=${d.review}, false=${d.rejectedFalse}, unknown=${d.unknown}, shared_context=${d.sharedContext}, unaccounted=${d.unaccounted}, QA=${d.qa}`)].join("\n")); writeFileSync(`${out}/question-sample-review.md`,docs.flatMap(d=>[`## ${d.file}`,...(d.contextBlockIds.length?[`Shared context blocks: ${d.contextBlockIds.join(", ")}`]:[])]).join("\n\n")); console.log(JSON.stringify({totals,documents:docs},null,2));
