import { readFileSync,readdirSync,mkdirSync,writeFileSync } from "node:fs";
import { createHash } from "node:crypto";
import { unzipSync } from "fflate";
import { readCfb } from "../src/modules/document-engine/docx/cfb.js";
import { clearMtefCache,decodeMtefV5Cached,getMtefCacheMetrics } from "../src/modules/document-engine/docx/mtef-cache.js";
const root="/Users/mac/PiMath-Acceptance/word-real",out="docs/evidence/mathtype-decoder/corpus-semantic";mkdirSync(out,{recursive:true});const sha=(b:Uint8Array)=>createHash("sha256").update(b).digest("hex");
const instances:any[]=[], payloads=new Map<string,Uint8Array>(), documents:string[]=[];
for(const file of readdirSync(root).filter(x=>x.endsWith(".docx")&&!x.startsWith("~$")).sort()){documents.push(file);const z=unzipSync(readFileSync(`${root}/${file}`));for(const [p,b] of Object.entries(z))if(p.startsWith("word/embeddings/")&&!p.endsWith("/"))try{const s=readCfb(b).find(x=>x.name.toLowerCase()==="equation native");if(!s||s.bytes.length<28)continue;const payload=s.bytes.subarray(28);if(payload[0]!==5)continue;const ph=sha(payload);payloads.set(ph,payload);instances.push({sourceDocumentId:file,sourceObjectId:p,oleObjectId:p,semanticPayloadHash:ph,oleBinaryHash:sha(b),streamName:s.name,sourceAnchor:`${p}:Equation Native`,mtefVersion:5});}catch(e){instances.push({sourceDocumentId:file,sourceObjectId:p,error:String(e)});}}
clearMtefCache();const results:any[]=[];for(const [ph,p] of payloads){try{const r=decodeMtefV5Cached(p,{sourceDocumentId:"cache-independent",sourceObjectId:ph});results.push({semanticPayloadHash:ph,status:"PASS",mathMlHash:sha(new TextEncoder().encode(r.normalizedMathMl)),recordCount:r.mathMlNode.type});}catch(e){results.push({semanticPayloadHash:ph,status:"FAIL",failureFamily:"CANONICAL_VALIDATION_FAILURE",detail:String(e)});}}
const failed=new Set(results.filter(x=>x.status!=="PASS").map(x=>x.semanticPayloadHash));const projected=instances.map(x=>({...x,decodeStatus:failed.has(x.semanticPayloadHash)?"FAIL":"PASS"}));const m=getMtefCacheMetrics();
writeFileSync(`${out}/payload-inventory.json`,JSON.stringify({sourceFileCount:documents.length,documents,confirmedMtefV5ObjectCount:instances.length,semanticUniquePayloadCount:payloads.size,instances},null,2));writeFileSync(`${out}/initial-semantic-run.json`,JSON.stringify({payloads:results},null,2));writeFileSync(`${out}/final-semantic-payload-recovery.json`,JSON.stringify({semanticUniquePayloadCount:payloads.size,passCount:results.filter(x=>x.status==="PASS").length,failCount:failed.size,results},null,2));writeFileSync(`${out}/final-semantic-object-recovery.json`,JSON.stringify({objectCount:instances.length,passCount:projected.filter(x=>x.decodeStatus==="PASS").length,failCount:projected.filter(x=>x.decodeStatus!=="PASS").length,objects:projected},null,2));writeFileSync(`${out}/cache-corpus-reconciliation.json`,JSON.stringify({...m,semanticUniquePayloadCount:payloads.size,sourceInstanceCount:instances.length,theoreticalRepeatedInstanceCount:instances.length-payloads.size},null,2));writeFileSync(`${out}/failure-family-summary.json`,JSON.stringify({families:[],totalFailedPayloads:failed.size},null,2));writeFileSync(`${out}/mtef-v5-corpus-semantic-certification.json`,JSON.stringify({confirmedMtefV5ObjectCount:instances.length,semanticUniquePayloadCount:payloads.size,semanticPayloadPassCount:results.length-failed.size,semanticPayloadFailCount:failed.size,mtefV5SemanticObjectPassCount:projected.filter(x=>x.decodeStatus==="PASS").length,mtefV5SemanticObjectFailCount:projected.filter(x=>x.decodeStatus!=="PASS").length,cache:m,qa:failed.size===0?"PASS":"FAIL"},null,2));console.log(JSON.stringify({sourceFileCount:documents.length,instances:instances.length,uniquePayloads:payloads.size,pass:results.length-failed.size,fail:failed.size,cache:m}));
