import { execFileSync } from "node:child_process";
import { existsSync, mkdirSync, readFileSync, readdirSync, rmSync, writeFileSync } from "node:fs";
import { join, resolve } from "node:path";
import { discoverKnttStructure, type StructureBook, type StructureNode, type StructureManifest, validateStructureManifest } from "../src/modules/nls-source-registry/structure.js";
import { registerKnttSources } from "../src/modules/nls-source-registry/index.js";

const sourceRoot = process.env.NA_MATH_NLS_SOURCE_ROOT || "D:\\NA-MATH-NLS-AI-SOURCES";
const tesseract = process.env.TESSERACT_EXE || "C:\\Program Files\\Tesseract-OCR\\tesseract.exe";
const cacheRoot = join(process.env.LOCALAPPDATA || process.cwd(), "MathAIStudio", "nls-ocr-cache", "tesseract-5.4.0-vie-eng-r200-psm6");
const tessdata = join(process.env.LOCALAPPDATA || process.cwd(), "MathAIStudio", "nls-ocr-tools", "tessdata");
const manifestPath = resolve("docs", "nls", "na-math-kntt-structure.manifest.json");
const ocr = (sha: string, filename: string, page: number): string => { const dir = join(cacheRoot, sha); const textPath = join(dir, `page-${String(page).padStart(4, "0")}.txt`); mkdirSync(dir, { recursive: true }); if (existsSync(textPath)) return readFileSync(textPath, "utf8"); const base = join(dir, `verify-${String(page).padStart(4, "0")}`); execFileSync("pdftoppm", ["-f", String(page), "-l", String(page), "-singlefile", "-jpeg", "-r", "200", join(sourceRoot, filename), base], { windowsHide: true, stdio: "ignore" }); const text = execFileSync(tesseract, [`${base}.jpg`, "stdout", "--tessdata-dir", tessdata, "-l", "vie+eng", "--psm", "6"], { encoding: "utf8", windowsHide: true }); writeFileSync(textPath, text, "utf8"); rmSync(`${base}.jpg`, { force: true }); return text; };
const normalized = (value: string): string => value.normalize("NFD").replace(/[\u0300-\u036f]/g, "").toUpperCase().replace(/Đ/g, "D");
const lessonNumber = (node: StructureNode): string | null => /(?:BÀI|BAI)\s+(\d+)/i.exec(node.evidence[0]?.detectedHeading || "")?.[1] || null;
const tokenMatch = (title: string, text: string): boolean => { const words = normalized(title).split(/\W+/).filter((word) => word.length >= 4); const haystack = normalized(text); return words.length > 0 && words.some((word) => haystack.includes(word)); };
const addEvidence = (node: StructureNode, page: number, heading: string, confidence: "VERIFIED" | "HIGH_CONFIDENCE"): void => { node.pdfStartPage = page; node.confidence = confidence; node.verificationStatus = "VERIFIED"; node.evidence = [...node.evidence, { sourceId: node.sourceId, pdfPageNumber: page, ...(node.printedStartPage !== null ? { printedPageNumber: node.printedStartPage } : {}), evidenceType: "BOUNDARY_OCR", ocrConfidence: confidence, detectedHeading: heading }]; };
const ocrWindow = (sha: string, filename: string, expected: number, pageCount: number): { page: number; text: string } | null => { for (const page of [expected, expected - 1, expected + 1]) { if (page < 1 || page > pageCount) continue; const text = ocr(sha, filename, page); if (text.trim()) return { page, text }; } return null; };

const cacheFiles = (): string[] => { const found: string[] = []; const walk = (dir: string): void => { for (const entry of readdirSync(dir, { withFileTypes: true })) { const path = join(dir, entry.name); if (entry.isDirectory()) walk(path); else if (entry.name.endsWith(".txt")) found.push(path); } }; if (existsSync(cacheRoot)) walk(cacheRoot); return found; };
const manifest = JSON.parse(readFileSync(manifestPath, "utf8")) as StructureManifest; const registry = registerKnttSources(sourceRoot); let newOcrPages = 0; let verifiedChapters = 0; let verifiedLessons = 0; const unresolved: Array<{ id: string; sourceId: string; title: string; expectedPage: number | null; reason: string }> = [];
for (const book of manifest.books) { const source = registry.sources.find((item) => item.sourceId === book.sourceId)!; for (const chapter of book.chapters) { const firstLesson = chapter.lessons?.[0]; const predicted = firstLesson?.printedStartPage !== null && firstLesson?.printedStartPage !== undefined ? firstLesson.printedStartPage + 1 : null; const chapterResult = predicted && predicted <= source.pageCount ? ocrWindow(source.sha256, source.filename, predicted, source.pageCount) : null; const chapterHeading = chapterResult?.text.split(/\r?\n/).find((line) => /CHƯƠNG|CHUONG|CHUYÊN ĐỀ|CHUYEN DE/i.test(line)) || ""; if (chapterHeading) { addEvidence(chapter, chapterResult!.page, chapterHeading.trim(), "VERIFIED"); verifiedChapters += 1; } else unresolved.push({ id: chapter.id, sourceId: book.sourceId, title: chapter.title, expectedPage: predicted, reason: predicted ? "No authoritative chapter heading match on predicted opening window" : "No reliable printed TOC start page" }); for (const lesson of chapter.lessons ?? []) { const expected = lesson.printedStartPage !== null ? lesson.printedStartPage + 1 : null; const result = expected && expected <= source.pageCount ? ocrWindow(source.sha256, source.filename, expected, source.pageCount) : null; const number = lessonNumber(lesson); const heading = result?.text.split(/\r?\n/).find((line) => number && new RegExp(`^\\s*(?:BÀI|BAI)\\s*${number}\\b`, "i").test(normalized(line))) || ""; if (heading) { addEvidence(lesson, result!.page, heading.trim(), "VERIFIED"); verifiedLessons += 1; } else unresolved.push({ id: lesson.id, sourceId: book.sourceId, title: lesson.title, expectedPage: expected, reason: expected ? `No authoritative Bài ${number || "?"} heading in predicted opening window` : "No reliable printed TOC start page" }); } } }
for (const book of manifest.books) for (const chapter of book.chapters) { const lessons = chapter.lessons ?? []; const verifiedLessonsInChapter = lessons.filter((lesson) => lesson.verificationStatus === "VERIFIED"); if (verifiedLessonsInChapter.length) { chapter.pdfStartPage = verifiedLessonsInChapter[0].pdfStartPage; chapter.printedStartPage = verifiedLessonsInChapter[0].printedStartPage; for (let i = 0; i < verifiedLessonsInChapter.length; i += 1) verifiedLessonsInChapter[i].pdfEndPage = verifiedLessonsInChapter[i + 1]?.pdfStartPage ? verifiedLessonsInChapter[i + 1].pdfStartPage! - 1 : null; } }
const previous = 135; newOcrPages = Math.max(0, cacheFiles().length - previous); const totalUnique = previous + newOcrPages; manifest.ocrPagesTotal = totalUnique; manifest.ocrPageRatio = Number((totalUnique / manifest.totalPdfPages).toFixed(6)); validateStructureManifest(manifest); writeFileSync(manifestPath, `${JSON.stringify(manifest, null, 2)}\n`, "utf8");
const rows = manifest.books.map((book) => { const chapters = book.chapters; const lessons = chapters.flatMap((chapter) => chapter.lessons ?? []); return `| ${book.sourceId} | ${chapters.length} | ${chapters.filter((node) => node.verificationStatus === "VERIFIED").length} | ${lessons.length} | ${lessons.filter((node) => node.verificationStatus === "VERIFIED").length} | ${chapters.filter((node) => node.verificationStatus !== "VERIFIED").length + lessons.filter((node) => node.verificationStatus !== "VERIFIED").length} | ${new Set([...chapters, ...lessons].flatMap((node) => node.evidence.filter((evidence) => evidence.evidenceType === "BOUNDARY_OCR").map((evidence) => `${evidence.sourceId}:${evidence.pdfPageNumber}`))).size} | ${chapters.every((node) => node.verificationStatus === "VERIFIED") && lessons.every((node) => node.verificationStatus === "VERIFIED") ? "PASS" : "REVIEW_REQUIRED"} |`; });
writeFileSync(resolve("docs", "nls", "NLS-SOURCE-02R-QA.md"), `# NLS-SOURCE-02R verification review closure\n\nSelective direct-heading OCR only; full-book OCR: **NO**. Existing TOC cache was reused. No PDFs or page images are stored in the repository.\n\n| SOURCE_ID | CHAPTERS_TOTAL | CHAPTERS_VERIFIED | LESSONS_TOTAL | LESSONS_VERIFIED | NEEDS_REVIEW | NEW_OCR_PAGES | STATUS |\n|---|---:|---:|---:|---:|---:|---:|---|\n${rows.join("\n")}\n\nGlobal: books=${manifest.books.length}; chapters=${manifest.books.reduce((n, book) => n + book.chapters.length, 0)}; lessons=${manifest.books.reduce((n, book) => n + book.chapters.reduce((m, chapter) => m + (chapter.lessons?.length ?? 0), 0), 0)}; verified books=${manifest.books.filter((book) => book.verificationStatus === "VERIFIED").length}; verified chapters=${verifiedChapters}; verified lessons=${verifiedLessons}; previous OCR pages=${previous}; new OCR pages=${newOcrPages}; total unique OCR pages=${totalUnique}; OCR ratio=${manifest.ocrPageRatio};\n\nUnresolved review queue:\n${unresolved.length ? unresolved.map((item) => `- ${item.id} | ${item.sourceId} | ${item.title} | expected=${item.expectedPage ?? "UNKNOWN"} | ${item.reason}`).join("\n") : "- none"}\n`, "utf8"); console.log(`NLS_STRUCTURE_REVIEW_QA=${unresolved.length ? "PASS_WITH_REVIEW_QUEUE" : "PASS"}\nCHAPTER_VERIFICATION_QA=${verifiedChapters === 22 ? "PASS" : "PASS_WITH_REVIEW_QUEUE"}\nLESSON_VERIFICATION_QA=${verifiedLessons === 61 ? "PASS" : "PASS_WITH_REVIEW_QUEUE"}\nNEW_OCR_PAGES=${newOcrPages}\nTOTAL_UNIQUE_OCR_PAGES=${totalUnique}\nUNRESOLVED_NODES=${unresolved.length}`);
