import assert from "node:assert/strict";
import { spawnSync } from "node:child_process";
import { loadTaskSpec } from "../automation/orchestrator/orchestrator.ts";
import { FakeCodingAgent, LocalProcessAgentAdapter, type CodingAgentResult } from "../automation/agents/codingAgent.ts";
import { discoverProviders } from "../automation/agents/providerDiscovery.ts";
import { buildAgentInstructions } from "../automation/agents/instructionBuilder.ts";
import { TaskExecutionSandbox, type GitSnapshot } from "../automation/agents/taskSandbox.ts";
import { CodingAgentRepairExecutor } from "../automation/orchestrator/repairExecutor.ts";

const root = process.cwd();
const spec = loadTaskSpec(root, "IA-0A.4");
const allowed = ["image-animation/automation/agents/example.ts"];
const baseResult = (changedFiles = allowed): CodingAgentResult => ({ status: "PASS", provider: "fake", exitCode: 0, changedFiles, stdoutSummary: "done", stderrSummary: "", startedAt: "", finishedAt: "" });
const snapshot = (branch = "feature/image-animation-foundation", head = "abc", changedFiles = allowed): GitSnapshot => ({ branch, head, status: "", changedFiles });
const sandbox = (agent: FakeCodingAgent, before = snapshot(), after = before) => new TaskExecutionSandbox(root, "feature/image-animation-foundation", spec, (() => { let index = 0; return () => index++ === 0 ? before : after; })()).execute(agent, spec.id, 1);

assert.equal(sandbox(new FakeCodingAgent(baseResult())).repositoryGuard.status, "PASS", "allowed fake edit accepted");
assert.equal(sandbox(new FakeCodingAgent(baseResult(["server/index.ts"]))).repositoryGuard.status, "FAIL", "forbidden fake edit blocked");
const processFailure = new LocalProcessAgentAdapter("ia-command-that-does-not-exist").execute({ taskId: spec.id, taskSpec: spec, goal: spec.goal, workspace: root, allowedPaths: spec.allowedPaths, forbiddenPaths: spec.forbiddenPaths, architectureLocked: true, attempt: 1, failureEvidence: [], instructions: "", mode: "REPAIR" });
assert.equal(processFailure.status, "NOT_AVAILABLE", "agent process failure is unavailable");
assert.equal(discoverProviders(["ia-command-that-does-not-exist"])[0].status, "NOT_AVAILABLE", "provider unavailable");
assert.equal(discoverProviders(["ia-command-that-does-not-exist"])[0].status, "NOT_AVAILABLE", "discovery only checks capability");
assert.throws(() => new TaskExecutionSandbox("D:\\outside", spec.expectedBranch, spec).execute(new FakeCodingAgent(baseResult()), spec.id, 1), /outside the project root/, "outside workspace blocked");
assert.equal(sandbox(new FakeCodingAgent(baseResult()), snapshot("wrong", "abc"), snapshot("wrong", "abc")).blockers[0], "Wrong branch before agent execution", "wrong branch blocked");
let evidence = sandbox(new FakeCodingAgent(baseResult()), snapshot(), snapshot("feature/image-animation-foundation", "def")).blockers;
assert.ok(evidence.includes("HEAD changed during agent execution"), "HEAD mutation blocked");
evidence = sandbox(new FakeCodingAgent(baseResult()), snapshot(), snapshot()).blockers;
assert.equal(evidence.length, 0, "no unauthorized commit on unchanged HEAD");
assert.equal(sandbox(new FakeCodingAgent(baseResult())).repositoryGuard.status, "PASS", "allowed modification accepted");
assert.equal(sandbox(new FakeCodingAgent(baseResult(["server/index.ts"]))).blockers.length > 0, true, "forbidden modification blocked");
assert.ok(sandbox(new FakeCodingAgent(baseResult(["image-animation/tests/agent-sandbox.test.ts"]))).blockers.length > 0, "protected test modification blocked");
assert.ok(sandbox(new FakeCodingAgent(baseResult(["image-animation/core/scene.ts"]))).blockers.length > 0, "architecture modification blocked");
const agentResult = new FakeCodingAgent({ ...baseResult(), status: "PASS" }).execute();
assert.equal(agentResult.status, "PASS", "agent output is data only and cannot set final status");
const instructions = buildAgentInstructions(spec, [], 1, "REPAIR");
assert.match(instructions, /Do not weaken/); assert.match(instructions, /Do not change architecture/); assert.match(instructions, /Do not commit/);
const repairExecutor = new CodingAgentRepairExecutor(new FakeCodingAgent(baseResult()), new TaskExecutionSandbox(root, spec.expectedBranch, spec));
assert.equal(repairExecutor.execute({ taskId: spec.id, attempt: 1, failureEvidence: [], allowedPaths: spec.allowedPaths, forbiddenPaths: spec.forbiddenPaths, architectureLocked: true }).status, "CHANGED", "repair executor uses coding agent sandbox");
const branchChange = sandbox(new FakeCodingAgent(baseResult()), snapshot(), snapshot("other", "abc"));
assert.ok(branchChange.blockers.includes("Branch changed during agent execution"), "branch change blocked");
const countAgent = new FakeCodingAgent(baseResult()); countAgent.execute(); assert.equal(countAgent.calls, 1, "fake agent deterministic call count");
assert.equal(new LocalProcessAgentAdapter("node", ["-e", "process.exit(1)"]).execute({ taskId: spec.id, taskSpec: spec, goal: spec.goal, workspace: root, allowedPaths: spec.allowedPaths, forbiddenPaths: spec.forbiddenPaths, architectureLocked: true, attempt: 1, failureEvidence: [], instructions: "", mode: "REVIEW" }).status, "FAIL", "process failure is reported");
assert.equal(new TaskExecutionSandbox(root, spec.expectedBranch, spec).execute(new FakeCodingAgent(baseResult()), spec.id, 1).before.head.length > 0, true, "before Git state recorded");
assert.equal(new TaskExecutionSandbox(root, spec.expectedBranch, spec).execute(new FakeCodingAgent(baseResult()), spec.id, 1).after.branch, spec.expectedBranch, "after Git state recorded");
assert.equal(new FakeCodingAgent(baseResult()).constructor.name, "FakeCodingAgent", "fake agent is explicit test provider");
assert.equal(spawnSync("node", ["-e", "process.exit(0)"]).status, 0, "deterministic test process available");
console.log("Agent and sandbox tests: 24/24 passed");