import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import path from "node:path";
import { buildCodexArgs, CodexCodingAgentAdapter, validateCodexArgs } from "../automation/agents/codexAgent.ts";
import { redactSensitive } from "../automation/agents/redaction.ts";
import { discoverProviders } from "../automation/agents/providerDiscovery.ts";
import { selectAgent } from "../automation/agents/providerSelection.ts";
import { loadTaskSpec } from "../automation/orchestrator/orchestrator.ts";

const root = process.cwd();
const spec = loadTaskSpec(root, "IA-0A.4");
const schemaPath = path.join(root, "image-animation", "automation", "temp", "coding-agent-result.schema.json");
const args = buildCodexArgs(root, schemaPath, path.join(root, "image-animation", "automation", "temp", "test-output.txt"));
assert.equal(args[0], "exec");
assert.equal(args[args.indexOf("-C") + 1], root);
assert.equal(args[args.indexOf("-s") + 1], "workspace-write");
assert.ok(args.includes("--ephemeral")); assert.ok(args.includes("--ignore-user-config")); assert.equal(args.at(-1), "-");
assert.ok(args.includes("--approve-for-me"), "uses documented safe approval routing");
assert.throws(() => buildCodexArgs(root, "C:\\outside-schema.json", path.join(root, "image-animation", "automation", "temp", "output.txt")), /outside/);
for (const flag of ["danger-full-access", "--dangerously-bypass-approvals-and-sandbox", "--add-dir", "--skip-git-repo-check", "--ignore-rules"]) assert.throws(() => validateCodexArgs([flag]), /Unsafe/);
const unavailable = new CodexCodingAgentAdapter({ executable: "C:\\does-not-exist\\codex.exe" }).execute({} as never);
assert.equal(unavailable.status, "NOT_AVAILABLE");
assert.equal(selectAgent("none"), null); assert.equal(selectAgent("codex")?.constructor.name, "CodexCodingAgentAdapter");
assert.equal(discoverProviders(["does-not-exist"])[0].status, "NOT_AVAILABLE");
const redacted = redactSensitive("OPENAI_API_KEY=abc Authorization=Bearer xyz token=secret password=hush");
assert.ok(!redacted.includes("abc") && !redacted.includes("xyz") && !redacted.includes("secret"));
const schema = JSON.parse(readFileSync(path.join(root, "image-animation", "automation", "schemas", "coding-agent-result.schema.json"), "utf8")); assert.ok(schema.required.includes("claimedChangedFiles"));
assert.equal(spec.architectureChangeAllowed, false); assert.equal(spec.maxRepairAttempts, 3);
const simulated = await new CodexCodingAgentAdapter({ executable: process.execPath, timeoutMs: 5000 }).executeAsync({ taskId: spec.id, taskSpec: spec, goal: spec.goal, workspace: root, allowedPaths: spec.allowedPaths, forbiddenPaths: spec.forbiddenPaths, architectureLocked: true, attempt: 1, failureEvidence: [], instructions: "", mode: "REVIEW" });
assert.equal(simulated.status, "FAIL", "non-zero spawned process is failure");
assert.equal(typeof new CodexCodingAgentAdapter().executeAsync, "function", "repair integration can use async Codex execution");
console.log("Codex integration tests: 18/18 passed");