import assert from "node:assert/strict";
import { createHash } from "node:crypto";
import { mkdirSync, mkdtempSync, readFileSync, writeFileSync } from "node:fs";
import os from "node:os";
import path from "node:path";
import { applyPatchTransaction, validatePatch } from "../automation/gates/patchTransaction.ts";
import type { FileEdit } from "../automation/agents/codingAgent.ts";
import { loadTaskSpec } from "../automation/orchestrator/orchestrator.ts";

const root = mkdtempSync(path.join(os.tmpdir(), "ia-patch-"));
const projectRoot = process.cwd();
const spec = loadTaskSpec(projectRoot, "IA-CANARY-001");
const target = "image-animation/fixtures/agent-canary/canary.txt";
const before = Buffer.from("BEFORE\n");
const hash = createHash("sha256").update(before).digest("hex");
const valid: FileEdit = { path: target, operation: "UPDATE", beforeSha256: hash, content: "AFTER\n" };
mkdirSync(path.dirname(path.join(root, target)), { recursive: true });
writeFileSync(path.join(root, target), before, "utf8");
const passSpec = { ...spec, allowedPaths: [target] };
assert.equal(validatePatch(root, passSpec, [valid]).status, "PASS");
assert.equal(applyPatchTransaction(root, [valid]).status, "PASS");
assert.equal(readFileSync(path.join(root, target), "utf8"), "AFTER\n");
assert.equal(validatePatch(root, passSpec, [{ ...valid, beforeSha256: "stale" }]).status, "FAIL");
assert.equal(validatePatch(root, passSpec, [{ ...valid, path: "../escape.txt" }]).status, "FAIL");
assert.equal(validatePatch(root, passSpec, [{ ...valid, path: "C:\\escape.txt" }]).status, "FAIL");
assert.equal(validatePatch(root, passSpec, [{ ...valid, path: "\\\\server\\share\\file" }]).status, "FAIL");
assert.equal(validatePatch(root, passSpec, [{ ...valid, path: ".git/config" }]).status, "FAIL");
assert.equal(validatePatch(root, passSpec, [{ ...valid, content: "x".repeat(300000) }]).status, "FAIL");
assert.equal(validatePatch(root, passSpec, [{ ...valid, path: "server/index.ts" }]).status, "FAIL");
assert.equal(validatePatch(root, passSpec, []).status, "FAIL");
console.log("Patch transaction tests: 9/9 passed");