import { DependencyGraph, type MathConstraint, type MathEntity, type MathEvent, type MathScene } from "../math-ir/index.js";
import { DYNAMIC_GEOMETRY_EPSILON, circleCircleIntersections, lineCircleIntersections, projectionPointToLine, recomputeScene, type Vec2, type Vec3 } from "../dynamic-geometry/construction-engine.js";

export type ConstraintResolutionStatus="SATISFIED"|"VIOLATED"|"CONFLICT"|"UNRESOLVED"|"UNSUPPORTED";
export type ConstraintReasonCode="CONSTRAINT_CONFLICT"|"OVER_CONSTRAINED"|"UNSUPPORTED_CONSTRAINT_COMBINATION"|"SOLVER_NOT_AVAILABLE"|"SOLVER_FAILED"|"DEGENERATE_GEOMETRY"|"INVALID_REFERENCE"|"INVALID_DEPENDENCY"|"TRANSACTION_REJECTED";
export interface ConstraintDiagnostic{constraintId:string;status:ConstraintResolutionStatus;reasonCode?:ConstraintReasonCode;affectedIds:string[];conflictingIds:string[];solverId?:SolverId;iterationCount:number;}
export interface ConstraintConflict{conflictingConstraintIds:string[];affectedObjectIds:string[];reason:string;classification:"CONTRADICTORY_LOCKED_CONSTRAINTS";}
export interface ConstraintOrchestrationResult{status:"PASS"|"FAIL";updatedScene:MathScene;affectedIds:string[];constraintResults:ConstraintDiagnostic[];conflicts:ConstraintConflict[];events:MathEvent[];iterations:number;issues:Array<{code:ConstraintReasonCode;message:string}>;operationCount:number;}
export type DegreeOfFreedom="FREE_2D"|"FREE_3D"|"PATH_1D"|"FIXED_0D"|"DEPENDENT"|"UNDER_CONSTRAINED"|"FULLY_CONSTRAINED"|"OVER_CONSTRAINED";
export type SolverId="POINT_ON_LINE_PROJECTOR"|"POINT_ON_SEGMENT_PROJECTOR"|"POINT_ON_CIRCLE_PROJECTOR"|"LINE_CIRCLE_INTERSECTION_SOLVER"|"CIRCLE_CIRCLE_INTERSECTION_SOLVER"|"FIXED_DISTANCE_SOLVER"|"POINT_ON_PLANE_PROJECTOR";
export interface SolverDescriptor{solverId:SolverId;supportedConstraintTypes:string[];supportedObjectTypes:string[];dimension:"2d"|"3d";determinism:"DETERMINISTIC";}
export const SPECIALIZED_SOLVER_REGISTRY:readonly SolverDescriptor[]=[
 {solverId:"POINT_ON_LINE_PROJECTOR",supportedConstraintTypes:["point_on_line"],supportedObjectTypes:["point","line"],dimension:"2d",determinism:"DETERMINISTIC"},
 {solverId:"POINT_ON_SEGMENT_PROJECTOR",supportedConstraintTypes:["point_on_segment"],supportedObjectTypes:["point","segment"],dimension:"2d",determinism:"DETERMINISTIC"},
 {solverId:"POINT_ON_CIRCLE_PROJECTOR",supportedConstraintTypes:["point_on_circle"],supportedObjectTypes:["point","circle"],dimension:"2d",determinism:"DETERMINISTIC"},
 {solverId:"LINE_CIRCLE_INTERSECTION_SOLVER",supportedConstraintTypes:["point_on_line","point_on_circle"],supportedObjectTypes:["point","line","circle"],dimension:"2d",determinism:"DETERMINISTIC"},
 {solverId:"CIRCLE_CIRCLE_INTERSECTION_SOLVER",supportedConstraintTypes:["point_on_circle"],supportedObjectTypes:["point","circle"],dimension:"2d",determinism:"DETERMINISTIC"},
 {solverId:"FIXED_DISTANCE_SOLVER",supportedConstraintTypes:["distance"],supportedObjectTypes:["point"],dimension:"2d",determinism:"DETERMINISTIC"},
 {solverId:"POINT_ON_PLANE_PROJECTOR",supportedConstraintTypes:["point_on_plane"],supportedObjectTypes:["point","plane"],dimension:"3d",determinism:"DETERMINISTIC"},
] as const;

type Definition={parameters?:Record<string,unknown>;freedom?:string};
const clone=<T>(v:T):T=>structuredClone(v), entity=(s:MathScene,id:string)=>s.entities.find(x=>x.id===id);
const coord=(x?:MathEntity):Vec2|Vec3|undefined=>x?.semanticCoordinate?.dimension==="2d"?[x.semanticCoordinate.x,x.semanticCoordinate.y]:x?.semanticCoordinate?.dimension==="3d"?[x.semanticCoordinate.x,x.semanticCoordinate.y,x.semanticCoordinate.z]:undefined;
const def=(x?:MathEntity)=>x?.metadata?.adapterMetadata?.construction as Definition|undefined;
const setCoord=(x:MathEntity,p:Vec2|Vec3):MathEntity=>({...x,semanticCoordinate:p.length===2?{dimension:"2d",x:p[0],y:p[1]}:{dimension:"3d",x:p[0],y:p[1],z:p[2]}} as MathEntity);
const line=(s:MathScene,x?:MathEntity):[Vec2,Vec2]|undefined=>{if(!x||!(x.type==="line"||x.type==="segment"||x.type==="ray"))return;const ids=x.type==="line"?x.pointIds:x.type==="segment"?[x.startPointId,x.endPointId]:[x.startPointId,x.throughPointId],a=coord(entity(s,ids[0])),b=coord(entity(s,ids[1]));return a?.length===2&&b?.length===2?[a as Vec2,b as Vec2]:undefined;};
const circle=(s:MathScene,x?:MathEntity)=>{if(x?.type!=="circle")return;const center=coord(entity(s,x.centerPointId)),radius=Number(def(x)?.parameters?.radius);return center?.length===2&&radius>DYNAMIC_GEOMETRY_EPSILON?{center:center as Vec2,radius}:undefined;};
const distance=(a:Vec2,b:Vec2)=>Math.hypot(a[0]-b[0],a[1]-b[1]);
const choose=(points:Vec2[],candidate:Vec2)=>[...points].sort((a,b)=>distance(a,candidate)-distance(b,candidate)||a[0]-b[0]||a[1]-b[1])[0];
const lockedFor=(scene:MathScene,id:string)=>scene.constraints.filter(c=>c.mode==="LOCKED"&&c.entityIds[0]===id).sort((a,b)=>a.id.localeCompare(b.id,"en"));
const diagnostic=(c:MathConstraint,status:ConstraintResolutionStatus,solverId?:SolverId,reasonCode?:ConstraintReasonCode,conflictingIds:string[]=[]):ConstraintDiagnostic=>({constraintId:c.id,status,...(reasonCode?{reasonCode}:{}),affectedIds:[...c.entityIds],conflictingIds,...(solverId?{solverId}:{}),iterationCount:1});

export function analyzeDegreesOfFreedom(scene:MathScene,objectId:string):{classification:DegreeOfFreedom;positionalDof:number;constraintIds:string[]}{const x=entity(scene,objectId),constraints=lockedFor(scene,objectId),path=constraints.filter(c=>["point_on_line","point_on_segment","point_on_circle","point_on_plane"].includes(c.type)),fixed=constraints.filter(c=>c.type==="distance"&&c.parameters?.fixed===true);if(!x)return{classification:"DEPENDENT",positionalDof:0,constraintIds:[]};if(constraints.length>2||fixed.length>1)return{classification:"OVER_CONSTRAINED",positionalDof:0,constraintIds:constraints.map(c=>c.id)};if(def(x)?.freedom==="DEPENDENT")return{classification:"DEPENDENT",positionalDof:0,constraintIds:constraints.map(c=>c.id)};if(def(x)?.freedom==="FIXED"||fixed.length&&path.length)return{classification:"FIXED_0D",positionalDof:0,constraintIds:constraints.map(c=>c.id)};if(path.length>1)return{classification:"FULLY_CONSTRAINED",positionalDof:0,constraintIds:constraints.map(c=>c.id)};if(path.length)return{classification:path[0].type==="point_on_plane"?"UNDER_CONSTRAINED":"PATH_1D",positionalDof:path[0].type==="point_on_plane"?2:1,constraintIds:constraints.map(c=>c.id)};return{classification:scene.dimension==="3d"?"FREE_3D":"FREE_2D",positionalDof:scene.dimension==="3d"?3:2,constraintIds:[]};}

function solvePoint(scene:MathScene,id:string,candidate:Vec2|Vec3,constraints:MathConstraint[]):{point?:Vec2|Vec3;results:ConstraintDiagnostic[];conflict?:ConstraintConflict}{
 const paths=constraints.filter(c=>["point_on_line","point_on_segment","point_on_circle","point_on_plane"].includes(c.type));
 const distances=constraints.filter(c=>c.type==="distance");
 if(distances.length>1){const groups=new Map(distances.map(c=>[c.entityIds[1],c]));if(groups.size<distances.length){const values=distances.map(c=>Number(c.parameters?.distance??c.parameters?.value));if(values.some(v=>Math.abs(v-values[0])>DYNAMIC_GEOMETRY_EPSILON)){const ids=distances.map(c=>c.id);return{results:constraints.map(c=>diagnostic(c,"CONFLICT",undefined,"CONSTRAINT_CONFLICT",ids)),conflict:{conflictingConstraintIds:ids,affectedObjectIds:[id],reason:"Contradictory fixed distances from the same center",classification:"CONTRADICTORY_LOCKED_CONSTRAINTS"}};}}}
 let output=candidate,solver:SolverId|undefined;
 if(paths.length===2&&output.length===2){const targets=paths.map(c=>entity(scene,c.entityIds[1])),lineTarget=targets.find(x=>x?.type==="line"||x?.type==="segment"),circles=targets.filter(x=>x?.type==="circle");let points:Vec2[]=[];if(lineTarget&&circles.length===1){const l=line(scene,lineTarget),c=circle(scene,circles[0]);if(l&&c){points=lineCircleIntersections(...l,c.center,c.radius).points as Vec2[];solver="LINE_CIRCLE_INTERSECTION_SOLVER";}}else if(circles.length===2){const a=circle(scene,circles[0]),b=circle(scene,circles[1]);if(a&&b){points=circleCircleIntersections(a.center,a.radius,b.center,b.radius).points as Vec2[];solver="CIRCLE_CIRCLE_INTERSECTION_SOLVER";}}if(!points.length){const ids=paths.map(c=>c.id);return{results:constraints.map(c=>diagnostic(c,"CONFLICT",solver,"CONSTRAINT_CONFLICT",ids)),conflict:{conflictingConstraintIds:ids,affectedObjectIds:[id],reason:"Locked paths have no common point",classification:"CONTRADICTORY_LOCKED_CONSTRAINTS"}};}output=choose(points,output as Vec2);}
 else for(const c of paths){const target=entity(scene,c.entityIds[1]);if(output.length===2&&(target?.type==="line"||target?.type==="segment")){const l=line(scene,target);if(!l)continue;output=projectionPointToLine(output as Vec2,...l,target.type==="segment"?"SEGMENT":undefined);solver=target.type==="segment"?"POINT_ON_SEGMENT_PROJECTOR":"POINT_ON_LINE_PROJECTOR";}else if(output.length===2&&target?.type==="circle"){const value=circle(scene,target);if(!value)continue;const d=[output[0]-value.center[0],output[1]-value.center[1]] as Vec2,n=Math.hypot(...d);if(n<=DYNAMIC_GEOMETRY_EPSILON)return{results:[diagnostic(c,"UNRESOLVED",undefined,"DEGENERATE_GEOMETRY")]};output=[value.center[0]+d[0]*value.radius/n,value.center[1]+d[1]*value.radius/n];solver="POINT_ON_CIRCLE_PROJECTOR";}else if(output.length===3&&target?.type==="plane"){const definition=def(target),normal=definition?.parameters?.normal as Vec3,offset=Number(definition?.parameters?.offset);if(!normal)continue;const den=normal[0]**2+normal[1]**2+normal[2]**2,t=(normal[0]*output[0]+normal[1]*output[1]+normal[2]*output[2]+offset)/den;output=[output[0]-normal[0]*t,output[1]-normal[1]*t,output[2]-normal[2]*t];solver="POINT_ON_PLANE_PROJECTOR";}else return{results:[diagnostic(c,"UNSUPPORTED",undefined,"UNSUPPORTED_CONSTRAINT_COMBINATION")]};}
 for(const c of distances){if(output.length!==2)return{results:[diagnostic(c,"UNSUPPORTED",undefined,"UNSUPPORTED_CONSTRAINT_COMBINATION")]};const center=coord(entity(scene,c.entityIds[1])),radius=Number(c.parameters?.distance??c.parameters?.value);if(center?.length!==2||!Number.isFinite(radius)||radius<0)return{results:[diagnostic(c,"UNRESOLVED",undefined,"INVALID_REFERENCE")]};const d=[output[0]-center[0],output[1]-center[1]] as Vec2,n=Math.hypot(...d);if(n<=DYNAMIC_GEOMETRY_EPSILON)return{results:[diagnostic(c,"UNRESOLVED",undefined,"DEGENERATE_GEOMETRY")]};output=[center[0]+d[0]*radius/n,center[1]+d[1]*radius/n];solver="FIXED_DISTANCE_SOLVER";}
 return{point:output,results:constraints.map(c=>diagnostic(c,"SATISFIED",solver))};
}

export function orchestrateConstraints(input:MathScene,mutation:{objectId:string;position:Vec2|Vec3}):ConstraintOrchestrationResult{
 const original=clone(input),target=entity(original,mutation.objectId);if(!target||target.type!=="point")return{status:"FAIL",updatedScene:original,affectedIds:[],constraintResults:[],conflicts:[],events:[],iterations:0,issues:[{code:"INVALID_REFERENCE",message:"Mutation target must be a point"}],operationCount:0};
 let graph:DependencyGraph;try{graph=new DependencyGraph(original.semantics?.dependencies??[]);}catch{return{status:"FAIL",updatedScene:original,affectedIds:[],constraintResults:[],conflicts:[],events:[],iterations:0,issues:[{code:"INVALID_DEPENDENCY",message:"Canonical dependency graph is invalid"}],operationCount:0};}
 const active=lockedFor(original,mutation.objectId),watch=original.constraints.filter(c=>c.mode==="WATCH"&&c.entityIds[0]===mutation.objectId).sort((a,b)=>a.id.localeCompare(b.id,"en")),solved=solvePoint(original,mutation.objectId,mutation.position,active);if(solved.conflict||!solved.point){const conflict=solved.conflict?[solved.conflict]:[];return{status:"FAIL",updatedScene:original,affectedIds:[mutation.objectId],constraintResults:solved.results,conflicts:conflict,events:[],iterations:1,issues:[{code:solved.conflict?"TRANSACTION_REJECTED":"SOLVER_FAILED",message:solved.conflict?.reason??"Constraint solve failed"}],operationCount:active.length};}
 const candidate={...original,entities:original.entities.map(x=>x.id===target.id?setCoord(x,solved.point!):x)},recomputed=recomputeScene(candidate,[target.id]);if(!recomputed.scene)return{status:"FAIL",updatedScene:original,affectedIds:[target.id],constraintResults:solved.results,conflicts:[],events:[],iterations:1,issues:[{code:"TRANSACTION_REJECTED",message:"Dependency recomputation rejected the candidate"}],operationCount:active.length};
 const affected=[target.id,...graph.recomputationOrder([target.id])],events:MathEvent[]=[{id:`constraint-orchestration:${target.id}`,kind:"OBJECT_CHANGED",sequence:0,objectIds:affected,changeKind:"SEMANTIC_CHANGE",payload:{constraintIds:active.map(c=>c.id)}}];
 const watchResults=watch.map(c=>diagnostic(c,recomputed.scene!.constraints.find(x=>x.id===c.id)?.status==="SATISFIED"?"SATISFIED":"VIOLATED"));
 return{status:"PASS",updatedScene:{...recomputed.scene,semantics:{...recomputed.scene.semantics,events:[...(recomputed.scene.semantics?.events??[]),...events]}},affectedIds:affected,constraintResults:[...solved.results,...watchResults],conflicts:[],events,iterations:1,issues:[],operationCount:active.length+affected.length};
}

export interface RenderObject{id:string;rendererObjectId:string;type:string;dimension:"2d"|"3d";visible:boolean;label?:string;coordinate?:Vec2|Vec3;definition?:Record<string,unknown>;}
export interface RenderSnapshot{sceneId:string;objects:RenderObject[];createdIds:string[];updatedIds:string[];removedIds:string[];}
export function createRenderSnapshot(scene:MathScene,previous?:RenderSnapshot):RenderSnapshot{const objects=scene.entities.map(x=>{const c=coord(x);return{id:x.id,rendererObjectId:`render:${x.id}`,type:x.type,dimension:c?.length===3?"3d":scene.dimension,visible:x.metadata?.adapterMetadata?.visible!==false,...(x.label?{label:x.label}:{}),...(c?{coordinate:c}:{}),...(def(x)?{definition:x.metadata!.adapterMetadata!.construction as Record<string,unknown>}:{})} as RenderObject;}),before=new Map((previous?.objects??[]).map(x=>[x.id,JSON.stringify(x)])),after=new Set(objects.map(x=>x.id));return{sceneId:scene.id,objects,createdIds:objects.filter(x=>!before.has(x.id)).map(x=>x.id),updatedIds:objects.filter(x=>before.has(x.id)&&before.get(x.id)!==JSON.stringify(x)).map(x=>x.id),removedIds:[...before.keys()].filter(x=>!after.has(x))};}

export type AdapterKind="three"|"geogebra"|"luadraw"|"manim"|"studio";
export interface AdapterObject{semanticObjectId:string;rendererObjectId:string;kind:string;geometry?:unknown;label?:string;visible:boolean;metadata:{rendererOwnsMath:false};}
export function adaptRenderSnapshot(snapshot:RenderSnapshot,kind:AdapterKind):{kind:AdapterKind;objects:AdapterObject[];unsupportedIds:string[]}{const supported:Record<AdapterKind,Set<string>>={three:new Set(["point","line","ray","segment","circle","polygon","plane"]),geogebra:new Set(["point","line","ray","segment","circle","polygon"]),luadraw:new Set(["point","line","ray","segment","circle","polygon","label"]),manim:new Set(["point","line","ray","segment","circle","polygon","plane","label"]),studio:new Set(snapshot.objects.map(x=>x.type))},objects=snapshot.objects.filter(x=>supported[kind].has(x.type)).map(x=>({semanticObjectId:x.id,rendererObjectId:`${kind}:${x.id}`,kind:x.type,...(x.coordinate||x.definition?{geometry:{coordinate:x.coordinate,definition:x.definition}}:{}),...(x.label?{label:x.label}:{}),visible:x.visible,metadata:{rendererOwnsMath:false as const}}));return{kind,objects,unsupportedIds:snapshot.objects.filter(x=>!supported[kind].has(x.type)).map(x=>x.id)};}

export function serializeConstraintState(value:{scene:MathScene;solverIds:SolverId[]}):string{return JSON.stringify(value);}
export function deserializeConstraintState(value:string):{scene:MathScene;solverIds:SolverId[]}{const parsed=JSON.parse(value) as {scene:MathScene;solverIds:SolverId[]};for(const id of parsed.solverIds)if(!SPECIALIZED_SOLVER_REGISTRY.some(x=>x.solverId===id))throw new Error("SOLVER_NOT_AVAILABLE");return parsed;}
