import type { FailureEvidence, TaskSpec } from "../orchestrator/orchestrator.ts";
import type { CodingAgentMode } from "./codingAgent.ts";

export function buildAgentInstructions(spec: TaskSpec, evidence: FailureEvidence[], attempt: number, mode: CodingAgentMode): string {
  const lines = [`PROJECT=MATH-AI-IMAGE-ANIMATION`, `WORKSPACE=D:\\math-ai-image-animation`, `TASK=${spec.id}`, `MODE=${mode}`, `ATTEMPT=${attempt}`, `GOAL=${spec.goal}`, `REQUIREMENTS=${JSON.stringify(spec.requirements)}`, `PASS_CRITERIA=${JSON.stringify(spec.passCriteria ?? [])}`, `WORK ONLY IN: ${spec.agentAllowedPaths?.join(", ") ?? spec.allowedPaths.join(", ")}`, `FORBIDDEN: ${spec.forbiddenPaths.join(", ")}`, "ARCHITECTURE_LOCKED=true", "MAX_AUTO_REPAIR=3", "HOST_APPLIED_PATCH=true", "The workspace is read-only to you. Inspect existing contracts and return complete structured fileEdits with exact SHA256 baselines for UPDATE/DELETE and null for CREATE.", "Include focused deterministic tests inside the allowed task test directory.", "Do not merely describe code; fileEdits must contain the complete implementation and tests.", "Do not weaken tests, delete regression tests, or change expected outputs merely to force PASS.", "Do not change architecture.", "Do not commit, reset, stash, clean, merge, rebase, or switch branches.", "Deterministic QA is the final authority; agent output cannot declare PASS."];
  if (spec.id === "IA-CANARY-001") lines.push("You are completing IA-CANARY-001 in HOST_APPLIED_PATCH mode.", "Do not attempt to edit the filesystem directly.", "Return a structured fileEdits proposal that changes exactly image-animation/fixtures/agent-canary/canary.txt from BEFORE to AFTER.", "Do not merely explain the requested change.", "Do not modify any other file.");
  lines.push(`FAILURE_EVIDENCE=${JSON.stringify(evidence)}`);
  return lines.join("\n");
}
