import type {MathEntity,MathScene} from "../math-ir/index.js";
import type {MathIntent} from "../intelligent-math-runtime/index.js";

export const MV5_MAX_AUTHORING_DEPTH=8;
export type AuthoringOperation="CREATE_POINT"|"CREATE_LINE"|"CREATE_SEGMENT"|"CREATE_RAY"|"CREATE_CIRCLE"|"CREATE_POLYGON"|"CREATE_PLANE"|"MIDPOINT"|"PERPENDICULAR_BISECTOR"|"INTERSECTION"|"PROJECTION"|"PARALLEL"|"PERPENDICULAR"|"TRANSLATE"|"ROTATE"|"REFLECT"|"SCALE"|"SET_CONSTRAINT"|"REMOVE_CONSTRAINT"|"RENAME"|"DELETE"|"SHOW"|"HIDE"|"MOVE"|"QUERY_OBJECT"|"QUERY_RELATION"|"QUERY_CONSTRAINT"|"VERIFY_CONSTRUCTION"|"EXPLAIN_CONSTRUCTION"|"EXPLAIN_CONFLICT"|"FOLD_OPERATION";
export interface AuthoringIntent{authoringId:string;operation:AuthoringOperation;references:string[];parameters?:Record<string,unknown>;language?:"vi"|"en";sourceText?:string;subgoals?:AuthoringIntent[];}
export interface ReferenceResolution{status:"RESOLVED"|"AMBIGUOUS"|"NOT_FOUND"|"TYPE_MISMATCH";reference:string;semanticIds:string[];entity?:MathEntity;message?:string;}
export const BILINGUAL_MATH_TERMINOLOGY=Object.freeze({
 MIDPOINT:{en:["midpoint"],vi:["trung điểm"]},PERPENDICULAR_BISECTOR:{en:["perpendicular bisector"],vi:["đường trung trực"]},PARALLEL:{en:["parallel line","parallel"],vi:["đường thẳng song song","song song"]},PERPENDICULAR:{en:["perpendicular line","perpendicular"],vi:["đường thẳng vuông góc","vuông góc"]},CREATE_PLANE:{en:["plane"],vi:["mặt phẳng"]},TRANSLATE:{en:["translation","translate"],vi:["phép tịnh tiến","tịnh tiến"]},ROTATE:{en:["rotation","rotate"],vi:["phép quay","quay"]},REFLECT:{en:["reflection","reflect"],vi:["phép đối xứng","đối xứng"]},PROJECTION:{en:["projection"],vi:["hình chiếu"]}
} satisfies Record<string,{en:string[];vi:string[]}>);
export function normalizeBilingualOperation(text:string):{status:"RESOLVED"|"UNSUPPORTED";operation?:AuthoringOperation;language?:"vi"|"en";sourceText:string}{const normalized=text.normalize("NFC").trim().toLocaleLowerCase("vi");for(const[operation,terms]of Object.entries(BILINGUAL_MATH_TERMINOLOGY))for(const language of ["vi","en"] as const)if(terms[language].some(term=>normalized.includes(term)))return{status:"RESOLVED",operation:operation as AuthoringOperation,language,sourceText:text};return{status:"UNSUPPORTED",sourceText:text};}
export function resolveMathReference(scene:MathScene,reference:string,expectedTypes:string[]=[]):ReferenceResolution{const exact=scene.entities.filter(entity=>entity.id===reference||entity.label===reference);let candidates=exact;if(!candidates.length){const compact=reference.replace(/\s+/g,"").toUpperCase(),pair=compact.match(/^(?:LINE|SEGMENT)?([A-Z])([A-Z])$/);if(pair)candidates=scene.entities.filter(entity=>{if(!(entity.type==="line"||entity.type==="segment"||entity.type==="ray"))return false;const ids=entity.type==="line"?entity.pointIds:entity.type==="segment"?[entity.startPointId,entity.endPointId]:[entity.startPointId,entity.throughPointId],labels=ids.map(id=>scene.entities.find(item=>item.id===id)?.label).join("");return labels===pair[1]+pair[2];});}if(!candidates.length)return{status:"NOT_FOUND",reference,semanticIds:[],message:`No semantic object matches ${reference}`};if(candidates.length>1)return{status:"AMBIGUOUS",reference,semanticIds:candidates.map(x=>x.id),message:`${reference} resolves to multiple objects`};const entity=candidates[0];if(expectedTypes.length&&!expectedTypes.includes(entity.type))return{status:"TYPE_MISMATCH",reference,semanticIds:[entity.id],entity,message:`Expected ${expectedTypes.join("|")}, received ${entity.type}`};return{status:"RESOLVED",reference,semanticIds:[entity.id],entity};}
export const AUTHORING_TEMPLATE_REGISTRY=Object.freeze({
 MIDPOINT_OF_SEGMENT:{requiredInputs:["point","point"],operation:"MIDPOINT"},PERPENDICULAR_BISECTOR:{requiredInputs:["point","point"],operation:"PERPENDICULAR_BISECTOR"},PARALLEL_THROUGH_POINT:{requiredInputs:["point","line"],operation:"PARALLEL"},PERPENDICULAR_THROUGH_POINT:{requiredInputs:["point","line"],operation:"PERPENDICULAR"},PROJECTION_TO_LINE:{requiredInputs:["point","line"],operation:"PROJECTION"}
} satisfies Record<string,{requiredInputs:string[];operation:AuthoringOperation}>);
const commandMap:Partial<Record<AuthoringOperation,string>>={CREATE_POINT:"CREATE_FREE_POINT",CREATE_LINE:"CREATE_LINE",CREATE_SEGMENT:"CREATE_SEGMENT",CREATE_RAY:"CREATE_RAY",CREATE_CIRCLE:"CREATE_CIRCLE_CENTER_RADIUS",CREATE_POLYGON:"CREATE_POLYGON",CREATE_PLANE:"CREATE_PLANE",INTERSECTION:"CREATE_INTERSECTION",PROJECTION:"CREATE_PROJECTION",PERPENDICULAR:"CREATE_PERPENDICULAR_LINE",TRANSLATE:"TRANSLATE_OBJECT",ROTATE:"ROTATE_OBJECT",REFLECT:"REFLECT_OBJECT",SCALE:"SCALE_OBJECT",RENAME:"RENAME_OBJECT",DELETE:"DELETE_OBJECT",SHOW:"SET_VISIBILITY",HIDE:"SET_VISIBILITY",MOVE:"MOVE_POINT"};
export function authoringIntentToMathIntent(scene:MathScene,intent:AuthoringIntent):{intent?:MathIntent;issues:Array<{code:string;message:string;requiredInputs:string[];missingInputs:string[];possibleInterpretations:string[]}>}{if(intent.subgoals?.length)return{issues:[{code:"MULTI_STEP",message:"Use the bounded authoring session for subgoals",requiredInputs:[],missingInputs:[],possibleInterpretations:[]}]};const resolved=intent.references.map(reference=>resolveMathReference(scene,reference));const failed=resolved.find(x=>x.status!=="RESOLVED");if(failed)return{issues:[{code:failed.status,message:failed.message??"Reference resolution failed",requiredInputs:intent.references,missingInputs:[failed.reference],possibleInterpretations:failed.semanticIds}]};const targets=resolved.map(x=>x.semanticIds[0]);if(intent.operation==="MIDPOINT"||intent.operation==="PERPENDICULAR_BISECTOR"||intent.operation==="PARALLEL")return{intent:{intentId:intent.authoringId,type:"CREATE_OBJECT",operation:intent.operation==="PARALLEL"?"PARALLEL_LINE":intent.operation,targets,parameters:intent.parameters,metadata:{sourceLanguage:intent.language,sourceText:intent.sourceText}} ,issues:[]};const commandId=commandMap[intent.operation];if(commandId)return{intent:{intentId:intent.authoringId,type:intent.operation==="MOVE"?"MOVE":intent.operation==="RENAME"?"RENAME":intent.operation==="DELETE"?"DELETE":intent.operation==="SHOW"||intent.operation==="HIDE"?"SET_VISIBILITY":"CREATE_OBJECT",operation:"COMMAND",targets,parameters:{commandId,commandParameters:{...intent.parameters,...(intent.operation==="SHOW"?{visible:true}:intent.operation==="HIDE"?{visible:false}:{})}},metadata:{sourceLanguage:intent.language}},issues:[]};return{issues:[{code:"UNSUPPORTED_CONSTRUCTION",message:`${intent.operation} requires a domain-specific or query workflow`,requiredInputs:[],missingInputs:[],possibleInterpretations:[]}]};}
