import type {MathScene} from "../math-ir/index.js";
import {executeMathIntent,type CommandLogEntry,type PlanDiagnostics} from "../intelligent-math-runtime/index.js";
import {MV5_MAX_AUTHORING_DEPTH,authoringIntentToMathIntent,type AuthoringIntent} from "./intent.js";
import {routeRuntimeWithFallback,type RuntimeTelemetry} from "./runtime-health.js";
import {verifyConstruction,type VerificationResult} from "./verification.js";
export interface AuthoringSessionReport{sessionId:string;status:"PASS"|"FAIL";initialScene:MathScene;scene:MathScene;intents:AuthoringIntent[];planDiagnostics:PlanDiagnostics[];commandLog:CommandLogEntry[];verifications:VerificationResult[];runtimeTelemetry:RuntimeTelemetry[];issues:Array<{code:string;message:string}>;transactionCommitted:boolean;}
export function executeAuthoringSession(initialScene:MathScene,intents:AuthoringIntent[],sessionId="authoring-session-1"):AuthoringSessionReport{const original=structuredClone(initialScene);if(intents.length>MV5_MAX_AUTHORING_DEPTH)return{sessionId,status:"FAIL",initialScene:original,scene:original,intents,planDiagnostics:[],commandLog:[],verifications:[],runtimeTelemetry:[],issues:[{code:"PLAN_INVALID",message:"Authoring depth exceeds the bounded limit"}],transactionCommitted:false};let scene=structuredClone(initialScene);const diagnostics:PlanDiagnostics[]=[],log:CommandLogEntry[]=[],verifications:VerificationResult[]=[],telemetry:RuntimeTelemetry[]=[];for(const[intentIndex,authoring]of intents.entries()){const converted=authoringIntentToMathIntent(scene,authoring);if(!converted.intent)return{sessionId,status:"FAIL",initialScene:original,scene:original,intents,planDiagnostics:diagnostics,commandLog:[],verifications:[],runtimeTelemetry:telemetry,issues:converted.issues.map(x=>({code:x.code,message:x.message})),transactionCommitted:false};const executed=executeMathIntent(scene,converted.intent);diagnostics.push(executed.diagnostics);if(executed.status!=="PASS")return{sessionId,status:"FAIL",initialScene:original,scene:original,intents,planDiagnostics:diagnostics,commandLog:[],verifications:[],runtimeTelemetry:telemetry,issues:executed.issues.map(x=>({code:x.code,message:x.message})),transactionCommitted:false};scene=executed.scene;log.push(...executed.commandLog);const created=executed.createdIds.at(-1);if(created&&(authoring.operation==="MIDPOINT"||authoring.operation==="PERPENDICULAR_BISECTOR")){const claim=authoring.operation==="MIDPOINT"?"MIDPOINT" as const:"PERPENDICULAR" as const,referenceIds=authoring.references.map(ref=>initialScene.entities.find(x=>x.id===ref||x.label===ref)?.id).filter(Boolean) as string[];verifications.push(verifyConstruction(scene,{verificationId:`verify:${authoring.authoringId}`,claim,targetIds:[created],referenceIds}));}telemetry.push(routeRuntimeWithFallback({capability:"interactive_2d",preferredBridgeId:intentIndex%2?"geogebra":"three"},intentIndex).telemetry);}const verificationFailed=verifications.some(x=>x.status!=="VERIFIED");return{sessionId,status:verificationFailed?"FAIL":"PASS",initialScene:original,scene:verificationFailed?original:scene,intents:structuredClone(intents),planDiagnostics:diagnostics,commandLog:log,verifications,runtimeTelemetry:telemetry,issues:verificationFailed?[{code:"VERIFICATION_FAILED",message:"Authoring result did not satisfy requested semantics"}]:[],transactionCommitted:!verificationFailed};}
export function serializeAuthoringReport(report:AuthoringSessionReport):string{return JSON.stringify({schemaVersion:"mv5-authoring-report/v1",report});}
export function deserializeAuthoringReport(value:string):AuthoringSessionReport{const parsed=JSON.parse(value) as {schemaVersion:string;report:AuthoringSessionReport};if(parsed.schemaVersion!=="mv5-authoring-report/v1")throw new Error("INVALID_AUTHORING_REPORT");return structuredClone(parsed.report);}
