import { useEffect, useMemo, useRef, useState } from "react";
import * as THREE from "three";
import { OrbitControls } from "three/examples/jsm/controls/OrbitControls.js";
import { createPatternFoldScene, createPatternThreeMapping, updatePatternFoldScene, createSquareSheetRegularSquareFrustum } from "../../modules/pattern-fold/index.js";
import { createFoldTeachingState, updateFoldTeachingState, type FoldTeachingState } from "../../modules/pattern-fold/teaching-state.js";
import type { PatternFoldSequence } from "../../modules/pattern-fold/types.js";
import { getNAMathVisualStyle } from "../../config/naMathFoldVisualStandardV1.js";
import { V3_FOLD_MODEL } from "../../modules/pattern-fold/v3-fold-model.js";

export default function FoldTeachingPlayback({ onExit }: { onExit: () => void }) {
  const [baseSide, setBaseSide] = useState(V3_FOLD_MODEL.defaultBaseSide);
  const sheet = useMemo(() => createSquareSheetRegularSquareFrustum(baseSide), [baseSide]);
  const sequence = useMemo<PatternFoldSequence>(() => ({ id: "teaching:frustum", steps: sheet.creases.map((c) => ({ creaseId: c.id })) }), [sheet]);
  const scene = useMemo(() => createPatternFoldScene(sheet, 0, sequence).value!, [sheet, sequence]);
  const [state, setState] = useState<FoldTeachingState>(() => createFoldTeachingState(scene));
  const [playing, setPlaying] = useState(false);
  const host = useRef<HTMLDivElement>(null);
  const mapping = useRef<ReturnType<typeof createPatternThreeMapping>>();
  useEffect(() => { if (!playing) return; const start = performance.now() - state.foldProgress * 5000; let frame = 0; const tick = (now: number) => { const p = Math.min(1, (now - start) / 5000); setState(s => updateFoldTeachingState(scene, s, p)); if (p < 1) frame = requestAnimationFrame(tick); else setPlaying(false); }; frame = requestAnimationFrame(tick); return () => cancelAnimationFrame(frame); }, [playing, scene]);
  useEffect(() => { const el = host.current; if (!el) return; const world = new THREE.Scene(); world.background = new THREE.Color("#101B3D"); const camera = new THREE.PerspectiveCamera(42, 1, .01, 100); camera.position.set(8, 8, 12); const renderer = new THREE.WebGLRenderer({ antialias: true }); const controls = new OrbitControls(camera, renderer.domElement); controls.enablePan = true; const m = createPatternThreeMapping(scene); mapping.current = m; m.group.traverse(o => { const mesh = o as THREE.Mesh; if (mesh.material && !Array.isArray(mesh.material)) { const material = mesh.material as THREE.MeshStandardMaterial; material.color.set(getNAMathVisualStyle(o.userData.faceId === "base" ? "base-face" : "folding-face").color); material.opacity = getNAMathVisualStyle(o.userData.faceId === "base" ? "base-face" : "folding-face").opacity; } }); el.appendChild(renderer.domElement); world.add(m.group, new THREE.HemisphereLight(0xffffff, 0x334155, 2)); const resize = () => { renderer.setSize(el.clientWidth, el.clientHeight, false); camera.aspect = el.clientWidth / el.clientHeight; camera.updateProjectionMatrix(); }; const ro = new ResizeObserver(resize); ro.observe(el); resize(); let live = true; const draw = () => { if (!live) return; controls.update(); renderer.render(world, camera); requestAnimationFrame(draw); }; draw(); return () => { live = false; ro.disconnect(); controls.dispose(); m.dispose(); renderer.dispose(); renderer.domElement.remove(); mapping.current = undefined; }; }, [scene]);
  useEffect(() => { const next = updatePatternFoldScene(scene, sequence.steps.length - 1, state.foldProgress).value; if (next) mapping.current?.apply(next); }, [scene, sequence, state.foldProgress]);
  const toggle = (key: keyof Pick<FoldTeachingState, "showCutPieces" | "showSourceSheet" | "showFoldLines" | "showDimensions">) => setState(s => ({ ...s, [key]: !s[key] }));
  return <main data-fold-teaching-mode style={{ minHeight: "100vh", padding: 20, background: "#101B3D", color: "#F3F6FB", fontFamily: "system-ui" }}><header style={{ display: "flex", justifyContent: "space-between", alignItems: "center" }}><div><h1 style={{ margin: 0 }}>Fold teaching / playback</h1><small>8×8 dm square sheet → regular square frustum</small></div><button onClick={onExit}>Authoring mode</button></header><div style={{ display: "grid", gridTemplateColumns: "minmax(0,1fr) 260px", gap: 16, marginTop: 16 }}><section ref={host} aria-label="3D fold playback canvas" style={{ minHeight: 650, background: "#101B3D", borderRadius: 12, border: "1px solid #334e80", overflow: "hidden" }} /><aside style={{ background: "#172554", padding: 16, borderRadius: 12 }}><label>Base side a: {baseSide.toFixed(1)} dm<input aria-label="Base side" type="range" min="1" max="5.5" step="0.1" value={baseSide} onChange={e => { setPlaying(false); setBaseSide(Number(e.target.value)); }} style={{ width: "100%" }} /></label><label>Fold progress <strong>{Math.round(state.foldProgress * 100)}%</strong><input aria-label="Fold slider" type="range" min="0" max="1" step="0.01" value={state.foldProgress} onChange={e => { setPlaying(false); setState(s => updateFoldTeachingState(scene, s, Number(e.target.value))); }} style={{ width: "100%" }} /></label><p><button onClick={() => setPlaying(true)}>▶ Fold</button> <button onClick={() => setPlaying(false)}>Pause</button> <button onClick={() => { setPlaying(false); setBaseSide(3); setState(() => createFoldTeachingState(scene, 0)); }}>Reset</button></p><fieldset><legend>Overlays</legend>{([["showCutPieces", "Show cut pieces"], ["showSourceSheet", "Show original sheet"], ["showFoldLines", "Show fold lines"], ["showDimensions", "Show dimensions"]] as const).map(([key, label]) => <label key={key} style={{ display: "block", margin: "8px 0" }}><input type="checkbox" checked={state[key]} onChange={() => toggle(key)} /> {label}</label>)}</fieldset><p style={{ color: getNAMathVisualStyle("label").color, fontSize: 12 }}>Drag to rotate · scroll/pinch to zoom · pan supported</p></aside></div></main>;
}
