import {useEffect,useRef,useState} from 'react';
import {createV3GeoGebraConstruction,type GeoGebraFoldApi} from '../../modules/geogebra/adapter.js';
import {GEOGEBRA_WEB3D_MODULE_URL} from '../../modules/geogebra/config.js';
import {parseV3FoldCommand} from '../../modules/geogebra/construction-ir.js';
import {classifyFoldInput} from '../../modules/geogebra/file-input.js';

type GgbModule={mathApps:{create(options:Record<string,unknown>):{inject(el:Element):Promise<{getAPI():Promise<GeoGebraFoldApi>}>}}};
const DEFAULT_COMMAND='Tạo tấm bìa hình vuông 8 dm, tạo đáy ABCD 3 dm, cắt bốn góc 1 dm, tạo bốn đường gấp và thanh trượt t.';
const gap=8;

export default function GeoGebraFoldView({onExit:_unused}:{onExit?:()=>void}){
  const host=useRef<HTMLDivElement>(null),fileInput=useRef<HTMLInputElement>(null),adapter=useRef<ReturnType<typeof createV3GeoGebraConstruction>>();
  const [status,setStatus]=useState('loading'),[message,setMessage]=useState('Đang tải GeoGebra…'),[command,setCommand]=useState(DEFAULT_COMMAND),[t,setT]=useState(0),[file,setFile]=useState('');
  const build=()=>{if(!parseV3FoldCommand(command).validation.valid){setMessage('Chưa nhận diện đủ dữ kiện để dựng hình.');return;}const api=adapter.current?.api;if(!api){setMessage('GeoGebra chưa sẵn sàng.');return;}try{adapter.current=createV3GeoGebraConstruction(api,{renderCutPieces:true});api.setPerspective?.('5');adapter.current.update(t,3);setMessage('Đã tạo hình V3');}catch(error){setStatus('error');setMessage(error instanceof Error?error.message:'Không thể tạo hình');}};
  useEffect(()=>{let dead=false;(async()=>{try{const mod=await import(/* @vite-ignore */GEOGEBRA_WEB3D_MODULE_URL);if(dead||!host.current)return;const embedded=await(mod as unknown as GgbModule).mathApps.create({appName:'3d',perspective:'5',showToolBar:true,allowStyleBar:true,showStyleBar:true,showAlgebraInput:false,showAlgebraView:false,showMenuBar:false,showResetIcon:true,showAnimationButton:false,enableShiftDragZoom:true}).inject(host.current);const api=await embedded.getAPI();if(dead)return;const style=document.createElement('style');style.textContent='.customScrollbar.tab:has(.algebraView){display:none!important}.main{left:0!important;width:100%!important}';host.current.append(style);adapter.current=createV3GeoGebraConstruction(api,{renderCutPieces:true});api.setPerspective?.('5');setStatus('ready');setMessage('GeoGebra sẵn sàng · Gấp ↔ Trải phẳng');}catch(error){if(!dead){setStatus('error');setMessage(error instanceof Error?error.message:'GeoGebra failed to load');}}})();return()=>{dead=true;host.current?.replaceChildren();};},[]);
  useEffect(()=>{if(status!=='ready')return;const current=adapter.current;if(!current)return;current.api.setPerspective?.('5');current.update(t,3);},[t,status]);
  useEffect(()=>{if(status!=='ready'||!host.current)return;const current=adapter.current;if(!current)return;const resize=()=>{const el=host.current;if(el)current.api.setSize?.(el.clientWidth,el.clientHeight);};const observer=new ResizeObserver(resize);observer.observe(host.current);resize();return()=>observer.disconnect();},[status]);
  const onFile=(next:File|undefined)=>{if(!next)return;const kind=classifyFoldInput(next.name,next.type);if(!kind){setMessage('Định dạng tệp chưa được hỗ trợ.');return;}setFile(next.name);setMessage('Đã nhận tệp · '+kind);};
  const reset=()=>{adapter.current?.reset();setT(0);};
  return <main data-geogebra-fold-view style={{height:'100dvh',width:'100%',overflow:'hidden',display:'grid',gridTemplateRows:'auto auto minmax(0,1fr) auto',boxSizing:'border-box',background:'#F7F9FC',color:'#17233F',fontFamily:'Libertinus Serif,Georgia,serif'}}>
    <header style={{minHeight:52,display:'flex',alignItems:'center',justifyContent:'space-between',padding:'0 16px',borderBottom:'1px solid #D9E0EA',background:'#FFFFFF'}}><h1 style={{fontFamily:'STIX Two Text,Georgia,serif',fontSize:22,lineHeight:1.1,margin:0}}>Gấp – Trải phẳng</h1><button type="button" onClick={reset} style={{fontFamily:'XCharter,Arial,sans-serif',padding:'4px 8px',border:'1px solid #AAB4C8',borderRadius:4,background:'#FFFFFF',color:'#17233F'}}>Đặt lại</button></header>
    <section aria-label="Nhập đề bài" style={{display:'grid',gridTemplateColumns:'auto minmax(0,1fr) auto',alignItems:'center',gap,padding:'8px 16px',borderBottom:'1px solid #D9E0EA',background:'#FFFFFF'}}><input ref={fileInput} type="file" accept="image/png,image/jpeg,image/webp,.docx,application/pdf" onChange={e=>onFile(e.target.files?.[0])} style={{display:'none'}}/><button type="button" onClick={()=>fileInput.current?.click()} style={{fontFamily:'XCharter,Arial,sans-serif',padding:'8px 12px',border:'1px solid #AAB4C8',borderRadius:4,background:'#FFFFFF',color:'#17233F'}}>Ảnh / Word / PDF</button><label style={{minWidth:0,display:'flex',alignItems:'center',gap,fontFamily:'XCharter,Arial,sans-serif',fontWeight:600}}><span style={{whiteSpace:'nowrap'}}>Nhập đề bài</span><textarea aria-label="Mô tả đề bài" value={command} onChange={e=>setCommand(e.target.value)} rows={1} style={{width:'100%',minWidth:0,resize:'none',padding:'4px 8px',border:'1px solid #AAB4C8',borderRadius:4,fontFamily:'Libertinus Serif,Georgia,serif'}}/></label><button type="button" onClick={build} style={{fontFamily:'XCharter,Arial,sans-serif',fontWeight:600,padding:'8px 12px',border:0,borderRadius:4,background:'#173B70',color:'#FFFFFF'}}>Tạo hình</button>{file&&<span style={{gridColumn:'1 / -1',fontSize:12,color:'#52627A'}}>Tệp: {file}</span>}</section>
    <div ref={host} aria-label="Embedded GeoGebra 3D applet" style={{minWidth:0,minHeight:0,width:'100%',height:'100%',overflow:'hidden',background:'#F7F9FC'}}>{status!=='ready'&&<p style={{padding:'0 16px'}}>{message}</p>}</div>
    <footer style={{display:'grid',gridTemplateColumns:'auto minmax(120px,1fr) auto auto',alignItems:'center',gap,padding:'8px 16px',borderTop:'1px solid #D9E0EA',background:'#FFFFFF',fontFamily:'XCharter,Arial,sans-serif',fontWeight:600}}><span>Trải phẳng</span><input aria-label="Mức gấp" type="range" min="0" max="1" step=".01" value={t} onChange={e=>setT(Number(e.target.value))} style={{width:'100%',accentColor:'#173B70'}}/><span>Gấp</span><span style={{minWidth:48,textAlign:'right',fontFamily:'Libertinus Math,Libertinus Serif,serif',fontWeight:400}}>t={t.toFixed(2)}</span></footer>
  </main>;
}
